kind = "web"
previewPath = "/"
title = "LazyTopper"
version = "1.0.0"
id = "lazytopper-frontend-v1"

[[services]]
localPort = 5173
name = "LazyTopper Frontend"
paths = ["/"]

[services.env]
PORT = "5173"

[services.development]
run = "cd lazytopper && npx vite"
