import type { CanonicalQuestion } from "../../types";

export const ABS2_PACK2: CanonicalQuestion[] = [
  {
    "id": "ABS2-001",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Properties of Acids and Bases",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "Which of the following is a characteristic property of acids?",
    "options": [
      "A) Sour taste and turn blue litmus red",
      "B) Bitter taste and turn red litmus blue",
      "C) Salty taste and do not change litmus color",
      "D) Sweet taste and turn phenolphthalein pink"
    ],
    "answer": "A) Sour taste and turn blue litmus red",
    "solutionSteps": [
      "Acids have characteristic properties:",
      "- Taste sour",
      "- Turn blue litmus paper red",
      "- React with bases to form salts and water",
      "- Conduct electricity in solution"
    ],
    "finalAnswer": "A) Sour taste and turn blue litmus red",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 InText"
  },
  {
    "id": "ABS2-002",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Properties of Acids and Bases",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "Which property is characteristic of bases?",
    "options": [
      "A) Sour taste and turn red litmus blue",
      "B) Bitter taste and turn red litmus blue",
      "C) Pungent smell and turn blue litmus red",
      "D) Salty taste and do not change any litmus"
    ],
    "answer": "B) Bitter taste and turn red litmus blue",
    "solutionSteps": [
      "Bases have characteristic properties:",
      "- Taste bitter",
      "- Feel slippery to touch",
      "- Turn red litmus paper blue",
      "- Conduct electricity in solution"
    ],
    "finalAnswer": "B) Bitter taste and turn red litmus blue",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 InText"
  },
  {
    "id": "ABS2-003",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "pH Scale",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "What is the pH value of a neutral solution?",
    "options": [
      "A) 0",
      "B) 7",
      "C) 14",
      "D) 1"
    ],
    "answer": "B) 7",
    "solutionSteps": [
      "pH scale ranges from 0 to 14",
      "pH < 7: Acidic solution",
      "pH = 7: Neutral solution",
      "pH > 7: Basic/Alkaline solution",
      "Pure water has pH = 7"
    ],
    "finalAnswer": "B) 7",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 Exercise"
  },
  {
    "id": "ABS2-004",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "pH Scale",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "Which pH indicator is used to determine the pH of a solution?",
    "options": [
      "A) Thermometer",
      "B) Barometer",
      "C) pH meter or Universal indicator",
      "D) Hygrometer"
    ],
    "answer": "C) pH meter or Universal indicator",
    "solutionSteps": [
      "pH indicators are used to measure acidity/basicity",
      "Common indicators:",
      "- Universal indicator (shows color range for different pH)",
      "- pH meter (digital measurement)",
      "- Litmus paper (qualitative test)"
    ],
    "finalAnswer": "C) pH meter or Universal indicator",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 InText"
  },
  {
    "id": "ABS2-005",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Properties of Acids and Bases",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Which of the following is a strong acid?",
    "options": [
      "A) Acetic acid (CH₃COOH)",
      "B) Hydrochloric acid (HCl)",
      "C) Carbonic acid (H₂CO₃)",
      "D) Citric acid"
    ],
    "answer": "B) Hydrochloric acid (HCl)",
    "solutionSteps": [
      "Strong acids completely ionize in water",
      "Common strong acids: HCl, H₂SO₄, HNO₃",
      "Common weak acids: CH₃COOH, H₂CO₃, citric acid",
      "HCl is a strong acid that completely dissociates"
    ],
    "finalAnswer": "B) Hydrochloric acid (HCl)",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 Exercise"
  },
  {
    "id": "ABS2-006",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "pH Scale",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "If the pH of a solution is 3, what can we infer about the solution?",
    "options": [
      "A) It is neutral",
      "B) It is strongly acidic",
      "C) It is weakly basic",
      "D) It is strongly basic"
    ],
    "answer": "B) It is strongly acidic",
    "solutionSteps": [
      "pH scale: 0-14",
      "pH < 7: Acidic (lower pH = more acidic)",
      "pH 3 is far from 7, indicating strong acidity",
      "[H⁺] concentration is high at pH 3",
      "This solution would have high acidity"
    ],
    "finalAnswer": "B) It is strongly acidic",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 InText"
  },
  {
    "id": "ABS2-007",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Salts and their Properties",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "What is formed when an acid reacts with a base?",
    "options": [
      "A) Another acid and water",
      "B) Salt and water",
      "C) Salt, water, and hydrogen gas",
      "D) Only hydrogen gas"
    ],
    "answer": "B) Salt and water",
    "solutionSteps": [
      "Neutralization reaction:",
      "Acid + Base → Salt + Water",
      "Example: HCl + NaOH → NaCl + H₂O",
      "This is an exothermic reaction"
    ],
    "finalAnswer": "B) Salt and water",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 Exercise"
  },
  {
    "id": "ABS2-008",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Neutralisation",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A farmer's field has acidic soil (pH 5). What should be added to neutralize it?",
    "options": [
      "A) More acidic fertilizer",
      "B) Lime (CaO) or calcium carbonate",
      "C) Sulfuric acid",
      "D) Ammonium sulfate"
    ],
    "answer": "B) Lime (CaO) or calcium carbonate",
    "solutionSteps": [
      "Acidic soil needs a basic substance to neutralize",
      "Lime (CaO) is basic and reacts with acid",
      "Calcium carbonate (CaCO₃) also works",
      "These raise the pH to neutral range (6.5-7.5)"
    ],
    "finalAnswer": "B) Lime (CaO) or calcium carbonate",
    "isCompetencyBased": true,
    "pyqYear": "2021",
    "pyqSet": "SET-A",
    "ncertRef": "NCERT Ch2 Exercise"
  },
  {
    "id": "ABS2-009",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Salts and their Properties",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Which of the following salts is basic in nature?",
    "options": [
      "A) NaCl (sodium chloride)",
      "B) Na₂CO₃ (sodium carbonate)",
      "C) NH₄Cl (ammonium chloride)",
      "D) KCl (potassium chloride)"
    ],
    "answer": "B) Na₂CO₃ (sodium carbonate)",
    "solutionSteps": [
      "Salts formed from weak acid + strong base are basic",
      "Na₂CO₃ is from H₂CO₃ (weak) + NaOH (strong)",
      "NaCl, KCl are neutral (strong acid + strong base)",
      "NH₄Cl is acidic (strong acid + weak base)"
    ],
    "finalAnswer": "B) Na₂CO₃ (sodium carbonate)",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 Exercise"
  },
  {
    "id": "ABS2-010",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Properties of Acids and Bases",
    "section": "B",
    "marks": 1,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Name any two acids found in food items and mention their sources.",
    "options": [],
    "answer": "Any two with correct sources",
    "solutionSteps": [
      "Common food acids:",
      "1. Acetic acid - found in vinegar",
      "2. Citric acid - found in lemons, oranges, limes",
      "3. Lactic acid - found in yogurt, sour milk",
      "4. Tartaric acid - found in grapes"
    ],
    "finalAnswer": "Any two with correct sources",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 InText"
  },
  {
    "id": "ABS2-011",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Neutralisation",
    "section": "B",
    "marks": 1,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Write the chemical equation for the neutralization of hydrochloric acid with sodium hydroxide.",
    "options": [],
    "answer": "HCl + NaOH → NaCl + H₂O",
    "solutionSteps": [
      "Neutralization reaction between strong acid and strong base:",
      "HCl (hydrochloric acid) + NaOH (sodium hydroxide)",
      "Products: NaCl (salt) + H₂O (water)",
      "The reaction is exothermic (releases heat)"
    ],
    "finalAnswer": "HCl + NaOH → NaCl + H₂O",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 Exercise"
  },
  {
    "id": "ABS2-012",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "pH Scale",
    "section": "C",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "If you add more water to an acidic solution, what happens to its pH?",
    "options": [
      "A) pH decreases (becomes more acidic)",
      "B) pH increases (becomes less acidic/neutral)",
      "C) pH remains the same",
      "D) pH becomes zero"
    ],
    "answer": "B) pH increases (becomes less acidic/neutral)",
    "solutionSteps": [
      "Dilution decreases concentration of H⁺ ions",
      "pH = -log[H⁺]",
      "Lower [H⁺] means higher pH value",
      "The solution becomes less acidic (closer to neutral)"
    ],
    "finalAnswer": "B) pH increases (becomes less acidic/neutral)",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 Exercise"
  },
  {
    "id": "ABS2-013",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Properties of Acids and Bases",
    "section": "C",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Which phenomenon explains why HCl is a strong acid while CH₃COOH is a weak acid?",
    "options": [
      "A) Molecular weight difference",
      "B) Complete vs partial ionization in water",
      "C) Color difference",
      "D) Solubility in water"
    ],
    "answer": "B) Complete vs partial ionization in water",
    "solutionSteps": [
      "Strong acids: HCl → H⁺ + Cl⁻ (complete ionization, 100%)",
      "Weak acids: CH₃COOH ⇌ CH₃COO⁻ + H⁺ (partial ionization)",
      "HCl completely dissociates, producing more H⁺ ions",
      "CH₃COOH reaches equilibrium with mostly un-ionized molecules"
    ],
    "finalAnswer": "B) Complete vs partial ionization in water",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 InText"
  },
  {
    "id": "ABS2-014",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Salts and their Properties",
    "section": "C",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Why is NH₄Cl solution acidic despite being formed from HCl and NH₃·H₂O?",
    "options": [
      "A) HCl is a strong acid",
      "B) NH₄⁺ ion undergoes hydrolysis releasing H⁺ ions",
      "C) Cl⁻ ions make it acidic",
      "D) NH₃ is volatile"
    ],
    "answer": "B) NH₄⁺ ion undergoes hydrolysis releasing H⁺ ions",
    "solutionSteps": [
      "NH₄Cl is formed from strong acid (HCl) and weak base (NH₃·H₂O)",
      "NH₄⁺ undergoes hydrolysis: NH₄⁺ + H₂O ⇌ NH₃·H₂O + H⁺",
      "This releases free H⁺ ions, making the solution acidic",
      "Salts of strong acid + weak base are always acidic"
    ],
    "finalAnswer": "B) NH₄⁺ ion undergoes hydrolysis releasing H⁺ ions",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": "SET-B",
    "ncertRef": "NCERT Ch2 Exercise"
  },
  {
    "id": "ABS2-015",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Neutralisation",
    "section": "C",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Assertion: During neutralization, the temperature of the solution increases. Reason: Neutralization is an exothermic reaction.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "Assertion: True - Temperature increases during neutralization",
      "Reason: True - Neutralization is exothermic (releases heat)",
      "Heat is released because strong bonds form between ions",
      "The increase in temperature is a direct result of heat release"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 InText"
  },
  {
    "id": "ABS2-016",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "pH Scale",
    "section": "C",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Assertion: Blood has a pH of approximately 7.4. Reason: The pH of blood is neutral because it contains equal amounts of acids and bases.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "A is true, R is false.",
    "solutionSteps": [
      "Assertion: True - Blood pH is 7.35-7.45 (slightly alkaline)",
      "Reason: False - Blood is slightly basic, not strictly neutral",
      "pH 7.4 is slightly above 7, making blood basic",
      "Blood maintains this pH through buffer systems, not just acid-base balance"
    ],
    "finalAnswer": "A is true, R is false.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 InText"
  },
  {
    "id": "ABS2-017",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Salts and their Properties",
    "section": "C",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "Assertion: Na₂SO₄ solution is neutral. Reason: It is formed from a strong acid (H₂SO₄) and a strong base (NaOH).",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "Assertion: True - Na₂SO₄ is neutral (pH ≈ 7)",
      "Reason: True - It's formed from H₂SO₄ (strong acid) + NaOH (strong base)",
      "Salts from strong acid + strong base are neutral",
      "Neither ion hydrolyzes to release H⁺ or OH⁻"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 Exercise"
  },
  {
    "id": "ABS2-018",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Properties of Acids and Bases",
    "section": "E",
    "marks": 4,
    "format": "Case-Based",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A student has three unknown solutions A, B, and C. She uses the following tests to identify them:\n\nTest 1: Addition of red litmus paper\n- Solution A: Litmus remains red\n- Solution B: Litmus turns blue\n- Solution C: No change in litmus color\n\nTest 2: pH measurement using pH meter\n- Solution A: pH = 2\n- Solution B: pH = 11\n- Solution C: pH = 7\n\nBased on these observations answer the following:\n(i) Identify the nature of each solution.\n(ii) Which solution when added to another would produce a neutralization reaction?\n(iii) Write the general equation for neutralization.",
    "options": [],
    "answer": "A: Acidic, B: Basic, C: Neutral; A+B neutralize; Acid + Base → Salt + Water",
    "solutionSteps": [
      "Analyzing Test 1 (Litmus test):",
      "- Solution A: Red litmus stays red → acidic",
      "- Solution B: Red litmus turns blue → basic",
      "- Solution C: No change → neutral",
      "",
      "Analyzing Test 2 (pH measurement):",
      "- pH < 7 (pH = 2) → acidic (Solution A)",
      "- pH > 7 (pH = 11) → basic (Solution B)",
      "- pH = 7 → neutral (Solution C)",
      "",
      "Neutralization:",
      "- Acidic solution A + Basic solution B → Salt + Water",
      "- General equation: Acid + Base → Salt + Water"
    ],
    "finalAnswer": "A: Acidic, B: Basic, C: Neutral; A+B neutralize; Acid + Base → Salt + Water",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 InText, Exercise"
  },
  {
    "id": "ABS2-019",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Neutralisation",
    "section": "E",
    "marks": 4,
    "format": "Case-Based",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A farmer observes that his field soil is showing signs of degradation with pH = 5. Plants are not growing well. He consults an agricultural expert who suggests adding lime to the field.\n\n(i) Why is the soil considered acidic? What are the effects of acidic soil on plant growth?\n(ii) What is lime and how does it neutralize the acidic soil? Write the equation.\n(iii) What would be the ideal pH range for healthy soil?\n(iv) Is this an example of neutralization reaction? Justify.",
    "options": [],
    "answer": "pH<7 acidic; lime (CaO/CaCO₃) neutralizes by reacting with H⁺; ideal pH 6.5-7.5; yes, neutralization reaction",
    "solutionSteps": [
      "Part (i) - Acidic Soil:",
      "- pH = 5 is less than 7, indicating acidity",
      "- Effects: reduced nutrient availability, aluminum toxicity,",
      "  poor microbial activity, stunted plant growth",
      "",
      "Part (ii) - Lime as Solution:",
      "- Lime is calcium oxide (CaO) or calcium carbonate (CaCO₃)",
      "- Equations:",
      "  CaO + 2H⁺ → Ca²⁺ + H₂O",
      "  CaCO₃ + 2H⁺ → Ca²⁺ + H₂O + CO₂",
      "- Neutralizes H⁺ ions, raising pH",
      "",
      "Part (iii) - Ideal pH:",
      "- 6.5-7.5 (slightly acidic to neutral) is optimal",
      "",
      "Part (iv) - Neutralization:",
      "- Yes, it's neutralization: Acid + Base → Salt + Water"
    ],
    "finalAnswer": "pH<7 acidic; lime (CaO/CaCO₃) neutralizes by reacting with H⁺; ideal pH 6.5-7.5; yes, neutralization reaction",
    "isCompetencyBased": true,
    "pyqYear": "2022",
    "pyqSet": "SET-A",
    "ncertRef": "NCERT Ch2 Exercise"
  },
  {
    "id": "ABS2-020",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Salts and their Properties",
    "section": "D",
    "marks": 5,
    "format": "Long",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "Explain the concept of pH and its importance. Describe how acidic, neutral, and basic solutions differ from each other. Give real-life examples of each type and explain how pH affects our everyday life. Also discuss the pH of common food items and their effects on health.",
    "options": [],
    "answer": "pH measures [H⁺] on 0-14 scale; acidic <7 (sour, H⁺ rich); neutral =7; basic >7 (bitter, OH⁻ rich); affects digestion, health, food preservation, environment; foods vary in pH affecting dental/bone health",
    "solutionSteps": [
      "PART 1: pH Concept",
      "- pH = -log[H⁺] ion concentration",
      "- Scale from 0 to 14",
      "- Measures acidity/basicity of solution",
      "",
      "PART 2: Differences",
      "- Acidic (pH < 7): excess H⁺ ions, sour taste, red litmus red",
      "  Example: lemon (pH 2), vinegar (pH 3), stomach acid (pH 1-2)",
      "",
      "- Neutral (pH = 7): [H⁺] = [OH⁻], pure water",
      "  Example: distilled water (pH 7), normal blood (pH 7.4)",
      "",
      "- Basic/Alkaline (pH > 7): excess OH⁻ ions, bitter taste, red litmus blue",
      "  Example: milk of magnesia (pH 10), bleach (pH 13), sea water (pH 8.5)",
      "",
      "PART 3: Real-Life Importance",
      "- Digestion: stomach pH 1-2 (HCl needed)",
      "- Dental health: teeth demineralize below pH 5.5",
      "- Food preservation: acidic foods resist spoilage",
      "- Environmental: acid rain (pH < 5.6) damages ecosystems",
      "- Agriculture: soil pH affects nutrient availability",
      "",
      "PART 4: Food pH & Health",
      "- Lemon juice: pH 2 (vitamin C, citric acid)",
      "- Milk: pH 6.6 (calcium, easy to curdle)",
      "- Apple: pH 3 (pectin, antioxidants)",
      "- Banana: pH 5.1 (potassium)",
      "- Egg white: pH 9 (protein rich)",
      "- Health effects: excessive acidic foods can cause:",
      "  * Tooth enamel erosion",
      "  * Acid reflux",
      "  * Weak bones (calcium loss)",
      "- Balanced diet needs both acidic and basic foods"
    ],
    "finalAnswer": "pH measures [H⁺] on 0-14 scale; acidic <7 (sour, H⁺ rich); neutral =7; basic >7 (bitter, OH⁻ rich); affects digestion, health, food preservation, environment; foods vary in pH affecting dental/bone health",
    "isCompetencyBased": true,
    "pyqYear": "2024",
    "pyqSet": "SET-A",
    "ncertRef": "NCERT Ch2 InText, Exercise"
  },
  {
    "id": "ABS2-021",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Properties of Acids and Bases",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "Which of the following will turn phenolphthalein pink?",
    "options": [
      "A) Acidic solution",
      "B) Basic solution",
      "C) Neutral solution",
      "D) None of the above"
    ],
    "answer": "B) Basic solution",
    "solutionSteps": [
      "Phenolphthalein is a pH indicator",
      "Colorless in acidic and neutral solutions",
      "Pink/magenta in basic solutions (pH > 8.2)",
      "Used to detect presence of bases"
    ],
    "finalAnswer": "B) Basic solution",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 InText"
  },
  {
    "id": "ABS2-022",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Neutralisation",
    "section": "B",
    "marks": 1,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "If 10 mL of an acid solution is neutralized by 20 mL of a base solution, which solution is more concentrated?",
    "options": [],
    "answer": "Acid solution is more concentrated",
    "solutionSteps": [
      "From neutralization: n(acid) = n(base)",
      "Moles of acid × Volume of acid = Moles of base × Volume of base",
      "If less volume of acid is needed to neutralize more volume of base,",
      "the acid must be more concentrated",
      "Molarity relationship: M₁V₁ = M₂V₂"
    ],
    "finalAnswer": "Acid solution is more concentrated",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 Exercise"
  },
  {
    "id": "ABS2-023",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Salts and their Properties",
    "section": "B",
    "marks": 1,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Explain why common salt (NaCl) is neutral, while sodium carbonate (Na₂CO₃) is basic in nature.",
    "options": [],
    "answer": "NaCl neutral (strong+strong); Na₂CO₃ basic (weak+strong, CO₃²⁻ hydrolyzes)",
    "solutionSteps": [
      "NaCl formation: HCl (strong) + NaOH (strong)",
      "Both ions (Na⁺, Cl⁻) do not hydrolyze significantly",
      "pH remains 7 (neutral)",
      "",
      "Na₂CO₃ formation: H₂CO₃ (weak) + 2NaOH (strong)",
      "CO₃²⁻ ion undergoes hydrolysis:",
      "CO₃²⁻ + H₂O ⇌ HCO₃⁻ + OH⁻",
      "Produces OH⁻ ions, making solution basic"
    ],
    "finalAnswer": "NaCl neutral (strong+strong); Na₂CO₃ basic (weak+strong, CO₃²⁻ hydrolyzes)",
    "isCompetencyBased": true,
    "pyqYear": "2019",
    "pyqSet": "SET-B",
    "ncertRef": "NCERT Ch2 Exercise"
  },
  {
    "id": "ABS2-024",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "pH Scale",
    "section": "B",
    "marks": 1,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "What will happen to the pH of a basic solution if it is diluted with water? Explain.",
    "options": [],
    "answer": "pH decreases, solution becomes less basic, approaches pH 7",
    "solutionSteps": [
      "Dilution reduces [OH⁻] ion concentration",
      "Lower [OH⁻] means lower pOH",
      "Since pH + pOH = 14",
      "Lower pOH → higher pH value? No!",
      "Recall: pH = 14 - pOH",
      "As concentration of OH⁻ decreases, pH approaches 7",
      "Solution becomes less basic (but still basic if not over-diluted)"
    ],
    "finalAnswer": "pH decreases, solution becomes less basic, approaches pH 7",
    "isCompetencyBased": true,
    "pyqYear": "2025",
    "pyqSet": "SET-A",
    "ncertRef": "NCERT Ch2 Exercise"
  },
  {
    "id": "ABS2-025",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Properties of Acids and Bases",
    "section": "C",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "When magnesium reacts with dilute hydrochloric acid, the reaction is vigorous. However, when magnesium reacts with acetic acid (a weak acid), the reaction is slow. This is because:",
    "options": [
      "A) HCl is more reactive than acetic acid",
      "B) HCl provides more H⁺ ions due to complete ionization",
      "C) Acetic acid has lower density",
      "D) Magnesium reacts only with strong acids"
    ],
    "answer": "B) HCl provides more H⁺ ions due to complete ionization",
    "solutionSteps": [
      "HCl is a strong acid: HCl → H⁺ + Cl⁻ (complete ionization, 100%)",
      "CH₃COOH is weak acid: ⇌ H⁺ + CH₃COO⁻ (partial ionization)",
      "More H⁺ ions available from HCl → faster reaction",
      "Fewer H⁺ ions from acetic acid → slower reaction",
      "Rate depends on [H⁺], not molecular formula"
    ],
    "finalAnswer": "B) HCl provides more H⁺ ions due to complete ionization",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 InText"
  },
  {
    "id": "ABS2-027",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Properties of Acids and Bases",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "Which indicator turns red in acidic solution?",
    "options": [
      "A) Methyl orange",
      "B) Turmeric",
      "C) Phenolphthalein",
      "D) None of the above"
    ],
    "answer": "A) Methyl orange",
    "solutionSteps": [
      "Indicators are substances that change color based on pH.",
      "Methyl orange turns red in acidic solutions (pH < 4.4).",
      "Turmeric and phenolphthalein are indicators for basic solutions."
    ],
    "finalAnswer": "A) Methyl orange",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 InText"
  },
  {
    "id": "ABS2-028",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "pH Scale",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "A solution has pH = 7. This solution is:",
    "options": [
      "A) Acidic",
      "B) Basic",
      "C) Neutral",
      "D) Strongly acidic"
    ],
    "answer": "C) Neutral",
    "solutionSteps": [
      "The pH scale ranges from 0 to 14.",
      "pH = 7 indicates [H⁺] = [OH⁻]",
      "When hydrogen ion concentration equals hydroxide ion concentration, the solution is neutral.",
      "pH < 7 is acidic, pH > 7 is basic, pH = 7 is neutral."
    ],
    "finalAnswer": "C) Neutral",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 InText"
  },
  {
    "id": "ABS2-029",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "pH Scale",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "The pH of lemon juice is approximately 2. This means it is:",
    "options": [
      "A) Weakly acidic",
      "B) Strongly acidic",
      "C) Neutral",
      "D) Basic"
    ],
    "answer": "B) Strongly acidic",
    "solutionSteps": [
      "pH values 0-3 indicate strongly acidic solutions.",
      "pH values 4-6 indicate weakly acidic solutions.",
      "Lemon juice with pH = 2 is strongly acidic.",
      "Lower pH value means higher [H⁺] concentration and stronger acidity."
    ],
    "finalAnswer": "B) Strongly acidic",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 InText"
  },
  {
    "id": "ABS2-030",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Salts and their Properties",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "NaCl is formed by neutralization of:",
    "options": [
      "A) HCl and NaOH",
      "B) HNO₃ and NaOH",
      "C) H₂SO₄ and Na₂O",
      "D) HCl and Na₂O"
    ],
    "answer": "A) HCl and NaOH",
    "solutionSteps": [
      "Neutralization: Acid + Base → Salt + Water",
      "HCl (strong acid) + NaOH (strong base) → NaCl (salt) + H₂O",
      "NaCl is sodium chloride, formed from HCl and NaOH."
    ],
    "finalAnswer": "A) HCl and NaOH",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 Exercise"
  },
  {
    "id": "ABS2-031",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Neutralisation",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "When an acid is neutralized by a base, the products formed are:",
    "options": [
      "A) Only salt",
      "B) Salt and water",
      "C) Only water",
      "D) Salt, water, and heat"
    ],
    "answer": "D) Salt, water, and heat",
    "solutionSteps": [
      "Neutralization is an exothermic reaction.",
      "Acid + Base → Salt + Water + Heat energy",
      "All four products are formed in a neutralization reaction.",
      "The reaction releases heat, making it exothermic."
    ],
    "finalAnswer": "D) Salt, water, and heat",
    "isCompetencyBased": true,
    "pyqYear": "2021",
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 InText"
  },
  {
    "id": "ABS2-032",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Properties of Acids and Bases",
    "section": "B",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Analysing",
    "questionText": "Assertion (A): All salts are ionic compounds.\nReason (R): Salts are formed by neutralization of acids and bases, which are ionic in nature.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "Assertion: Salts are ionic compounds formed between cations and anions.",
      "Reason: Acids and bases undergo neutralization to form salts.",
      "Most salts are indeed ionic in nature.",
      "The reason correctly explains why salts are ionic."
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": "2022",
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 Exercise"
  },
  {
    "id": "ABS2-033",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "pH Scale",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Which of the following solutions would require the least amount of base to neutralize 100 mL of it?",
    "options": [
      "A) 0.1 M HCl",
      "B) 0.01 M HCl",
      "C) 1 M HCl",
      "D) 10 M HCl"
    ],
    "answer": "B) 0.01 M HCl",
    "solutionSteps": [
      "The amount of base needed depends on the concentration of acid.",
      "Lower concentration requires less base for complete neutralization.",
      "0.01 M HCl is the most dilute, requiring the least base.",
      "Using Moles = Molarity × Volume, 0.01 M has the fewest moles of HCl."
    ],
    "finalAnswer": "B) 0.01 M HCl",
    "isCompetencyBased": true,
    "pyqYear": "2020",
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 InText"
  },
  {
    "id": "ABS2-034",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Salts and their Properties",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Which salt is formed when H₂SO₄ reacts with NaOH?",
    "options": [
      "A) NaSO₄",
      "B) Na₂SO₄",
      "C) NaHSO₄",
      "D) Na₃SO₄"
    ],
    "answer": "B) Na₂SO₄",
    "solutionSteps": [
      "H₂SO₄ is a diprotic acid (has 2 H⁺ ions).",
      "NaOH is a monobasic base.",
      "Complete neutralization: H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O",
      "The salt formed is sodium sulfate, Na₂SO₄."
    ],
    "finalAnswer": "B) Na₂SO₄",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 Exercise"
  },
  {
    "id": "ABS2-035",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Properties of Acids and Bases",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A student adds 10 drops of phenolphthalein to a colorless solution and observes that it turns pink. What can you conclude about the nature of the solution? Give reasons.",
    "options": [],
    "answer": "The solution is basic (alkaline). Phenolphthalein changes color from colorless to pink in basic solutions with pH > 8.2.",
    "solutionSteps": [
      "Phenolphthalein is an indicator that is colorless in acidic and neutral solutions.",
      "Phenolphthalein turns pink/magenta in basic solutions (pH > 8.2).",
      "Since the solution turned pink, it must be basic.",
      "The presence of excess OH⁻ ions makes the solution basic."
    ],
    "finalAnswer": "The solution is basic (alkaline). Phenolphthalein changes color from colorless to pink in basic solutions with pH > 8.2.",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 InText"
  },
  {
    "id": "ABS2-036",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "pH Scale",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "How would you determine whether a given salt solution is acidic, basic, or neutral using pH paper?",
    "options": [],
    "answer": "Dip pH paper into the salt solution, observe the color change, and compare it with the standard color chart. The color will indicate the pH value, showing whether the solution is acidic (pH < 7), neutral (pH = 7), or basic (pH > 7).",
    "solutionSteps": [
      "Dip the pH paper in the salt solution.",
      "Observe the color change on the pH paper.",
      "Compare the color with the standard color scale.",
      "If pH < 7: acidic, pH = 7: neutral, pH > 7: basic"
    ],
    "finalAnswer": "Dip pH paper into the salt solution, observe the color change, and compare it with the standard color chart. The color will indicate the pH value, showing whether the solution is acidic (pH < 7), neutral (pH = 7), or basic (pH > 7).",
    "isCompetencyBased": true,
    "pyqYear": "2019",
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 InText"
  },
  {
    "id": "ABS2-037",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Neutralisation",
    "section": "C",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Analysing",
    "questionText": "Assertion (A): Neutralization reactions are always exothermic.\nReason (R): The breaking of bonds requires energy while formation of bonds releases energy, and in neutralization, bond formation exceeds bond breaking.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "Neutralization: H⁺ + OH⁻ → H₂O + Heat",
      "Formation of water (strong O-H bonds) releases significant energy.",
      "This makes the reaction exothermic (releases heat).",
      "The reason correctly explains why the reaction is exothermic."
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": "2024",
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 InText"
  },
  {
    "id": "ABS2-038",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Salts and their Properties",
    "section": "C",
    "marks": 2,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "A salt is formed from a weak acid and a strong base. Predict whether the salt solution will be acidic, basic, or neutral. Explain your reasoning.",
    "options": [],
    "answer": "The salt solution will be basic because the anion from the weak acid undergoes hydrolysis with water, producing OH⁻ ions and making the solution basic.",
    "solutionSteps": [
      "When a weak acid and strong base form a salt, the anion from the weak acid hydrolyzes.",
      "The anion will accept H⁺ from water: A⁻ + H₂O ⇌ HA + OH⁻",
      "This hydrolysis produces OH⁻ ions, making the solution basic.",
      "Example: CH₃COO⁻ (from weak acid CH₃COOH) + H₂O → CH₃COOH + OH⁻"
    ],
    "finalAnswer": "The salt solution will be basic because the anion from the weak acid undergoes hydrolysis with water, producing OH⁻ ions and making the solution basic.",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 Exercise"
  },
  {
    "id": "ABS2-039",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Properties of Acids and Bases",
    "section": "C",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "When dilute H₂SO₄ is added to BaCl₂ solution, a white precipitate forms. This white precipitate is:",
    "options": [
      "A) BaSO₃",
      "B) BaSO₄",
      "C) HCl",
      "D) H₂SO₄"
    ],
    "answer": "B) BaSO₄",
    "solutionSteps": [
      "H₂SO₄ + BaCl₂ → BaSO₄↓ + 2HCl",
      "Barium sulfate (BaSO₄) is sparingly soluble in water.",
      "It forms a white precipitate due to its low solubility.",
      "This is a classic double displacement reaction."
    ],
    "finalAnswer": "B) BaSO₄",
    "isCompetencyBased": true,
    "pyqYear": "2020",
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 InText"
  },
  {
    "id": "ABS2-040",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "pH Scale",
    "section": "C",
    "marks": 2,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Applying",
    "questionText": "A solution of sodium carbonate (Na₂CO₃) has a pH of 11.6. Explain why the pH is basic even though no base was directly added to the solution.",
    "options": [],
    "answer": "Although no base was directly added, the carbonate ion (CO₃²⁻) from the salt undergoes hydrolysis with water, producing hydroxide ions (OH⁻). This makes the solution basic with pH > 7.",
    "solutionSteps": [
      "Na₂CO₃ is a salt of a weak acid (H₂CO₃) and strong base (NaOH).",
      "The carbonate ion (CO₃²⁻) hydrolyzes with water: CO₃²⁻ + H₂O ⇌ HCO₃⁻ + OH⁻",
      "This produces OH⁻ ions, making the solution basic.",
      "Greater concentration of OH⁻ than H⁺ results in pH > 7."
    ],
    "finalAnswer": "Although no base was directly added, the carbonate ion (CO₃²⁻) from the salt undergoes hydrolysis with water, producing hydroxide ions (OH⁻). This makes the solution basic with pH > 7.",
    "isCompetencyBased": true,
    "pyqYear": "2022",
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 Exercise"
  },
  {
    "id": "ABS2-041",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Neutralisation",
    "section": "C",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Assertion (A): When HCl is neutralized by NaOH, the resulting solution is always neutral.\nReason (R): The neutralization of a strong acid by a strong base produces a salt that does not undergo hydrolysis.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "HCl (strong acid) + NaOH (strong base) → NaCl (salt) + H₂O",
      "NaCl is a salt of strong acid and strong base.",
      "Neither Na⁺ nor Cl⁻ undergoes hydrolysis.",
      "The solution remains neutral (pH = 7).",
      "The reason correctly explains this phenomenon."
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": "2024",
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 Exercise"
  },
  {
    "id": "ABS2-042",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Salts and their Properties",
    "section": "E",
    "marks": 4,
    "format": "Case-Based",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "A laboratory conducted an experiment on three salt solutions: (i) NaCl, (ii) Na₂CO₃, and (iii) NH₄Cl. They tested each solution using pH paper and observed the following pH values: NaCl (pH = 7), Na₂CO₃ (pH = 11), and NH₄Cl (pH = 5).\n\n(a) Why does NaCl solution have a neutral pH?\n(b) Explain why Na₂CO₃ solution is basic.\n(c) Write the hydrolysis equation for NH₄Cl.\n(d) Which salt solution would require the least amount of acid to neutralize? Why?",
    "options": [],
    "answer": "(a) NaCl produces no hydrolysis products as it's from a strong acid-strong base pair. (b) Carbonate ion hydrolyzes: CO₃²⁻ + H₂O ⇌ HCO₃⁻ + OH⁻, producing OH⁻ ions. (c) NH₄⁺ + H₂O ⇌ NH₃ + H₃O⁺. (d) NaCl solution would require the least amount of acid as it's already neutral.",
    "solutionSteps": [
      "Part (a): NaCl is from strong acid (HCl) and strong base (NaOH). Neither ion hydrolyzes, so pH = 7.",
      "Part (b): Na₂CO₃ is from weak acid (H₂CO₃) and strong base. CO₃²⁻ + H₂O ⇌ HCO₃⁻ + OH⁻",
      "Part (c): NH₄Cl is from weak base (NH₃) and strong acid. NH₄⁺ + H₂O ⇌ NH₃ + H₃O⁺ (acidic)",
      "Part (d): NaCl is already neutral, needs no acid. NH₄Cl is acidic, needs some base. Na₂CO₃ is basic, needs the most acid."
    ],
    "finalAnswer": "(a) NaCl produces no hydrolysis products as it's from a strong acid-strong base pair. (b) Carbonate ion hydrolyzes: CO₃²⁻ + H₂O ⇌ HCO₃⁻ + OH⁻, producing OH⁻ ions. (c) NH₄⁺ + H₂O ⇌ NH₃ + H₃O⁺. (d) NaCl solution would require the least amount of acid as it's already neutral.",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 Exercise"
  },
  {
    "id": "ABS2-043",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Properties of Acids and Bases",
    "section": "D",
    "marks": 5,
    "format": "Long",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Explain the concept of pH and how it is related to the concentration of hydrogen ions (H⁺) in a solution. Give examples of solutions with different pH values and explain the nature of each.",
    "options": [],
    "answer": "pH measures hydrogen ion concentration using pH = -log[H⁺]. The scale ranges from 0-14: pH < 7 is acidic (high [H⁺]), pH = 7 is neutral ([H⁺] = [OH⁻]), and pH > 7 is basic (low [H⁺]). Examples: HCl (strongly acidic), water (neutral), NaOH (strongly basic).",
    "solutionSteps": [
      "pH is defined as the negative logarithm of hydrogen ion concentration: pH = -log[H⁺]",
      "As [H⁺] increases, pH decreases (inverse relationship).",
      "When [H⁺] = 10⁻¹ M, pH = 1 (strongly acidic)",
      "When [H⁺] = 10⁻⁷ M, pH = 7 (neutral)",
      "When [H⁺] = 10⁻¹³ M, pH = 13 (strongly basic)",
      "Examples: HCl (pH 0-1), lemon juice (pH 2), milk (pH 6.5), water (pH 7), baking soda (pH 8.3), ammonia (pH 11), NaOH (pH 13-14)"
    ],
    "finalAnswer": "pH measures hydrogen ion concentration using pH = -log[H⁺]. The scale ranges from 0-14: pH < 7 is acidic (high [H⁺]), pH = 7 is neutral ([H⁺] = [OH⁻]), and pH > 7 is basic (low [H⁺]). Examples: HCl (strongly acidic), water (neutral), NaOH (strongly basic).",
    "isCompetencyBased": true,
    "pyqYear": "2021",
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 InText"
  },
  {
    "id": "ABS2-044",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Neutralisation",
    "section": "D",
    "marks": 5,
    "format": "Long",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "Describe the complete neutralization process when nitric acid (HNO₃) reacts with calcium hydroxide [Ca(OH)₂]. Write the balanced chemical equation, explain the reaction mechanism, and discuss the nature of the salt formed. What practical applications does this reaction have?",
    "options": [],
    "answer": "The balanced equation is: 2HNO₃ + Ca(OH)₂ → Ca(NO₃)₂ + 2H₂O. The mechanism involves H⁺ ions from HNO₃ reacting with OH⁻ ions from Ca(OH)₂ to form water, with Ca²⁺ and NO₃⁻ ions remaining as a neutral salt. Applications include agricultural lime treatment, fertilizer production, and neutralization of acidic waste.",
    "solutionSteps": [
      "HNO₃ is a strong monobasic acid; Ca(OH)₂ is a strong dibasic base.",
      "Balanced equation: 2HNO₃ + Ca(OH)₂ → Ca(NO₃)₂ + 2H₂O",
      "Ionic equation: 2H⁺ + 2NO₃⁻ + Ca²⁺ + 2OH⁻ → Ca²⁺ + 2NO₃⁻ + 2H₂O",
      "Net ionic equation: H⁺ + OH⁻ → H₂O",
      "Ca(NO₃)₂ is a neutral salt (strong acid + strong base), pH = 7.",
      "The reaction is exothermic, releasing heat energy.",
      "Applications: Soil treatment in agriculture, fertilizer production, waste neutralization."
    ],
    "finalAnswer": "The balanced equation is: 2HNO₃ + Ca(OH)₂ → Ca(NO₃)₂ + 2H₂O. The mechanism involves H⁺ ions from HNO₃ reacting with OH⁻ ions from Ca(OH)₂ to form water, with Ca²⁺ and NO₃⁻ ions remaining as a neutral salt. Applications include agricultural lime treatment, fertilizer production, and neutralization of acidic waste.",
    "isCompetencyBased": true,
    "pyqYear": "2022",
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 Exercise"
  },
  {
    "id": "ABS2-045",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Properties of Acids and Bases",
    "section": "D",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "Which of the following is a weak base?",
    "options": [
      "A) NaOH",
      "B) KOH",
      "C) NH₃",
      "D) Ca(OH)₂"
    ],
    "answer": "C) NH₃",
    "solutionSteps": [
      "Strong bases: NaOH, KOH, Ca(OH)₂ - fully ionize in water",
      "Weak bases: NH₃ (ammonia) - partially ionizes in water",
      "NH₃ + H₂O ⇌ NH₄⁺ + OH⁻ (reversible reaction)"
    ],
    "finalAnswer": "C) NH₃",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 InText"
  },
  {
    "id": "ABS2-046",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "pH Scale",
    "section": "D",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "What happens to the pH when 1 mL of water is added to 100 mL of 0.1 M HCl solution?",
    "options": [
      "A) pH increases",
      "B) pH decreases",
      "C) pH remains constant",
      "D) pH becomes zero"
    ],
    "answer": "A) pH increases",
    "solutionSteps": [
      "Adding water dilutes the acid solution.",
      "Dilution decreases [H⁺] concentration.",
      "Lower [H⁺] means higher pH value.",
      "Therefore, pH increases (moves towards neutral/basic direction)."
    ],
    "finalAnswer": "A) pH increases",
    "isCompetencyBased": true,
    "pyqYear": "2025",
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 InText"
  },
  {
    "id": "ABS2-047",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Salts and their Properties",
    "section": "D",
    "marks": 2,
    "format": "Short",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "What is the difference between a salt and a base? Give one example of each.",
    "options": [],
    "answer": "A salt is an ionic compound formed from the neutralization of an acid and a base, while a base is a compound that produces hydroxide ions in water. Example of salt: NaCl. Example of base: NaOH.",
    "solutionSteps": [
      "Base: Compound that produces OH⁻ ions in water. Example: NaOH, KOH, Ca(OH)₂",
      "Salt: Ionic compound formed by neutralization of acid and base. Example: NaCl, CuSO₄, Na₂CO₃",
      "All bases are not salts; all salts are not bases.",
      "Key difference: Salts result from complete neutralization reactions."
    ],
    "finalAnswer": "A salt is an ionic compound formed from the neutralization of an acid and a base, while a base is a compound that produces hydroxide ions in water. Example of salt: NaCl. Example of base: NaOH.",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 InText"
  },
  {
    "id": "ABS2-048",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Properties of Acids and Bases",
    "section": "D",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A student accidentally spills concentrated sulfuric acid on the laboratory bench. Explain the steps to safely neutralize the acid using a commonly available base.",
    "options": [],
    "answer": "Sprinkle sodium bicarbonate (baking soda) gradually over the spilled acid. It reacts safely: 2NaHCO₃ + H₂SO₄ → Na₂SO₄ + 2H₂O + CO₂. This method is safe because NaHCO₃ is a weak base that doesn't cause violent reactions or excessive heating.",
    "solutionSteps": [
      "Never pour water directly on concentrated H₂SO₄ as it's highly exothermic.",
      "Use sodium bicarbonate (NaHCO₃) - a weak base that reacts safely.",
      "Reaction: 2NaHCO₃ + H₂SO₄ → Na₂SO₄ + 2H₂O + CO₂↑",
      "Sprinkle NaHCO₃ gradually over the spill to neutralize.",
      "Clean with water after complete neutralization.",
      "Avoid using strong bases directly as they can cause splashing."
    ],
    "finalAnswer": "Sprinkle sodium bicarbonate (baking soda) gradually over the spilled acid. It reacts safely: 2NaHCO₃ + H₂SO₄ → Na₂SO₄ + 2H₂O + CO₂. This method is safe because NaHCO₃ is a weak base that doesn't cause violent reactions or excessive heating.",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 InText"
  },
  {
    "id": "ABS2-049",
    "subject": "Science",
    "topicKey": "Acids, Bases and Salts",
    "subtopic": "Neutralisation",
    "section": "D",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "In a neutralization reaction between HNO₃ and NH₃, the salt formed is NH₄NO₃. What is the nature of this salt solution?",
    "options": [
      "A) Acidic",
      "B) Basic",
      "C) Neutral",
      "D) Cannot be determined"
    ],
    "answer": "A) Acidic",
    "solutionSteps": [
      "HNO₃ is a strong acid; NH₃ is a weak base.",
      "NH₄NO₃ is a salt of strong acid and weak base.",
      "NH₄⁺ undergoes hydrolysis: NH₄⁺ + H₂O ⇌ NH₃ + H₃O⁺",
      "Hydrolysis produces H₃O⁺ ions, making the solution acidic.",
      "pH < 7 for NH₄NO₃ solution."
    ],
    "finalAnswer": "A) Acidic",
    "isCompetencyBased": true,
    "pyqYear": "2024",
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch2 Exercise"
  }
];
