import type { CanonicalQuestion } from "../../types";

export const CC2_PACK2: CanonicalQuestion[] = [
  {
    "id": "CC2-001",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Bonding in Carbon",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "Carbon forms four covalent bonds because it has:",
    "options": [
      "2 electrons in valence shell",
      "4 electrons in valence shell",
      "6 electrons in valence shell",
      "8 electrons in valence shell"
    ],
    "answer": "4 electrons in valence shell",
    "solutionSteps": [
      "Carbon atomic number is 6",
      "Electronic configuration: 2,4",
      "4 electrons in outermost shell (valence shell)",
      "Forms 4 covalent bonds to complete octet"
    ],
    "finalAnswer": "4 electrons in valence shell",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch4 InText"
  },
  {
    "id": "CC2-002",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Bonding in Carbon",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "The bond between two carbon atoms in ethene (C2H4) is:",
    "options": [
      "Single covalent bond",
      "Double covalent bond",
      "Triple covalent bond",
      "Coordinate bond"
    ],
    "answer": "Double covalent bond",
    "solutionSteps": [
      "Ethene: C=C with 4 hydrogens",
      "Each carbon shares 2 electron pairs with other carbon",
      "This forms double bond (C=C)"
    ],
    "finalAnswer": "Double covalent bond",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch4 InText"
  },
  {
    "id": "CC2-003",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Homologous Series",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "Which of the following is a characteristic of homologous series?",
    "options": [
      "All members have different functional groups",
      "Members differ by CH2 unit",
      "All members have same chemical properties",
      "Members have no common general formula"
    ],
    "answer": "Members differ by CH2 unit",
    "solutionSteps": [
      "Homologous series: consecutive organic compounds",
      "Differ by one -CH2- group",
      "Example: CH4, C2H6, C3H8 differ by CH2",
      "Same functional group, similar properties"
    ],
    "finalAnswer": "Members differ by CH2 unit",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch4 Exercise"
  },
  {
    "id": "CC2-004",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Homologous Series",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "The general formula for alkanes is:",
    "options": [
      "CnH2n",
      "CnH2n+2",
      "CnH2n-2",
      "CnHn"
    ],
    "answer": "CnH2n+2",
    "solutionSteps": [
      "Alkanes: saturated hydrocarbons",
      "Single bonds only",
      "Methane: CH4 = C1H2(1)+2 = C1H4 ✓",
      "Ethane: C2H6 = C2H2(2)+2 = C2H6 ✓"
    ],
    "finalAnswer": "CnH2n+2",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch4 InText"
  },
  {
    "id": "CC2-005",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Nomenclature",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "The IUPAC name of CH3-CH2-CH2-CH3 is:",
    "options": [
      "Butane",
      "Propane",
      "Pentane",
      "Methane"
    ],
    "answer": "Butane",
    "solutionSteps": [
      "Count carbon atoms: 4",
      "All single bonds",
      "Prefix for 4 carbons: but-",
      "Suffix for alkane: -ane",
      "Name: Butane"
    ],
    "finalAnswer": "Butane",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch4 InText"
  },
  {
    "id": "CC2-006",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Nomenclature",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "What is the IUPAC name of the compound CH2=CH-CH3?",
    "options": [
      "Propane",
      "Propene",
      "Propyne",
      "Prop-2-ene"
    ],
    "answer": "Propene",
    "solutionSteps": [
      "3 carbon atoms present",
      "Double bond between C1 and C2",
      "Prefix: prop-",
      "Suffix for double bond: -ene",
      "Name: Propene (double bond position 1 is implicit)"
    ],
    "finalAnswer": "Propene",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch4 Exercise"
  },
  {
    "id": "CC2-007",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Chemical Properties",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Combustion of alkanes is a/an:",
    "options": [
      "Addition reaction",
      "Substitution reaction",
      "Oxidation reaction",
      "Elimination reaction"
    ],
    "answer": "Oxidation reaction",
    "solutionSteps": [
      "CH4 + 2O2 → CO2 + 2H2O",
      "Carbon loses electrons (oxidized)",
      "Oxygen gains electrons (reduced)",
      "This is redox/oxidation reaction"
    ],
    "finalAnswer": "Oxidation reaction",
    "isCompetencyBased": true,
    "pyqYear": "2021",
    "pyqSet": "Set-2",
    "ncertRef": "NCERT Ch4 Exercise"
  },
  {
    "id": "CC2-008",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Chemical Properties",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Addition reaction occurs in:",
    "options": [
      "Alkanes only",
      "Alkenes and alkynes",
      "Alcohols only",
      "Carboxylic acids"
    ],
    "answer": "Alkenes and alkynes",
    "solutionSteps": [
      "Addition requires unsaturation (C=C or C≡C)",
      "Alkenes: contain C=C double bonds",
      "Alkynes: contain C≡C triple bonds",
      "H2, Br2, HCl can add across these bonds",
      "Alkanes cannot undergo addition (saturated)"
    ],
    "finalAnswer": "Alkenes and alkynes",
    "isCompetencyBased": true,
    "pyqYear": "2022",
    "pyqSet": "Set-1",
    "ncertRef": "NCERT Ch4 InText"
  },
  {
    "id": "CC2-009",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Chemical Properties",
    "section": "B",
    "marks": 1,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Write a balanced chemical equation for the combustion of ethane (C2H6).",
    "options": [],
    "answer": "2C2H6 + 7O2 → 4CO2 + 6H2O",
    "solutionSteps": [
      "Ethane: C2H6",
      "Complete combustion produces CO2 and H2O",
      "Balance carbon: 2 on left, need 4CO2",
      "Balance hydrogen: 6 on left, need 6H2O",
      "Balance oxygen: 4(2) + 6(1) = 14, need 7O2"
    ],
    "finalAnswer": "2C2H6 + 7O2 → 4CO2 + 6H2O",
    "isCompetencyBased": true,
    "pyqYear": "2020",
    "pyqSet": "Set-2",
    "ncertRef": "NCERT Ch4 Exercise"
  },
  {
    "id": "CC2-010",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Chemical Properties",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Substitution reaction in alkanes is facilitated by:",
    "options": [
      "Heat and sunlight",
      "Catalyst",
      "Pressure",
      "Moisture"
    ],
    "answer": "Heat and sunlight",
    "solutionSteps": [
      "CH4 + Cl2 → CH3Cl + HCl (substitution)",
      "This requires UV light or heat",
      "Breaks C-H or Cl-Cl bonds",
      "Homolytic fission occurs with light/heat"
    ],
    "finalAnswer": "Heat and sunlight",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": "Set-1",
    "ncertRef": "NCERT Ch4 InText"
  },
  {
    "id": "CC2-011",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Bonding in Carbon",
    "section": "C",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Analysing",
    "questionText": "Assertion (A): Diamond is extremely hard. Reason (R): Each carbon atom in diamond is bonded to four other carbon atoms through strong covalent bonds in a rigid 3D structure.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "Diamond: allotrope of carbon",
      "Each C bonded to 4 other C atoms tetrahedrally",
      "Strong C-C covalent bonds throughout",
      "3D network structure provides rigidity",
      "Explains extreme hardness of diamond"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": "2024",
    "pyqSet": "Set-1",
    "ncertRef": "NCERT Ch4 InText"
  },
  {
    "id": "CC2-012",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Homologous Series",
    "section": "C",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Analysing",
    "questionText": "Assertion (A): Ethane and propane have similar chemical properties. Reason (R): Both belong to the same homologous series and contain only C-C and C-H single bonds.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "Ethane (C2H6) and propane (C3H8) are alkanes",
      "Both in same homologous series",
      "Both contain only single bonds (C-C, C-H)",
      "Same functional group → similar reactions",
      "Both undergo combustion, substitution similarly"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": "2025",
    "pyqSet": "Set-2",
    "ncertRef": "NCERT Ch4 Exercise"
  },
  {
    "id": "CC2-013",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Chemical Properties",
    "section": "C",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "Assertion (A): Ethene (C2H4) readily decolorizes bromine water. Reason (R): Ethene has a carbon-carbon triple bond that breaks easily to accommodate new atoms.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "A is true, R is false.",
    "solutionSteps": [
      "Ethene (C2H4) does decolorize Br2/water (true)",
      "But ethene has C=C (double bond), not triple bond",
      "Addition of Br2: C2H4 + Br2 → C2H4Br2",
      "Double bond is unsaturated, breaks for addition",
      "So A is true but R is false"
    ],
    "finalAnswer": "A is true, R is false.",
    "isCompetencyBased": true,
    "pyqYear": "2019",
    "pyqSet": "Set-1",
    "ncertRef": "NCERT Ch4 Exercise"
  },
  {
    "id": "CC2-014",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Soaps and Detergents",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "The cleaning action of soap is due to its:",
    "options": [
      "Acidic nature",
      "Basic nature",
      "Amphoteric nature",
      "Amphipathic nature"
    ],
    "answer": "Amphipathic nature",
    "solutionSteps": [
      "Soap: long chain carboxylic acid salt",
      "Has hydrophobic tail (nonpolar) and hydrophilic head (polar)",
      "Amphipathic: has both hydrophobic and hydrophilic parts",
      "Hydrophobic tail interacts with oil/grease",
      "Hydrophilic head remains in water",
      "This allows soap to remove dirt"
    ],
    "finalAnswer": "Amphipathic nature",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": "Set-2",
    "ncertRef": "NCERT Ch4 InText"
  },
  {
    "id": "CC2-015",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Soaps and Detergents",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Why does soap form scum in hard water but detergents don't?",
    "options": [
      "Soap is ionic, detergent is covalent",
      "Soap reacts with Ca2+/Mg2+ ions; detergents don't",
      "Soap is not polar, detergent is polar",
      "Detergent is stronger than soap"
    ],
    "answer": "Soap reacts with Ca2+/Mg2+ ions; detergents don't",
    "solutionSteps": [
      "Hard water contains Ca2+ and Mg2+ ions",
      "Soap + Ca2+/Mg2+ → insoluble salt (scum)",
      "Example: 2C17H35COO-Na+ + Ca2+ → (C17H35COO-)2Ca + 2Na+",
      "Detergents: synthetic, don't form scum with hard water",
      "Detergent-metal compounds remain soluble"
    ],
    "finalAnswer": "Soap reacts with Ca2+/Mg2+ ions; detergents don't",
    "isCompetencyBased": true,
    "pyqYear": "2021",
    "pyqSet": "Set-1",
    "ncertRef": "NCERT Ch4 Exercise"
  },
  {
    "id": "CC2-016",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Soaps and Detergents",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "The general formula for soap is:",
    "options": [
      "CnH2n+1COOH",
      "CnH2n+1COONa",
      "CnH2nOH",
      "CnH2n+2O"
    ],
    "answer": "CnH2n+1COONa",
    "solutionSteps": [
      "Soap: sodium salt of long-chain carboxylic acid",
      "Long hydrophobic chain: CnH2n+1-",
      "Carboxylate head: -COO-Na+",
      "Complete formula: CnH2n+1COONa",
      "Example: Sodium stearate C17H35COONa"
    ],
    "finalAnswer": "CnH2n+1COONa",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch4 InText"
  },
  {
    "id": "CC2-017",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Nomenclature",
    "section": "C",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Applying",
    "questionText": "The IUPAC name of the compound (CH3)2CHCH2CH3 is:",
    "options": [
      "Pentane",
      "2-Methylbutane",
      "3-Methylbutane",
      "Isopentane"
    ],
    "answer": "2-Methylbutane",
    "solutionSteps": [
      "Structure: CH3-CH(CH3)-CH2-CH3",
      "Identify longest carbon chain: 4 carbons = butane",
      "Methyl group attached to C2",
      "Position from nearer end: position 2",
      "Name: 2-Methylbutane (common: isobutane, but IUPAC: 2-methylbutane)"
    ],
    "finalAnswer": "2-Methylbutane",
    "isCompetencyBased": true,
    "pyqYear": "2024",
    "pyqSet": "Set-2",
    "ncertRef": "NCERT Ch4 Exercise"
  },
  {
    "id": "CC2-018",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Bonding in Carbon",
    "section": "C",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Why is graphite softer than diamond despite both being allotropes of carbon?",
    "options": [
      "Graphite has ionic bonds",
      "Graphite has weak van der Waals forces between layers",
      "Graphite has fewer carbon atoms",
      "Graphite has polar bonds"
    ],
    "answer": "Graphite has weak van der Waals forces between layers",
    "solutionSteps": [
      "Graphite: layered structure",
      "Within layers: strong C-C covalent bonds",
      "Between layers: weak van der Waals forces",
      "Layers can slide over each other easily",
      "Diamond: rigid 3D network of strong bonds",
      "No weak layers in diamond"
    ],
    "finalAnswer": "Graphite has weak van der Waals forces between layers",
    "isCompetencyBased": true,
    "pyqYear": "2025",
    "pyqSet": "Set-1",
    "ncertRef": "NCERT Ch4 InText"
  },
  {
    "id": "CC2-019",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Chemical Properties",
    "section": "C",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Applying",
    "questionText": "When ethyne (C2H2) is passed through bromine water, it:",
    "options": [
      "Remains colorless",
      "Decolorizes immediately (1,2-dibromination only)",
      "Decolorizes in two stages (tetrabromo product)",
      "Forms a precipitate"
    ],
    "answer": "Decolorizes in two stages (tetrabromo product)",
    "solutionSteps": [
      "Ethyne: HC≡CH (triple bond)",
      "First addition: HC≡CH + Br2 → CHBr=CHBr",
      "Decolorizes bromine (brown → colorless)",
      "Second addition: CHBr=CHBr + Br2 → CHBr2-CHBr2",
      "Can undergo two consecutive additions",
      "Triple bond allows two molecules of Br2 to add"
    ],
    "finalAnswer": "Decolorizes in two stages (tetrabromo product)",
    "isCompetencyBased": true,
    "pyqYear": "2022",
    "pyqSet": "Set-2",
    "ncertRef": "NCERT Ch4 Exercise"
  },
  {
    "id": "CC2-020",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Soaps and Detergents",
    "section": "E",
    "marks": 4,
    "format": "Case-Based",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Priya wants to clean her clothes. She uses soap for washing in soft water from her well, but the soap doesn't work well in hard water from a tube. She is confused why the same soap works differently in different water.\n\n(a) What is the composition of hard water?\n(b) What is the chemical formula of soap and what happens when soap reacts with hard water?\n(c) What is the advantage of using detergent over soap?\n(d) Write the equation for soap reacting with hard water.",
    "options": [],
    "answer": "(a) Ca2+ and Mg2+ ions (b) CnH2n+1COONa; forms insoluble scum (c) Works in hard water (d) 2C17H35COO-Na+ + Ca2+ → (C17H35COO-)2Ca↓ + 2Na+",
    "solutionSteps": [
      "Hard water: contains dissolved Ca2+ and Mg2+ salts",
      "Soap: sodium salt of long-chain carboxylic acid",
      "In hard water: soap + Ca2+/Mg2+ → insoluble salt (scum)",
      "Scum reduces cleaning ability",
      "Detergents: synthetic, sulfonate-based salts",
      "Don't precipitate with Ca2+/Mg2+ ions",
      "Work effectively in both soft and hard water"
    ],
    "finalAnswer": "(a) Ca2+ and Mg2+ ions (b) CnH2n+1COONa; forms insoluble scum (c) Works in hard water (d) 2C17H35COO-Na+ + Ca2+ → (C17H35COO-)2Ca↓ + 2Na+",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": "Set-1",
    "ncertRef": "NCERT Ch4 Exercise"
  },
  {
    "id": "CC2-021",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Chemical Properties",
    "section": "E",
    "marks": 4,
    "format": "Case-Based",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "A student conducts an experiment with three compounds: methane (CH4), ethene (C2H4), and ethyne (C2H2). She burns each in air and also tests their reactions with bromine water.\n\n(a) Write the balanced equations for complete combustion of each compound.\n(b) What observations would be seen when each is added to bromine water?\n(c) Explain why ethane and ethyne show different behaviors with bromine water.\n(d) Which reaction represents oxidation and which represents addition?",
    "options": [],
    "answer": "(a) CH4+2O2→CO2+2H2O; 2C2H4+6O2→4CO2+4H2O; 2C2H2+5O2→4CO2+2H2O (b) CH4: no change; C2H4 & C2H2: brown to colorless (c) Different degrees of unsaturation (d) Combustion=oxidation; Br2=addition",
    "solutionSteps": [
      "Combustion: complete oxidation of organic compounds",
      "Products: CO2 + H2O (complete combustion)",
      "Bromine test: detects unsaturation (C=C, C≡C)",
      "Methane: saturated (no C=C or C≡C), no color change",
      "Ethene: C=C double bond, Br2 adds once, decolorizes immediately",
      "Ethyne: C≡C triple bond, Br2 adds twice, decolorizes in 2 stages",
      "Addition reaction: Br2 adds across double/triple bonds",
      "Oxidation: combustion with O2"
    ],
    "finalAnswer": "(a) CH4+2O2→CO2+2H2O; 2C2H4+6O2→4CO2+4H2O; 2C2H2+5O2→4CO2+2H2O (b) CH4: no change; C2H4 & C2H2: brown to colorless (c) Different degrees of unsaturation (d) Combustion=oxidation; Br2=addition",
    "isCompetencyBased": true,
    "pyqYear": "2024",
    "pyqSet": "Set-1",
    "ncertRef": "NCERT Ch4 Exercise"
  },
  {
    "id": "CC2-022",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Homologous Series, Nomenclature, Chemical Properties",
    "section": "D",
    "marks": 5,
    "format": "Long",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "Carbon forms a vast number of organic compounds. Explain how the properties of organic compounds vary systematically in a homologous series. Take the example of alkanes (CH4, C2H6, C3H8, C4H10) and discuss:\n(a) How does boiling point change in alkanes and why?\n(b) What are the physical and chemical properties that remain similar in alkanes?\n(c) How would you distinguish between saturated and unsaturated hydrocarbons using chemical tests?\n(d) Predict the molecular formula and name of the sixth member of the alkane series.",
    "options": [],
    "answer": "(a) Increases due to stronger van der Waals forces (b) Covalent, saturated, formula CnH2n+2, similar combustion (c) Br2/KMnO4 tests (d) C6H14 (Hexane)",
    "solutionSteps": [
      "(a) Boiling point increases down the series:",
      "CH4 (-162°C) < C2H6 (-89°C) < C3H8 (-42°C) < C4H10 (0°C)",
      "Reason: Increasing molecular size → stronger van der Waals forces",
      "More electrons → stronger dispersion forces",
      "(b) Similar properties:",
      "- All covalent hydrocarbons",
      "- Saturated (only single bonds)",
      "- General formula: CnH2n+2",
      "- Combustion reactions are similar",
      "- Don't decolorize bromine or KMnO4",
      "- Relatively inert (require heat/light for substitution)",
      "- Non-polar in nature",
      "(c) Tests to distinguish:",
      "- Bromine water: Unsaturated decolorizes (brown→colorless), saturated no change",
      "- KMnO4 solution: Unsaturated decolorizes (purple→colorless), saturated no change",
      "- These tests show presence of C=C or C≡C bonds",
      "(d) Sixth member of alkane series:",
      "Pattern: C1H4, C2H6, C3H8, C4H10, C5H12, C6H14",
      "Sixth member: C6H14 (Hexane)",
      "Can have structural isomers like 2-methylpentane, 3-methylpentane, etc."
    ],
    "finalAnswer": "(a) Increases due to stronger van der Waals forces (b) Covalent, saturated, formula CnH2n+2, similar combustion (c) Br2/KMnO4 tests (d) C6H14 (Hexane)",
    "isCompetencyBased": true,
    "pyqYear": "2025",
    "pyqSet": "Set-2",
    "ncertRef": "NCERT Ch4 InText, NCERT Ch4 Exercise"
  },
  {
    "id": "CC2-023",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Bonding in Carbon",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "The bond angle in methane (CH4) is approximately:",
    "options": [
      "90°",
      "109.5°",
      "120°",
      "180°"
    ],
    "answer": "109.5°",
    "solutionSteps": [
      "Methane: tetrahedral structure",
      "Central carbon with 4 hydrogen atoms",
      "Tetrahedral geometry gives 109.5° bond angles",
      "sp3 hybridization of carbon"
    ],
    "finalAnswer": "109.5°",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch4 InText"
  },
  {
    "id": "CC2-024",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Nomenclature",
    "section": "B",
    "marks": 1,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Give the IUPAC name for: CH3-CH2-OH",
    "options": [],
    "answer": "Ethanol",
    "solutionSteps": [
      "2 carbon atoms in main chain",
      "Hydroxyl (-OH) functional group present",
      "Prefix: eth- (2 carbons)",
      "Suffix: -ol (alcohol/hydroxyl group)",
      "Position of -OH: at C1 (implied in alcohols)",
      "Name: Ethanol"
    ],
    "finalAnswer": "Ethanol",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch4 Exercise"
  },
  {
    "id": "CC2-025",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Soaps and Detergents",
    "section": "B",
    "marks": 1,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Why is the hydrophilic head of soap attracted to water while the hydrophobic tail is repelled by water?",
    "options": [],
    "answer": "Hydrophilic head is polar/ionic; hydrophobic tail is nonpolar. Polar dissolves in water; nonpolar doesn't.",
    "solutionSteps": [
      "Soap structure: -COO-Na+ (head) and CnH2n+1- (tail)",
      "Head: negatively charged carboxylate, polar",
      "Polar head forms hydrogen bonds with water",
      "Tail: long hydrocarbon chain, nonpolar",
      "Nonpolar doesn't form H-bonds with water",
      "Principle: 'Like dissolves in like'",
      "Polar solvents dissolve polar solutes",
      "Nonpolar solvents dissolve nonpolar solutes"
    ],
    "finalAnswer": "Hydrophilic head is polar/ionic; hydrophobic tail is nonpolar. Polar dissolves in water; nonpolar doesn't.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch4 Exercise"
  },
  {
    "id": "CC2-026",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Bonding in Carbon",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "Carbon has an atomic number of 6. How many valence electrons does it have?",
    "options": [
      "2",
      "4",
      "6",
      "8"
    ],
    "answer": "4",
    "solutionSteps": [
      "Atomic number of C = 6",
      "Electronic configuration = 2,4",
      "Valence electrons = electrons in outermost shell = 4"
    ],
    "finalAnswer": "4",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch4 InText"
  },
  {
    "id": "CC2-027",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Bonding in Carbon",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "Which type of bond is formed between two carbon atoms in ethane (C₂H₆)?",
    "options": [
      "Ionic bond",
      "Covalent bond",
      "Hydrogen bond",
      "Metallic bond"
    ],
    "answer": "Covalent bond",
    "solutionSteps": [
      "Carbon atoms share electrons to form bonds",
      "In ethane, C-C and C-H bonds are covalent",
      "Both atoms contribute electrons to the shared pair"
    ],
    "finalAnswer": "Covalent bond",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch4 InText"
  },
  {
    "id": "CC2-028",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Bonding in Carbon",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Carbon can form four covalent bonds. This property is known as:",
    "options": [
      "Allotropy",
      "Tetravalency",
      "Catenation",
      "Isomerism"
    ],
    "answer": "Tetravalency",
    "solutionSteps": [
      "Tetravalency refers to the ability of carbon to form 4 covalent bonds",
      "This is due to 4 valence electrons in carbon",
      "Allotropy = different forms of same element",
      "Catenation = chain formation"
    ],
    "finalAnswer": "Tetravalency",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch4 InText"
  },
  {
    "id": "CC2-029",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Bonding in Carbon",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "The ability of carbon to form long chains of atoms is called:",
    "options": [
      "Polymerization",
      "Catenation",
      "Hybridization",
      "Condensation"
    ],
    "answer": "Catenation",
    "solutionSteps": [
      "Catenation is the property of forming long chains",
      "Carbon atoms link with each other via C-C bonds",
      "This creates organic compounds with multiple carbon atoms",
      "Polymerization = formation of polymers from monomers"
    ],
    "finalAnswer": "Catenation",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch4 InText"
  },
  {
    "id": "CC2-030",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Homologous Series",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "What is the molecular formula of the first member of alkane series?",
    "options": [
      "CH₄",
      "C₂H₆",
      "C₃H₈",
      "C₄H₁₀"
    ],
    "answer": "CH₄",
    "solutionSteps": [
      "Alkanes follow the general formula CₙH₂ₙ₊₂",
      "First member: n=1",
      "Formula = C₁H₂(₁)₊₂ = CH₄ (methane)"
    ],
    "finalAnswer": "CH₄",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch4 Exercise"
  },
  {
    "id": "CC2-031",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Homologous Series",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Which of the following is NOT a characteristic of a homologous series?",
    "options": [
      "Same functional group",
      "Differ by CH₂",
      "Same chemical properties",
      "Different physical properties"
    ],
    "answer": "Different physical properties",
    "solutionSteps": [
      "Homologous series have: same general formula, differ by CH₂, same functional group, similar chemical properties",
      "Physical properties (bp, mp, density) vary gradually, not in the same manner",
      "This helps distinguish homologs"
    ],
    "finalAnswer": "Different physical properties",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch4 InText"
  },
  {
    "id": "CC2-032",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Homologous Series",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "If ethane has molecular formula C₂H₆, what is the molecular formula of propane?",
    "options": [
      "C₃H₈",
      "C₃H₆",
      "C₃H₁₀",
      "C₂H₈"
    ],
    "answer": "C₃H₈",
    "solutionSteps": [
      "Propane = ethane + CH₂",
      "C₂H₆ + CH₂ = C₃H₈",
      "Each member of alkane series differs by CH₂ unit"
    ],
    "finalAnswer": "C₃H₈",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch4 Exercise"
  },
  {
    "id": "CC2-033",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Nomenclature",
    "section": "C",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "The IUPAC name of CH₃CH₂OH is:",
    "options": [
      "Methanol",
      "Ethanol",
      "Propanol",
      "Methanal"
    ],
    "answer": "Ethanol",
    "solutionSteps": [
      "CH₃CH₂OH has 2 carbon atoms",
      "Prefix 'Eth' = 2 carbons",
      "Suffix 'ol' = alcohol group (-OH)",
      "Name = Ethanol"
    ],
    "finalAnswer": "Ethanol",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch4 InText"
  },
  {
    "id": "CC2-034",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Nomenclature",
    "section": "C",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "What does the suffix '-oic acid' indicate in organic nomenclature?",
    "options": [
      "Alcohol",
      "Aldehyde",
      "Carboxylic acid",
      "Ketone"
    ],
    "answer": "Carboxylic acid",
    "solutionSteps": [
      "Suffix '-oic acid' denotes carboxylic acid group (-COOH)",
      "Example: Ethanoic acid (acetic acid) = CH₃COOH",
      "'-ol' = alcohol, '-al' = aldehyde, '-one' = ketone"
    ],
    "finalAnswer": "Carboxylic acid",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch4 Exercise"
  },
  {
    "id": "CC2-035",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Nomenclature",
    "section": "C",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Applying",
    "questionText": "Give the IUPAC name of the compound: CH₃-CH(OH)-CH₃",
    "options": [
      "1-Propanol",
      "2-Propanol",
      "Propanone",
      "Propanal"
    ],
    "answer": "2-Propanol",
    "solutionSteps": [
      "Structure has 3 carbons in main chain",
      "Prefix = Prop (3 carbons)",
      "-OH group is on 2nd carbon",
      "Suffix = -an-ol (alcohol)",
      "Name = 2-Propanol (isopropanol)"
    ],
    "finalAnswer": "2-Propanol",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": "Delhi",
    "ncertRef": "NCERT Ch4 Exercise"
  },
  {
    "id": "CC2-036",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Chemical Properties",
    "section": "D",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "What is the product when ethane undergoes combustion?",
    "options": [
      "C and H₂O",
      "CO₂ and H₂O",
      "CO and H₂",
      "C₂H₄ and H₂O"
    ],
    "answer": "CO₂ and H₂O",
    "solutionSteps": [
      "Complete combustion of hydrocarbons produces CO₂ and H₂O",
      "C₂H₆ + 3.5O₂ → 2CO₂ + 3H₂O",
      "This is an oxidation reaction"
    ],
    "finalAnswer": "CO₂ and H₂O",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch4 InText"
  },
  {
    "id": "CC2-037",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Chemical Properties",
    "section": "D",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "When ethene (C₂H₄) reacts with bromine water, the orange color disappears. This indicates:",
    "options": [
      "Addition reaction",
      "Substitution reaction",
      "Oxidation reaction",
      "Polymerization"
    ],
    "answer": "Addition reaction",
    "solutionSteps": [
      "Ethene has a C=C double bond",
      "Br₂ adds across the double bond: C₂H₄ + Br₂ → C₂H₄Br₂",
      "Double bond breaks, Br atoms add",
      "Brown color of Br₂ disappears"
    ],
    "finalAnswer": "Addition reaction",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch4 InText"
  },
  {
    "id": "CC2-038",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Chemical Properties",
    "section": "D",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Ethanol reacts with sodium to produce hydrogen gas. This shows that:",
    "options": [
      "Ethanol is acidic",
      "Ethanol is basic",
      "Ethanol has acidic hydrogen in -OH group",
      "Ethanol undergoes addition"
    ],
    "answer": "Ethanol has acidic hydrogen in -OH group",
    "solutionSteps": [
      "2C₂H₅OH + 2Na → 2C₂H₅ONa + H₂",
      "The H of -OH group reacts with Na",
      "This hydrogen is acidic in nature",
      "Alcohols are weak acids"
    ],
    "finalAnswer": "Ethanol has acidic hydrogen in -OH group",
    "isCompetencyBased": true,
    "pyqYear": "2022",
    "pyqSet": "All India",
    "ncertRef": "NCERT Ch4 Exercise"
  },
  {
    "id": "CC2-039",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Chemical Properties",
    "section": "D",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Which of the following is a substitution reaction characteristic of alkanes?",
    "options": [
      "Burning in air",
      "Adding Br₂ to C=C",
      "Reaction with Cl₂ in sunlight",
      "Polymerization"
    ],
    "answer": "Reaction with Cl₂ in sunlight",
    "solutionSteps": [
      "Alkanes have C-C and C-H single bonds",
      "They undergo substitution, not addition",
      "CH₄ + Cl₂ → CH₃Cl + HCl (in sunlight)",
      "H atom is replaced by Cl atom",
      "Burning = combustion (oxidation)"
    ],
    "finalAnswer": "Reaction with Cl₂ in sunlight",
    "isCompetencyBased": true,
    "pyqYear": "2024",
    "pyqSet": "Delhi",
    "ncertRef": "NCERT Ch4 Exercise"
  },
  {
    "id": "CC2-040",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Soaps and Detergents",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "Soap is the sodium or potassium salt of:",
    "options": [
      "Long-chain carboxylic acids",
      "Short-chain alcohols",
      "Hydrocarbons",
      "Amino acids"
    ],
    "answer": "Long-chain carboxylic acids",
    "solutionSteps": [
      "Soap = Na/K salt of long-chain fatty acids",
      "Fatty acids: C₁₅H₃₁COOH, C₁₇H₃₅COOH, etc.",
      "Produced by saponification of fats/oils",
      "General structure: RCOONa (where R is long alkyl chain)"
    ],
    "finalAnswer": "Long-chain carboxylic acids",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch4 InText"
  },
  {
    "id": "CC2-041",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Soaps and Detergents",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Why does soap not work well in hard water?",
    "options": [
      "Soap decomposes",
      "Soap forms insoluble precipitate with Ca²⁺ and Mg²⁺ ions",
      "Soap reacts with oxygen",
      "Soap becomes more soluble"
    ],
    "answer": "Soap forms insoluble precipitate with Ca²⁺ and Mg²⁺ ions",
    "solutionSteps": [
      "Hard water contains Ca²⁺ and Mg²⁺ ions",
      "2C₁₇H₃₅COONa + Ca²⁺ → (C₁₇H₃₅COO)₂Ca↓ + 2Na⁺",
      "Insoluble precipitate formed = scum",
      "Reduces cleaning efficiency"
    ],
    "finalAnswer": "Soap forms insoluble precipitate with Ca²⁺ and Mg²⁺ ions",
    "isCompetencyBased": true,
    "pyqYear": "2021",
    "pyqSet": "All India",
    "ncertRef": "NCERT Ch4 InText"
  },
  {
    "id": "CC2-042",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Soaps and Detergents",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "What is the advantage of using detergents over soaps?",
    "options": [
      "More biodegradable",
      "Work effectively in hard water",
      "Less expensive",
      "More natural"
    ],
    "answer": "Work effectively in hard water",
    "solutionSteps": [
      "Detergents have sulphonate or sulphate groups",
      "Do not form precipitate with hard water ions",
      "Work well in hard and soft water",
      "Also known as synthetic detergents or soapless soaps"
    ],
    "finalAnswer": "Work effectively in hard water",
    "isCompetencyBased": true,
    "pyqYear": "2025",
    "pyqSet": "Delhi",
    "ncertRef": "NCERT Ch4 Exercise"
  },
  {
    "id": "CC2-043",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Soaps and Detergents",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "How does soap work at the molecular level to remove dirt?",
    "options": [
      "Soap dissolves dirt",
      "Hydrophobic tail enters dirt, hydrophilic head faces water",
      "Soap reacts with dirt",
      "Soap absorbs dirt"
    ],
    "answer": "Hydrophobic tail enters dirt, hydrophilic head faces water",
    "solutionSteps": [
      "Soap molecule has two parts: hydrophobic tail (long alkyl chain), hydrophilic head (COO⁻)",
      "Tail surrounds oil/dirt particle",
      "Head faces water, forms micelle",
      "Dirt particle is suspended in water and removed"
    ],
    "finalAnswer": "Hydrophobic tail enters dirt, hydrophilic head faces water",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch4 InText"
  },
  {
    "id": "CC2-044",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Bonding in Carbon",
    "section": "A",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Assertion (A): Carbon can form up to 4 covalent bonds. Reason (R): Carbon has 4 valence electrons.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "A: Carbon forms 4 covalent bonds - TRUE",
      "R: Carbon has 4 valence electrons - TRUE",
      "Connection: 4 valence electrons enable 4 bonds formation",
      "R explains A correctly"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch4 InText"
  },
  {
    "id": "CC2-045",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Homologous Series",
    "section": "B",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Analysing",
    "questionText": "Assertion (A): All members of alkane series have similar chemical properties. Reason (R): All alkanes have the same functional group.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "A: Similar chemical properties in homologous series - TRUE",
      "R: Same functional group - TRUE",
      "Alkanes have only C-C and C-H bonds (no distinct functional group, but all have same structure)",
      "R explains A"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": "All India",
    "ncertRef": "NCERT Ch4 Exercise"
  },
  {
    "id": "CC2-046",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Chemical Properties",
    "section": "D",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Assertion (A): Alkenes undergo addition reactions readily. Reason (R): Alkenes have a carbon-carbon double bond which is unstable.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "A: Alkenes readily show addition reactions - TRUE",
      "R: C=C bond is electron-rich and can break - TRUE",
      "Double bond is less stable than single bond",
      "Electrons in π-bond easily available for addition",
      "R correctly explains A"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": "2024",
    "pyqSet": "All India",
    "ncertRef": "NCERT Ch4 InText"
  },
  {
    "id": "CC2-047",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Nomenclature",
    "section": "C",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Write the structural formula and IUPAC name for the alcohol having 3 carbon atoms.",
    "options": [],
    "answer": "CH₃-CH(OH)-CH₃; 2-Propanol (also CH₃CH₂CH₂OH; 1-Propanol)",
    "solutionSteps": [
      "3 carbon atoms alcohol = propanol",
      "Two isomers possible:",
      "1) CH₃-CH(OH)-CH₃ = 2-Propanol (secondary alcohol)",
      "2) CH₃-CH₂-CH₂OH = 1-Propanol (primary alcohol)",
      "Most common is 2-propanol (isopropanol)"
    ],
    "finalAnswer": "CH₃-CH(OH)-CH₃; 2-Propanol (also CH₃CH₂CH₂OH; 1-Propanol)",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch4 Exercise"
  },
  {
    "id": "CC2-048",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Chemical Properties",
    "section": "D",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Explain the difference between addition and substitution reactions with one example each.",
    "options": [],
    "answer": "Addition involves breaking of double bonds with atoms adding (C₂H₄ + Br₂ → C₂H₄Br₂); Substitution involves replacement of atoms (CH₄ + Cl₂ → CH₃Cl + HCl)",
    "solutionSteps": [
      "Addition reaction: Double/triple bond breaks, atoms add across",
      "Example: C₂H₄ + Br₂ → C₂H₄Br₂",
      "Substitution reaction: One atom/group replaced by another",
      "Example: CH₄ + Cl₂ → CH₃Cl + HCl (in sunlight)",
      "Alkenes show addition, alkanes show substitution"
    ],
    "finalAnswer": "Addition involves breaking of double bonds with atoms adding (C₂H₄ + Br₂ → C₂H₄Br₂); Substitution involves replacement of atoms (CH₄ + Cl₂ → CH₃Cl + HCl)",
    "isCompetencyBased": true,
    "pyqYear": "2022",
    "pyqSet": "Delhi",
    "ncertRef": "NCERT Ch4 InText"
  },
  {
    "id": "CC2-049",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Soaps and Detergents",
    "section": "E",
    "marks": 4,
    "format": "Case-Based",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "A student tried to wash a greasy plate using soap in hard water. The soap did not work effectively, and a white precipitate formed. Later, the student used a detergent and the plate was cleaned effectively without any precipitate.\n\nA) Why did the soap fail to clean in hard water?\nB) What is the white precipitate formed?\nC) Why does detergent work better in hard water?\nD) Name one advantage and one disadvantage of detergents over soaps.",
    "options": [],
    "answer": "A) Hard water ions form insoluble salts with soap; B) Calcium/magnesium stearate; C) Sulphonate groups don't precipitate; D) Adv-Works in hard water; Disadv-Non-biodegradable",
    "solutionSteps": [
      "A) Hard water contains Ca²⁺ and Mg²⁺",
      "Soap (RCOONa) + Ca²⁺ → (RCOO)₂Ca↓",
      "Precipitate forms, reducing cleaning power",
      "B) White precipitate is calcium or magnesium salt of fatty acid (soap scum)",
      "C) Detergent has sulphonate (-SO₃⁻) or sulphate group",
      "These ions don't form precipitate with Ca²⁺/Mg²⁺",
      "D) Advantages: Works in hard water, better detergency",
      "Disadvantages: Less biodegradable, more expensive, synthetic"
    ],
    "finalAnswer": "A) Hard water ions form insoluble salts with soap; B) Calcium/magnesium stearate; C) Sulphonate groups don't precipitate; D) Adv-Works in hard water; Disadv-Non-biodegradable",
    "isCompetencyBased": true,
    "pyqYear": "2025",
    "pyqSet": "All India",
    "ncertRef": "NCERT Ch4 InText"
  },
  {
    "id": "CC2-050",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Bonding in Carbon and Chemical Properties",
    "section": "A",
    "marks": 5,
    "format": "Long",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "Carbon exhibits unique properties like catenation and tetravalency. Using these properties, explain why carbon forms an enormous variety of compounds. Also, discuss how these properties relate to the structural diversity of carbon compounds.",
    "options": [],
    "answer": "Tetravalency allows formation of 4 bonds with various elements, creating diverse functional groups. Catenation enables long chain/ring formation. Together they produce structural isomerism, chain isomerism, and positional isomerism, resulting in enormous variety of compounds.",
    "solutionSteps": [
      "1. Tetravalency of Carbon:",
      "   - 4 valence electrons enable formation of 4 covalent bonds",
      "   - Can bond with C, H, O, N, S, P, halogens",
      "   - Allows diverse functional groups: -OH, -NH₂, -COOH, -CHO, etc.",
      "2. Catenation:",
      "   - C-C bond is strong and stable",
      "   - Forms long chains and rings",
      "   - Chains can be straight, branched, or cyclic",
      "3. Structural Diversity:",
      "   - Chain isomerism: Different arrangements of same formula",
      "     Example: C₅H₁₂ has 3 isomers (pentane, isopentane, neopentane)",
      "   - Position isomerism: Functional group at different positions",
      "     Example: CH₃CH₂CHO vs CH₃COCH₃ (both C₃H₆O)",
      "   - Functional group isomerism: Different functional groups",
      "4. Result: Millions of organic compounds possible",
      "   From simple (CH₄) to complex (proteins, DNA)"
    ],
    "finalAnswer": "Tetravalency allows formation of 4 bonds with various elements, creating diverse functional groups. Catenation enables long chain/ring formation. Together they produce structural isomerism, chain isomerism, and positional isomerism, resulting in enormous variety of compounds.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch4 InText, NCERT Ch4 Exercise"
  },
  {
    "id": "CC2-051",
    "subject": "Science",
    "topicKey": "Carbon and its Compounds",
    "subtopic": "Homologous Series and Nomenclature",
    "section": "B",
    "marks": 5,
    "format": "Long",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Define a homologous series and state its characteristics. Taking alkane and alkene series as examples, explain how the properties change within a homologous series and what causes these changes. Also, explain why homologous compounds have similar chemical properties.",
    "options": [],
    "answer": "Homologous series = group differing by CH₂ with same formula type and functional group. Physical properties change gradually due to increasing mass and intermolecular forces. Chemical properties remain similar because functional groups are identical, determining reaction behavior.",
    "solutionSteps": [
      "1. Definition of Homologous Series:",
      "   A group of organic compounds with the same general formula, differing by one or more CH₂ units, derived from the same parent compound",
      "2. Characteristics:",
      "   - Same general formula (alkanes: CₙH₂ₙ₊₂)",
      "   - Differ by CH₂ unit in molecular formula",
      "   - Have same functional group",
      "   - Show gradual change in physical properties",
      "   - Similar chemical properties",
      "   - Obtained by same method of preparation",
      "3. Examples:",
      "   Alkanes: CH₄, C₂H₆, C₃H₈, C₄H₁₀",
      "   Alkenes: C₂H₄, C₃H₆, C₄H₈, C₅H₁₀",
      "4. Change in Physical Properties:",
      "   - Boiling point increases (CH₄: -161°C → C₄H₁₀: -0.5°C)",
      "   - Density increases",
      "   - Solubility in water decreases",
      "   - Cause: Increase in mass and intermolecular forces (Van der Waals forces)",
      "5. Similar Chemical Properties:",
      "   - All alkanes: Combustion, substitution with halogens",
      "   - All alkenes: Addition reactions, combustion",
      "   - Reason: Same functional group (C-C or C=C)",
      "   The functional group determines reactivity"
    ],
    "finalAnswer": "Homologous series = group differing by CH₂ with same formula type and functional group. Physical properties change gradually due to increasing mass and intermolecular forces. Chemical properties remain similar because functional groups are identical, determining reaction behavior.",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": "All India",
    "ncertRef": "NCERT Ch4 InText, NCERT Ch4 Exercise"
  }
];
