import type { CanonicalQuestion } from "../../types";

export const HE2_PACK2: CanonicalQuestion[] = [
  {
    "id": "HE2-001",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Mendel Experiments",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "Mendel conducted his experiments on which plant?",
    "options": [
      "Maize",
      "Pea plant",
      "Wheat",
      "Rice"
    ],
    "answer": "Pea plant",
    "solutionSteps": [
      "Mendel chose Pisum sativum (garden pea) for his experiments",
      "It had easily distinguishable traits and short generation time"
    ],
    "finalAnswer": "Pea plant",
    "explanation": "Mendel chose Pisum sativum (garden pea) for his experiments. It had easily distinguishable traits and short generation time. Therefore, the correct answer is Pea plant.",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch9 InText"
  },
  {
    "id": "HE2-002",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Mendel Experiments",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "In Mendel's monohybrid cross, the ratio of dominant to recessive traits in F2 generation is:",
    "options": [
      "1:1",
      "3:1",
      "9:3:3:1",
      "1:2:1"
    ],
    "answer": "3:1",
    "solutionSteps": [
      "In monohybrid cross, Mendel observed phenotypic ratio in F2",
      "Dominant traits appeared 3 times for every 1 recessive trait"
    ],
    "finalAnswer": "3:1",
    "explanation": "In monohybrid cross, Mendel observed phenotypic ratio in F2. Dominant traits appeared 3 times for every 1 recessive trait. Therefore, the correct answer is 3:1.",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch9 InText"
  },
  {
    "id": "HE2-003",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Heredity Rules",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "What is an allele?",
    "options": [
      "Different forms of a gene",
      "A type of chromosome",
      "A protein molecule",
      "A DNA segment without function"
    ],
    "answer": "Different forms of a gene",
    "solutionSteps": [
      "Alleles are alternate forms of the same gene",
      "They control the same trait but produce different effects"
    ],
    "finalAnswer": "Different forms of a gene",
    "explanation": "Alleles are alternate forms of the same gene. They control the same trait but produce different effects. Therefore, the correct answer is Different forms of a gene.",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch9 Exercise"
  },
  {
    "id": "HE2-004",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Heredity Rules",
    "section": "A",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Assertion (A): Homozygous organisms always show dominant traits. Reason (R): Homozygous organisms carry two identical alleles for a trait.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "A is false, R is true.",
    "solutionSteps": [
      "Homozygous means two identical alleles (R is true)",
      "If homozygous recessive (aa), recessive traits appear, not dominant (A is false)",
      "Therefore, A is false but R is true"
    ],
    "finalAnswer": "A is false, R is true.",
    "explanation": "The Assertion contains an incorrect claim. The Reason, however, is a true and valid statement on its own.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch9 InText"
  },
  {
    "id": "HE2-005",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Mendel Experiments",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A tall pea plant (TT) is crossed with a dwarf pea plant (tt). What will be the genotype and phenotype of F1 generation?",
    "options": [],
    "answer": "F1 Genotype: Tt; F1 Phenotype: All tall plants",
    "solutionSteps": [
      "Cross: TT × tt",
      "All F1 offspring receive T from tall parent and t from dwarf parent",
      "Genotype: Tt (100% heterozygous)",
      "Phenotype: All tall (T is dominant over t)"
    ],
    "finalAnswer": "F1 Genotype: Tt; F1 Phenotype: All tall plants",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch9 InText"
  },
  {
    "id": "HE2-006",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Heredity Rules",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Distinguish between dominant and recessive traits with examples.",
    "options": [],
    "answer": "Dominant traits mask recessive traits; recessive only show when homozygous",
    "solutionSteps": [
      "Dominant trait: Expressed in both homozygous and heterozygous individuals",
      "Example: Tall pea plants (TT and Tt)",
      "Recessive trait: Expressed only in homozygous recessive individuals",
      "Example: Dwarf pea plants (tt only)"
    ],
    "finalAnswer": "Dominant traits mask recessive traits; recessive only show when homozygous",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch9 InText"
  },
  {
    "id": "HE2-007",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Sex Determination",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "In humans, which chromosome pair determines sex?",
    "options": [
      "Chromosome 1",
      "Chromosome 21",
      "Chromosome 22",
      "Chromosome 23 (X and Y)"
    ],
    "answer": "Chromosome 23 (X and Y)",
    "solutionSteps": [
      "Humans have 23 pairs of chromosomes",
      "The 23rd pair consists of sex chromosomes: XX (female) or XY (male)"
    ],
    "finalAnswer": "Chromosome 23 (X and Y)",
    "explanation": "Humans have 23 pairs of chromosomes. The 23rd pair consists of sex chromosomes: XX (female) or XY (male). Therefore, the correct answer is Chromosome 23 (X and Y).",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch9 Exercise"
  },
  {
    "id": "HE2-008",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Sex Determination",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A color-blind woman marries a normal man. What will be the phenotype of their sons and daughters?",
    "options": [],
    "answer": "Sons: 100% color-blind; Daughters: 100% normal (carriers)",
    "solutionSteps": [
      "Color-blindness: X-linked recessive trait",
      "Woman: XᶜXᶜ (color-blind), Man: XᴺY (normal)",
      "Daughters: XᴺXᶜ (normal but carriers)",
      "Sons: XᶜY (all color-blind)"
    ],
    "finalAnswer": "Sons: 100% color-blind; Daughters: 100% normal (carriers)",
    "isCompetencyBased": true,
    "pyqYear": "2020",
    "pyqSet": "Set-I",
    "ncertRef": "NCERT Ch9 InText"
  },
  {
    "id": "HE2-009",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Evolution",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "Who gave the theory of evolution by natural selection?",
    "options": [
      "Gregor Mendel",
      "Jean Baptiste Lamarck",
      "Charles Darwin",
      "August Weismann"
    ],
    "answer": "Charles Darwin",
    "solutionSteps": [
      "Charles Darwin proposed the theory of evolution by natural selection",
      "Published in 'On the Origin of Species' (1859)"
    ],
    "finalAnswer": "Charles Darwin",
    "explanation": "Charles Darwin proposed the theory of evolution by natural selection. Published in 'On the Origin of Species' (1859). Therefore, the correct answer is Charles Darwin.",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch9 Exercise"
  },
  {
    "id": "HE2-010",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Evolution",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Vestigial organs are evidence of evolution because they:",
    "options": [
      "Help organisms adapt to new environments",
      "Are non-functional but present in current organisms",
      "Prove Lamarck's theory",
      "Do not exist in any organism"
    ],
    "answer": "Are non-functional but present in current organisms",
    "solutionSteps": [
      "Vestigial organs are reduced in size and function",
      "Examples: Human appendix, wisdom teeth, coccyx",
      "Indicate common ancestry with organisms that used them functionally"
    ],
    "finalAnswer": "Are non-functional but present in current organisms",
    "explanation": "Vestigial organs are reduced in size and function. Examples: Human appendix, wisdom teeth, coccyx. Indicate common ancestry with organisms that used them functionally. Therefore, the correct answer is Are non-functional but present in current organisms.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch9 InText"
  },
  {
    "id": "HE2-011",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Evolution",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "What are homologous structures? Give one example.",
    "options": [],
    "answer": "Similar structures with different functions indicating common ancestry. Example: Arm, wing, flipper",
    "solutionSteps": [
      "Homologous structures: Similar in structure, origin, and embryological development",
      "Different functions due to adaptation to different environments",
      "Example: Human arm, bat wing, whale flipper, horse leg",
      "Indicate common ancestry (divergent evolution)"
    ],
    "finalAnswer": "Similar structures with different functions indicating common ancestry. Example: Arm, wing, flipper",
    "isCompetencyBased": true,
    "pyqYear": "2019",
    "pyqSet": "Set-II",
    "ncertRef": "NCERT Ch9 InText"
  },
  {
    "id": "HE2-012",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Speciation",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "What is speciation?",
    "options": [
      "Extinction of organisms",
      "Formation of new species from existing species",
      "Variation within a species",
      "Mutation in genes"
    ],
    "answer": "Formation of new species from existing species",
    "solutionSteps": [
      "Speciation is the evolutionary process by which new species arise",
      "Results from reproductive isolation and accumulated genetic differences"
    ],
    "finalAnswer": "Formation of new species from existing species",
    "explanation": "Speciation is the evolutionary process by which new species arise. Results from reproductive isolation and accumulated genetic differences. Therefore, the correct answer is Formation of new species from existing species.",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch9 Exercise"
  },
  {
    "id": "HE2-013",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Evolution",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Explain why antibiotic-resistant bacteria develop faster in hospitals.",
    "options": [],
    "answer": "Antibiotics create selection pressure; resistant bacteria survive and reproduce",
    "solutionSteps": [
      "Bacteria with resistance genes survive antibiotic treatment",
      "Non-resistant bacteria are killed by antibiotics",
      "Resistant bacteria multiply rapidly in antibiotic-rich hospital environment",
      "This is natural selection in action demonstrating evolution"
    ],
    "finalAnswer": "Antibiotics create selection pressure; resistant bacteria survive and reproduce",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch9 InText"
  },
  {
    "id": "HE2-014",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Heredity Rules",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "In a dihybrid cross between AaBb × AaBb, what is the probability of getting aabb offspring?",
    "options": [],
    "answer": "1/16 or 6.25%",
    "solutionSteps": [
      "For dihybrid cross: AaBb × AaBb",
      "Probability of aa = 1/4",
      "Probability of bb = 1/4",
      "Probability of aabb = 1/4 × 1/4 = 1/16"
    ],
    "finalAnswer": "1/16 or 6.25%",
    "isCompetencyBased": true,
    "pyqYear": "2021",
    "pyqSet": "Set-I",
    "ncertRef": "NCERT Ch9 InText"
  },
  {
    "id": "HE2-015",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Sex Determination",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Why is the probability of having a male or female child approximately 50% in humans?",
    "options": [],
    "answer": "Equal distribution of X and Y sperm gives 50:50 probability",
    "solutionSteps": [
      "Male: XY produces two types of sperm - X and Y in equal proportion",
      "Female: XX produces only X eggs",
      "X sperm + egg = XX (female)",
      "Y sperm + egg = XY (male)",
      "Equal chance of each type of sperm fertilizing egg"
    ],
    "finalAnswer": "Equal distribution of X and Y sperm gives 50:50 probability",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch9 Exercise"
  },
  {
    "id": "HE2-016",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Evolution",
    "section": "C",
    "marks": 3,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "How do analogous structures differ from homologous structures? Explain with examples.",
    "options": [],
    "answer": "Homologous=similar origin/different function; Analogous=different origin/similar function",
    "solutionSteps": [
      "Homologous structures: Similar origin and embryology, different functions",
      "Examples: Bat wing, human arm, whale flipper (all vertebrate limbs)",
      "Show common ancestry (divergent evolution)",
      "Analogous structures: Different origin and structure, similar function",
      "Examples: Bird wing and insect wing (both for flight)",
      "Show adaptation to similar environments (convergent evolution)"
    ],
    "finalAnswer": "Homologous=similar origin/different function; Analogous=different origin/similar function",
    "isCompetencyBased": true,
    "pyqYear": "2022",
    "pyqSet": "Set-II",
    "ncertRef": "NCERT Ch9 InText"
  },
  {
    "id": "HE2-017",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Heredity Rules",
    "section": "A",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Analysing",
    "questionText": "Assertion (A): A heterozygous tall plant crossed with a homozygous dwarf plant produces 50% tall and 50% dwarf offspring. Reason (R): Heterozygous individual produces two types of gametes.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "Cross: Tt (heterozygous tall) × tt (homozygous dwarf)",
      "Heterozygous Tt produces gametes T and t (R is true)",
      "Offspring: Tt (tall) and tt (dwarf) in 1:1 ratio or 50:50 (A is true)",
      "R correctly explains why A is true"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "explanation": "Both the Assertion and the Reason are correct statements. The Reason directly explains the scientific/mathematical basis that makes the Assertion true, so R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch9 InText"
  },
  {
    "id": "HE2-018",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Evolution",
    "section": "E",
    "marks": 4,
    "format": "Case-Based",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A farmer observed that after using a particular pesticide for several years, it became less effective. Initially, the pesticide killed 99% of insects, but after 5 years, it killed only 10% of the insect population.\n\nQuestion 1: Why did the pesticide become less effective over time?\nQuestion 2: Name the evolutionary mechanism responsible for this change.\nQuestion 3: How can the farmer overcome this problem?",
    "options": [],
    "answer": "1) Resistant insects survived and reproduced; 2) Natural Selection; 3) Rotate pesticides",
    "solutionSteps": [
      "Question 1: Insects with resistance genes survived pesticide exposure and reproduced",
      "Non-resistant insects were eliminated; resistant population increased over generations",
      "Question 2: Natural selection - environmental pressure (pesticide) selected for resistance genes",
      "Question 3: Rotate different pesticides to prevent resistance buildup in one type",
      "Alternative: Use integrated pest management with multiple control methods"
    ],
    "finalAnswer": "1) Resistant insects survived and reproduced; 2) Natural Selection; 3) Rotate pesticides",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": "Set-I",
    "ncertRef": "NCERT Ch9 InText"
  },
  {
    "id": "HE2-019",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Sex Determination",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "In birds, the ZW sex determination system is present. If a female bird is ZW and a male is ZZ, what will be the sex ratio of offspring in ZZ × ZW cross?",
    "options": [
      "100% male",
      "100% female",
      "50% male and 50% female",
      "75% male and 25% female"
    ],
    "answer": "50% male and 50% female",
    "solutionSteps": [
      "Female bird: ZW (can contribute Z or W)",
      "Male bird: ZZ (can contribute only Z)",
      "Offspring: ZZ (male) from Z+Z, ZW (female) from Z+W",
      "Ratio: 1 ZZ : 1 ZW = 50% male : 50% female"
    ],
    "finalAnswer": "50% male and 50% female",
    "explanation": "Female bird: ZW (can contribute Z or W). Male bird: ZZ (can contribute only Z). Offspring: ZZ (male) from Z+Z, ZW (female) from Z+W. Ratio: 1 ZZ : 1 ZW = 50% male : 50% female. Therefore, the correct answer is 50% male and 50% female.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch9 Exercise"
  },
  {
    "id": "HE2-020",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Evolution",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "What are fossils? How do they provide evidence for evolution?",
    "options": [],
    "answer": "Fossils are preserved ancient remains showing gradual evolutionary changes",
    "solutionSteps": [
      "Fossils are preserved remains, impressions, or traces of ancient organisms",
      "Show transitional forms between different species",
      "Demonstrate that organisms have changed over millions of years",
      "Provide chronological sequence of evolution",
      "Example: Fossil evidence shows evolution of horse from small multi-toed ancestor"
    ],
    "finalAnswer": "Fossils are preserved ancient remains showing gradual evolutionary changes",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch9 InText"
  },
  {
    "id": "HE2-021",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Mendel Experiments",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "The law of segregation states that:",
    "options": [
      "Alleles blend together permanently",
      "Alleles separate during gamete formation",
      "Traits from both parents always blend equally",
      "Dominant alleles are always passed to offspring"
    ],
    "answer": "Alleles separate during gamete formation",
    "solutionSteps": [
      "Law of segregation: Mendel's first law",
      "Alleles of a trait separate during meiosis",
      "Each gamete receives only one allele for each trait"
    ],
    "finalAnswer": "Alleles separate during gamete formation",
    "explanation": "Law of segregation: Mendel's first law. Alleles of a trait separate during meiosis. Each gamete receives only one allele for each trait. Therefore, the correct answer is Alleles separate during gamete formation.",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch9 InText"
  },
  {
    "id": "HE2-022",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Speciation",
    "section": "C",
    "marks": 3,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Explain how reproductive isolation leads to speciation. Give an example.",
    "options": [],
    "answer": "Reproductive isolation prevents gene flow; accumulated mutations → new species",
    "solutionSteps": [
      "Reproductive isolation: Populations cannot interbreed",
      "Types: Geographical, behavioral, temporal, genetic isolation",
      "Without gene flow, populations accumulate different mutations",
      "Over time, genetic differences become so large that even if populations meet, they cannot produce fertile offspring",
      "Example: Darwin's finches in Galápagos - different islands isolated populations",
      "Different beak sizes evolved on different islands (reproductive isolation)"
    ],
    "finalAnswer": "Reproductive isolation prevents gene flow; accumulated mutations → new species",
    "isCompetencyBased": true,
    "pyqYear": "2024",
    "pyqSet": "Set-III",
    "ncertRef": "NCERT Ch9 Exercise"
  },
  {
    "id": "HE2-023",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Heredity Rules",
    "section": "E",
    "marks": 4,
    "format": "Case-Based",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "A couple has three children: two boys and one girl. They want to know the probability of their next child being a boy. The woman says, 'Since we have had two boys, the next child is more likely to be a girl to balance the ratio.' The man says, 'Each child has an equal 50% chance of being a boy or girl, regardless of previous children.'\n\nQuestion 1: Who is correct and why?\nQuestion 2: What is the probability of their next child being a boy?\nQuestion 3: Why does human sex determination work this way?",
    "options": [],
    "answer": "Man is correct; 50% probability; Independent events due to equal X and Y sperm",
    "solutionSteps": [
      "Question 1: Man is correct. Each pregnancy is an independent event",
      "Past results do not affect future probability (gambler's fallacy)",
      "Question 2: Probability = 50% or 0.5 or 1/2",
      "Question 3: Male produces equal numbers of X and Y sperm",
      "Each has 50% chance of fertilizing egg (independent of previous children)"
    ],
    "finalAnswer": "Man is correct; 50% probability; Independent events due to equal X and Y sperm",
    "isCompetencyBased": true,
    "pyqYear": "2025",
    "pyqSet": "Set-I",
    "ncertRef": "NCERT Ch9 InText"
  },
  {
    "id": "HE2-024",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Evolution",
    "section": "D",
    "marks": 5,
    "format": "Long",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "Explain the theory of natural selection with reference to Darwin's observations during his voyage on HMS Beagle. How is it different from Lamarck's theory of evolution? What are the limitations of natural selection in explaining evolution?",
    "options": [],
    "answer": "Darwin observed variation, adaptation, and competition. Natural selection preserves beneficial traits. Differs from Lamarck's inheritance of acquired traits. Limitations: doesn't explain all evolutionary mechanisms",
    "solutionSteps": [
      "Darwin's observations:",
      "- Visited Galápagos Islands and observed finch variations",
      "- Noticed similarities between species in different regions",
      "- Observed adaptation to local environments",
      "Natural Selection Theory:",
      "- Organisms produce more offspring than can survive",
      "- Struggle for existence due to limited resources",
      "- Variation in populations provides differential survival",
      "- Traits favoring survival are passed to next generation",
      "Difference from Lamarck's Theory:",
      "- Lamarck: Acquired characteristics are inherited (disproven)",
      "- Darwin: Inherited variation + natural selection (supported by evidence)",
      "Limitations of Natural Selection:",
      "- Cannot explain sudden mutations and genetic drift",
      "- Cannot fully explain complexity of some traits",
      "- Gene flow and other mechanisms also important",
      "- Cannot explain initial origin of variations perfectly"
    ],
    "finalAnswer": "Darwin observed variation, adaptation, and competition. Natural selection preserves beneficial traits. Differs from Lamarck's inheritance of acquired traits. Limitations: doesn't explain all evolutionary mechanisms",
    "isCompetencyBased": true,
    "pyqYear": "2021",
    "pyqSet": "Set-II",
    "ncertRef": "NCERT Ch9 InText"
  },
  {
    "id": "HE2-025",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Heredity Rules",
    "section": "A",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Assertion (A): In a test cross between Aa and aa, the recessive phenotype will appear in 50% of offspring. Reason (R): Test cross is conducted with homozygous dominant individual.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "A is true, R is false.",
    "solutionSteps": [
      "Cross: Aa (heterozygous) × aa (homozygous recessive)",
      "Offspring: Aa (dominant phenotype) and aa (recessive phenotype) in 1:1 ratio",
      "50% show recessive phenotype (A is true)",
      "Test cross is with homozygous RECESSIVE (aa), not dominant (BB is false)",
      "Therefore A is true but R is false"
    ],
    "finalAnswer": "A is true, R is false.",
    "explanation": "The Assertion is a correct statement. However, the Reason given contains an incorrect claim or formula, making R false.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch9 Exercise"
  },
  {
    "id": "HE2-026",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Mendel Experiments",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "In Mendel's monohybrid cross between tall and dwarf pea plants, what was the phenotypic ratio in F₂ generation?",
    "options": [
      "1:1",
      "3:1",
      "9:3:3:1",
      "1:2:1"
    ],
    "answer": "3:1",
    "solutionSteps": [
      "In F₁ generation, all plants were tall (heterozygous Tt)",
      "In F₂ generation, self-pollination of F₁ gave: TT, Tt, Tt, tt",
      "Phenotypic ratio: 3 tall : 1 dwarf"
    ],
    "finalAnswer": "3:1",
    "explanation": "In F₁ generation, all plants were tall (heterozygous Tt). In F₂ generation, self-pollination of F₁ gave: TT, Tt, Tt, tt. Phenotypic ratio: 3 tall : 1 dwarf. Therefore, the correct answer is 3:1.",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch9 InText Q1"
  },
  {
    "id": "HE2-027",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Mendel Experiments",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "What was the main reason Mendel selected garden pea plant for his experiments?",
    "options": [
      "It had short life cycle",
      "It was easily available",
      "It had easily distinguishable traits and could self-pollinate",
      "It produced many seeds"
    ],
    "answer": "It had easily distinguishable traits and could self-pollinate",
    "solutionSteps": [
      "Pea plants had contrasting traits (tall/dwarf, green/yellow seeds)",
      "Could undergo both self-pollination and cross-pollination",
      "Short life cycle allowed multiple generations in short time",
      "These features made it ideal for genetic studies"
    ],
    "finalAnswer": "It had easily distinguishable traits and could self-pollinate",
    "explanation": "Pea plants had contrasting traits (tall/dwarf, green/yellow seeds). Could undergo both self-pollination and cross-pollination. Short life cycle allowed multiple generations in short time. These features made it ideal for genetic studies. Therefore, the correct answer is It had easily distinguishable traits and could self-pollinate.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch9 InText"
  },
  {
    "id": "HE2-028",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Heredity Rules",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "If a plant with genotype Aa is crossed with aa, the expected genotypic ratio in offspring would be:",
    "options": [
      "100% AA",
      "50% Aa : 50% aa",
      "75% Aa : 25% AA",
      "All recessive (aa)"
    ],
    "answer": "50% Aa : 50% aa",
    "solutionSteps": [
      "Cross: Aa × aa",
      "Gametes from Aa: A and a",
      "Gametes from aa: only a",
      "Punnett square: Aa (50%) and aa (50%)",
      "This is a test cross"
    ],
    "finalAnswer": "50% Aa : 50% aa",
    "explanation": "Cross: Aa × aa. Gametes from Aa: A and a. Gametes from aa: only a. Punnett square: Aa (50%) and aa (50%). This is a test cross. Therefore, the correct answer is 50% Aa : 50% aa.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch9 Exercise Q2"
  },
  {
    "id": "HE2-029",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Heredity Rules",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "State Mendel's Law of Segregation. Explain how it is demonstrated in a monohybrid cross.",
    "options": [],
    "answer": "Alleles segregate during gamete formation producing 3:1 ratio in F₂",
    "solutionSteps": [
      "Segregation Law: Allele pairs separate during meiosis",
      "Each gamete carries only one allele for a trait",
      "In F₁: Tt (all appear tall)",
      "In F₂: Gametes T and t combine as TT, Tt, Tt, tt",
      "Result: 3 tall : 1 dwarf ratio"
    ],
    "finalAnswer": "Alleles segregate during gamete formation producing 3:1 ratio in F₂",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch9 InText"
  },
  {
    "id": "HE2-030",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Mendel Experiments",
    "section": "A",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Analysing",
    "questionText": "Assertion (A): In a dihybrid cross of AaBb × AaBb, the F₂ phenotypic ratio is 9:3:3:1.\nReason (R): The two genes assort independently during gamete formation.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "Law of Independent Assortment: genes assort independently",
      "In dihybrid cross, 16 genotypic combinations form",
      "Phenotypic ratio: 9 (A_B_) : 3 (A_bb) : 3 (aaB_) : 1 (aabb)",
      "Independent assortment causes this 9:3:3:1 ratio"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "explanation": "Both the Assertion and the Reason are correct statements. The Reason directly explains the scientific/mathematical basis that makes the Assertion true, so R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": "2021",
    "pyqSet": "Set-1",
    "ncertRef": "NCERT Ch9 Exercise"
  },
  {
    "id": "HE2-031",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Sex Determination",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "In humans, sex is determined by:",
    "options": [
      "Number of X chromosomes",
      "Presence or absence of Y chromosome",
      "Environmental factors during development",
      "Dominance of female characters"
    ],
    "answer": "Presence or absence of Y chromosome",
    "solutionSteps": [
      "Males: XY (have Y chromosome)",
      "Females: XX (no Y chromosome)",
      "Y chromosome carries male-determining genes",
      "Male offspring: 50% chance when father's Y combines with mother's X"
    ],
    "finalAnswer": "Presence or absence of Y chromosome",
    "explanation": "Males: XY (have Y chromosome). Females: XX (no Y chromosome). Y chromosome carries male-determining genes. Male offspring: 50% chance when father's Y combines with mother's X. Therefore, the correct answer is Presence or absence of Y chromosome.",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch9 InText Q3"
  },
  {
    "id": "HE2-032",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Sex Determination",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A sex-linked trait is controlled by a recessive allele on X chromosome. Write the genotypes of affected and unaffected individuals in males and females.",
    "options": [],
    "answer": "Males: X^a Y affected, X^A Y unaffected. Females: X^a X^a affected, X^A X^A or X^A X^a unaffected",
    "solutionSteps": [
      "Sex-linked traits are on X chromosome",
      "Males (XY): one allele shows phenotype - X^A Y normal, X^a Y affected",
      "Females (XX): need two recessive for affected - X^a X^a",
      "Females can be carriers - X^A X^a",
      "Males are more frequently affected"
    ],
    "finalAnswer": "Males: X^a Y affected, X^A Y unaffected. Females: X^a X^a affected, X^A X^A or X^A X^a unaffected",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch9 Exercise Q5"
  },
  {
    "id": "HE2-033",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Evolution",
    "section": "C",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "Which of the following is an evidence for evolution?",
    "options": [
      "Similar bone structure in vertebrate limbs",
      "Different sizes of organisms",
      "Color variations in plants",
      "Seasonal changes in animals"
    ],
    "answer": "Similar bone structure in vertebrate limbs",
    "solutionSteps": [
      "Homologous structures show common ancestry",
      "Forelimbs of humans, dogs, whales, birds have similar basic structure",
      "Different functions but same origin = homology",
      "Proves evolution from common ancestor"
    ],
    "finalAnswer": "Similar bone structure in vertebrate limbs",
    "explanation": "Homologous structures show common ancestry. Forelimbs of humans, dogs, whales, birds have similar basic structure. Different functions but same origin = homology. Proves evolution from common ancestor. Therefore, the correct answer is Similar bone structure in vertebrate limbs.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch9 InText Q6"
  },
  {
    "id": "HE2-034",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Evolution",
    "section": "C",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Analysing",
    "questionText": "Analogous structures in different species indicate:",
    "options": [
      "Common ancestry",
      "Convergent evolution",
      "Recent evolutionary changes",
      "Environmental stability"
    ],
    "answer": "Convergent evolution",
    "solutionSteps": [
      "Analogous structures: different origin, similar function",
      "Wings of birds, bats, insects - adapted to same environment",
      "Different evolutionary paths led to similar adaptations",
      "Shows convergent evolution, not common ancestry"
    ],
    "finalAnswer": "Convergent evolution",
    "explanation": "Analogous structures: different origin, similar function. Wings of birds, bats, insects - adapted to same environment. Different evolutionary paths led to similar adaptations. Shows convergent evolution, not common ancestry. Therefore, the correct answer is Convergent evolution.",
    "isCompetencyBased": true,
    "pyqYear": "2022",
    "pyqSet": "Set-2",
    "ncertRef": "NCERT Ch9 InText"
  },
  {
    "id": "HE2-035",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Evolution",
    "section": "C",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "What do fossils tell us about evolution? Explain with one example.",
    "options": [],
    "answer": "Fossils show transitional forms and gradual evolutionary change over time",
    "solutionSteps": [
      "Fossils are preserved remains of extinct organisms",
      "Show organisms that existed in past",
      "Fossil sequence demonstrates transitional forms",
      "Horse fossil record: Eohippus (small, 4-toed) → Modern horse (large, 1-toed)",
      "Shows gradual adaptation to changing environments"
    ],
    "finalAnswer": "Fossils show transitional forms and gradual evolutionary change over time",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch9 Exercise Q8"
  },
  {
    "id": "HE2-036",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Evolution",
    "section": "C",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Analysing",
    "questionText": "Assertion (A): Vestigial organs are non-functional structures in organisms.\nReason (R): Vestigial organs prove that organisms have evolved from common ancestors.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "Vestigial organs: reduced, non-functional remnants (human appendix, tailbone)",
      "These structures were functional in ancestral forms",
      "Prove organisms inherited traits from common ancestors",
      "Vestigial structures are direct evidence of evolution"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "explanation": "Both the Assertion and the Reason are correct statements. The Reason directly explains the scientific/mathematical basis that makes the Assertion true, so R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": "Set-1",
    "ncertRef": "NCERT Ch9 InText"
  },
  {
    "id": "HE2-037",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Evolution",
    "section": "C",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "The concept that species with more favorable variations survive and reproduce more is called:",
    "options": [
      "Artificial selection",
      "Natural selection",
      "Genetic drift",
      "Gene flow"
    ],
    "answer": "Natural selection",
    "solutionSteps": [
      "Darwin's mechanism of evolution",
      "Organisms with beneficial traits survive better",
      "These traits passed to next generation",
      "Over time, favorable traits become common",
      "Leads to adaptation and speciation"
    ],
    "finalAnswer": "Natural selection",
    "explanation": "Darwin's mechanism of evolution. Organisms with beneficial traits survive better. These traits passed to next generation. Over time, favorable traits become common. Leads to adaptation and speciation. Therefore, the correct answer is Natural selection.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch9 Exercise Q10"
  },
  {
    "id": "HE2-038",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Speciation",
    "section": "D",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Speciation is the process by which:",
    "options": [
      "One species evolves into two or more different species",
      "Organisms adapt to environment",
      "Genes mutate randomly",
      "Populations migrate to new areas"
    ],
    "answer": "One species evolves into two or more different species",
    "solutionSteps": [
      "Speciation: formation of new species from ancestral species",
      "Results from reproductive isolation",
      "Allopatric speciation: geographic isolation prevents gene flow",
      "Accumulation of genetic differences leads to new species"
    ],
    "finalAnswer": "One species evolves into two or more different species",
    "explanation": "Speciation: formation of new species from ancestral species. Results from reproductive isolation. Allopatric speciation: geographic isolation prevents gene flow. Accumulation of genetic differences leads to new species. Therefore, the correct answer is One species evolves into two or more different species.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch9 InText Q7"
  },
  {
    "id": "HE2-039",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Speciation",
    "section": "D",
    "marks": 2,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "How does geographic isolation contribute to speciation? Explain the concept of reproductive isolation.",
    "options": [],
    "answer": "Geographic isolation causes reproductive isolation leading to speciation",
    "solutionSteps": [
      "Geographic isolation: populations separated by physical barriers",
      "No gene flow between isolated populations",
      "Different mutations accumulate in each group",
      "Different selective pressures drive different adaptations",
      "Eventually cannot interbreed = reproductive isolation",
      "Result: two distinct species from one ancestral species"
    ],
    "finalAnswer": "Geographic isolation causes reproductive isolation leading to speciation",
    "isCompetencyBased": true,
    "pyqYear": "2024",
    "pyqSet": "Set-3",
    "ncertRef": "NCERT Ch9 Exercise Q9"
  },
  {
    "id": "HE2-040",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Heredity Rules",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A carrier female for a recessive X-linked trait (X^A X^a) is crossed with a normal male (X^A Y). What is the probability of having an affected son?",
    "options": [
      "0%",
      "25%",
      "50%",
      "75%"
    ],
    "answer": "25%",
    "solutionSteps": [
      "Cross: X^A X^a × X^A Y",
      "Possible offspring: X^A X^A (normal daughter), X^A X^a (carrier daughter), X^A Y (normal son), X^a Y (affected son)",
      "For affected son: needs X^a from mother and Y from father",
      "X^a Y probability = 1/4 = 25% affected son"
    ],
    "finalAnswer": "25%",
    "explanation": "Cross: X^A X^a × X^A Y. Possible offspring: X^A X^A (normal daughter), X^A X^a (carrier daughter), X^A Y (normal son), X^a Y (affected son). For affected son: needs X^a from mother and Y from father. X^a Y probability = 1/4 = 25% affected son. Therefore, the correct answer is 25%.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch9 Exercise"
  },
  {
    "id": "HE2-041",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Mendel Experiments",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "If in a test cross of a plant with genotype Aa, the ratio obtained is not 1:1, it could be due to:",
    "options": [
      "Incomplete dominance",
      "Lethal alleles",
      "Incomplete segregation",
      "Random fertilization"
    ],
    "answer": "Lethal alleles",
    "solutionSteps": [
      "Expected test cross ratio for Aa × aa should be 1:1",
      "If ratio deviates, it indicates deviation from normal Mendelian inheritance",
      "Lethal alleles cause death of certain genotypes",
      "Example: AA lethal in yellow coat mice - only Aa survives",
      "Results in 2:1 instead of expected ratio"
    ],
    "finalAnswer": "Lethal alleles",
    "explanation": "Expected test cross ratio for Aa × aa should be 1:1. If ratio deviates, it indicates deviation from normal Mendelian inheritance. Lethal alleles cause death of certain genotypes. Example: AA lethal in yellow coat mice - only Aa survives. Results in 2:1 instead of expected ratio. Therefore, the correct answer is Lethal alleles.",
    "isCompetencyBased": true,
    "pyqYear": "2020",
    "pyqSet": "Set-2",
    "ncertRef": "NCERT Ch9 InText"
  },
  {
    "id": "HE2-042",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Heredity Rules",
    "section": "B",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Assertion (A): In a cross between two heterozygous tall plants (Tt × Tt), approximately 75% of F₁ offspring will be tall.\nReason (R): Tall is a dominant trait over dwarf in pea plants.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "Cross: Tt × Tt",
      "Offspring: 1 TT : 2 Tt : 1 tt",
      "TT (25%) tall, Tt (50%) tall = 75% tall total",
      "tt (25%) dwarf",
      "Dominant allele T produces tall phenotype",
      "Both assertion and reason are correct explanations"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "explanation": "Both the Assertion and the Reason are correct statements. The Reason directly explains the scientific/mathematical basis that makes the Assertion true, so R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch9 InText"
  },
  {
    "id": "HE2-043",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Evolution",
    "section": "E",
    "marks": 4,
    "format": "Case-Based",
    "difficulty": "Medium",
    "bloomSkill": "Analysing",
    "questionText": "A researcher studied two populations of beetles on an island. Population A had mostly dark-colored beetles and Population B had mostly light-colored beetles. After a volcanic eruption covered the vegetation with dark ash, light-colored beetles in Population A rapidly decreased in number. However, Population B remained predominantly light-colored. The researcher could not find evidence of migration between the two populations despite them living on the same island.\n\n(i) Explain why light-colored beetles decreased in Population A.\n(ii) How does natural selection differ in the two populations?\n(iii) Why might the two populations eventually become separate species despite living on the same island?\n(iv) What is this type of speciation called?",
    "options": [],
    "answer": "(i) Poor camouflage increases predation (ii) Different selective pressures (iii) Genetic divergence and reproductive isolation (iv) Sympatric speciation",
    "solutionSteps": [
      "Part (i): Camouflage is crucial for survival. Dark ash background makes light beetles visible to predators, increasing predation rate. Dark beetles survive better.",
      "Part (ii): Natural selection acts differently. In A: selects for dark color. In B: selects for light color. Directional selection with opposite pressures.",
      "Part (iii): Reproductive isolation occurs through behavioral/genetic divergence without geographic barriers. Different alleles become fixed in each population.",
      "Part (iv): Speciation without geographic isolation = sympatric speciation. Reproductive isolation develops through ecological/behavioral isolation."
    ],
    "finalAnswer": "(i) Poor camouflage increases predation (ii) Different selective pressures (iii) Genetic divergence and reproductive isolation (iv) Sympatric speciation",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": "Set-2",
    "ncertRef": "NCERT Ch9 Exercise"
  },
  {
    "id": "HE2-044",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Mendel Experiments",
    "section": "A",
    "marks": 5,
    "format": "Long",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "Explain Mendel's Law of Independent Assortment with a dihybrid cross involving seed color (yellow-dominant, green-recessive) and seed shape (round-dominant, wrinkled-recessive). Show the Punnett square and explain how the 9:3:3:1 ratio proves independent assortment. How would the ratio change if the genes were linked?",
    "options": [],
    "answer": "9:3:3:1 ratio proves independent assortment; linked genes show deviation with parental phenotypes more frequent",
    "solutionSteps": [
      "Mendel's Law of Independent Assortment: alleles of different genes assort independently during gamete formation.",
      "Parental cross: AABB (yellow round) × aabb (green wrinkled)",
      "F₁: All AaBb (yellow round)",
      "F₁ × F₁: AaBb × AaBb",
      "Gamete types: AB, Ab, aB, ab (4 types from each parent)",
      "Punnett square: 16 boxes showing all combinations",
      "Phenotypic ratio: 9:3:3:1",
      "9 A_B_: yellow round (both dominant)",
      "3 A_bb: yellow wrinkled (seed color dominant)",
      "3 aaB_: green round (seed shape dominant)",
      "1 aabb: green wrinkled (both recessive)",
      "If genes linked: Lower recombination types, higher parental types",
      "Example: 11:1:1:3 or other deviations from 9:3:3:1"
    ],
    "finalAnswer": "9:3:3:1 ratio proves independent assortment; linked genes show deviation with parental phenotypes more frequent",
    "isCompetencyBased": true,
    "pyqYear": "2024",
    "pyqSet": "Set-1",
    "ncertRef": "NCERT Ch9 Exercise Q3"
  },
  {
    "id": "HE2-045",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Evolution",
    "section": "C",
    "marks": 5,
    "format": "Long",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "Explain how homologous and analogous structures serve as evidence for evolution. Compare and contrast them. Give two examples each and explain how they support the theory of evolution by natural selection. How do vestigial organs also act as evidence?",
    "options": [],
    "answer": "Homologous structures: Same origin, different functions (forelimbs of mammals, bird wings). Show common ancestry, support evolution from single ancestor. Analogous structures: Different origin, similar functions (bird and bat wings). Show convergent evolution, adaptation to similar environments without common ancestry for that trait. Vestigial organs prove descent from common ancestors that needed these structures.",
    "solutionSteps": [
      "Homologous structures:",
      "Definition: Similar structure, different function, common ancestry",
      "Example 1: Human arm, dog leg, whale flipper, bat wing - all have similar bone arrangement (humerus, radius, ulna, carpals, metacarpals, phalanges)",
      "Example 2: Bird wing and human arm - both used for different purposes but homologous",
      "Evidence: Genetic and embryological similarity proves common ancestry",
      "Support for evolution: Different modifications of same ancestral structure",
      "",
      "Analogous structures:",
      "Definition: Different structure, similar function, different origin",
      "Example 1: Bird wing (feathers on bones) vs Bat wing (membrane between bones) vs Insect wing (chitinous)",
      "Example 2: Fish fin vs Dolphin flipper - different structure but similar function",
      "Evidence: Similar function for similar environments but different evolutionary pathways",
      "Support: Shows convergent evolution - natural selection produces similar solutions to same environmental problems",
      "",
      "Vestigial organs:",
      "Definition: Non-functional or reduced structures inherited from ancestors",
      "Examples: Human tailbone (coccyx), appendix, wisdom teeth",
      "Evidence: Prove organisms evolved from ancestors that needed these organs",
      "Support: Show evolutionary history and common descent",
      "",
      "All three support evolution theory by showing:",
      "Common ancestry (homologous)",
      "Adaptation to environment (analogous, natural selection)",
      "Evolutionary history (vestigial)"
    ],
    "finalAnswer": "Homologous structures: Same origin, different functions (forelimbs of mammals, bird wings). Show common ancestry, support evolution from single ancestor. Analogous structures: Different origin, similar functions (bird and bat wings). Show convergent evolution, adaptation to similar environments without common ancestry for that trait. Vestigial organs prove descent from common ancestors that needed these structures.",
    "isCompetencyBased": true,
    "pyqYear": "2022",
    "pyqSet": "Set-1",
    "ncertRef": "NCERT Ch9 Exercise Q7"
  },
  {
    "id": "HE2-046",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Sex Determination",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A color-blind woman marries a normal man. What is the genotype of the color-blind woman and what will be the phenotype of their daughters?",
    "options": [
      "X^a X^a; all daughters normal",
      "X^A X^a; all daughters normal",
      "X^a X^a; all daughters color-blind",
      "X^A X^a; half daughters color-blind"
    ],
    "answer": "X^a X^a; all daughters normal",
    "solutionSteps": [
      "Color-blind is X-linked recessive",
      "Color-blind woman: X^a X^a (homozygous recessive)",
      "Normal man: X^A Y (has dominant allele)",
      "Cross: X^a X^a × X^A Y",
      "Daughters: X^A X^a (carriers, phenotypically normal)",
      "Sons: X^a Y (color-blind)"
    ],
    "finalAnswer": "X^a X^a; all daughters normal",
    "explanation": "Color-blind is X-linked recessive. Color-blind woman: X^a X^a (homozygous recessive). Normal man: X^A Y (has dominant allele). Cross: X^a X^a × X^A Y. Daughters: X^A X^a (carriers, phenotypically normal). Sons: X^a Y (color-blind). Therefore, the correct answer is X^a X^a; all daughters normal.",
    "isCompetencyBased": true,
    "pyqYear": "2019",
    "pyqSet": "Set-1",
    "ncertRef": "NCERT Ch9 Exercise Q4"
  },
  {
    "id": "HE2-047",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Speciation",
    "section": "D",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "Darwin's finches in Galapagos Islands show variation in beak size and shape adapted to different food sources. This is an example of:",
    "options": [
      "Artificial selection",
      "Adaptive radiation",
      "Genetic drift",
      "Gene flow"
    ],
    "answer": "Adaptive radiation",
    "solutionSteps": [
      "Adaptive radiation: rapid evolution of diverse species from common ancestor",
      "Darwin's finches: descended from single ancestral species",
      "Different islands and food sources drove divergence",
      "Each population adapted to local environment",
      "Resulted in 13+ species with different beak morphologies",
      "Classic example of evolution in action"
    ],
    "finalAnswer": "Adaptive radiation",
    "explanation": "Adaptive radiation: rapid evolution of diverse species from common ancestor. Darwin's finches: descended from single ancestral species. Different islands and food sources drove divergence. Each population adapted to local environment. Resulted in 13+ species with different beak morphologies. Classic example of evolution in action. Therefore, the correct answer is Adaptive radiation.",
    "isCompetencyBased": true,
    "pyqYear": "2025",
    "pyqSet": "Set-2",
    "ncertRef": "NCERT Ch9 InText"
  },
  {
    "id": "HE2-048",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Heredity Rules",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "In humans, the ability to roll tongue is dominant over inability to roll it. If a woman who cannot roll her tongue has a child that can roll tongue, what is the father's genotype? (R = rolling, r = non-rolling)",
    "options": [],
    "answer": "Father: RR or Rr (most likely Rr)",
    "solutionSteps": [
      "Woman (non-roller): genotype rr",
      "Child (roller): genotype R_ (must have at least one R)",
      "Woman can only contribute r alleles",
      "Child's R allele must come from father",
      "Father must have at least one R allele",
      "Father's genotype: RR or Rr",
      "Most probable: Rr (heterozygous)"
    ],
    "finalAnswer": "Father: RR or Rr (most likely Rr)",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch9 Exercise Q1"
  },
  {
    "id": "HE2-049",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Evolution",
    "section": "C",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "The organism that shows characteristics between two different species is called a/an:",
    "options": [
      "Mutation",
      "Transitional form",
      "Variation",
      "Adaptation"
    ],
    "answer": "Transitional form",
    "solutionSteps": [
      "Transitional forms: organisms showing intermediate characteristics",
      "Link between ancestral and derived species",
      "Example: Archaeopteryx (link between reptiles and birds)",
      "Fossil evidence of evolution"
    ],
    "finalAnswer": "Transitional form",
    "explanation": "Transitional forms: organisms showing intermediate characteristics. Link between ancestral and derived species. Example: Archaeopteryx (link between reptiles and birds). Fossil evidence of evolution. Therefore, the correct answer is Transitional form.",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch9 InText Q8"
  },
  {
    "id": "HE2-050",
    "subject": "Science",
    "topicKey": "Heredity and Evolution",
    "subtopic": "Mendel Experiments",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "What does F₁ generation represent in Mendel's experiments?",
    "options": [
      "First parental generation",
      "Second filial generation",
      "First filial generation (offspring of pure parents)",
      "Final generation"
    ],
    "answer": "First filial generation (offspring of pure parents)",
    "solutionSteps": [
      "F₀ or P: Parental generation (pure-breeding)",
      "F₁: First filial generation (offspring from P cross)",
      "F₂: Second filial generation (F₁ × F₁ offspring)",
      "In monohybrid cross, F₁ are all heterozygous and show dominant trait"
    ],
    "finalAnswer": "First filial generation (offspring of pure parents)",
    "explanation": "F₀ or P: Parental generation (pure-breeding). F₁: First filial generation (offspring from P cross). F₂: Second filial generation (F₁ × F₁ offspring). In monohybrid cross, F₁ are all heterozygous and show dominant trait. Therefore, the correct answer is First filial generation (offspring of pure parents).",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch9 InText"
  }
];
