import type { CanonicalQuestion } from "../../types";

export const LT2_PACK2: CanonicalQuestion[] = [
  {
    "id": "LT2-001",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Laws of Reflection",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "The angle of incidence is equal to the angle of reflection. This statement refers to which law of reflection?",
    "options": [
      "First law of reflection",
      "Second law of reflection",
      "Third law of reflection",
      "Law of refraction"
    ],
    "answer": "Second law of reflection",
    "solutionSteps": [
      "The second law of reflection states that the angle of incidence equals the angle of reflection",
      "Both angles are measured from the normal to the surface"
    ],
    "finalAnswer": "Second law of reflection",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch10 InText Q1"
  },
  {
    "id": "LT2-002",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Laws of Reflection",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "A ray of light hits a plane mirror at an angle of 30° to the mirror surface. What is the angle of reflection?",
    "options": [
      "30°",
      "60°",
      "90°",
      "120°"
    ],
    "answer": "60°",
    "solutionSteps": [
      "Angle to mirror surface = 30°",
      "Angle of incidence (from normal) = 90° - 30° = 60°",
      "By law of reflection, angle of reflection = angle of incidence = 60°"
    ],
    "finalAnswer": "60°",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch10 Exercise Q2"
  },
  {
    "id": "LT2-003",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Laws of Reflection",
    "section": "A",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Analysing",
    "questionText": "Assertion (A): The incident ray, reflected ray, and normal all lie in the same plane. Reason (R): This is the first law of reflection.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "The first law of reflection states that incident ray, reflected ray, and normal lie in the same plane",
      "This is indeed the first law, and it explains why the assertion is true"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": "2021",
    "pyqSet": "Delhi",
    "ncertRef": "NCERT Ch10 InText"
  },
  {
    "id": "LT2-004",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Spherical Mirrors",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "What is the focal length of a spherical mirror if its radius of curvature is 40 cm?",
    "options": [
      "40 cm",
      "20 cm",
      "80 cm",
      "10 cm"
    ],
    "answer": "20 cm",
    "solutionSteps": [
      "Focal length (f) = Radius of curvature (R) / 2",
      "f = 40 / 2 = 20 cm"
    ],
    "finalAnswer": "20 cm",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch10 InText Q5"
  },
  {
    "id": "LT2-005",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Spherical Mirrors",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "A concave mirror has a focal length of 15 cm. Where should an object be placed to obtain a real, inverted, and same-sized image?",
    "options": [
      "At the focal point",
      "At the center of curvature",
      "Between focal point and center",
      "Beyond center of curvature"
    ],
    "answer": "At the center of curvature",
    "solutionSteps": [
      "For a real, inverted, same-sized image in a concave mirror",
      "Object distance must equal radius of curvature",
      "Center of curvature is at distance R = 2f = 2(15) = 30 cm"
    ],
    "finalAnswer": "At the center of curvature",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch10 Exercise Q6"
  },
  {
    "id": "LT2-006",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Spherical Mirrors",
    "section": "B",
    "marks": 1,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Name the type of mirror used in search lights and headlights. Why is it used?",
    "options": [],
    "answer": "Concave mirror; it converges light rays to produce a strong parallel beam",
    "solutionSteps": [
      "Search lights and headlights need focused, parallel rays",
      "Concave mirrors converge light from a point source placed at focal point",
      "This produces a strong parallel beam of light"
    ],
    "finalAnswer": "Concave mirror; it converges light rays to produce a strong parallel beam",
    "isCompetencyBased": true,
    "pyqYear": "2020",
    "pyqSet": "All India",
    "ncertRef": "NCERT Ch10 Exercise Q10"
  },
  {
    "id": "LT2-007",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Mirror Formula",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "An object of height 5 cm is placed at a distance of 30 cm from a concave mirror of focal length 10 cm. Find the position and height of the image.",
    "options": [],
    "answer": "v = 15 cm; Image height = 2.5 cm",
    "solutionSteps": [
      "Using mirror formula: 1/f = 1/u + 1/v",
      "1/10 = 1/30 + 1/v",
      "1/v = 1/10 - 1/30 = 3/30 - 1/30 = 2/30 = 1/15",
      "v = 15 cm (real, inverted image)",
      "Magnification m = -v/u = -15/30 = -0.5",
      "Image height = 0.5 × 5 = 2.5 cm"
    ],
    "finalAnswer": "v = 15 cm; Image height = 2.5 cm",
    "isCompetencyBased": true,
    "pyqYear": "2019",
    "pyqSet": "Delhi",
    "ncertRef": "NCERT Ch10 Exercise Q7"
  },
  {
    "id": "LT2-008",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Mirror Formula",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "The mirror formula is:",
    "options": [
      "1/f = 1/u - 1/v",
      "1/f = 1/u + 1/v",
      "f = u + v",
      "f = uv/(u+v)"
    ],
    "answer": "1/f = 1/u + 1/v",
    "solutionSteps": [
      "The mirror formula relates object distance (u), image distance (v), and focal length (f)",
      "Standard form: 1/f = 1/u + 1/v"
    ],
    "finalAnswer": "1/f = 1/u + 1/v",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch10 InText"
  },
  {
    "id": "LT2-009",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Mirror Formula",
    "section": "C",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Assertion (A): For a convex mirror, the image is always virtual, erect, and diminished. Reason (R): Convex mirrors diverge all incident rays, and their focal length is negative.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "Convex mirrors diverge incident rays",
      "This creates a virtual, erect, diminished image",
      "Focal length is negative (f < 0) for convex mirrors",
      "The diverging nature explains the image characteristics"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": "2022",
    "pyqSet": "All India",
    "ncertRef": "NCERT Ch10 Exercise Q8"
  },
  {
    "id": "LT2-010",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Refraction",
    "section": "C",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "Which of the following correctly states Snell's law?",
    "options": [
      "n₁ sin θ₁ = n₂ sin θ₂",
      "n₁ θ₁ = n₂ θ₂",
      "sin θ₁ / sin θ₂ = θ₁ / θ₂",
      "n₁ / n₂ = sin θ₁ / sin θ₂"
    ],
    "answer": "n₁ sin θ₁ = n₂ sin θ₂",
    "solutionSteps": [
      "Snell's law: n₁ sin θ₁ = n₂ sin θ₂",
      "where n is refractive index and θ is angle of incidence/refraction"
    ],
    "finalAnswer": "n₁ sin θ₁ = n₂ sin θ₂",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch10 InText Q3"
  },
  {
    "id": "LT2-011",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Refraction",
    "section": "C",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "When light travels from a denser medium to a rarer medium, it bends:",
    "options": [
      "Towards the normal",
      "Away from the normal",
      "Along the normal",
      "Perpendicular to the normal"
    ],
    "answer": "Away from the normal",
    "solutionSteps": [
      "When light goes from denser (higher n) to rarer (lower n) medium",
      "Using Snell's law: n₁ sin θ₁ = n₂ sin θ₂",
      "Since n₁ > n₂, we need sin θ₂ > sin θ₁",
      "Therefore θ₂ > θ₁, light bends away from normal"
    ],
    "finalAnswer": "Away from the normal",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch10 Exercise Q3"
  },
  {
    "id": "LT2-012",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Refraction",
    "section": "C",
    "marks": 2,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Applying",
    "questionText": "Light enters water from air at an angle of incidence 45°. If the refractive index of water is 4/3, find the angle of refraction.",
    "options": [],
    "answer": "θ₂ ≈ 32°",
    "solutionSteps": [
      "Using Snell's law: n₁ sin θ₁ = n₂ sin θ₂",
      "1 × sin 45° = (4/3) × sin θ₂",
      "sin θ₂ = (3/4) × sin 45°",
      "sin θ₂ = (3/4) × (1/√2) = 3/(4√2) = 0.530",
      "θ₂ = sin⁻¹(0.530) ≈ 32°"
    ],
    "finalAnswer": "θ₂ ≈ 32°",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": "Delhi",
    "ncertRef": "NCERT Ch10 Exercise Q4"
  },
  {
    "id": "LT2-013",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Refraction",
    "section": "C",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "The critical angle for total internal reflection occurs when light travels from:",
    "options": [
      "Air to glass",
      "Glass to air",
      "Water to air",
      "Glass to water"
    ],
    "answer": "Glass to air",
    "solutionSteps": [
      "Critical angle occurs when light goes from denser to rarer medium",
      "Glass (n ≈ 1.5) to air (n = 1) is denser to rarer",
      "At critical angle, refraction angle = 90°"
    ],
    "finalAnswer": "Glass to air",
    "isCompetencyBased": true,
    "pyqYear": "2024",
    "pyqSet": "All India",
    "ncertRef": "NCERT Ch10 Exercise Q5"
  },
  {
    "id": "LT2-014",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Lens Formula",
    "section": "D",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "The lens formula is:",
    "options": [
      "1/f = 1/u + 1/v",
      "1/f = 1/v - 1/u",
      "f = u + v",
      "f² = u² + v²"
    ],
    "answer": "1/f = 1/u + 1/v",
    "solutionSteps": [
      "The lens formula is identical in form to mirror formula",
      "1/f = 1/u + 1/v",
      "where f is focal length, u is object distance, v is image distance"
    ],
    "finalAnswer": "1/f = 1/u + 1/v",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch10 InText Q6"
  },
  {
    "id": "LT2-015",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Lens Formula",
    "section": "D",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "For a convex lens, which combination of object and image distances results in magnification m = 1?",
    "options": [
      "u = v = f",
      "u = v = 2f",
      "u = f, v = ∞",
      "u = 2f, v = 2f"
    ],
    "answer": "u = v = 2f",
    "solutionSteps": [
      "Magnification m = -v/u",
      "For m = -1 (same-sized image), u = v",
      "Using lens formula: 1/f = 1/u + 1/u = 2/u",
      "Therefore u = 2f and v = 2f"
    ],
    "finalAnswer": "u = v = 2f",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch10 Exercise Q9"
  },
  {
    "id": "LT2-016",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Lens Formula",
    "section": "D",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "An object is placed 15 cm from a convex lens of focal length 10 cm. Find the position and nature of the image.",
    "options": [],
    "answer": "v = 30 cm, real and inverted",
    "solutionSteps": [
      "Using lens formula: 1/f = 1/u + 1/v",
      "1/10 = 1/15 + 1/v",
      "1/v = 1/10 - 1/15 = 3/30 - 2/30 = 1/30",
      "v = 30 cm",
      "Since v > 0, image is real and inverted"
    ],
    "finalAnswer": "v = 30 cm, real and inverted",
    "isCompetencyBased": true,
    "pyqYear": "2019",
    "pyqSet": "All India",
    "ncertRef": "NCERT Ch10 Exercise Q8"
  },
  {
    "id": "LT2-017",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Lens Formula",
    "section": "D",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "A concave lens always forms an image that is:",
    "options": [
      "Real, inverted, and diminished",
      "Real, erect, and magnified",
      "Virtual, erect, and diminished",
      "Virtual, inverted, and magnified"
    ],
    "answer": "Virtual, erect, and diminished",
    "solutionSteps": [
      "Concave lens diverges all incident rays",
      "The diverged rays appear to come from a virtual focus",
      "Virtual image is always erect and diminished",
      "Image distance v is always negative and |v| < |u|"
    ],
    "finalAnswer": "Virtual, erect, and diminished",
    "isCompetencyBased": true,
    "pyqYear": "2022",
    "pyqSet": "Delhi",
    "ncertRef": "NCERT Ch10 Exercise Q10"
  },
  {
    "id": "LT2-018",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Lens Formula",
    "section": "D",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Assertion (A): Power of a lens is inversely proportional to its focal length. Reason (R): Power of a lens P = 1/f, measured in diopters.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "Power P = 1/f (in meters)",
      "If f increases, P decreases (inverse relationship)",
      "The formula P = 1/f explains why they are inversely related",
      "Power is measured in diopters (D)"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": "2021",
    "pyqSet": "All India",
    "ncertRef": "NCERT Ch10 InText"
  },
  {
    "id": "LT2-019",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Refraction",
    "section": "E",
    "marks": 4,
    "format": "Case-Based",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A fish is swimming in a pond. An observer standing on the bank sees the fish at an apparent depth of 2 m, while the actual depth is 2.5 m. (a) Calculate the refractive index of water. (b) What happens to the apparent position when the observer moves to a different angle?",
    "options": [],
    "answer": "(a) Refractive index = 1.25 (b) Apparent position shifts with viewing angle",
    "solutionSteps": [
      "Real depth = 2.5 m, Apparent depth = 2 m",
      "Refractive index n = Real depth / Apparent depth",
      "n = 2.5 / 2 = 1.25",
      "When viewing angle changes, the light path changes",
      "This results in a different apparent depth at different angles"
    ],
    "finalAnswer": "(a) Refractive index = 1.25 (b) Apparent position shifts with viewing angle",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": "Delhi",
    "ncertRef": "NCERT Ch10 Exercise"
  },
  {
    "id": "LT2-020",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Spherical Mirrors",
    "section": "E",
    "marks": 4,
    "format": "Case-Based",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "A dentist uses a concave mirror to examine a patient's teeth. The mirror has a focal length of 1.5 cm. The dentist positions the mirror 1.2 cm from a tooth. (a) Is the image real or virtual? (b) Calculate the magnification. (c) What is the advantage of using this mirror?",
    "options": [],
    "answer": "(a) Virtual image (b) m = 5 (magnified) (c) Provides magnified erect image for dental examination",
    "solutionSteps": [
      "f = 1.5 cm, u = 1.2 cm",
      "Using lens formula: 1/f = 1/u + 1/v",
      "1/1.5 = 1/1.2 + 1/v",
      "1/v = 1/1.5 - 1/1.2 = (2/3 - 5/6) = (4-5)/6 = -1/6",
      "v = -6 cm (negative, so virtual image)",
      "m = -v/u = 6/1.2 = 5 (magnified, erect)",
      "Concave mirrors magnify and provide erect virtual images for close examination"
    ],
    "finalAnswer": "(a) Virtual image (b) m = 5 (magnified) (c) Provides magnified erect image for dental examination",
    "isCompetencyBased": true,
    "pyqYear": "2024",
    "pyqSet": "All India",
    "ncertRef": "NCERT Ch10 Exercise Q11"
  },
  {
    "id": "LT2-021",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Mirror Formula",
    "section": "D",
    "marks": 5,
    "format": "Long",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "An object of height 10 cm is placed at a distance of 50 cm from a concave mirror. A real image of height 5 cm is formed on a screen. (a) Find the focal length of the mirror. (b) At what distance is the screen placed from the mirror? (c) If the object is moved 10 cm closer to the mirror, find the new image position and nature. (d) Explain why the image height changes.",
    "options": [],
    "answer": "(a) f ≈ 16.67 cm (b) Screen at 25 cm (c) New image at ≈28.57 cm, real and inverted (d) Image height changes due to changing magnification with object distance",
    "solutionSteps": [
      "Part (a): Using magnification m = h₂/h₁ = -v/u",
      "m = -5/10 = -0.5 = -v/u",
      "Therefore, v/u = 0.5, so v = 0.5 × 50 = 25 cm",
      "Using mirror formula: 1/f = 1/u + 1/v",
      "1/f = 1/50 + 1/25 = 1/50 + 2/50 = 3/50",
      "f = 50/3 ≈ 16.67 cm",
      "",
      "Part (b): Screen is at v = 25 cm from mirror",
      "",
      "Part (c): New object distance u' = 50 - 10 = 40 cm",
      "1/f = 1/u' + 1/v'",
      "3/50 = 1/40 + 1/v'",
      "1/v' = 3/50 - 1/40 = 12/200 - 5/200 = 7/200",
      "v' ≈ 28.57 cm (real, inverted)",
      "",
      "Part (d): Magnification changed from m = -0.5 to m = -v'/u' = -28.57/40 ≈ -0.71",
      "As object distance changes, magnification changes",
      "Therefore image height h' = |m'| × 10 ≈ 7.1 cm"
    ],
    "finalAnswer": "(a) f ≈ 16.67 cm (b) Screen at 25 cm (c) New image at ≈28.57 cm, real and inverted (d) Image height changes due to changing magnification with object distance",
    "isCompetencyBased": true,
    "pyqYear": "2025",
    "pyqSet": "Delhi",
    "ncertRef": "NCERT Ch10 Exercise Q12"
  },
  {
    "id": "LT2-022",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Refraction",
    "section": "C",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "The refractive index of a medium is defined as:",
    "options": [
      "Speed of light in medium / Speed of light in vacuum",
      "Speed of light in vacuum / Speed of light in medium",
      "Speed of light in medium × Speed of light in vacuum",
      "Speed of light in vacuum + Speed of light in medium"
    ],
    "answer": "Speed of light in vacuum / Speed of light in medium",
    "solutionSteps": [
      "Refractive index n = c/v",
      "where c = speed in vacuum (3×10⁸ m/s)",
      "v = speed in medium"
    ],
    "finalAnswer": "Speed of light in vacuum / Speed of light in medium",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch10 InText Q4"
  },
  {
    "id": "LT2-023",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Spherical Mirrors",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "A concave mirror is also known as a:",
    "options": [
      "Converging mirror",
      "Diverging mirror",
      "Plane mirror",
      "Cylindrical mirror"
    ],
    "answer": "Converging mirror",
    "solutionSteps": [
      "Concave mirrors converge parallel incident rays to a focal point",
      "They are therefore called converging mirrors"
    ],
    "finalAnswer": "Converging mirror",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch10 InText"
  },
  {
    "id": "LT2-024",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Lens Formula",
    "section": "D",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A magnifying glass is a convex lens with power +5 diopters. (a) Find its focal length. (b) At what distance should an object be placed to see a virtual magnified image?",
    "options": [],
    "answer": "(a) f = 20 cm (b) Object distance < 20 cm",
    "solutionSteps": [
      "Part (a): P = 1/f = 5 D",
      "f = 1/5 = 0.2 m = 20 cm",
      "",
      "Part (b): For virtual magnified image with convex lens",
      "Object must be placed between the lens and focal point",
      "i.e., u < f = 20 cm"
    ],
    "finalAnswer": "(a) f = 20 cm (b) Object distance < 20 cm",
    "isCompetencyBased": true,
    "pyqYear": "2022",
    "pyqSet": "All India",
    "ncertRef": "NCERT Ch10 Exercise Q9"
  },
  {
    "id": "LT2-025",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Laws of Reflection",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Two mirrors are inclined at 90° to each other. An object is placed between them. How many images are formed?",
    "options": [
      "1",
      "2",
      "3",
      "4"
    ],
    "answer": "3",
    "solutionSteps": [
      "For two mirrors at angle θ, number of images = (360°/θ) - 1",
      "Here θ = 90°",
      "Number of images = 360°/90° - 1 = 4 - 1 = 3"
    ],
    "finalAnswer": "3",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": "All India",
    "ncertRef": "NCERT Ch10 Exercise Q1"
  },
  {
    "id": "LT2-026",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Laws of Reflection",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "According to the law of reflection, the angle of incidence is always equal to the angle of reflection. These angles are measured from which line?",
    "options": [
      "The reflecting surface",
      "The normal to the reflecting surface",
      "The horizontal plane",
      "The vertical plane"
    ],
    "answer": "The normal to the reflecting surface",
    "solutionSteps": [
      "Both angles of incidence and reflection are measured from the normal (perpendicular) to the reflecting surface",
      "This is a fundamental law of reflection"
    ],
    "finalAnswer": "The normal to the reflecting surface",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch10 InText"
  },
  {
    "id": "LT2-027",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Laws of Reflection",
    "section": "A",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "Assertion (A): A plane mirror always produces an upright and virtual image. Reason (R): The incident ray, reflected ray, and normal all lie in the same plane.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, but R is not the correct explanation of A.",
    "solutionSteps": [
      "Assertion A is true: plane mirrors produce upright virtual images",
      "Reason R is also true: the law of reflection states all three lie in the same plane",
      "But R explains the law of reflection, not why images are upright",
      "The upright nature comes from the geometry of plane mirror reflection"
    ],
    "finalAnswer": "Both A and R are true, but R is not the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch10 InText"
  },
  {
    "id": "LT2-028",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Spherical Mirrors",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "A concave mirror has a focal length of 15 cm. What is its radius of curvature?",
    "options": [
      "7.5 cm",
      "15 cm",
      "30 cm",
      "60 cm"
    ],
    "answer": "30 cm",
    "solutionSteps": [
      "Relationship: R = 2f, where R is radius of curvature and f is focal length",
      "R = 2 × 15 = 30 cm"
    ],
    "finalAnswer": "30 cm",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch10 Exercise"
  },
  {
    "id": "LT2-029",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Spherical Mirrors",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "An object is placed at the center of curvature of a concave mirror. Which of the following is true about its image?",
    "options": [
      "Real, inverted, and magnified",
      "Real, inverted, and same size as object",
      "Virtual, upright, and magnified",
      "Real, upright, and reduced"
    ],
    "answer": "Real, inverted, and same size as object",
    "solutionSteps": [
      "When object is at center of curvature (u = R = 2f)",
      "Using mirror formula: 1/f = 1/u + 1/v gives v = R = 2f",
      "Image is at center of curvature on opposite side",
      "Magnification m = -v/u = -1 (same size, inverted)"
    ],
    "finalAnswer": "Real, inverted, and same size as object",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch10 Exercise"
  },
  {
    "id": "LT2-030",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Mirror Formula",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "An object of height 5 cm is placed at 25 cm from a concave mirror of focal length 10 cm. Find the position of the image.",
    "options": [
      "16.67 cm in front of mirror",
      "20 cm in front of mirror",
      "25 cm behind mirror",
      "10 cm in front of mirror"
    ],
    "answer": "16.67 cm in front of mirror",
    "solutionSteps": [
      "Using mirror formula: 1/f = 1/u + 1/v",
      "Given: f = 10 cm, u = 25 cm",
      "1/10 = 1/25 + 1/v",
      "1/v = 1/10 - 1/25 = (5-2)/50 = 3/50",
      "v = 50/3 = 16.67 cm (in front of mirror)"
    ],
    "finalAnswer": "16.67 cm in front of mirror",
    "isCompetencyBased": true,
    "pyqYear": "2022",
    "pyqSet": "Set 2",
    "ncertRef": "NCERT Ch10 Exercise"
  },
  {
    "id": "LT2-031",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Mirror Formula",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A convex mirror has a focal length of 20 cm. An object is placed at 30 cm from it. Calculate the position and nature of the image formed.",
    "options": [],
    "answer": "Image position: 12 cm behind mirror; Virtual, erect, and diminished",
    "solutionSteps": [
      "For convex mirror: f = +20 cm (positive), u = -30 cm (object distance)",
      "Using mirror formula: 1/f = 1/u + 1/v",
      "1/20 = 1/(-30) + 1/v",
      "1/v = 1/20 + 1/30 = (3+2)/60 = 5/60 = 1/12",
      "v = +12 cm (behind mirror, virtual image)",
      "Magnification m = -v/u = -12/(-30) = 0.4 (diminished)"
    ],
    "finalAnswer": "Image position: 12 cm behind mirror; Virtual, erect, and diminished",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch10 Exercise"
  },
  {
    "id": "LT2-032",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Spherical Mirrors",
    "section": "C",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "A concave mirror is used in a searchlight. Why is the light source placed at the focal point of the mirror?",
    "options": [
      "To produce a real, inverted, and magnified image",
      "To produce parallel rays of light",
      "To produce virtual, erect, and magnified image",
      "To reduce the intensity of light"
    ],
    "answer": "To produce parallel rays of light",
    "solutionSteps": [
      "When object is at focal point (u = f) of concave mirror",
      "From mirror formula: 1/f = 1/f + 1/v gives 1/v = 0, so v = ∞",
      "Image at infinity means reflected rays are parallel",
      "This is useful in searchlights for long-distance illumination"
    ],
    "finalAnswer": "To produce parallel rays of light",
    "isCompetencyBased": true,
    "pyqYear": "2021",
    "pyqSet": "Set 1",
    "ncertRef": "NCERT Ch10 InText"
  },
  {
    "id": "LT2-033",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Refraction",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "Refraction of light occurs when light passes from one medium to another because of the change in:",
    "options": [
      "Frequency of light",
      "Wavelength and speed of light",
      "Amplitude of light",
      "Direction of light source"
    ],
    "answer": "Wavelength and speed of light",
    "solutionSteps": [
      "Frequency remains constant during refraction",
      "When light enters a different medium, its speed changes",
      "As v = fλ, if v changes and f is constant, λ must change",
      "This change in speed causes bending of light"
    ],
    "finalAnswer": "Wavelength and speed of light",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch10 InText"
  },
  {
    "id": "LT2-034",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Refraction",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "The refractive index of a medium is 1.5. What is the speed of light in this medium? (Speed of light in vacuum c = 3 × 10⁸ m/s)",
    "options": [
      "4.5 × 10⁸ m/s",
      "2 × 10⁸ m/s",
      "1 × 10⁸ m/s",
      "3 × 10⁸ m/s"
    ],
    "answer": "2 × 10⁸ m/s",
    "solutionSteps": [
      "Refractive index n = c/v",
      "1.5 = (3 × 10⁸)/v",
      "v = (3 × 10⁸)/1.5 = 2 × 10⁸ m/s"
    ],
    "finalAnswer": "2 × 10⁸ m/s",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": "Set 1",
    "ncertRef": "NCERT Ch10 Exercise"
  },
  {
    "id": "LT2-035",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Refraction",
    "section": "C",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Assertion (A): A pencil partially immersed in water appears bent at the water surface. Reason (R): Light travels at the same speed in water and air.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "A is true, R is false.",
    "solutionSteps": [
      "Assertion A is true: due to refraction, pencil appears bent",
      "Reason R is false: light travels at different speeds in different media",
      "Water (n=1.33) has slower light speed than air (n=1)",
      "This difference in speed causes refraction and apparent bending"
    ],
    "finalAnswer": "A is true, R is false.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch10 InText"
  },
  {
    "id": "LT2-036",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Lens Formula",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "The lens formula is used to find the relationship between object distance, image distance, and focal length. Which equation represents the lens formula?",
    "options": [
      "1/f = 1/u - 1/v",
      "1/f = 1/u + 1/v",
      "f = u + v",
      "f = u/v"
    ],
    "answer": "1/f = 1/u + 1/v",
    "solutionSteps": [
      "The lens formula is: 1/f = 1/u + 1/v",
      "where f = focal length, u = object distance, v = image distance",
      "This applies to both converging and diverging lenses"
    ],
    "finalAnswer": "1/f = 1/u + 1/v",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch10 Exercise"
  },
  {
    "id": "LT2-037",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Lens Formula",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A convex lens has focal length 20 cm. An object is placed at 30 cm from it. Find the image distance.",
    "options": [
      "20 cm",
      "30 cm",
      "60 cm",
      "-60 cm"
    ],
    "answer": "60 cm",
    "solutionSteps": [
      "Using lens formula: 1/f = 1/u + 1/v",
      "Given: f = 20 cm, u = 30 cm",
      "1/20 = 1/30 + 1/v",
      "1/v = 1/20 - 1/30 = (3-2)/60 = 1/60",
      "v = 60 cm (positive, real image)"
    ],
    "finalAnswer": "60 cm",
    "isCompetencyBased": true,
    "pyqYear": "2024",
    "pyqSet": "Set 1",
    "ncertRef": "NCERT Ch10 Exercise"
  },
  {
    "id": "LT2-038",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Lens Formula",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A concave lens has a focal length of 15 cm. An object of height 4 cm is placed at 30 cm from the lens. Calculate the position and size of the image.",
    "options": [],
    "answer": "Image position: 10 cm on same side as object; Image height: 1.33 cm",
    "solutionSteps": [
      "For concave lens: f = -15 cm, u = -30 cm",
      "Using lens formula: 1/f = 1/u + 1/v",
      "1/(-15) = 1/(-30) + 1/v",
      "-1/15 = -1/30 + 1/v",
      "1/v = -1/15 + 1/30 = (-2+1)/30 = -1/30",
      "v = -10 cm (virtual image, same side as object)",
      "Magnification m = v/u = (-10)/(-30) = 1/3",
      "Image height = 4 × 1/3 = 1.33 cm"
    ],
    "finalAnswer": "Image position: 10 cm on same side as object; Image height: 1.33 cm",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch10 Exercise"
  },
  {
    "id": "LT2-039",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Refraction",
    "section": "C",
    "marks": 2,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Light travels from a medium of refractive index 1.5 to air (refractive index 1). The angle of incidence is 30°. Using Snell's law, find the angle of refraction.",
    "options": [],
    "answer": "Angle of refraction ≈ 48.6°",
    "solutionSteps": [
      "Using Snell's law: n₁ sin θ₁ = n₂ sin θ₂",
      "n₁ = 1.5 (denser medium), θ₁ = 30°",
      "n₂ = 1 (air), θ₂ = ?",
      "1.5 × sin(30°) = 1 × sin(θ₂)",
      "1.5 × 0.5 = sin(θ₂)",
      "0.75 = sin(θ₂)",
      "θ₂ = sin⁻¹(0.75) ≈ 48.6°",
      "Light bends away from normal when going from denser to rarer medium"
    ],
    "finalAnswer": "Angle of refraction ≈ 48.6°",
    "isCompetencyBased": true,
    "pyqYear": "2020",
    "pyqSet": "Set 3",
    "ncertRef": "NCERT Ch10 InText"
  },
  {
    "id": "LT2-040",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Spherical Mirrors",
    "section": "C",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Assertion (A): A convex mirror always forms a virtual, erect, and diminished image. Reason (R): The focal point and center of curvature of a convex mirror are behind the mirror surface.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "Assertion A is true: convex mirrors always form virtual, erect, diminished images",
      "Reason R is true: focal point and center of curvature are behind the mirror",
      "The position behind mirror means light never actually converges",
      "This results in virtual image formation always",
      "The diverging nature produces diminished, erect images"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch10 InText"
  },
  {
    "id": "LT2-041",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Lens Formula",
    "section": "C",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "A converging lens of focal length 10 cm forms an image at 15 cm from the lens. What are the possible object distances?",
    "options": [
      "30 cm only",
      "6 cm only",
      "30 cm and 6 cm",
      "15 cm only"
    ],
    "answer": "30 cm and 6 cm",
    "solutionSteps": [
      "Using lens formula: 1/f = 1/u + 1/v",
      "Given: f = 10 cm, v = 15 cm",
      "1/10 = 1/u + 1/15",
      "1/u = 1/10 - 1/15 = (3-2)/30 = 1/30",
      "u = 30 cm (object beyond 2f, real image)",
      "If v = -15 cm (virtual image on same side)",
      "1/10 = 1/u - 1/15",
      "1/u = 1/10 + 1/15 = (3+2)/30 = 1/6",
      "u = 6 cm (object between f and 2f)"
    ],
    "finalAnswer": "30 cm and 6 cm",
    "isCompetencyBased": true,
    "pyqYear": "2025",
    "pyqSet": "Set 2",
    "ncertRef": "NCERT Ch10 Exercise"
  },
  {
    "id": "LT2-042",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Refraction",
    "section": "E",
    "marks": 4,
    "format": "Case-Based",
    "difficulty": "Medium",
    "bloomSkill": "Analysing",
    "questionText": "A student observes that when light passes through a glass prism, it bends towards the normal at the first surface and away from the normal at the second surface. The refractive index of glass is 1.5 and the refractive index of air is 1. Based on this observation, answer the following:\n(i) Why does light bend towards normal at the first surface?\n(ii) Calculate the speed of light in glass.\n(iii) If the angle of incidence is 45° at the first surface, find the angle of refraction using Snell's law.\n(iv) Explain what happens to the frequency and wavelength of light in glass.",
    "options": [],
    "answer": "(i) Light bends towards normal when entering denser medium; (ii) 2×10⁸ m/s; (iii) 28.1°; (iv) Frequency constant, wavelength decreases",
    "solutionSteps": [
      "(i) When light passes from air (rarer) to glass (denser), it bends towards normal because light slows down",
      "(ii) n = c/v → 1.5 = (3×10⁸)/v → v = 2×10⁸ m/s",
      "(iii) At first surface: n₁sinθ₁ = n₂sinθ₂ → 1×sin45° = 1.5×sinθ₂ → 0.707 = 1.5×sinθ₂ → sinθ₂ = 0.471 → θ₂ = 28.1°",
      "(iv) Frequency remains constant (determined by source), but wavelength decreases as λ = v/f and v decreases in glass"
    ],
    "finalAnswer": "(i) Light bends towards normal when entering denser medium; (ii) 2×10⁸ m/s; (iii) 28.1°; (iv) Frequency constant, wavelength decreases",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": "Set 2",
    "ncertRef": "NCERT Ch10 InText, NCERT Ch10 Exercise"
  },
  {
    "id": "LT2-043",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Mirror Formula",
    "section": "D",
    "marks": 5,
    "format": "Long",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "An object of height 10 cm is placed at different positions in front of a concave mirror of focal length 20 cm. For each position, determine: (a) Image position, (b) Image height, (c) Nature of image (real/virtual, inverted/erect, magnified/diminished). Consider object positions at: (i) 60 cm, (ii) 40 cm, (iii) 20 cm. Also explain the practical applications of such mirrors.",
    "options": [],
    "answer": "(i) u=60cm: v=30cm, h=5cm, real inverted diminished; (ii) u=40cm: v=40cm, h=10cm, real inverted same size; (iii) u=20cm: v=∞, h=∞, image at infinity",
    "solutionSteps": [
      "(i) u = 60 cm: 1/20 = 1/60 + 1/v → 1/v = 1/20 - 1/60 = 1/30 → v = 30 cm",
      "Magnification m = -v/u = -30/60 = -0.5 → Image height = 10 × 0.5 = 5 cm",
      "Nature: Real (v positive), inverted (m negative), diminished (|m| < 1)",
      "(ii) u = 40 cm: 1/20 = 1/40 + 1/v → 1/v = 1/20 - 1/40 = 1/40 → v = 40 cm",
      "m = -40/40 = -1 → Image height = 10 × 1 = 10 cm",
      "Nature: Real, inverted, same size",
      "(iii) u = 20 cm (at focal point): 1/20 = 1/20 + 1/v → 1/v = 0 → v = ∞",
      "Image at infinity with infinite height; rays emerge parallel",
      "Applications: Searchlights use this principle for parallel beam; shaving mirrors use position (i) for magnification"
    ],
    "finalAnswer": "(i) u=60cm: v=30cm, h=5cm, real inverted diminished; (ii) u=40cm: v=40cm, h=10cm, real inverted same size; (iii) u=20cm: v=∞, h=∞, image at infinity",
    "isCompetencyBased": true,
    "pyqYear": "2022",
    "pyqSet": "Set 1",
    "ncertRef": "NCERT Ch10 Exercise"
  },
  {
    "id": "LT2-044",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Lens Formula",
    "section": "D",
    "marks": 5,
    "format": "Long",
    "difficulty": "Hard",
    "bloomSkill": "Creating",
    "questionText": "A camera uses a converging lens of focal length 5 cm to form images of objects at different distances. (a) If an object at distance 20 cm is to be photographed, calculate the image distance and magnification. (b) What happens to the image when the object is moved closer to the lens? (c) Explain why adjusting the position of the film (sensor) is necessary when photographing objects at different distances. (d) Design an optical system that can photograph both near and distant objects clearly.",
    "options": [],
    "answer": "Image at 6.67cm, magnification -0.33; Image moves farther as object approaches; Focus adjustment needed; Use autofocus or variable aperture",
    "solutionSteps": [
      "(a) f = 5 cm, u = 20 cm (object beyond 2f = 10 cm)",
      "1/5 = 1/20 + 1/v → 1/v = 1/5 - 1/20 = 3/20 → v = 6.67 cm",
      "m = -v/u = -6.67/20 = -0.33 (diminished inverted)",
      "(b) As object approaches lens, image distance increases (moves away from lens)",
      "When u = 10 cm: 1/5 = 1/10 + 1/v → v = 10 cm",
      "When u approaches f = 5 cm: v approaches infinity",
      "(c) Since v depends on u through lens formula, different object distances require different image distances",
      "The sensor/film must be at image distance for sharp focus",
      "(d) Autofocus systems use sensors to detect focus and adjust lens position; Variable aperture increases depth of field"
    ],
    "finalAnswer": "Image at 6.67cm, magnification -0.33; Image moves farther as object approaches; Focus adjustment needed; Use autofocus or variable aperture",
    "isCompetencyBased": true,
    "pyqYear": "2024",
    "pyqSet": "Set 3",
    "ncertRef": "NCERT Ch10 Exercise"
  },
  {
    "id": "LT2-045",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Laws of Reflection",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "A ray of light is incident on a plane mirror at an angle of 40° to the mirror surface. What is the angle of incidence?",
    "options": [
      "40°",
      "50°",
      "60°",
      "80°"
    ],
    "answer": "50°",
    "solutionSteps": [
      "Angle to mirror surface = 40°",
      "Angle of incidence is measured from normal (perpendicular to surface)",
      "Angle of incidence = 90° - 40° = 50°"
    ],
    "finalAnswer": "50°",
    "isCompetencyBased": true,
    "pyqYear": "2019",
    "pyqSet": "Set 1",
    "ncertRef": "NCERT Ch10 InText"
  },
  {
    "id": "LT2-046",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Refraction",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "A glass block with refractive index 1.6 is placed on a table. A light ray is incident at the top surface with an angle of incidence of 60°. Calculate the angle of refraction at the air-glass interface and explain the phenomenon.",
    "options": [],
    "answer": "Angle of refraction ≈ 33.7°; Light bends towards normal",
    "solutionSteps": [
      "Using Snell's law: n₁sinθ₁ = n₂sinθ₂",
      "n₁ = 1 (air), θ₁ = 60°, n₂ = 1.6 (glass)",
      "1 × sin(60°) = 1.6 × sin(θ₂)",
      "0.866 = 1.6 × sin(θ₂)",
      "sin(θ₂) = 0.541",
      "θ₂ = 32.8° ≈ 33.7°",
      "Phenomenon: Light bends towards normal because glass is optically denser than air, reducing light speed"
    ],
    "finalAnswer": "Angle of refraction ≈ 33.7°; Light bends towards normal",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch10 Exercise"
  },
  {
    "id": "LT2-047",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Spherical Mirrors",
    "section": "C",
    "marks": 2,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "A dentist uses a concave mirror to examine teeth. Explain why a concave mirror is preferred, what type of image is formed, and at what object distance this occurs. How would the image change if a convex mirror were used instead?",
    "options": [],
    "answer": "Concave mirror forms magnified virtual erect image when object is between f and mirror; convex mirror always forms diminished virtual image",
    "solutionSteps": [
      "Concave mirror acts as diverging when object between f and mirror surface (u < f)",
      "From mirror formula: when u < f, 1/v becomes negative, giving v negative (virtual, behind mirror)",
      "Magnification m = -v/u becomes positive, giving erect image with |m| > 1 (magnified)",
      "This position (u < f) is ideal for dental examination - magnified and erect view",
      "Convex mirror: always gives virtual, erect, diminished image regardless of position",
      "Too diminished for detailed dental work - would not show sufficient detail",
      "Therefore concave mirror is superior for dental applications"
    ],
    "finalAnswer": "Concave mirror forms magnified virtual erect image when object is between f and mirror; convex mirror always forms diminished virtual image",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch10 InText"
  },
  {
    "id": "LT2-048",
    "subject": "Science",
    "topicKey": "Light – Reflection and Refraction",
    "subtopic": "Lens Formula",
    "section": "C",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Analysing",
    "questionText": "A lens has a focal length of 25 cm. Its power is:",
    "options": [
      "+4 D",
      "+0.04 D",
      "+2.5 D",
      "-4 D"
    ],
    "answer": "+4 D",
    "solutionSteps": [
      "Power P = 1/f (in meters)",
      "f = 25 cm = 0.25 m",
      "P = 1/0.25 = 4 D (diopters)",
      "Positive power indicates converging lens"
    ],
    "finalAnswer": "+4 D",
    "isCompetencyBased": true,
    "pyqYear": "2021",
    "pyqSet": "Set 3",
    "ncertRef": "NCERT Ch10 Exercise"
  }
];
