import type { CanonicalQuestion } from "../../types";

export const ME2_PACK2: CanonicalQuestion[] = [
  {
    "id": "ME2-001",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Magnetic Field",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "The magnetic field around a straight current-carrying conductor is represented by:",
    "options": [
      "Straight lines",
      "Concentric circles",
      "Elliptical paths",
      "Parabolic curves"
    ],
    "answer": "Concentric circles",
    "solutionSteps": [
      "A straight current-carrying conductor produces a magnetic field around it.",
      "The field lines form concentric circles centered on the wire.",
      "This pattern can be verified using the right-hand thumb rule."
    ],
    "finalAnswer": "Concentric circles",
    "explanation": "A straight current-carrying conductor produces a magnetic field around it. The field lines form concentric circles centered on the wire. This pattern can be verified using the right-hand thumb rule. Therefore, the correct answer is Concentric circles.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch13 InText Q1"
  },
  {
    "id": "ME2-002",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Magnetic Field",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "Which of the following is NOT a characteristic of magnetic field lines?",
    "options": [
      "They form closed loops",
      "They never intersect each other",
      "They originate from south pole and end at north pole",
      "They represent direction of force on north pole"
    ],
    "answer": "They originate from south pole and end at north pole",
    "solutionSteps": [
      "Magnetic field lines originate from north pole and end at south pole (outside the magnet).",
      "Inside the magnet, they travel from south to north.",
      "Other options are correct characteristics of field lines."
    ],
    "finalAnswer": "They originate from south pole and end at north pole",
    "explanation": "Magnetic field lines originate from north pole and end at south pole (outside the magnet). Inside the magnet, they travel from south to north. Other options are correct characteristics of field lines. Therefore, the correct answer is They originate from south pole and end at north pole.",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch13 InText"
  },
  {
    "id": "ME2-003",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Magnetic Field",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A wire carrying current is placed perpendicular to a magnetic field. The force on the wire is maximum when:",
    "options": [
      "Wire is parallel to field",
      "Wire is perpendicular to field",
      "Wire makes 45° angle with field",
      "Wire is at angle between parallel and perpendicular"
    ],
    "answer": "Wire is perpendicular to field",
    "solutionSteps": [
      "Force on current-carrying wire: F = BIL sin θ",
      "Force is maximum when sin θ = 1, i.e., θ = 90°",
      "This means wire must be perpendicular to magnetic field."
    ],
    "finalAnswer": "Wire is perpendicular to field",
    "explanation": "Force on current-carrying wire: F = BIL sin θ. Force is maximum when sin θ = 1, i.e., θ = 90°. This means wire must be perpendicular to magnetic field. Therefore, the correct answer is Wire is perpendicular to field.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch13 InText"
  },
  {
    "id": "ME2-004",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Fleming Rules",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "Fleming's left-hand rule is used to determine:",
    "options": [
      "Direction of magnetic field",
      "Direction of induced current",
      "Direction of force on current-carrying conductor",
      "Magnitude of induced EMF"
    ],
    "answer": "Direction of force on current-carrying conductor",
    "solutionSteps": [
      "Fleming's left-hand rule: Thumb (Force), Index (field), Middle (current)",
      "It determines the direction of force when current flows through a conductor in a magnetic field.",
      "Fleming's right-hand rule is used for electromagnetic induction."
    ],
    "finalAnswer": "Direction of force on current-carrying conductor",
    "explanation": "Fleming's left-hand rule: Thumb (Force), Index (field), Middle (current). It determines the direction of force when current flows through a conductor in a magnetic field. Fleming's right-hand rule is used for electromagnetic induction. Therefore, the correct answer is Direction of force on current-carrying conductor.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch13 InText Q2"
  },
  {
    "id": "ME2-005",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Fleming Rules",
    "section": "A",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Analysing",
    "questionText": "Assertion: Fleming's right-hand rule is used in electric motors. Reason: It determines the direction of force on the current-carrying coil.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "A is false, R is true.",
    "solutionSteps": [
      "Fleming's LEFT-hand rule is used in electric motors (motor rule).",
      "Fleming's right-hand rule is used in electromagnetic induction.",
      "The reason states correct function but applied to wrong rule."
    ],
    "finalAnswer": "A is false, R is true.",
    "explanation": "The Assertion contains an incorrect claim. The Reason, however, is a true and valid statement on its own.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch13 Exercise"
  },
  {
    "id": "ME2-006",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Electromagnet",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "An electromagnet can be made stronger by:",
    "options": [
      "Decreasing the number of turns in the coil",
      "Increasing the current through the coil",
      "Using a wooden core instead of iron",
      "Reducing the area of the coil"
    ],
    "answer": "Increasing the current through the coil",
    "solutionSteps": [
      "Strength of electromagnet depends on: number of turns, current, and core material.",
      "Higher current → stronger magnetic field",
      "More turns → stronger field",
      "Soft iron core → stronger field than air/wood"
    ],
    "finalAnswer": "Increasing the current through the coil",
    "explanation": "Strength of electromagnet depends on: number of turns, current, and core material. Higher current → stronger magnetic field. More turns → stronger field. Soft iron core → stronger field than air/wood. Therefore, the correct answer is Increasing the current through the coil.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch13 InText Q3"
  },
  {
    "id": "ME2-007",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Electromagnet",
    "section": "A",
    "marks": 1,
    "format": "Short",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "Name the material most suitable for making the core of an electromagnet.",
    "options": [],
    "answer": "Soft iron (or iron core)",
    "solutionSteps": [
      "Soft iron has high permeability and low retentivity.",
      "It readily magnetizes and demagnetizes when current is switched on/off.",
      "This makes it ideal for electromagnets in practical applications."
    ],
    "finalAnswer": "Soft iron (or iron core)",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch13 InText"
  },
  {
    "id": "ME2-008",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Electric Motor",
    "section": "B",
    "marks": 2,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "In an electric motor, the split ring commutator serves the purpose of:",
    "options": [
      "Converting mechanical energy to electrical energy",
      "Reversing the direction of current in the coil periodically",
      "Reducing the friction in bearings",
      "Increasing the speed of rotation"
    ],
    "answer": "Reversing the direction of current in the coil periodically",
    "solutionSteps": [
      "Commutator is a split ring that rotates with the coil.",
      "It ensures current reversal every half rotation.",
      "This maintains continuous rotation in one direction.",
      "Without it, the coil would oscillate back and forth."
    ],
    "finalAnswer": "Reversing the direction of current in the coil periodically",
    "explanation": "Commutator is a split ring that rotates with the coil. It ensures current reversal every half rotation. This maintains continuous rotation in one direction. Without it, the coil would oscillate back and forth. Therefore, the correct answer is Reversing the direction of current in the coil periodically.",
    "isCompetencyBased": true,
    "pyqYear": "2021",
    "pyqSet": "Delhi",
    "ncertRef": "NCERT Ch13 InText Q4"
  },
  {
    "id": "ME2-009",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Electric Motor",
    "section": "B",
    "marks": 2,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "The principle of an electric motor is based on:",
    "options": [
      "Electromagnetic induction",
      "Force on a current-carrying conductor in a magnetic field",
      "Self-induction",
      "Mutual induction"
    ],
    "answer": "Force on a current-carrying conductor in a magnetic field",
    "solutionSteps": [
      "When current flows through a conductor in a magnetic field, it experiences a force.",
      "This force causes the coil to rotate in the motor.",
      "The direction of force is given by Fleming's left-hand rule."
    ],
    "finalAnswer": "Force on a current-carrying conductor in a magnetic field",
    "explanation": "When current flows through a conductor in a magnetic field, it experiences a force. This force causes the coil to rotate in the motor. The direction of force is given by Fleming's left-hand rule. Therefore, the correct answer is Force on a current-carrying conductor in a magnetic field.",
    "isCompetencyBased": true,
    "pyqYear": "2020",
    "pyqSet": "All India",
    "ncertRef": "NCERT Ch13 Exercise Q1"
  },
  {
    "id": "ME2-010",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Electric Motor",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Draw a simple diagram of an electric motor and label its main parts (coil, commutator, magnetic field).",
    "options": [],
    "answer": "Labeled diagram of DC motor with all essential components",
    "solutionSteps": [
      "Draw a rectangular coil positioned between two magnetic poles.",
      "Show the split-ring commutator at the center.",
      "Indicate brushes connected to external circuit.",
      "Mark direction of current and magnetic field.",
      "Show direction of force/motion using arrows."
    ],
    "finalAnswer": "Labeled diagram of DC motor with all essential components",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch13 InText"
  },
  {
    "id": "ME2-011",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Electromagnetic Induction",
    "section": "B",
    "marks": 2,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "Electromagnetic induction is the phenomenon of:",
    "options": [
      "Magnetization of iron",
      "Generation of electric current due to changing magnetic field",
      "Deflection of compass needle",
      "Production of magnetic field by permanent magnet"
    ],
    "answer": "Generation of electric current due to changing magnetic field",
    "solutionSteps": [
      "Faraday discovered that changing magnetic flux induces EMF.",
      "This induces current in a conductor.",
      "Rate of change of flux determines magnitude of induced EMF.",
      "This is the principle of generators and transformers."
    ],
    "finalAnswer": "Generation of electric current due to changing magnetic field",
    "explanation": "Faraday discovered that changing magnetic flux induces EMF. This induces current in a conductor. Rate of change of flux determines magnitude of induced EMF. This is the principle of generators and transformers. Therefore, the correct answer is Generation of electric current due to changing magnetic field.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch13 InText Q5"
  },
  {
    "id": "ME2-012",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Electromagnetic Induction",
    "section": "B",
    "marks": 2,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "When a magnet is moved towards a coil, the induced current direction is such that it:",
    "options": [
      "Attracts the magnet",
      "Repels the magnet",
      "Remains unaffected by magnet's motion",
      "Oscillates between attraction and repulsion"
    ],
    "answer": "Repels the magnet",
    "solutionSteps": [
      "By Lenz's law, induced effect opposes the cause.",
      "When magnet approaches, flux increases.",
      "Induced current creates field opposing this increase.",
      "This induced field repels the approaching magnet."
    ],
    "finalAnswer": "Repels the magnet",
    "explanation": "By Lenz's law, induced effect opposes the cause. When magnet approaches, flux increases. Induced current creates field opposing this increase. This induced field repels the approaching magnet. Therefore, the correct answer is Repels the magnet.",
    "isCompetencyBased": true,
    "pyqYear": "2019",
    "pyqSet": "Delhi",
    "ncertRef": "NCERT Ch13 InText"
  },
  {
    "id": "ME2-013",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Electromagnetic Induction",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "State Faraday's law of electromagnetic induction.",
    "options": [],
    "answer": "ε = -dΦ/dt (Induced EMF = negative rate of change of flux)",
    "solutionSteps": [
      "Faraday's law quantifies electromagnetic induction.",
      "Induced EMF is proportional to rate of change of magnetic flux.",
      "Negative sign indicates Lenz's law (opposition to change).",
      "Stronger the change in flux, greater the induced EMF."
    ],
    "finalAnswer": "ε = -dΦ/dt (Induced EMF = negative rate of change of flux)",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch13 Exercise Q2"
  },
  {
    "id": "ME2-014",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Electromagnetic Induction",
    "section": "C",
    "marks": 3,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Analysing",
    "questionText": "Assertion: A magnet moving towards a coil induces a larger current than a magnet moving away. Reason: The rate of change of magnetic flux is greater when magnet approaches.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "Induced current depends on rate of change of flux (Faraday's law).",
      "Flux change is typically faster when magnet approaches (entering field region).",
      "Higher rate of change → larger induced EMF → larger current.",
      "Both statements are correct and logically connected."
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "explanation": "Both the Assertion and the Reason are correct statements. The Reason directly explains the scientific/mathematical basis that makes the Assertion true, so R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch13 InText"
  },
  {
    "id": "ME2-015",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "AC and DC",
    "section": "C",
    "marks": 3,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "Direct current (DC) is produced by:",
    "options": [
      "AC generator with commutator",
      "DC generator with slip rings",
      "DC generator with commutator",
      "All AC generators"
    ],
    "answer": "DC generator with commutator",
    "solutionSteps": [
      "DC generator uses a split-ring commutator.",
      "Commutator reverses connections every half rotation.",
      "This converts alternating EMF into unidirectional (DC) output.",
      "Slip rings produce AC; commutator produces DC."
    ],
    "finalAnswer": "DC generator with commutator",
    "explanation": "DC generator uses a split-ring commutator. Commutator reverses connections every half rotation. This converts alternating EMF into unidirectional (DC) output. Slip rings produce AC; commutator produces DC. Therefore, the correct answer is DC generator with commutator.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch13 InText Q6"
  },
  {
    "id": "ME2-016",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "AC and DC",
    "section": "C",
    "marks": 3,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Alternating current (AC) differs from direct current (DC) in that:",
    "options": [
      "AC has higher voltage",
      "AC's direction changes periodically with time",
      "AC is always more efficient",
      "AC requires no conductor"
    ],
    "answer": "AC's direction changes periodically with time",
    "solutionSteps": [
      "AC: Current direction reverses at regular intervals (50/60 Hz in India/US).",
      "DC: Current flows in only one direction.",
      "AC uses slip rings in generators; DC uses commutator.",
      "AC and DC generators differ in output waveform, not fundamentally in voltage."
    ],
    "finalAnswer": "AC's direction changes periodically with time",
    "explanation": "AC: Current direction reverses at regular intervals (50/60 Hz in India/US). DC: Current flows in only one direction. AC uses slip rings in generators; DC uses commutator. AC and DC generators differ in output waveform, not fundamentally in voltage. Therefore, the correct answer is AC's direction changes periodically with time.",
    "isCompetencyBased": true,
    "pyqYear": "2022",
    "pyqSet": "All India",
    "ncertRef": "NCERT Ch13 InText"
  },
  {
    "id": "ME2-017",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "AC and DC",
    "section": "C",
    "marks": 3,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Why is AC preferred over DC for long-distance transmission of electrical power?",
    "options": [],
    "answer": "Transformers enable voltage step-up/down; high voltage reduces I²R losses",
    "solutionSteps": [
      "AC can be transformed to high voltage using step-up transformer.",
      "Power loss = I²R; at same power, high voltage means low current.",
      "Low current reduces resistive losses in transmission lines.",
      "At destination, step-down transformer reduces voltage for use.",
      "DC cannot be easily transformed, requiring high current for transmission."
    ],
    "finalAnswer": "AC (alternating current) is preferred over DC (direct current) for long-distance electrical power transmission because AC voltage can be easily stepped up or down using transformers, whereas DC cannot be transformed efficiently by conventional transformers. Before transmission, a step-up transformer raises the voltage to a very high level (such as hundreds of thousands of volts), which proportionally reduces the current. Since the power lost as heat in the transmission cables is given by P = I²R, reducing the current dramatically reduces the resistive losses in the lines. At the destination, a step-down transformer reduces the voltage to a safe level suitable for domestic and industrial use. This makes AC transmission far more energy-efficient and economical over long distances than DC transmission.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch13 Exercise Q3"
  },
  {
    "id": "ME2-018",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Magnetic Field",
    "section": "C",
    "marks": 3,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "A current-carrying circular coil experiences no net force in a uniform magnetic field, but experiences a torque. Explain why.",
    "options": [],
    "answer": "Equal opposite forces form couple producing torque without net force",
    "solutionSteps": [
      "Consider two opposite sides of a circular coil.",
      "Current directions are opposite in these sides.",
      "Forces on them are opposite (by F = BIL sin θ).",
      "Equal and opposite forces don't produce net force.",
      "But they are displaced, forming a couple.",
      "Couple produces torque: τ = NBIA sin θ"
    ],
    "finalAnswer": "When a current-carrying circular coil is placed in a uniform magnetic field, the force on each small current element is given by F = BIL sin θ. Opposite sides of the coil carry current in opposite directions; by Fleming's left-hand rule, the forces on opposite sides are equal in magnitude but opposite in direction. Since these two equal and opposite forces are not collinear (they act along parallel lines separated by the diameter of the coil), they form a couple. A couple produces a net torque (rotational turning effect) that tends to rotate the coil about its axis; however, because the two forces are exactly equal and opposite, the net translational (linear) force on the coil as a whole is zero — the coil experiences no net force and will not translate, but it will rotate due to the torque produced by the couple.",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": "Delhi",
    "ncertRef": "NCERT Ch13 Exercise"
  },
  {
    "id": "ME2-019",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Electric Motor",
    "section": "E",
    "marks": 4,
    "format": "Case-Based",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A student is building a simple DC motor using a battery, rectangular coil, permanent magnet, and commutator. (a) Why is a commutator essential in this motor? (b) What would happen if the commutator were replaced with slip rings? (c) How can the motor's speed be increased? (d) Explain the direction of force on the coil sides using Fleming's rule.",
    "options": [],
    "answer": "Detailed explanation of motor operation, commutator function, and factors affecting speed",
    "solutionSteps": [
      "(a) Each coil half-rotation reverses the magnetic force direction automatically.",
      "(b) Slip rings don't reverse connections, so forces would alternate.",
      "(c) From τ = NBIA sin θ, torque increases with I, B, and N.",
      "(d) Apply Fleming's left-hand rule to coil sides AB and CD.",
      "Show side AB experiences force in one direction, CD in opposite.",
      "This creates net torque causing rotation."
    ],
    "finalAnswer": "(a) The commutator is essential in a DC motor because at each half rotation of the coil it reverses the direction of current through the coil, ensuring that the force on the coil always acts in the same rotational direction to produce continuous rotation. (b) If the commutator were replaced with slip rings, the current direction would not be reversed at each half rotation, so the force would alternate direction and the coil would oscillate back and forth rather than rotate continuously. (c) The motor's speed can be increased by increasing the current through the coil, increasing the strength of the magnetic field, or increasing the number of turns in the coil, since torque τ = NBIA sin θ depends on all three quantities. (d) Applying Fleming's left-hand rule to the coil sides, side AB experiences a force in one direction (say upward) and side CD experiences an equal and opposite force (downward), creating a net torque that causes the coil to rotate continuously.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch13 InText & Exercise"
  },
  {
    "id": "ME2-020",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Electromagnetic Induction",
    "section": "E",
    "marks": 4,
    "format": "Case-Based",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "An AC generator produces a sinusoidal voltage with peak value 310 V and frequency 50 Hz. (a) What is the RMS voltage? (b) What is the period of oscillation? (c) Explain why the induced EMF varies sinusoidally. (d) How does increasing the rotation speed affect the frequency?",
    "options": [],
    "answer": "RMS=219V, T=0.02s, sinusoidal due to rotating coil geometry, f increases with speed",
    "solutionSteps": [
      "(a) RMS voltage = V_peak/√2 = 310/1.414 = 219.2 V",
      "(b) Period T = 1/f = 1/50 = 0.02 seconds = 20 ms",
      "(c) As coil rotates, angle θ = ωt changes, so EMF = NABω sin(ωt) varies sinusoidally.",
      "(d) f = Np/60 where N is speed, p is poles. Higher speed → higher frequency.",
      "Show relationship: at 50 Hz, coil completes 50 cycles per second."
    ],
    "finalAnswer": "RMS=219V, T=0.02s, sinusoidal due to rotating coil geometry, f increases with speed",
    "isCompetencyBased": true,
    "pyqYear": "2024",
    "pyqSet": "All India",
    "ncertRef": "NCERT Ch13 Exercise Q4"
  },
  {
    "id": "ME2-021",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Electromagnetic Induction",
    "section": "D",
    "marks": 5,
    "format": "Long",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "Explain the working of an AC generator with a neat labeled diagram. Describe how the induced EMF varies with rotation and derive the expression EMF = NABω sin(ωt). Also explain the advantage of AC generator over DC generator.",
    "options": [],
    "answer": "Complete AC generator analysis with diagram, EMF derivation, and advantages over DC",
    "solutionSteps": [
      "1. Draw AC generator diagram: rectangular coil between N-S poles, slip rings, brushes, galvanometer.",
      "2. Explain: Rotating coil experiences changing magnetic flux.",
      "3. Magnetic flux: Φ = NAB cos(θ) where θ = ωt",
      "4. Induced EMF: ε = -dΦ/dt = NABω sin(ωt)",
      "5. At θ = 0°: EMF = 0; At θ = 90°: EMF = maximum (NABω)",
      "6. At θ = 180°: EMF = 0; At θ = 270°: EMF = -maximum",
      "7. This produces sinusoidal variation.",
      "8. Advantages of AC: Easily transformed, less power loss in transmission, cheaper to produce.",
      "9. DC generator requires split-ring commutator, more complex, difficult to transform."
    ],
    "finalAnswer": "An AC generator consists of a rectangular coil rotating between the poles of a permanent magnet, connected to an external circuit through slip rings and brushes. As the coil rotates, the magnetic flux through it changes as Φ = NAB cos(ωt). By Faraday's law of electromagnetic induction, the induced EMF is ε = −dΦ/dt = NABω sin(ωt), where N is the number of turns, A is the area of the coil, B is the magnetic field strength, and ω is the angular velocity. The induced EMF is zero when the coil lies perpendicular to the field (θ = 0°), rises to a maximum of NABω at θ = 90°, returns to zero at θ = 180°, and reaches a negative maximum at θ = 270°, producing a sinusoidal variation. The main advantages of the AC generator over the DC generator are: (i) AC voltage can be easily stepped up or down using transformers, reducing power loss during long-distance transmission; (ii) AC generators are simpler in construction as they use slip rings instead of the more complex split-ring commutator required in DC generators.",
    "isCompetencyBased": true,
    "pyqYear": "2025",
    "pyqSet": "Delhi",
    "ncertRef": "NCERT Ch13 Exercise Q5"
  },
  {
    "id": "ME2-022",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Magnetic Field",
    "section": "B",
    "marks": 2,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Two parallel wires carrying currents in the same direction experience:",
    "options": [
      "Repulsive force",
      "Attractive force",
      "No force",
      "Force perpendicular to both wires"
    ],
    "answer": "Attractive force",
    "solutionSteps": [
      "Wire A carrying current I₁ creates magnetic field around wire B.",
      "By right-hand rule, field direction is determined.",
      "Current I₂ in wire B experiences force F = BI₂L in field of wire A.",
      "Same direction currents: field from A attracts current in B.",
      "Opposite currents: field repels."
    ],
    "finalAnswer": "Attractive force",
    "explanation": "Wire A carrying current I₁ creates magnetic field around wire B. By right-hand rule, field direction is determined. Current I₂ in wire B experiences force F = BI₂L in field of wire A. Same direction currents: field from A attracts current in B. Opposite currents: field repels. Therefore, the correct answer is Attractive force.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch13 InText"
  },
  {
    "id": "ME2-023",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Electromagnet",
    "section": "B",
    "marks": 2,
    "format": "Assertion-Reasoning",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "Assertion: A soft iron core is preferred over a steel core in electromagnets. Reason: Steel has higher retentivity than soft iron.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, but R is not the correct explanation of A.",
    "solutionSteps": [
      "Soft iron is preferred because it has LOW retentivity (demagnetizes easily).",
      "Steel has HIGH retentivity (retains magnetism).",
      "For electromagnet, we want it ON with current and OFF without current.",
      "So soft iron's low retentivity is the advantage, not disadvantage.",
      "Reason is true but explains why steel is NOT preferred."
    ],
    "finalAnswer": "Both A and R are true, but R is not the correct explanation of A.",
    "explanation": "Both statements are individually correct. However, the Reason does not directly cause or explain the Assertion — they are independent true facts about the same concept.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch13 Exercise"
  },
  {
    "id": "ME2-024",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Fleming Rules",
    "section": "C",
    "marks": 3,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Applying",
    "questionText": "A current-carrying conductor of length 50 cm is placed in a magnetic field of 2 T perpendicular to it. If the current is 5 A, calculate the force on the conductor and determine its direction using Fleming's rule.",
    "options": [],
    "answer": "F = 5 N; direction given by Fleming's left-hand rule",
    "solutionSteps": [
      "Given: L = 50 cm = 0.5 m, B = 2 T, I = 5 A, θ = 90°",
      "Formula: F = BIL sin θ",
      "F = 2 × 5 × 0.5 × sin(90°)",
      "F = 2 × 5 × 0.5 × 1 = 5 N",
      "Direction: Apply Fleming's left-hand rule.",
      "Point Index finger in direction of magnetic field (N to S).",
      "Point Middle finger in direction of current.",
      "Thumb points in direction of force."
    ],
    "finalAnswer": "The force on the conductor is calculated using the formula F = BIL sin θ, where B = 2 T (magnetic field), I = 5 A (current), L = 0.5 m (length of conductor, converted from 50 cm), and θ = 90° (since the conductor is perpendicular to the field). Substituting: F = 2 × 5 × 0.5 × sin 90° = 2 × 5 × 0.5 × 1 = 5 N. Therefore, the force acting on the conductor is 5 N. The direction of this force is determined using Fleming's left-hand rule: hold the left hand so that the index finger points in the direction of the magnetic field (B), the middle finger (at right angles to the index finger) points in the direction of conventional current (I), and the thumb then points in the direction of the force (thrust) on the conductor.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch13 Exercise"
  },
  {
    "id": "ME2-025",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "AC and DC",
    "section": "D",
    "marks": 5,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "Compare and contrast DC motor and AC generator in terms of: (a) Energy conversion, (b) Role of commutator/slip rings, (c) Output nature.",
    "options": [],
    "answer": "Detailed comparison showing opposite energy conversions, different connector types, and output characteristics",
    "solutionSteps": [
      "(a) Motor converts electrical energy to mechanical (rotation).",
      "    Generator converts mechanical energy to electrical (EMF).",
      "(b) Commutator in motor ensures unidirectional force for continuous rotation.",
      "    Slip rings in generator maintain connection without reversing current direction.",
      "(c) Motor operates on DC (unidirectional current required).",
      "    Generator produces AC (alternating EMF as coil rotates).",
      "(d) Both use rotating coil in magnetic field.",
      "    Both use same principle: F = BIL or EMF = NABω sin(ωt)"
    ],
    "finalAnswer": "(a) Energy conversion: A DC motor converts electrical energy into mechanical energy (rotation of the coil), whereas an AC generator converts mechanical energy into electrical energy by generating an induced EMF. (b) Role of commutator or slip rings: In a DC motor, a split-ring commutator reverses the current through the coil at every half rotation, ensuring that the torque always acts in the same rotational direction for continuous rotation. In an AC generator, slip rings maintain a continuous electrical connection with the rotating coil without reversing the current, so the output EMF alternates naturally as the coil rotates. (c) Output nature: A DC motor requires a unidirectional (direct) current as its input to produce continuous rotation in one direction, whereas an AC generator produces an alternating EMF as its output since the induced EMF varies sinusoidally as ε = NABω sin(ωt).",
    "isCompetencyBased": true,
    "pyqYear": "2024",
    "pyqSet": "Delhi",
    "ncertRef": "NCERT Ch13 InText & Exercise"
  },
  {
    "id": "ME2-027",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Magnetic Field",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "What happens to the magnetic field around a conductor when the current through it is increased?",
    "options": [
      "Field strength decreases",
      "Field strength increases",
      "Field direction reverses",
      "No change in field"
    ],
    "answer": "Field strength increases",
    "solutionSteps": [
      "Magnetic field strength is directly proportional to current",
      "Higher current → stronger magnetic field",
      "Lower current → weaker magnetic field"
    ],
    "finalAnswer": "Field strength increases",
    "explanation": "Magnetic field strength is directly proportional to current. Higher current → stronger magnetic field. Lower current → weaker magnetic field. Therefore, the correct answer is Field strength increases.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch13 InText"
  },
  {
    "id": "ME2-028",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Electromagnet",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "An electromagnet is a magnet in which the magnetic field is produced by:",
    "options": [
      "Permanent magnetization of iron",
      "Electric current flowing through a coil",
      "Heating of the coil",
      "Motion of the coil"
    ],
    "answer": "Electric current flowing through a coil",
    "solutionSteps": [
      "An electromagnet uses electric current to generate a magnetic field",
      "When current flows through a coil, it acts as a magnet",
      "The field disappears when current is switched off"
    ],
    "finalAnswer": "Electric current flowing through a coil",
    "explanation": "An electromagnet uses electric current to generate a magnetic field. When current flows through a coil, it acts as a magnet. The field disappears when current is switched off. Therefore, the correct answer is Electric current flowing through a coil.",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch13 Exercise Q2"
  },
  {
    "id": "ME2-029",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Electromagnet",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "The strength of an electromagnet can be increased by:",
    "options": [
      "Decreasing the number of coils",
      "Using an AC source instead of DC",
      "Increasing the current and using an iron core",
      "Reducing the diameter of the coil"
    ],
    "answer": "Increasing the current and using an iron core",
    "solutionSteps": [
      "More coils → stronger field",
      "Larger current → stronger field",
      "Iron core increases permeability → stronger field"
    ],
    "finalAnswer": "Increasing the current and using an iron core",
    "explanation": "More coils → stronger field. Larger current → stronger field. Iron core increases permeability → stronger field. Therefore, the correct answer is Increasing the current and using an iron core.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch13 InText"
  },
  {
    "id": "ME2-030",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Fleming Rules",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Fleming's Left Hand Rule is used to determine:",
    "options": [
      "Direction of induced current",
      "Direction of force on a current-carrying conductor in a magnetic field",
      "Strength of the magnetic field",
      "Magnitude of induced EMF"
    ],
    "answer": "Direction of force on a current-carrying conductor in a magnetic field",
    "solutionSteps": [
      "Fleming's Left Hand Rule: Thumb=Force, Index=Field, Middle=Current",
      "Used for motors (force determination)",
      "Fleming's Right Hand Rule is for generators (induced current)"
    ],
    "finalAnswer": "Direction of force on a current-carrying conductor in a magnetic field",
    "explanation": "Fleming's Left Hand Rule: Thumb=Force, Index=Field, Middle=Current. Used for motors (force determination). Fleming's Right Hand Rule is for generators (induced current). Therefore, the correct answer is Direction of force on a current-carrying conductor in a magnetic field.",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch13 InText Q5"
  },
  {
    "id": "ME2-031",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Fleming Rules",
    "section": "B",
    "marks": 2,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Analysing",
    "questionText": "Assertion (A): Fleming's Right Hand Rule is used in electric generators. Reason (R): The right hand rule determines the direction of induced current when a conductor moves through a magnetic field.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "Fleming's Right Hand Rule: Thumb=motion, Index=field, Middle=current",
      "It determines induced current direction in generators",
      "R correctly explains why A is true"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "explanation": "Both the Assertion and the Reason are correct statements. The Reason directly explains the scientific/mathematical basis that makes the Assertion true, so R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch13 InText"
  },
  {
    "id": "ME2-032",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Electric Motor",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "An electric motor converts:",
    "options": [
      "Mechanical energy to electrical energy",
      "Electrical energy to mechanical energy",
      "Heat energy to mechanical energy",
      "Chemical energy to electrical energy"
    ],
    "answer": "Electrical energy to mechanical energy",
    "solutionSteps": [
      "Motor: Electrical input → Mechanical output (rotation)",
      "Uses magnetic force on current-carrying conductor",
      "Based on Fleming's Left Hand Rule"
    ],
    "finalAnswer": "Electrical energy to mechanical energy",
    "explanation": "Motor: Electrical input → Mechanical output (rotation). Uses magnetic force on current-carrying conductor. Based on Fleming's Left Hand Rule. Therefore, the correct answer is Electrical energy to mechanical energy.",
    "isCompetencyBased": false,
    "pyqYear": "2021",
    "pyqSet": "Delhi",
    "ncertRef": "NCERT Ch13 Exercise Q1"
  },
  {
    "id": "ME2-033",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Electric Motor",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Why is a split ring commutator essential in a DC motor? Explain its function.",
    "options": [],
    "answer": "A split ring commutator reverses the direction of current in the coil after every half rotation, ensuring that the force on the coil always acts in the same direction relative to motion, enabling continuous rotation.",
    "solutionSteps": [
      "Commutator is a split ring connected to coil ends",
      "It reverses current direction every half rotation",
      "This ensures the magnetic force continues in same direction",
      "Results in continuous rotation of the motor"
    ],
    "finalAnswer": "A split ring commutator reverses the direction of current in the coil after every half rotation, ensuring that the force on the coil always acts in the same direction relative to motion, enabling continuous rotation.",
    "isCompetencyBased": true,
    "pyqYear": "2022",
    "pyqSet": "All India",
    "ncertRef": "NCERT Ch13 InText Q6"
  },
  {
    "id": "ME2-034",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Electric Motor",
    "section": "B",
    "marks": 2,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "In an electric motor, the coil rotates continuously because:",
    "options": [
      "The magnetic field is constantly increasing",
      "The commutator reverses the current direction regularly",
      "The coil has decreasing resistance",
      "The magnetic poles are moving"
    ],
    "answer": "The commutator reverses the current direction regularly",
    "solutionSteps": [
      "Commutator switches current direction every half rotation",
      "This keeps the force direction consistent",
      "Results in continuous rotation in one direction"
    ],
    "finalAnswer": "The commutator reverses the current direction regularly",
    "explanation": "Commutator switches current direction every half rotation. This keeps the force direction consistent. Results in continuous rotation in one direction. Therefore, the correct answer is The commutator reverses the current direction regularly.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch13 Exercise Q4"
  },
  {
    "id": "ME2-035",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Electromagnetic Induction",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "Electromagnetic induction is the process of generating:",
    "options": [
      "Magnetic field from heat",
      "Electric current from a changing magnetic field",
      "Permanent magnets from coils",
      "Magnetic field from mechanical motion"
    ],
    "answer": "Electric current from a changing magnetic field",
    "solutionSteps": [
      "Induction: Change in magnetic flux → induced EMF/current",
      "Discovered by Michael Faraday",
      "Principle behind generators and transformers"
    ],
    "finalAnswer": "Electric current from a changing magnetic field",
    "explanation": "Induction: Change in magnetic flux → induced EMF/current. Discovered by Michael Faraday. Principle behind generators and transformers. Therefore, the correct answer is Electric current from a changing magnetic field.",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch13 InText Q8"
  },
  {
    "id": "ME2-036",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Electromagnetic Induction",
    "section": "B",
    "marks": 2,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "When a magnet is moved quickly into a coil, the induced current will be:",
    "options": [
      "Zero",
      "Stronger than when moved slowly",
      "In the same direction as magnet motion",
      "Constant throughout the motion"
    ],
    "answer": "Stronger than when moved slowly",
    "solutionSteps": [
      "Faraday's Law: Induced EMF ∝ rate of change of flux",
      "Faster motion → larger rate of change → stronger current",
      "Slower motion → weaker current"
    ],
    "finalAnswer": "Stronger than when moved slowly",
    "explanation": "Faraday's Law: Induced EMF ∝ rate of change of flux. Faster motion → larger rate of change → stronger current. Slower motion → weaker current. Therefore, the correct answer is Stronger than when moved slowly.",
    "isCompetencyBased": true,
    "pyqYear": "2020",
    "pyqSet": "Delhi",
    "ncertRef": "NCERT Ch13 InText"
  },
  {
    "id": "ME2-037",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Electromagnetic Induction",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "State Faraday's Law of Electromagnetic Induction.",
    "options": [],
    "answer": "The induced EMF in a closed coil is directly proportional to the rate of change of magnetic flux through the coil. Mathematically: ε = -N(dΦ/dt), where dΦ/dt is the rate of change of flux and N is the number of turns.",
    "solutionSteps": [
      "The induced EMF in a coil is directly proportional to the rate of change of magnetic flux",
      "EMF = -N × dΦ/dt (N = number of turns)",
      "The negative sign indicates direction (Lenz's Law)"
    ],
    "finalAnswer": "The induced EMF in a closed coil is directly proportional to the rate of change of magnetic flux through the coil. Mathematically: ε = -N(dΦ/dt), where dΦ/dt is the rate of change of flux and N is the number of turns.",
    "isCompetencyBased": false,
    "pyqYear": "2019",
    "pyqSet": "All India",
    "ncertRef": "NCERT Ch13 Exercise Q5"
  },
  {
    "id": "ME2-038",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Electromagnetic Induction",
    "section": "B",
    "marks": 2,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Analysing",
    "questionText": "Assertion (A): Lenz's Law states that induced current opposes the change causing it. Reason (R): This is why the negative sign appears in Faraday's law equation.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "Lenz's Law: Induced effects oppose the cause",
      "The negative sign in ε = -N(dΦ/dt) represents this opposition",
      "R correctly explains A"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "explanation": "Both the Assertion and the Reason are correct statements. The Reason directly explains the scientific/mathematical basis that makes the Assertion true, so R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch13 InText Q9"
  },
  {
    "id": "ME2-039",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "AC and DC",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "The main difference between AC and DC current is:",
    "options": [
      "AC is stronger than DC",
      "AC changes direction periodically while DC flows in one direction",
      "DC can be transmitted over long distances",
      "AC is generated in batteries"
    ],
    "answer": "AC changes direction periodically while DC flows in one direction",
    "solutionSteps": [
      "DC (Direct Current): Flows in one direction, from battery",
      "AC (Alternating Current): Changes direction periodically, from generator",
      "AC frequency is typically 50 Hz or 60 Hz"
    ],
    "finalAnswer": "AC changes direction periodically while DC flows in one direction",
    "explanation": "DC (Direct Current): Flows in one direction, from battery. AC (Alternating Current): Changes direction periodically, from generator. AC frequency is typically 50 Hz or 60 Hz. Therefore, the correct answer is AC changes direction periodically while DC flows in one direction.",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch13 InText Q11"
  },
  {
    "id": "ME2-040",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "AC and DC",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "AC generators produce current by rotating a coil in a magnetic field, which causes:",
    "options": [
      "Constant increase in magnetic flux",
      "Periodic change in magnetic flux through the coil",
      "Unidirectional current to flow",
      "No change in flux direction"
    ],
    "answer": "Periodic change in magnetic flux through the coil",
    "solutionSteps": [
      "Rotating coil → flux through it changes periodically",
      "Flux alternates from maximum in one direction to maximum opposite",
      "Induces alternating EMF and current"
    ],
    "finalAnswer": "Periodic change in magnetic flux through the coil",
    "explanation": "Rotating coil → flux through it changes periodically. Flux alternates from maximum in one direction to maximum opposite. Induces alternating EMF and current. Therefore, the correct answer is Periodic change in magnetic flux through the coil.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch13 Exercise Q6"
  },
  {
    "id": "ME2-041",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "AC and DC",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Why is AC preferred over DC for power transmission over long distances?",
    "options": [],
    "answer": "AC is preferred because it can be easily stepped up to high voltage for transmission (reducing losses) and then stepped down at the destination using simple and efficient transformers. DC cannot be easily transformed and would require expensive and complex conversion equipment.",
    "solutionSteps": [
      "AC voltage can be increased using step-up transformers",
      "Higher voltage → lower current → reduced power loss (I²R)",
      "At destination, voltage stepped down to usable levels",
      "DC cannot use transformers, requires expensive DC-DC converters"
    ],
    "finalAnswer": "AC is preferred because it can be easily stepped up to high voltage for transmission (reducing losses) and then stepped down at the destination using simple and efficient transformers. DC cannot be easily transformed and would require expensive and complex conversion equipment.",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": "All India",
    "ncertRef": "NCERT Ch13 Exercise Q7"
  },
  {
    "id": "ME2-042",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Magnetic Field",
    "section": "B",
    "marks": 2,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Two parallel wires carrying currents in the same direction will:",
    "options": [
      "Repel each other",
      "Attract each other",
      "Have no force between them",
      "Create a uniform magnetic field"
    ],
    "answer": "Attract each other",
    "solutionSteps": [
      "Magnetic field from wire 1 passes through wire 2",
      "Using Fleming's Left Hand Rule on wire 2",
      "Current in same direction → fields aid each other → attraction",
      "Current in opposite directions would repel"
    ],
    "finalAnswer": "Attract each other",
    "explanation": "Magnetic field from wire 1 passes through wire 2. Using Fleming's Left Hand Rule on wire 2. Current in same direction → fields aid each other → attraction. Current in opposite directions would repel. Therefore, the correct answer is Attract each other.",
    "isCompetencyBased": true,
    "pyqYear": "2024",
    "pyqSet": "Delhi",
    "ncertRef": "NCERT Ch13 InText Q3"
  },
  {
    "id": "ME2-043",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Electromagnet",
    "section": "E",
    "marks": 4,
    "format": "Case-Based",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "A student designed an electromagnet using a soft iron core, insulated copper wire wound in 500 turns, connected to a 12V DC source with 2A current. Later, she wanted to lift heavier objects, so she made the following changes:\n(i) Increased the number of turns to 1000\n(ii) Used thicker wire to reduce resistance\n(iii) Increased voltage to 24V\n(iv) Added an air gap in the core\n\nBased on electromagnet principles:\n(a) Which changes would increase the strength of electromagnet?\n(b) Which change would be counterproductive and why?\n(c) If the current is kept at 2A, which change (ii or iii) is better for electromagnet strength?",
    "options": [],
    "answer": "(a) Changes (i), (ii), and (iii) increase electromagnet strength because: (i) more turns increase coil ampere-turns, (ii) reduced resistance allows higher current, (iii) higher voltage drives more current. (b) Change (iv) is counterproductive as air gap introduces reluctance and breaks the magnetic circuit, significantly weakening the field. (c) Change (iii) is better because increased voltage with thicker wire allows greater current, directly increasing electromagnetic force; Change (ii) alone doesn't help if current remains 2A.",
    "solutionSteps": [
      "(a) Change (i): More turns → stronger field; Change (ii): Thicker wire reduces resistance, allows more current → stronger field; Change (iii): Higher voltage increases current → stronger field",
      "(b) Change (iv) is counterproductive because air gap increases reluctance and weakens the magnetic field due to air's low permeability compared to iron",
      "(c) If current stays at 2A: Change (ii) doesn't help field strength (no current change), but Change (iii) enables higher current through thicker wire → stronger field"
    ],
    "finalAnswer": "(a) Changes (i), (ii), and (iii) all increase the strength of the electromagnet: increasing the number of turns to 1000 doubles the coil's ampere-turns, which directly increases the magnetic field strength; using thicker wire reduces the circuit resistance, allowing more current to flow and increasing the ampere-turns; increasing the voltage to 24V drives a greater current through the coil, which also increases the magnetic field. (b) Change (iv) — adding an air gap to the core — is counterproductive because air has a very low magnetic permeability compared to soft iron; introducing an air gap creates a region of high magnetic reluctance that reduces the overall magnetic flux through the core, significantly weakening the electromagnet's field strength. (c) If the current is kept constant at 2 A, change (ii) (using thicker wire) does not increase the electromagnet's strength because the field strength depends on the current, not on the wire resistance alone; change (iii) (increasing the voltage) is the better choice because, with thicker wire already reducing resistance, the higher voltage will drive more current through the coil, directly increasing the magnetic force.",
    "isCompetencyBased": true,
    "pyqYear": "2024",
    "pyqSet": "CBSE",
    "ncertRef": "NCERT Ch13 InText Q4"
  },
  {
    "id": "ME2-044",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Electric Motor",
    "section": "D",
    "marks": 5,
    "format": "Long",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Explain the working principle of a DC electric motor with the help of a labeled diagram. Include the roles of magnetic field, current-carrying coil, commutator, and brushes in continuous rotation.",
    "options": [],
    "answer": "A DC motor works by applying a current through a coil in a magnetic field. The current-carrying sides of the coil experience forces (according to Fleming's Left Hand Rule) that create a torque, rotating the coil. The split-ring commutator automatically reverses the current direction every half-rotation, ensuring the magnetic force continues to act in the direction of motion, resulting in continuous rotation. The brushes maintain electrical contact with the commutator throughout this process.",
    "solutionSteps": [
      "A rectangular coil is placed between two magnetic poles (N and S)",
      "When current flows through the coil (via brushes and commutator), each side experiences a force (Fleming's Left Hand Rule)",
      "Force on side AB (towards N pole): upward; Force on side CD (towards S pole): downward",
      "This creates a torque, rotating the coil",
      "As coil rotates 180°, commutator segments switch the brush contacts",
      "Current direction reverses, so force direction reverses relative to coil's new position",
      "This ensures force always acts in the direction of motion → continuous rotation",
      "Role of brushes: conduct current to commutator",
      "Role of commutator: maintains force direction by reversing current every half rotation"
    ],
    "finalAnswer": "A DC motor works by applying a current through a coil in a magnetic field. The current-carrying sides of the coil experience forces (according to Fleming's Left Hand Rule) that create a torque, rotating the coil. The split-ring commutator automatically reverses the current direction every half-rotation, ensuring the magnetic force continues to act in the direction of motion, resulting in continuous rotation. The brushes maintain electrical contact with the commutator throughout this process.",
    "isCompetencyBased": true,
    "pyqYear": "2022",
    "pyqSet": "All India",
    "ncertRef": "NCERT Ch13 Exercise Q3"
  },
  {
    "id": "ME2-045",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Electromagnetic Induction",
    "section": "D",
    "marks": 5,
    "format": "Long",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "A generator consists of a rectangular coil ABCD rotating in a uniform magnetic field. Explain how AC is generated in this rotating coil generator with reference to Faraday's Law and Lenz's Law. Why is the current alternating?",
    "options": [],
    "answer": "In a rotating generator, as the coil rotates, the magnetic flux through it changes continuously and periodically. According to Faraday's Law, this changing flux induces an EMF: ε = -N(dΦ/dt). The EMF alternates because the rate of flux change (dΦ/dt) changes sign after every 180° rotation. When the coil plane is perpendicular to the field, dΦ/dt is maximum (EMF is maximum); when parallel, dΦ/dt is zero (EMF is zero). Lenz's Law explains that the induced current creates a magnetic field opposing the flux change. This results in an alternating EMF and current with frequency equal to the rotation frequency.",
    "solutionSteps": [
      "As coil rotates, magnetic flux through it changes periodically",
      "When coil plane is perpendicular to field → maximum flux → zero EMF",
      "When coil plane is parallel to field → zero flux → maximum EMF",
      "According to Faraday's Law: ε = -N(dΦ/dt)",
      "The EMF is zero when flux is maximum (dΦ/dt = 0)",
      "The EMF is maximum when flux changes fastest (maximum |dΦ/dt|)",
      "After 180° rotation, flux direction reverses → EMF polarity reverses",
      "This alternating EMF drives alternating current through the circuit",
      "Lenz's Law ensures induced current opposes flux changes, confirming energy conservation",
      "Frequency = rotation frequency (e.g., 50 Hz for 50 rotations/sec)"
    ],
    "finalAnswer": "In a rotating generator, as the coil rotates, the magnetic flux through it changes continuously and periodically. According to Faraday's Law, this changing flux induces an EMF: ε = -N(dΦ/dt). The EMF alternates because the rate of flux change (dΦ/dt) changes sign after every 180° rotation. When the coil plane is perpendicular to the field, dΦ/dt is maximum (EMF is maximum); when parallel, dΦ/dt is zero (EMF is zero). Lenz's Law explains that the induced current creates a magnetic field opposing the flux change. This results in an alternating EMF and current with frequency equal to the rotation frequency.",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": "Delhi",
    "ncertRef": "NCERT Ch13 Exercise Q8"
  },
  {
    "id": "ME2-046",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Fleming Rules",
    "section": "B",
    "marks": 2,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Applying",
    "questionText": "A current-carrying conductor in a magnetic field experiences maximum force when the conductor is:",
    "options": [
      "Parallel to the magnetic field",
      "Perpendicular to the magnetic field",
      "At 45° to the magnetic field",
      "At any angle to the field"
    ],
    "answer": "Perpendicular to the magnetic field",
    "solutionSteps": [
      "Force F = BIL sin(θ) where θ is angle between conductor and field",
      "Force is maximum when sin(θ) = 1, i.e., θ = 90°",
      "This means conductor is perpendicular to the field"
    ],
    "finalAnswer": "Perpendicular to the magnetic field",
    "explanation": "Force F = BIL sin(θ) where θ is angle between conductor and field. Force is maximum when sin(θ) = 1, i.e., θ = 90°. This means conductor is perpendicular to the field. Therefore, the correct answer is Perpendicular to the magnetic field.",
    "isCompetencyBased": true,
    "pyqYear": "2025",
    "pyqSet": "All India",
    "ncertRef": "NCERT Ch13 InText Q7"
  },
  {
    "id": "ME2-047",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Magnetic Field",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Why does the magnetic field strength decrease with distance from a current-carrying conductor? Explain using the concept of field lines.",
    "options": [],
    "answer": "The magnetic field strength decreases with distance because the magnetic field lines spread out. The field lines form concentric circles around the conductor, and as the radius increases, the same number of field lines is distributed over a larger circumference. This reduces the density of field lines, indicating weaker field strength at greater distances. The relationship is inverse: B ∝ 1/r.",
    "solutionSteps": [
      "Magnetic field lines form concentric circles around a straight conductor",
      "The density of field lines (number per unit area) represents field strength",
      "As distance increases, these circles become larger",
      "The same number of field lines spread over a larger circumference",
      "Therefore, field line density decreases → field strength decreases",
      "Mathematically: B ∝ 1/r (inversely proportional to distance)"
    ],
    "finalAnswer": "The magnetic field strength decreases with distance because the magnetic field lines spread out. The field lines form concentric circles around the conductor, and as the radius increases, the same number of field lines is distributed over a larger circumference. This reduces the density of field lines, indicating weaker field strength at greater distances. The relationship is inverse: B ∝ 1/r.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch13 InText Q2"
  },
  {
    "id": "ME2-048",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "AC and DC",
    "section": "B",
    "marks": 2,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Assertion (A): DC current flows in a constant direction and has constant magnitude. Reason (R): DC is generated by a battery where one terminal is always positive and other is always negative.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "DC has constant direction (unidirectional) and constant magnitude",
      "Battery's fixed polarity ensures electrons always flow from negative to positive terminal",
      "This explains why DC is constant"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "explanation": "Both the Assertion and the Reason are correct statements. The Reason directly explains the scientific/mathematical basis that makes the Assertion true, so R is the correct explanation of A.",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch13 InText Q12"
  },
  {
    "id": "ME2-049",
    "subject": "Science",
    "topicKey": "Magnetic Effects of Electric Current",
    "subtopic": "Electromagnet",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A coil with 200 turns carrying 1A current acts as an electromagnet. How would doubling the current to 2A affect its magnetic strength? Justify your answer.",
    "options": [],
    "answer": "Doubling the current to 2A would double the magnetic strength of the electromagnet. This is because the magnetic field strength is directly proportional to the current flowing through it (B ∝ NI). Since N remains constant at 200 turns, and I doubles, the field strength also doubles.",
    "solutionSteps": [
      "Magnetic field strength B is directly proportional to current I",
      "B ∝ N × I (where N is number of turns)",
      "Original: B₁ ∝ 200 × 1 = 200",
      "New: B₂ ∝ 200 × 2 = 400",
      "B₂ = 2 × B₁",
      "Therefore, doubling current doubles the magnetic strength"
    ],
    "finalAnswer": "Doubling the current to 2A would double the magnetic strength of the electromagnet. This is because the magnetic field strength is directly proportional to the current flowing through it (B ∝ NI). Since N remains constant at 200 turns, and I doubles, the field strength also doubles.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch13 Exercise Q2"
  }
];
