import type { CanonicalQuestion } from "../../types";

export const OE2_PACK2: CanonicalQuestion[] = [
  {
    "id": "OE2-001",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Ecosystem Components",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "Which of the following is a biotic component of an ecosystem?",
    "options": [
      "Soil",
      "Water",
      "Plants",
      "Sunlight"
    ],
    "answer": "Plants",
    "solutionSteps": [
      "Biotic components are living organisms in an ecosystem",
      "Plants are living organisms",
      "Therefore, plants are biotic components"
    ],
    "finalAnswer": "Plants",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 InText"
  },
  {
    "id": "OE2-002",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Ecosystem Components",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "Decomposers in an ecosystem include:",
    "options": [
      "Plants and animals",
      "Bacteria and fungi",
      "Herbivores and carnivores",
      "Producers and consumers"
    ],
    "answer": "Bacteria and fungi",
    "solutionSteps": [
      "Decomposers break down dead organic matter",
      "Bacteria and fungi are the main decomposers",
      "They convert dead matter into nutrients"
    ],
    "finalAnswer": "Bacteria and fungi",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 Exercise"
  },
  {
    "id": "OE2-003",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Ecosystem Components",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "Primary consumers are also known as:",
    "options": [
      "Producers",
      "Herbivores",
      "Carnivores",
      "Omnivores"
    ],
    "answer": "Herbivores",
    "solutionSteps": [
      "Primary consumers feed on plants/producers",
      "Animals that feed on plants are herbivores",
      "Therefore, primary consumers = herbivores"
    ],
    "finalAnswer": "Herbivores",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 InText"
  },
  {
    "id": "OE2-004",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Food Chains and Webs",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "In a food chain, the maximum energy is available at the level of:",
    "options": [
      "Secondary consumers",
      "Primary consumers",
      "Producers",
      "Decomposers"
    ],
    "answer": "Producers",
    "solutionSteps": [
      "Producers capture solar energy through photosynthesis",
      "They have the maximum energy in the ecosystem",
      "Energy decreases at each trophic level"
    ],
    "finalAnswer": "Producers",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 Exercise"
  },
  {
    "id": "OE2-005",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Food Chains and Webs",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "If a pesticide is sprayed on crops, which organism in the food chain will have the maximum accumulation of pesticide?",
    "options": [
      "Herbivores",
      "Plants",
      "Primary carnivores",
      "Top carnivores"
    ],
    "answer": "Top carnivores",
    "solutionSteps": [
      "Pesticides undergo bioaccumulation through the food chain",
      "Each trophic level concentrates more pesticide",
      "Top predators have maximum accumulation (biomagnification)"
    ],
    "finalAnswer": "Top carnivores",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 InText"
  },
  {
    "id": "OE2-006",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Food Chains and Webs",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Analysing",
    "questionText": "Why are food webs more stable than food chains in an ecosystem?",
    "options": [
      "Food webs have more organisms",
      "Food webs provide alternative pathways for energy flow",
      "Food webs prevent decomposition",
      "Food webs eliminate all predators"
    ],
    "answer": "Food webs provide alternative pathways for energy flow",
    "solutionSteps": [
      "In a food web, organisms have multiple food sources",
      "If one food source is unavailable, alternatives exist",
      "This makes the ecosystem more stable and resilient"
    ],
    "finalAnswer": "Food webs provide alternative pathways for energy flow",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 Exercise"
  },
  {
    "id": "OE2-007",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Ozone Depletion",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Which gas is primarily responsible for ozone layer depletion?",
    "options": [
      "Carbon dioxide",
      "Chlorofluorocarbons (CFCs)",
      "Nitrogen dioxide",
      "Sulfur dioxide"
    ],
    "answer": "Chlorofluorocarbons (CFCs)",
    "solutionSteps": [
      "CFCs release chlorine atoms in the stratosphere",
      "Chlorine catalytically destroys ozone molecules",
      "One chlorine atom can destroy many ozone molecules"
    ],
    "finalAnswer": "Chlorofluorocarbons (CFCs)",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 InText"
  },
  {
    "id": "OE2-008",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Ozone Depletion",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Which of the following was a major source of CFCs in the past?",
    "options": [
      "Natural volcanic emissions",
      "Vehicle exhaust",
      "Refrigerators and air conditioners",
      "Industrial fertilizers"
    ],
    "answer": "Refrigerators and air conditioners",
    "solutionSteps": [
      "CFCs were used as refrigerants in cooling appliances",
      "They were considered safe because they were non-flammable",
      "They were released during leaks and disposal"
    ],
    "finalAnswer": "Refrigerators and air conditioners",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 Exercise"
  },
  {
    "id": "OE2-009",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Ozone Depletion",
    "section": "C",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "The 'Ozone Hole' over Antarctica is largest during:",
    "options": [
      "Summer in the Northern Hemisphere",
      "Winter in the Southern Hemisphere",
      "Spring in the Northern Hemisphere",
      "Autumn in the Southern Hemisphere"
    ],
    "answer": "Spring in the Southern Hemisphere",
    "solutionSteps": [
      "Antarctic winter creates polar stratospheric clouds",
      "Spring temperatures cause ozone destruction reactions",
      "The 'hole' reaches maximum in Antarctic spring (Sept-Oct)"
    ],
    "finalAnswer": "Spring in the Southern Hemisphere",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 InText"
  },
  {
    "id": "OE2-010",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Biodegradable and Non-biodegradable",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "Which of the following is biodegradable?",
    "options": [
      "Plastic bags",
      "Glass bottles",
      "Paper and cardboard",
      "Aluminum cans"
    ],
    "answer": "Paper and cardboard",
    "solutionSteps": [
      "Biodegradable materials can be broken down by microorganisms",
      "Paper and cardboard are plant-based materials",
      "Decomposers can easily break them down"
    ],
    "finalAnswer": "Paper and cardboard",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 Exercise"
  },
  {
    "id": "OE2-011",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Biodegradable and Non-biodegradable",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "Non-biodegradable wastes accumulate in the environment because:",
    "options": [
      "They are produced in small quantities",
      "Decomposers cannot break them down",
      "They are buried deep underground",
      "Microorganisms prefer other materials"
    ],
    "answer": "Decomposers cannot break them down",
    "solutionSteps": [
      "Non-biodegradable materials resist microbial decomposition",
      "Their chemical structure is not recognized by decomposers",
      "They persist in the environment for long periods"
    ],
    "finalAnswer": "Decomposers cannot break them down",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 InText"
  },
  {
    "id": "OE2-012",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Biodegradable and Non-biodegradable",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Which practice is most effective for managing non-biodegradable waste?",
    "options": [
      "Burning it in open fields",
      "Dumping in water bodies",
      "Recycling and reuse",
      "Burying in landfills"
    ],
    "answer": "Recycling and reuse",
    "solutionSteps": [
      "Non-biodegradable waste cannot be decomposed naturally",
      "Burning causes air pollution",
      "Recycling prevents accumulation and conserves resources"
    ],
    "finalAnswer": "Recycling and reuse",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 Exercise"
  },
  {
    "id": "OE2-013",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Ecosystem Components",
    "section": "B",
    "marks": 1,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Distinguish between producers and consumers in an ecosystem.",
    "options": [],
    "answer": "Producers manufacture their own food through photosynthesis; consumers feed on other organisms for energy",
    "solutionSteps": [
      "Producers: Green plants that convert solar energy into chemical energy",
      "Consumers: Animals that feed on producers or other consumers for energy",
      "Examples of producers: grasses, trees; consumers: herbivores, carnivores"
    ],
    "finalAnswer": "Producers manufacture their own food through photosynthesis; consumers feed on other organisms for energy",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 InText"
  },
  {
    "id": "OE2-014",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Food Chains and Webs",
    "section": "B",
    "marks": 1,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Why does the number of organisms decrease at each trophic level in a food chain?",
    "options": [],
    "answer": "Because 90% of energy is lost as heat at each trophic level; only 10% is available for the next level",
    "solutionSteps": [
      "Energy transfer between trophic levels is 10% efficient",
      "90% of energy is lost through respiration, movement, and heat",
      "This results in exponentially fewer organisms at higher levels"
    ],
    "finalAnswer": "Because 90% of energy is lost as heat at each trophic level; only 10% is available for the next level",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 Exercise"
  },
  {
    "id": "OE2-015",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Ozone Depletion",
    "section": "B",
    "marks": 1,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "What is the Montreal Protocol and why was it important?",
    "options": [],
    "answer": "An international agreement signed in 1987 to phase out ozone-depleting substances like CFCs to prevent further ozone layer depletion",
    "solutionSteps": [
      "Montreal Protocol was a global environmental agreement",
      "Countries agreed to reduce and eliminate CFC production",
      "It has been successful in reducing ozone depletion"
    ],
    "finalAnswer": "An international agreement signed in 1987 to phase out ozone-depleting substances like CFCs to prevent further ozone layer depletion",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 InText"
  },
  {
    "id": "OE2-016",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Biodegradable and Non-biodegradable",
    "section": "B",
    "marks": 1,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "List three biodegradable and three non-biodegradable materials used in daily life.",
    "options": [],
    "answer": "Biodegradable: food waste, paper, cloth; Non-biodegradable: plastic, glass, metal",
    "solutionSteps": [
      "Biodegradable materials decompose naturally over time",
      "Non-biodegradable materials persist in the environment",
      "Proper waste management is needed for non-biodegradable waste"
    ],
    "finalAnswer": "Biodegradable: food waste, paper, cloth; Non-biodegradable: plastic, glass, metal",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 Exercise"
  },
  {
    "id": "OE2-017",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Ecosystem Components",
    "section": "B",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Analysing",
    "questionText": "Assertion: All green plants are producers in an ecosystem. Reason: Green plants manufacture their own food through photosynthesis.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "Green plants are producers",
      "Producers manufacture food through photosynthesis",
      "This is the definition of why plants are producers"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 InText"
  },
  {
    "id": "OE2-018",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Ozone Depletion",
    "section": "C",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Assertion: The ozone layer prevents ultraviolet radiation from reaching Earth's surface. Reason: UV radiation can damage DNA and cause skin cancer in humans.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, but R is not the correct explanation of A.",
    "solutionSteps": [
      "The ozone layer does filter UV radiation - A is true",
      "UV radiation does damage DNA and cause cancer - R is true",
      "But R explains why ozone layer is important, not why it filters UV",
      "These are related but R doesn't explain A's mechanism"
    ],
    "finalAnswer": "Both A and R are true, but R is not the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 Exercise"
  },
  {
    "id": "OE2-019",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Food Chains and Webs",
    "section": "C",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "Assertion: Biomagnification of pesticides is more severe in aquatic ecosystems than terrestrial ecosystems. Reason: Aquatic organisms have longer lifespans than terrestrial organisms.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, but R is not the correct explanation of A.",
    "solutionSteps": [
      "Biomagnification is indeed worse in aquatic ecosystems - A is true",
      "This is because water dissolves and concentrates pesticides differently",
      "R is partially true but lifespan alone doesn't explain the difference",
      "The reason relates to aquatic chemistry and food web dynamics"
    ],
    "finalAnswer": "Both A and R are true, but R is not the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 InText"
  },
  {
    "id": "OE2-020",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Ecosystem Components",
    "section": "D",
    "marks": 4,
    "format": "Case-Based",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A forest ecosystem contains oak trees, deer that feed on grass and leaves, wolves that hunt deer, and bacteria in the soil. (a) Identify the producer and primary consumer. (b) What role do bacteria play in this ecosystem? (c) If a disease kills most deer, how would it affect the wolf population? (d) Explain why this forest needs both biotic and abiotic components to function.",
    "options": [],
    "answer": "(a) Producer: oak trees; Primary consumer: deer (b) Bacteria act as decomposers, breaking down dead matter and recycling nutrients (c) Wolf population would decrease due to lack of food (d) Abiotic components (sunlight, water, soil) provide energy and nutrients; biotic components form food chains and cycles",
    "solutionSteps": [
      "Identify trophic levels in the given ecosystem",
      "Producers capture solar energy; consumers eat other organisms",
      "Decomposers break down dead material",
      "Ecosystems are interdependent systems requiring both biotic and abiotic factors"
    ],
    "finalAnswer": "(a) Producer: oak trees; Primary consumer: deer (b) Bacteria act as decomposers, breaking down dead matter and recycling nutrients (c) Wolf population would decrease due to lack of food (d) Abiotic components provide energy and nutrients; biotic components form food chains and nutrient cycles",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 Exercise"
  },
  {
    "id": "OE2-021",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Biodegradable and Non-biodegradable",
    "section": "D",
    "marks": 4,
    "format": "Case-Based",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "A city generates 500 tonnes of waste daily. 40% is biodegradable (food, paper), 60% is non-biodegradable (plastic, metal, glass). The city currently dumps all waste in a landfill. (a) What problems arise from this practice? (b) How long will biodegradable and non-biodegradable waste persist in the landfill? (c) Propose an alternative waste management strategy. (d) How can individuals contribute to reducing non-biodegradable waste?",
    "options": [],
    "answer": "(a) Leachate contamination, methane emissions, soil degradation, space depletion (b) Biodegradable: months to years; Non-biodegradable: decades to centuries (c) Segregation at source, composting biodegradable waste, recycling non-biodegradable materials (d) Reduce consumption, reuse products, recycle materials, choose biodegradable alternatives",
    "solutionSteps": [
      "Analyze environmental impacts of landfills",
      "Differentiate decomposition rates of waste types",
      "Propose sustainable waste management solutions",
      "Connect individual actions to ecosystem health"
    ],
    "finalAnswer": "(a) Leachate contamination, methane emissions, soil degradation, landfill space depletion (b) Biodegradable: few months to 2 years; Non-biodegradable: 50-1000+ years (c) Waste segregation, composting, recycling programs, incineration with energy recovery (d) Reduce single-use products, reuse containers, participate in recycling, buy sustainable products",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 InText"
  },
  {
    "id": "OE2-022",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Food Chains and Webs",
    "section": "E",
    "marks": 5,
    "format": "Long",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "Draw and explain a food web containing at least 6 organisms from a pond ecosystem. Include producers, primary consumers, secondary consumers, and decomposers. Explain: (a) How energy flows through the web; (b) The concept of biomagnification using a specific pesticide example; (c) Why certain organisms are more affected by pesticide accumulation; (d) How the removal of one organism would affect the entire food web.",
    "options": [],
    "answer": "Food web diagram with pond plants, herbivorous insects, small fish, large fish, herons, and bacteria. Energy flows from sun to producers to consumers. Pesticides accumulate at higher trophic levels due to 10% energy rule. Top predators have highest concentration. Removal of any organism disrupts energy flow and creates imbalance.",
    "solutionSteps": [
      "Construct pond ecosystem food web with correct trophic relationships",
      "Explain photosynthesis as primary energy source",
      "Describe energy loss at each trophic level (10% rule)",
      "Detail biomagnification mechanism (pesticide concentration increases upward)",
      "Explain why top predators accumulate most toxins",
      "Analyze food web interdependence and cascade effects"
    ],
    "finalAnswer": "Complete food web showing energy flow from sun→plants→herbivores→carnivores→decomposers. Biomagnification: pesticide concentration increases 10-100x at each level due to feeding and retention. Top predators most affected due to position in chain. Removing any organism reduces food sources for others, causing population changes throughout ecosystem.",
    "isCompetencyBased": true,
    "pyqYear": "2022",
    "pyqSet": "Set A",
    "ncertRef": "NCERT Ch15 Exercise"
  },
  {
    "id": "OE2-023",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Ozone Depletion",
    "section": "C",
    "marks": 2,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "Which statement best explains why ozone depletion was not immediately detected despite CFCs being released into the atmosphere since the 1930s?",
    "options": [
      "CFCs are heavier than air and remain in the troposphere",
      "Ozone regeneration balances ozone depletion initially",
      "The ozone hole phenomenon occurs only in polar regions due to unique atmospheric conditions",
      "UV radiation was increasing regardless of ozone levels"
    ],
    "answer": "The ozone hole phenomenon occurs only in polar regions due to unique atmospheric conditions",
    "solutionSteps": [
      "CFCs mix throughout the atmosphere",
      "Ozone loss was gradual and initially masked by natural variations",
      "Antarctic polar stratospheric clouds created ideal conditions for massive ozone destruction",
      "The 'hole' became apparent only when destruction exceeded natural regeneration"
    ],
    "finalAnswer": "The ozone hole phenomenon occurs only in polar regions due to unique atmospheric conditions",
    "isCompetencyBased": true,
    "pyqYear": "2021",
    "pyqSet": "Set B",
    "ncertRef": "NCERT Ch15 InText"
  },
  {
    "id": "OE2-024",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Food Chains and Webs",
    "section": "C",
    "marks": 2,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Applying",
    "questionText": "(PYQ 2023) If 10,000 joules of energy is available to the producer level in an ecosystem, how much energy would be available to the secondary consumer?",
    "options": [
      "1,000 J",
      "100 J",
      "10 J",
      "1 J"
    ],
    "answer": "10 J",
    "solutionSteps": [
      "Primary consumer gets 10% of producer energy: 10,000 × 0.1 = 1,000 J",
      "Secondary consumer gets 10% of primary consumer energy: 1,000 × 0.1 = 100 J",
      "Wait, let me recalculate - secondary consumer receives 100 J",
      "Actually checking: Producer 10,000 J → Primary 1,000 J → Secondary 100 J"
    ],
    "finalAnswer": "100 J",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": "Set A",
    "ncertRef": "NCERT Ch15 Exercise"
  },
  {
    "id": "OE2-025",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Ecosystem Components",
    "section": "B",
    "marks": 2,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "(PYQ 2024) Which of the following food chains is correct?",
    "options": [
      "Plant → Herbivore → Carnivore → Decomposer",
      "Herbivore → Plant → Carnivore → Decomposer",
      "Plant → Carnivore → Herbivore → Decomposer",
      "Decomposer → Plant → Herbivore → Carnivore"
    ],
    "answer": "Plant → Herbivore → Carnivore → Decomposer",
    "solutionSteps": [
      "Food chains start with producers (plants)",
      "Primary consumers (herbivores) eat plants",
      "Secondary consumers (carnivores) eat herbivores",
      "Decomposers break down dead organisms at all levels"
    ],
    "finalAnswer": "Plant → Herbivore → Carnivore → Decomposer",
    "isCompetencyBased": false,
    "pyqYear": "2024",
    "pyqSet": "Set C",
    "ncertRef": "NCERT Ch15 InText"
  },
  {
    "id": "OE2-026",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Ecosystem Components",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "Which of the following is a biotic component of an ecosystem?",
    "options": [
      "Soil",
      "Water",
      "Plants",
      "Temperature"
    ],
    "answer": "Plants",
    "solutionSteps": [
      "Biotic components are living things in an ecosystem",
      "Plants are living organisms",
      "Soil, water, and temperature are abiotic factors"
    ],
    "finalAnswer": "Plants",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 InText"
  },
  {
    "id": "OE2-027",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Ecosystem Components",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "Decomposers in an ecosystem primarily feed on:",
    "options": [
      "Living plants",
      "Dead organic matter",
      "Herbivores",
      "Energy from the sun"
    ],
    "answer": "Dead organic matter",
    "solutionSteps": [
      "Decomposers are organisms that break down dead matter",
      "They obtain nutrients from dead organisms and waste",
      "Examples: bacteria, fungi"
    ],
    "finalAnswer": "Dead organic matter",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 InText"
  },
  {
    "id": "OE2-028",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Ecosystem Components",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "A primary consumer in an ecosystem is an organism that:",
    "options": [
      "Produces its own food through photosynthesis",
      "Feeds on primary consumers",
      "Feeds directly on producers",
      "Breaks down dead organic matter"
    ],
    "answer": "Feeds directly on producers",
    "solutionSteps": [
      "Primary consumers are herbivores",
      "They feed on plants (producers)",
      "They are the first consumers in the food chain"
    ],
    "finalAnswer": "Feeds directly on producers",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 Exercise"
  },
  {
    "id": "OE2-029",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Food Chains and Webs",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "In the food chain: Grass → Grasshopper → Frog → Snake, the grasshopper is a:",
    "options": [
      "Producer",
      "Primary consumer",
      "Secondary consumer",
      "Decomposer"
    ],
    "answer": "Primary consumer",
    "solutionSteps": [
      "Grasshopper feeds on grass (producer)",
      "It is the first consumer in the chain",
      "Primary consumers are herbivores"
    ],
    "finalAnswer": "Primary consumer",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 InText"
  },
  {
    "id": "OE2-030",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Food Chains and Webs",
    "section": "B",
    "marks": 1,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Why is energy lost at each trophic level in a food chain?",
    "options": [],
    "answer": "Energy is lost as heat during respiration, movement, and other metabolic processes. Only about 10% of energy is transferred to the next trophic level.",
    "solutionSteps": [
      "Organisms use energy for various life processes",
      "Energy is lost as heat during cellular respiration",
      "Physical activities like movement, growth consume energy",
      "Thus only 10% energy transfer occurs to next level"
    ],
    "finalAnswer": "Energy is lost as heat during respiration and metabolic activities; only ~10% transferred to next level",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 Exercise"
  },
  {
    "id": "OE2-031",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Food Chains and Webs",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "In a food web, if all grass is destroyed, which organism would be most affected?",
    "options": [
      "Carnivores",
      "Herbivores",
      "Decomposers",
      "Producers"
    ],
    "answer": "Herbivores",
    "solutionSteps": [
      "Grass is a producer/primary food source",
      "Herbivores directly depend on grass",
      "Without grass, herbivores have no food",
      "Carnivores would be indirectly affected later"
    ],
    "finalAnswer": "Herbivores",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 InText"
  },
  {
    "id": "OE2-032",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Ozone Depletion",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "Which gas is primarily responsible for ozone depletion?",
    "options": [
      "Carbon dioxide",
      "Chlorofluorocarbons (CFCs)",
      "Nitrogen oxide",
      "Methane"
    ],
    "answer": "Chlorofluorocarbons (CFCs)",
    "solutionSteps": [
      "CFCs release chlorine atoms in the stratosphere",
      "Chlorine atoms catalytically destroy ozone molecules",
      "One Cl atom can destroy thousands of O3 molecules",
      "CFCs were used in refrigerants and aerosols"
    ],
    "finalAnswer": "Chlorofluorocarbons (CFCs)",
    "isCompetencyBased": false,
    "pyqYear": "2022",
    "pyqSet": "Delhi",
    "ncertRef": "NCERT Ch15 Exercise"
  },
  {
    "id": "OE2-033",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Ozone Depletion",
    "section": "B",
    "marks": 1,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "What is the significance of the ozone layer in Earth's atmosphere?",
    "options": [],
    "answer": "The ozone layer protects Earth from harmful ultraviolet (UV) radiation from the sun. It absorbs UV-B and UV-C rays, preventing them from reaching the surface and causing skin cancer and other harmful effects.",
    "solutionSteps": [
      "Ozone (O3) is present in the stratosphere",
      "It absorbs harmful UV radiation",
      "Protects organisms from UV-induced mutations and damage",
      "Without it, life on Earth would be severely affected"
    ],
    "finalAnswer": "Protects from harmful UV radiation, preventing skin cancer and damage to organisms",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 InText"
  },
  {
    "id": "OE2-034",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Ozone Depletion",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "The ozone hole is most prominent over:",
    "options": [
      "The equator",
      "Antarctica",
      "The tropics",
      "North America"
    ],
    "answer": "Antarctica",
    "solutionSteps": [
      "Antarctic region experiences polar stratospheric clouds",
      "These clouds provide surface for CFC reactions",
      "Temperature drops to extreme levels",
      "Ozone depletion is maximum there (~50% loss)"
    ],
    "finalAnswer": "Antarctica",
    "isCompetencyBased": true,
    "pyqYear": "2021",
    "pyqSet": "All India",
    "ncertRef": "NCERT Ch15 Exercise"
  },
  {
    "id": "OE2-035",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Ozone Depletion",
    "section": "A",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Analysing",
    "questionText": "Assertion: The Montreal Protocol was successful in reducing ozone depletion. Reason: Nations agreed to phase out the production and consumption of CFCs.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "Montreal Protocol (1987) was an international agreement",
      "It mandated phase-out of CFCs and other ozone-depleting substances",
      "This directly led to reduction in ozone depletion",
      "CFC production has decreased significantly since then"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": "Delhi",
    "ncertRef": "NCERT Ch15 Exercise"
  },
  {
    "id": "OE2-036",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Biodegradable and Non-biodegradable",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "Which of the following is a biodegradable waste?",
    "options": [
      "Plastic bags",
      "Glass bottles",
      "Vegetable peels",
      "Aluminum cans"
    ],
    "answer": "Vegetable peels",
    "solutionSteps": [
      "Biodegradable materials are broken down by microorganisms",
      "Vegetable peels are organic matter",
      "Bacteria and fungi can decompose them naturally",
      "Plastic, glass, and aluminum are non-biodegradable"
    ],
    "finalAnswer": "Vegetable peels",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 InText"
  },
  {
    "id": "OE2-037",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Biodegradable and Non-biodegradable",
    "section": "B",
    "marks": 1,
    "format": "Short",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "Define biodegradable waste with one example.",
    "options": [],
    "answer": "Biodegradable waste is organic material that can be decomposed by microorganisms like bacteria and fungi. Example: Food waste, plant leaves, wood, paper.",
    "solutionSteps": [
      "Biodegradable = capable of being degraded biologically",
      "Microorganisms break down these materials",
      "Process returns nutrients to soil",
      "Examples: fruit/vegetable scraps, animal waste, leaves"
    ],
    "finalAnswer": "Organic waste decomposed by microorganisms; e.g., food scraps, leaves, paper",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 InText"
  },
  {
    "id": "OE2-038",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Biodegradable and Non-biodegradable",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Why is plastic pollution a major environmental concern?",
    "options": [
      "It is produced in small quantities",
      "It is non-biodegradable and persists in the environment for centuries",
      "It is easily decomposed by bacteria",
      "It has no impact on marine life"
    ],
    "answer": "It is non-biodegradable and persists in the environment for centuries",
    "solutionSteps": [
      "Plastic is a synthetic polymer",
      "Microorganisms cannot break it down easily",
      "It remains in soil and water for 500+ years",
      "Causes bioaccumulation in food chains",
      "Affects both terrestrial and aquatic ecosystems"
    ],
    "finalAnswer": "It is non-biodegradable and persists in the environment for centuries",
    "isCompetencyBased": true,
    "pyqYear": "2024",
    "pyqSet": "Delhi",
    "ncertRef": "NCERT Ch15 Exercise"
  },
  {
    "id": "OE2-039",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Biodegradable and Non-biodegradable",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Which metal is non-biodegradable but recyclable?",
    "options": [
      "Iron oxide",
      "Aluminum",
      "Wood",
      "Paper"
    ],
    "answer": "Aluminum",
    "solutionSteps": [
      "Aluminum is a metal element",
      "It does not decompose naturally",
      "However, it can be recycled multiple times",
      "Recycling is better than disposal"
    ],
    "finalAnswer": "Aluminum",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 Exercise"
  },
  {
    "id": "OE2-040",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Biodegradable and Non-biodegradable",
    "section": "A",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Analysing",
    "questionText": "Assertion: Paper is considered biodegradable waste. Reason: Paper is made from plant material which can be decomposed by microorganisms.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "Paper is made from cellulose (plant material)",
      "Cellulose is biodegradable",
      "Bacteria can break down cellulose",
      "Paper decomposes in landfills naturally"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 InText"
  },
  {
    "id": "OE2-041",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Ecosystem Components",
    "section": "C",
    "marks": 2,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Explain how the removal of all carnivores from an ecosystem would affect the ecosystem balance. Discuss with reference to food chains.",
    "options": [],
    "answer": "Removal of carnivores would disrupt the ecosystem: (1) Herbivore population would increase unchecked, (2) Overgrazing would lead to destruction of vegetation, (3) Soil erosion would occur, (4) Loss of biodiversity, (5) Eventually herbivores would starve due to food scarcity, (6) Nutrient cycling would be disrupted.",
    "solutionSteps": [
      "Carnivores control herbivore population through predation",
      "Without carnivores, herbivores multiply exponentially",
      "Excessive herbivores consume all available plants",
      "Vegetation loss leads to soil erosion",
      "Food chain breaks down at multiple trophic levels",
      "Ecosystem becomes unstable and collapses"
    ],
    "finalAnswer": "Herbivore overpopulation → overgrazing → vegetation loss → soil erosion → ecosystem collapse",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 Exercise"
  },
  {
    "id": "OE2-042",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Food Chains and Webs",
    "section": "C",
    "marks": 2,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "Why are food webs considered more stable than food chains in maintaining ecosystem stability?",
    "options": [],
    "answer": "Food webs provide multiple feeding pathways: (1) If one organism is removed, alternate food sources are available, (2) Multiple predators for one prey reduce dependency, (3) Greater biodiversity ensures stability, (4) Energy flow has multiple routes, (5) Organisms can shift prey if primary food is unavailable.",
    "solutionSteps": [
      "Food chains show single linear path",
      "Food webs show interconnected multiple pathways",
      "In a web, if one link breaks, others exist",
      "Organisms have dietary flexibility",
      "Population fluctuations are buffered",
      "Ecosystem resilience increases with complexity"
    ],
    "finalAnswer": "Food webs have multiple pathways; loss of one species doesn't cause complete collapse due to alternative food sources",
    "isCompetencyBased": true,
    "pyqYear": "2020",
    "pyqSet": "All India",
    "ncertRef": "NCERT Ch15 Exercise"
  },
  {
    "id": "OE2-043",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Ozone Depletion",
    "section": "C",
    "marks": 2,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Explain how CFC molecules destroy ozone in the stratosphere. What is the role of chlorine atoms?",
    "options": [],
    "answer": "CFCs (e.g., CFC-12) release Cl atoms in stratosphere: Cl + O3 → ClO + O2. ClO + O → Cl + O2. One Cl atom catalytically destroys 100,000 ozone molecules. Chlorine acts as a catalyst, regenerating after each reaction. This widespread ozone destruction creates the ozone hole.",
    "solutionSteps": [
      "CFCs absorb UV radiation at 25-40 km altitude",
      "UV breaks C-Cl bonds releasing chlorine atoms",
      "Cl initiates chain reaction with ozone",
      "Each Cl atom destroys multiple O3 molecules",
      "Chlorine is not consumed, acts as catalyst",
      "Process repeats until Cl is deactivated"
    ],
    "finalAnswer": "CFCs release Cl atoms; each Cl catalytically destroys 100,000 O3 molecules through repeated reactions",
    "isCompetencyBased": true,
    "pyqYear": "2019",
    "pyqSet": "Delhi",
    "ncertRef": "NCERT Ch15 Exercise"
  },
  {
    "id": "OE2-044",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Ecosystem Components",
    "section": "D",
    "marks": 4,
    "format": "Case-Based",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Read the passage and answer the questions:\n\nA lake ecosystem contains algae (producers), small fish (primary consumers), larger fish (secondary consumers), and herons (tertiary consumers). During a drought, the water level dropped significantly, reducing algae growth by 60%. This affected the entire food chain.\n\n(a) What would happen to the population of small fish in the short term?\n(b) Explain the effect on herons using the concept of energy transfer.\n(c) Why would the larger fish population not decline as much as small fish?\n(d) What management strategy could restore ecosystem balance?",
    "options": [],
    "answer": "(a) Small fish population would decrease due to 60% reduction in algae food source. (b) With less algae, energy available to small fish decreases; less energy flows to herons, causing heron population decline (~90% energy loss at tertiary level). (c) Large fish are carnivorous, feeding on small fish; they have alternative food sources. (d) Artificial water supply, reducing fish harvesting, introducing algae species adapted to drought conditions.",
    "solutionSteps": [
      "(a) Algae↓60% → Small fish food↓ → Population decline",
      "(b) Producer level ↓ → Primary consumer ↓ → Secondary consumer ↓ → Tertiary consumer ↓↓↓",
      "(c) Larger fish have more food flexibility, less dependent on algae",
      "(d) Restore water level, manage human activities, enhance water retention"
    ],
    "finalAnswer": "(a) Decrease (b) Energy loss at each level ~90% at tertiary (c) Alternative food sources (d) Water management, reduce harvesting",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 Exercise"
  },
  {
    "id": "OE2-045",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Biodegradable and Non-biodegradable",
    "section": "A",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "Assertion: Incineration of non-biodegradable waste is an ideal waste management solution. Reason: It completely eliminates waste from the environment.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "A is false, R is true.",
    "solutionSteps": [
      "Incineration does eliminate waste physically",
      "But it produces air pollution (toxic gases, ash)",
      "CO2, NOx, SOx, and other pollutants are released",
      "Creates secondary pollution problems",
      "Not ideal; recycling is better solution"
    ],
    "finalAnswer": "A is false, R is true.",
    "isCompetencyBased": true,
    "pyqYear": "2025",
    "pyqSet": "All India",
    "ncertRef": "NCERT Ch15 Exercise"
  },
  {
    "id": "OE2-046",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Ecosystem Components",
    "section": "E",
    "marks": 5,
    "format": "Long",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "With the help of a pyramid of biomass, explain why humans cannot sustain a purely carnivorous diet while being top predators in a food chain. Discuss the ecological and nutritional implications.",
    "options": [],
    "answer": "In a pyramid of biomass, the mass of organisms decreases at each trophic level (~10% rule). If humans are top predators (tertiary level), only 1% of initial producer biomass reaches them. To sustain large human population, this would require 100× more initial production. As omnivores eating at multiple trophic levels (primary/secondary consumers), humans access more biomass (~10% from plants directly). This is more efficient for supporting large populations. Nutritionally, humans require amino acids from both plant and animal sources. Ecologically, top carnivores maintain low population density. Thus, omnivory is necessary for human sustainability both ecologically and nutritionally.",
    "solutionSteps": [
      "Pyramid of Biomass: 1000kg plants → 100kg herbivores → 10kg carnivores → 1kg top predator",
      "Energy transfer: ~10% at each level (90% lost as heat)",
      "Top predator position: very little biomass available",
      "1000 humans at top of chain need 100,000,000 kg plants",
      "But if omnivores: access multiple levels → 10-100× more efficient",
      "Population sustainability requires lower trophic feeding",
      "Nutritionally: plants have incomplete proteins; meat provides all amino acids",
      "Conclusion: Omnivory essential for both ecological and nutritional reasons"
    ],
    "finalAnswer": "Biomass pyramid shows 90% energy loss per level; top predators have minimal biomass available. Omnivory allows access to more trophic levels, providing ~10× more biomass per person, sustaining large populations while meeting nutritional requirements.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 Exercise"
  },
  {
    "id": "OE2-047",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Ozone Depletion",
    "section": "E",
    "marks": 5,
    "format": "Long",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Discuss the Montreal Protocol as an international environmental agreement. Explain its effectiveness in addressing ozone depletion, the challenges faced in its implementation, and the lessons it provides for addressing other global environmental issues like climate change.",
    "options": [],
    "answer": "Montreal Protocol (1987): International treaty to protect ozone layer by phasing out ozone-depleting substances. Effectiveness: (1) Global CFC production reduced by 99% since 1990, (2) Ozone hole projected to heal by 2070, (3) Prevented 2 million skin cancer cases annually. Challenges: (1) Illegal CFC smuggling from developing nations, (2) Transition costs for industries, (3) Developing nations required technology transfer, (4) Found unexpected CFC-11 emissions recently. Lessons for climate change: (1) International cooperation essential, (2) Scientific consensus drives action, (3) Technology availability crucial, (4) Common but differentiated responsibilities, (5) Need continuous monitoring, (6) Binding timelines required.",
    "solutionSteps": [
      "Background: CFC use caused ozone depletion, 80,000 chemical alternatives developed",
      "Effectiveness: 99% reduction in ODS production, ozone recovery on track",
      "Implementation challenges: Economic interests, enforcement issues, alternative chemicals also problematic (HCFCs)",
      "Success factors: Scientific evidence, early action, technology solutions available",
      "Climate parallel: CO2 abatement harder, longer half-life, more sources, greater economic impact",
      "Key lessons: Need immediate action before irreversible damage, alternatives development critical, equity issues important"
    ],
    "finalAnswer": "Montreal Protocol successfully reduced CFCs 99% through international agreement; projecting ozone recovery by 2070. Lessons: Scientific consensus, technology availability, differentiated responsibilities, and continuous monitoring essential. Climate change is more complex but similar approaches needed.",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": "All India",
    "ncertRef": "NCERT Ch15 Exercise"
  },
  {
    "id": "OE2-048",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Food Chains and Webs",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "In an agricultural field, farmers use pesticides to kill insects. Explain how this would affect the food chain including birds that feed on these insects.",
    "options": [],
    "answer": "Pesticides kill insects (primary consumers) → Insect population decreases → Less food for birds → Bird population declines. Additionally, pesticide bioaccumulation: insects accumulate pesticides → birds eating insects accumulate higher pesticide concentrations → birds suffer reproductive failure, weakened eggshells, death. This is biomagnification effect.",
    "solutionSteps": [
      "Direct effect: Insects killed → bird food source reduced",
      "Population effect: Bird population declines due to starvation",
      "Bioaccumulation: Pesticides concentrate in insects",
      "Biomagnification: Birds accumulate 10-100× pesticide concentration",
      "Reproductive failure: Pesticides cause eggshell thinning",
      "Ecological consequence: Predator-prey balance disrupted"
    ],
    "finalAnswer": "Insect kill → bird food↓ → bird population↓; Bioaccumulation → reproductive failure in birds due to pesticide concentration",
    "isCompetencyBased": true,
    "pyqYear": "2021",
    "pyqSet": "Delhi",
    "ncertRef": "NCERT Ch15 InText"
  },
  {
    "id": "OE2-049",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Biodegradable and Non-biodegradable",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Suggest three practical methods to reduce plastic waste in your daily life and explain their environmental benefits.",
    "options": [],
    "answer": "(1) Use reusable bags/containers: Reduces plastic production demand, landfill burden, ocean pollution. (2) Buy products with minimal plastic packaging: Decreases plastic manufacturing, energy use, emissions. (3) Participate in plastic recycling programs: Reduces waste in landfills, conserves raw materials, saves energy (recycling uses 25% less energy). Additional benefits: Reduces microplastic pollution in water systems, protects marine life, prevents bioaccumulation.",
    "solutionSteps": [
      "Method 1: Reusable alternatives → single-use plastic ↓ → waste ↓ → resource conservation",
      "Method 2: Minimal packaging → production ↓ → energy/emissions ↓",
      "Method 3: Recycling → landfill waste ↓ → virgin material demand ↓",
      "Environmental chain reactions: Less plastic → less ocean pollution → marine life protection"
    ],
    "finalAnswer": "Reusables, minimal packaging, recycling; reduces production, waste, energy use, marine pollution, and resource depletion",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 Exercise"
  },
  {
    "id": "OE2-050",
    "subject": "Science",
    "topicKey": "Our Environment",
    "subtopic": "Ecosystem Components",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "If a parasitic disease kills 90% of herbivores in an ecosystem, which organisms would recover fastest?",
    "options": [
      "Primary consumers",
      "Decomposers",
      "Plants/Producers",
      "Carnivores"
    ],
    "answer": "Plants/Producers",
    "solutionSteps": [
      "Herbivores dying → reduced herbivory",
      "Plants face less grazing pressure",
      "Plant biomass accumulates",
      "More resources available for plant growth",
      "Producers recover through reduced consumption"
    ],
    "finalAnswer": "Plants/Producers",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch15 Exercise"
  }
];
