import type { CanonicalQuestion } from "../../types";

export const REP2_PACK2: CanonicalQuestion[] = [
  {
    "id": "REP2-001",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Asexual Reproduction",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "Which of the following is an example of asexual reproduction?",
    "options": [
      "Reproduction in humans",
      "Budding in hydra",
      "Pollination in flowering plants",
      "Fertilization in frogs"
    ],
    "answer": "Budding in hydra",
    "solutionSteps": [
      "Asexual reproduction involves only one parent organism",
      "Budding in hydra is a form of asexual reproduction where a new organism develops from a bud",
      "Other options involve sexual reproduction (two parents)",
      "Therefore, budding in hydra is the correct answer"
    ],
    "finalAnswer": "Budding in hydra",
    "explanation": "Asexual reproduction involves only one parent organism. Budding in hydra is a form of asexual reproduction where a new organism develops from a bud. Other options involve sexual reproduction (two parents). Therefore, budding in hydra is the correct answer. Therefore, the correct answer is Budding in hydra.",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch8 InText"
  },
  {
    "id": "REP2-002",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Asexual Reproduction",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "Fission in bacteria produces:",
    "options": [
      "Two identical daughter cells",
      "Four daughter cells",
      "One daughter cell",
      "Multiple daughter cells of different sizes"
    ],
    "answer": "Two identical daughter cells",
    "solutionSteps": [
      "Bacteria reproduce by binary fission",
      "In binary fission, one bacterium divides into two identical daughter cells",
      "This is an asexual reproduction method",
      "Each daughter cell is genetically identical to the parent"
    ],
    "finalAnswer": "Two identical daughter cells",
    "explanation": "Bacteria reproduce by binary fission. In binary fission, one bacterium divides into two identical daughter cells. This is an asexual reproduction method. Each daughter cell is genetically identical to the parent. Therefore, the correct answer is Two identical daughter cells.",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch8 InText"
  },
  {
    "id": "REP2-003",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Asexual Reproduction",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Vegetative propagation in potato occurs through:",
    "options": [
      "Seeds",
      "Tubers",
      "Flowers",
      "Leaves"
    ],
    "answer": "Tubers",
    "solutionSteps": [
      "Vegetative propagation is asexual reproduction in plants",
      "Potato plants have underground stems called tubers",
      "New potato plants grow from the 'eyes' on tubers",
      "This is a form of asexual reproduction producing genetically identical plants"
    ],
    "finalAnswer": "Tubers",
    "explanation": "Vegetative propagation is asexual reproduction in plants. Potato plants have underground stems called tubers. New potato plants grow from the 'eyes' on tubers. This is a form of asexual reproduction producing genetically identical plants. Therefore, the correct answer is Tubers.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch8 Exercise"
  },
  {
    "id": "REP2-004",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Asexual Reproduction",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Name any two methods of asexual reproduction and give an example of each.",
    "options": [],
    "answer": "Budding in Hydra and Fission in Bacteria (or any two different methods with examples)",
    "solutionSteps": [
      "Asexual reproduction involves only one parent organism",
      "Budding: A new organism develops as an outgrowth of the parent body (Hydra)",
      "Fission: Parent organism divides into two or more daughter organisms (Bacteria, Amoeba)",
      "Other valid examples: Fragmentation (Starfish), Spore formation (Fungi)"
    ],
    "finalAnswer": "Budding in Hydra and Fission in Bacteria (or any two different methods with examples)",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch8 InText"
  },
  {
    "id": "REP2-005",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Sexual Reproduction in Plants",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "The male reproductive organ of a flower is called:",
    "options": [
      "Pistil",
      "Stamen",
      "Sepal",
      "Petal"
    ],
    "answer": "Stamen",
    "solutionSteps": [
      "Flower has male and female reproductive organs",
      "The male reproductive organ is the stamen",
      "Stamen consists of anther (produces pollen) and filament",
      "Pistil is the female reproductive organ"
    ],
    "finalAnswer": "Stamen",
    "explanation": "Flower has male and female reproductive organs. The male reproductive organ is the stamen. Stamen consists of anther (produces pollen) and filament. Pistil is the female reproductive organ. Therefore, the correct answer is Stamen.",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch8 InText"
  },
  {
    "id": "REP2-006",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Sexual Reproduction in Plants",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "Pollination is the transfer of pollen from:",
    "options": [
      "Anther to stigma",
      "Stigma to ovary",
      "Ovule to anther",
      "Filament to pistil"
    ],
    "answer": "Anther to stigma",
    "solutionSteps": [
      "Pollination is a crucial step in sexual reproduction of plants",
      "Pollen is produced in the anther (male organ)",
      "Pollen must be transferred to the stigma (part of female organ)",
      "This transfer is called pollination"
    ],
    "finalAnswer": "Anther to stigma",
    "explanation": "Pollination is a crucial step in sexual reproduction of plants. Pollen is produced in the anther (male organ). Pollen must be transferred to the stigma (part of female organ). This transfer is called pollination. Therefore, the correct answer is Anther to stigma.",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch8 InText"
  },
  {
    "id": "REP2-007",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Sexual Reproduction in Plants",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Self-pollination occurs when:",
    "options": [
      "Pollen from one flower pollinates another flower on the same plant",
      "Pollen from one plant pollinates flowers of a different plant",
      "Wind carries pollen from one plant to another",
      "Insects transfer pollen between different plant species"
    ],
    "answer": "Pollen from one flower pollinates another flower on the same plant",
    "solutionSteps": [
      "Pollination is classified as self-pollination and cross-pollination",
      "Self-pollination: Pollen from anther of one flower fertilizes stigma of the same flower or another flower on the same plant",
      "Cross-pollination: Pollen from one plant fertilizes flowers of a different plant",
      "Options B, C, and D describe cross-pollination"
    ],
    "finalAnswer": "Pollen from one flower pollinates another flower on the same plant",
    "explanation": "Pollination is classified as self-pollination and cross-pollination. Self-pollination: Pollen from anther of one flower fertilizes stigma of the same flower or another flower on the same plant. Cross-pollination: Pollen from one plant fertilizes flowers of a different plant. Options B, C, and D describe cross-pollination. Therefore, the correct answer is Pollen from one flower pollinates another flower on the same plant.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch8 Exercise"
  },
  {
    "id": "REP2-008",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Sexual Reproduction in Plants",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Distinguish between self-pollination and cross-pollination.",
    "options": [],
    "answer": "Self-pollination: Same plant or same flower; Cross-pollination: Different plants",
    "solutionSteps": [
      "Self-pollination involves genetic material from only one plant",
      "Cross-pollination involves genetic material from two different plants",
      "Self-pollination produces less genetic variation",
      "Cross-pollination produces more genetic variation and stronger offspring",
      "Example of self-pollination: Wheat",
      "Example of cross-pollination: Apple, Mango"
    ],
    "finalAnswer": "Self-pollination: Same plant or same flower; Cross-pollination: Different plants",
    "isCompetencyBased": true,
    "pyqYear": "2020",
    "pyqSet": "A",
    "ncertRef": "NCERT Ch8 Exercise"
  },
  {
    "id": "REP2-009",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Sexual Reproduction in Plants",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Why is genetic variation important in the offspring produced by cross-pollination?",
    "options": [],
    "answer": "Genetic variation provides adaptability, disease resistance, and survival advantage",
    "solutionSteps": [
      "Cross-pollination introduces genetic diversity",
      "Offspring have traits from two different parents",
      "This variation helps population adapt to changing environments",
      "Increases disease resistance and vigor (hybrid vigor)",
      "Provides raw material for natural selection",
      "Reduces harmful effects of recessive genes"
    ],
    "finalAnswer": "Genetic variation provides adaptability, disease resistance, and survival advantage",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch8 InText"
  },
  {
    "id": "REP2-010",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Human Reproductive System",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "The part of the testis that produces sperm is called:",
    "options": [
      "Epididymis",
      "Seminiferous tubule",
      "Ductus deferens",
      "Prostate gland"
    ],
    "answer": "Seminiferous tubule",
    "solutionSteps": [
      "Testis is the male reproductive gland",
      "Testis contains seminiferous tubules",
      "Sperm are produced in seminiferous tubules through spermatogenesis",
      "Epididymis stores and matures sperm",
      "Ductus deferens transports sperm"
    ],
    "finalAnswer": "Seminiferous tubule",
    "explanation": "Testis is the male reproductive gland. Testis contains seminiferous tubules. Sperm are produced in seminiferous tubules through spermatogenesis. Epididymis stores and matures sperm. Ductus deferens transports sperm. Therefore, the correct answer is Seminiferous tubule.",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch8 InText"
  },
  {
    "id": "REP2-011",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Human Reproductive System",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "The female gamete is called:",
    "options": [
      "Sperm",
      "Ovum",
      "Zygote",
      "Embryo"
    ],
    "answer": "Ovum",
    "solutionSteps": [
      "Gametes are sex cells involved in sexual reproduction",
      "Male gamete is sperm (produced in testis)",
      "Female gamete is ovum or egg (produced in ovary)",
      "Zygote is formed after fertilization",
      "Embryo is developing organism after several divisions"
    ],
    "finalAnswer": "Ovum",
    "explanation": "Gametes are sex cells involved in sexual reproduction. Male gamete is sperm (produced in testis). Female gamete is ovum or egg (produced in ovary). Zygote is formed after fertilization. Embryo is developing organism after several divisions. Therefore, the correct answer is Ovum.",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch8 InText"
  },
  {
    "id": "REP2-012",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Human Reproductive System",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Fertilization in humans normally occurs in:",
    "options": [
      "Ovary",
      "Uterus",
      "Fallopian tube",
      "Vagina"
    ],
    "answer": "Fallopian tube",
    "solutionSteps": [
      "Ovum is released from ovary during ovulation",
      "Ovum travels through fallopian tube",
      "Sperm travel up through vagina, cervix, uterus to fallopian tube",
      "Fertilization (fusion of sperm and ovum) occurs in the fallopian tube",
      "Fertilized ovum then travels to uterus for implantation"
    ],
    "finalAnswer": "Fallopian tube",
    "explanation": "Ovum is released from ovary during ovulation. Ovum travels through fallopian tube. Sperm travel up through vagina, cervix, uterus to fallopian tube. Fertilization (fusion of sperm and ovum) occurs in the fallopian tube. Fertilized ovum then travels to uterus for implantation. Therefore, the correct answer is Fallopian tube.",
    "isCompetencyBased": true,
    "pyqYear": "2019",
    "pyqSet": "B",
    "ncertRef": "NCERT Ch8 InText"
  },
  {
    "id": "REP2-013",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Human Reproductive System",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Name the hormones secreted by the testis and ovary, and mention one function of each.",
    "options": [],
    "answer": "Testis: Testosterone; Ovary: Estrogen and Progesterone",
    "solutionSteps": [
      "Hormones are chemical messengers in the body",
      "Testis is an endocrine gland secreting testosterone",
      "Testosterone functions: develops male characteristics, deep voice, facial hair, muscle development",
      "Ovary secretes estrogen and progesterone",
      "Estrogen: develops female characteristics, breast development, hip widening",
      "Progesterone: maintains pregnancy, thickens uterine lining"
    ],
    "finalAnswer": "Testis: Testosterone; Ovary: Estrogen and Progesterone",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch8 Exercise"
  },
  {
    "id": "REP2-014",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Human Reproductive System",
    "section": "C",
    "marks": 3,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Analysing",
    "questionText": "Assertion (A): The testes are located outside the abdominal cavity. Reason (R): The temperature inside the abdomen is higher than that required for sperm production.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "A",
    "solutionSteps": [
      "Assertion is true: Testes are located in scrotum outside the abdominal cavity",
      "Reason is true: Sperm production requires temperature about 2-3°C lower than body temperature",
      "The reason correctly explains why testes are outside the abdomen",
      "This is an adaptive feature for successful spermatogenesis"
    ],
    "finalAnswer": "A",
    "explanation": "The correct answer is: A. Evaluate each statement independently before checking if R explains A.",
    "isCompetencyBased": true,
    "pyqYear": "2021",
    "pyqSet": "A",
    "ncertRef": "NCERT Ch8 InText"
  },
  {
    "id": "REP2-015",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Reproductive Health",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "The contraceptive device that prevents implantation of fertilized ovum is:",
    "options": [
      "Condom",
      "Oral contraceptive pills",
      "Intrauterine device (IUD)",
      "Diaphragm"
    ],
    "answer": "Intrauterine device (IUD)",
    "solutionSteps": [
      "IUD is a T-shaped device inserted into the uterus",
      "IUD prevents implantation of fertilized ovum in the uterine wall",
      "It also increases prostaglandins causing sperm death",
      "Condom is a barrier method",
      "Pills contain hormones to prevent ovulation",
      "Diaphragm is a barrier method"
    ],
    "finalAnswer": "Intrauterine device (IUD)",
    "explanation": "IUD is a T-shaped device inserted into the uterus. IUD prevents implantation of fertilized ovum in the uterine wall. It also increases prostaglandins causing sperm death. Condom is a barrier method. Pills contain hormones to prevent ovulation. Diaphragm is a barrier method. Therefore, the correct answer is Intrauterine device (IUD).",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch8 Exercise"
  },
  {
    "id": "REP2-016",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Reproductive Health",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Which of the following STIs is caused by a virus?",
    "options": [
      "Gonorrhea",
      "Syphilis",
      "HIV/AIDS",
      "Chlamydia"
    ],
    "answer": "HIV/AIDS",
    "solutionSteps": [
      "STIs are sexually transmitted infections",
      "Gonorrhea is caused by bacterium Neisseria gonorrhoeae",
      "Syphilis is caused by bacterium Treponema pallidum",
      "HIV/AIDS is caused by virus HIV",
      "Chlamydia is caused by bacterium Chlamydia trachomatis",
      "Only HIV/AIDS is viral; others are bacterial"
    ],
    "finalAnswer": "HIV/AIDS",
    "explanation": "STIs are sexually transmitted infections. Gonorrhea is caused by bacterium Neisseria gonorrhoeae. Syphilis is caused by bacterium Treponema pallidum. HIV/AIDS is caused by virus HIV. Chlamydia is caused by bacterium Chlamydia trachomatis. Only HIV/AIDS is viral; others are bacterial. Therefore, the correct answer is HIV/AIDS.",
    "isCompetencyBased": true,
    "pyqYear": "2022",
    "pyqSet": "B",
    "ncertRef": "NCERT Ch8 Exercise"
  },
  {
    "id": "REP2-017",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Reproductive Health",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Explain why contraception is important for reproductive health.",
    "options": [],
    "answer": "Contraception enables family planning, prevents STIs, improves women's and child health, and supports socio-economic development",
    "solutionSteps": [
      "Contraception provides control over fertility and family size",
      "Allows spacing between pregnancies for maternal recovery",
      "Reduces complications from frequent pregnancies",
      "Prevents spread of sexually transmitted infections (with barrier methods)",
      "Empowers women by giving reproductive choices",
      "Helps in socio-economic development",
      "Prevents unsafe abortions and their complications"
    ],
    "finalAnswer": "Contraception enables family planning, prevents STIs, improves women's and child health, and supports socio-economic development",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch8 Exercise"
  },
  {
    "id": "REP2-018",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Reproductive Health",
    "section": "C",
    "marks": 3,
    "format": "Assertion-Reasoning",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Assertion (A): Barrier contraceptives are more effective than hormonal contraceptives in preventing STIs. Reason (R): Barrier methods physically prevent contact between reproductive organs and body fluids.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "A",
    "solutionSteps": [
      "Assertion is true: Barrier methods (condom) prevent STIs better than hormonal methods",
      "Reason is true: Condoms create physical barrier preventing direct contact",
      "Hormonal methods don't prevent STI transmission as they only prevent pregnancy",
      "Reason correctly explains the assertion",
      "This is important for comprehensive reproductive health"
    ],
    "finalAnswer": "A",
    "explanation": "The correct answer is: A. Evaluate each statement independently before checking if R explains A.",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": "C",
    "ncertRef": "NCERT Ch8 Exercise"
  },
  {
    "id": "REP2-019",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Human Reproductive System",
    "section": "C",
    "marks": 3,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Assertion (A): The menstrual cycle repeats approximately every 28 days. Reason (R): The menstrual cycle is regulated by hormones FSH, LH, estrogen, and progesterone.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "A",
    "solutionSteps": [
      "Assertion is true: Menstrual cycle is typically 28 days (can range 21-35 days)",
      "Reason is true: FSH, LH, estrogen, and progesterone regulate the cycle",
      "FSH stimulates follicle development and estrogen production",
      "LH surge triggers ovulation",
      "Progesterone prepares uterus for implantation",
      "Reason correctly explains the cyclical nature"
    ],
    "finalAnswer": "A",
    "explanation": "The correct answer is: A. Evaluate each statement independently before checking if R explains A.",
    "isCompetencyBased": true,
    "pyqYear": "2024",
    "pyqSet": "A",
    "ncertRef": "NCERT Ch8 InText"
  },
  {
    "id": "REP2-020",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Sexual Reproduction in Plants",
    "section": "E",
    "marks": 4,
    "format": "Case-Based",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "A farmer wants to increase crop production using improved varieties of wheat. He observes that when wheat plants are allowed to self-pollinate, the crop yield remains constant over generations. However, when he allows cross-pollination between different wheat varieties, the yield increases significantly in the first generation. (a) Explain why cross-pollination produces better results than self-pollination. (b) Name the phenomenon observed in the first generation. (c) Suggest why the farmer should continue cross-pollination practice.",
    "options": [],
    "answer": "(a) Genetic diversity and hybrid vigor (b) Hybrid vigor/Heterosis (c) Maintains diversity and prevents inbreeding depression",
    "solutionSteps": [
      "Part (a): Self-pollination produces genetically identical offspring with same traits",
      "Cross-pollination combines traits from two different plants creating variation",
      "Genetic variation results in stronger, more productive offspring",
      "Diverse gene combinations provide better disease resistance and adaptability",
      "Part (b): The phenomenon of enhanced vigor in cross-pollinated offspring is called hybrid vigor or heterosis",
      "This is due to increased heterozygosity in offspring",
      "Part (c): Continuous cross-pollination maintains genetic diversity in population",
      "Prevents accumulation of harmful recessive genes (inbreeding depression)",
      "Ensures sustainable high yield and adaptability to changing environmental conditions"
    ],
    "finalAnswer": "(a) Genetic diversity and hybrid vigor (b) Hybrid vigor/Heterosis (c) Maintains diversity and prevents inbreeding depression",
    "isCompetencyBased": true,
    "pyqYear": "2024",
    "pyqSet": "B",
    "ncertRef": "NCERT Ch8 Exercise"
  },
  {
    "id": "REP2-021",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Reproductive Health",
    "section": "E",
    "marks": 4,
    "format": "Case-Based",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "A 35-year-old woman visits a doctor complaining of irregular menstrual periods and experiencing symptoms like hot flashes, mood swings, and decreased bone density. The doctor diagnoses her with early menopause. (a) What is menopause and why does it occur? (b) Explain the hormonal changes causing her symptoms. (c) Suggest preventive measures to address bone density loss.",
    "options": [],
    "answer": "(a) Permanent end of menstruation due to estrogen depletion (b) Low estrogen causes vasodilation, neurological symptoms, and bone loss (c) Calcium, vitamin D, exercise, HRT",
    "solutionSteps": [
      "Part (a): Menopause marks end of reproductive years in women",
      "Occurs when ovarian follicles deplete and estrogen production decreases significantly",
      "Typically occurs around age 50 but can be early (before 40)",
      "Part (b): Hormonal changes in menopause",
      "Decreased estrogen causes blood vessel dilation leading to hot flashes",
      "Altered neurotransmitter levels cause mood swings and sleep disturbances",
      "Estrogen is essential for bone mineralization; its loss causes osteoporosis",
      "FSH and LH levels increase due to loss of negative feedback",
      "Part (c): Prevention of bone loss",
      "Adequate calcium intake (1200 mg/day)",
      "Vitamin D supplementation for calcium absorption",
      "Weight-bearing exercises to stimulate bone formation",
      "Avoid smoking and excessive alcohol",
      "HRT (Hormone Replacement Therapy) as per medical advice"
    ],
    "finalAnswer": "(a) Permanent end of menstruation due to estrogen depletion (b) Low estrogen causes vasodilation, neurological symptoms, and bone loss (c) Calcium, vitamin D, exercise, HRT",
    "isCompetencyBased": true,
    "pyqYear": "2025",
    "pyqSet": "C",
    "ncertRef": "NCERT Ch8 Exercise"
  },
  {
    "id": "REP2-022",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Human Reproductive System",
    "section": "D",
    "marks": 5,
    "format": "Long",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "Describe the process of gametogenesis in humans. Compare spermatogenesis and oogenesis, highlighting the differences in location, duration, timing, and number of gametes produced.",
    "options": [],
    "answer": "Gametogenesis produces haploid gametes through meiosis. Spermatogenesis: testis, continuous, 74 days, 4 sperm per cell from puberty. Oogenesis: ovary, cyclic, variable duration, 1 ovum per cell from fetal stage.",
    "solutionSteps": [
      "Gametogenesis is formation of gametes through meiosis",
      "Meiosis I: Reduces chromosome number from diploid (2n) to haploid (n)",
      "Meiosis II: Separates sister chromatids",
      "SPERMATOGENESIS:",
      "Location: Seminiferous tubules of testis",
      "Initiation: Starts at puberty (age 12-14 years)",
      "Duration: Approximately 74 days",
      "Timing: Continuous process throughout adult life",
      "Number: One spermatogonium produces 4 functional sperms",
      "Process: Mitotic divisions produce spermatogonia → meiosis produces spermatids → spermiogenesis produces mature sperms",
      "OOGENESIS:",
      "Location: Ovarian follicles of ovary",
      "Initiation: Begins during fetal development",
      "Duration: Variable, meiosis I completes at ovulation",
      "Timing: Discontinuous - monthly cycle after puberty, stops after menopause",
      "Number: One oogonium produces 1 functional ovum and 2-3 polar bodies",
      "Process: Mitotic divisions → Primary oocyte (undergoes meiosis I) → Secondary oocyte arrested in metaphase II → Meiosis II completes only if fertilization occurs",
      "KEY DIFFERENCES:",
      "Spermatogenesis is continuous; Oogenesis is cyclic",
      "Spermatogenesis produces 4 functional gametes; Oogenesis produces 1 gamete",
      "Spermatogenesis starts at puberty; Oogenesis starts before birth",
      "Spermatogenesis completes in testis; Oogenesis completes in fallopian tube"
    ],
    "finalAnswer": "Gametogenesis produces haploid gametes through meiosis. Spermatogenesis: testis, continuous, 74 days, 4 sperm per cell from puberty. Oogenesis: ovary, cyclic, variable duration, 1 ovum per cell from fetal stage.",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": "A",
    "ncertRef": "NCERT Ch8 InText"
  },
  {
    "id": "REP2-023",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Asexual Reproduction",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "Why are organisms that reproduce asexually more vulnerable to environmental changes compared to those reproducing sexually?",
    "options": [],
    "answer": "Asexual reproduction produces genetic clones with no variation, making populations vulnerable to environmental changes and diseases. Sexual reproduction provides genetic diversity enabling population adaptation.",
    "solutionSteps": [
      "Asexual reproduction: No genetic recombination, all offspring are clones",
      "Genetic uniformity means all individuals have same genes and same weaknesses",
      "If pathogen or environmental change selects against a trait, entire population affected",
      "No diversity to draw upon for adaptation",
      "Example: Potato famine - all potatoes genetically identical, disease wiped out crops",
      "Sexual reproduction: Genetic variation through recombination",
      "Different individuals have different traits",
      "Some may have genes for disease resistance",
      "Population can adapt and survive environmental stress",
      "This is why sexually reproducing species have better long-term survival prospects"
    ],
    "finalAnswer": "Asexual reproduction produces genetic clones with no variation, making populations vulnerable to environmental changes and diseases. Sexual reproduction provides genetic diversity enabling population adaptation.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch8 InText"
  },
  {
    "id": "REP2-024",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Sexual Reproduction in Plants",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "What is double fertilization in flowering plants? Name the structures involved.",
    "options": [],
    "answer": "Two sperm fusions: (1) Sperm+Egg→Zygote→Embryo, (2) Sperm+Polar nuclei→Endosperm nucleus→Endosperm tissue",
    "solutionSteps": [
      "Flowering plants undergo unique process called double fertilization",
      "Pollen tube enters embryo sac carrying two sperm",
      "First fertilization: Sperm + Egg nucleus = Zygote",
      "Zygote undergoes mitotic divisions to form embryo",
      "Second fertilization: Sperm + Polar nuclei (fused) = Endosperm nucleus",
      "Endosperm nucleus undergoes divisions forming endosperm tissue",
      "Endosperm provides nutrition to developing embryo",
      "This is unique to flowering plants (angiosperms)",
      "Structures involved: Egg cell, Polar nuclei, Synergids, Antipodal cells in embryo sac"
    ],
    "finalAnswer": "Two sperm fusions: (1) Sperm+Egg→Zygote→Embryo, (2) Sperm+Polar nuclei→Endosperm nucleus→Endosperm tissue",
    "isCompetencyBased": true,
    "pyqYear": "2021",
    "pyqSet": "B",
    "ncertRef": "NCERT Ch8 InText"
  },
  {
    "id": "REP2-025",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Reproductive Health",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "List any four methods of contraception and classify them as reversible or irreversible.",
    "options": [],
    "answer": "Reversible: Condom, IUD, Pills, Injectables; Irreversible: Tubectomy, Vasectomy",
    "solutionSteps": [
      "Contraceptive methods are classified based on reversibility",
      "REVERSIBLE METHODS:",
      "1. Condoms - Physical barrier, prevents sperm entry, also prevents STIs",
      "2. IUD (Intrauterine Device) - Inserted in uterus, prevents implantation",
      "3. Oral Contraceptive Pills - Hormonal method, prevents ovulation",
      "4. Injectables - Hormonal injections given periodically",
      "5. Diaphragm - Barrier method",
      "6. Cervical caps - Barrier method",
      "IRREVERSIBLE METHODS:",
      "1. Tubectomy - Surgical blocking of fallopian tubes in females",
      "2. Vasectomy - Surgical blocking of vas deferens in males",
      "These permanent methods require surgical reversal which is complex",
      "Reversible methods can be discontinued anytime"
    ],
    "finalAnswer": "Reversible: Condom, IUD, Pills, Injectables; Irreversible: Tubectomy, Vasectomy",
    "isCompetencyBased": true,
    "pyqYear": "2022",
    "pyqSet": "A",
    "ncertRef": "NCERT Ch8 Exercise"
  },
  {
    "id": "REP2-027",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Asexual Reproduction",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "Fission in amoeba produces:",
    "options": [
      "A. Two unequal daughter cells",
      "B. Two genetically identical daughter cells",
      "C. Four daughter cells",
      "D. Multiple flagellated cells"
    ],
    "answer": "B. Two genetically identical daughter cells",
    "solutionSteps": [
      "Binary fission in amoeba is a form of asexual reproduction.",
      "The parent cell divides into two equal-sized daughter cells.",
      "Both daughter cells are genetically identical to each other and the parent."
    ],
    "finalAnswer": "B. Two genetically identical daughter cells",
    "explanation": "Binary fission in amoeba is a form of asexual reproduction. The parent cell divides into two equal-sized daughter cells. Both daughter cells are genetically identical to each other and the parent. Therefore, the correct answer is B. Two genetically identical daughter cells.",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch8 InText"
  },
  {
    "id": "REP2-028",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Asexual Reproduction",
    "section": "A",
    "marks": 1,
    "format": "Short",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "Name one advantage of asexual reproduction.",
    "options": [],
    "answer": "Any valid advantage such as: Rapid reproduction, no need for mate, genetic identity with parent",
    "solutionSteps": [
      "Asexual reproduction has several advantages:",
      "1. It is faster than sexual reproduction",
      "2. Only one parent is required",
      "3. Genetic variation is minimal, preserving favorable traits"
    ],
    "finalAnswer": "Any valid advantage such as: Rapid reproduction, no need for mate, genetic identity with parent",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch8 Exercise"
  },
  {
    "id": "REP2-029",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Sexual Reproduction in Plants",
    "section": "B",
    "marks": 2,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "The male reproductive part of a flower is:",
    "options": [
      "A. Carpel",
      "B. Stamen",
      "C. Sepal",
      "D. Stigma"
    ],
    "answer": "B. Stamen",
    "solutionSteps": [
      "A flower has male and female reproductive parts.",
      "The stamen is the male part consisting of anther and filament.",
      "The anther produces pollen grains.",
      "Carpel is the female part."
    ],
    "finalAnswer": "B. Stamen",
    "explanation": "A flower has male and female reproductive parts. The stamen is the male part consisting of anther and filament. The anther produces pollen grains. Carpel is the female part. Therefore, the correct answer is B. Stamen.",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch8 InText"
  },
  {
    "id": "REP2-030",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Sexual Reproduction in Plants",
    "section": "B",
    "marks": 2,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Pollination by wind is called:",
    "options": [
      "A. Entomophily",
      "B. Hydrophily",
      "C. Anemophily",
      "D. Zoophily"
    ],
    "answer": "C. Anemophily",
    "solutionSteps": [
      "Different types of pollination exist based on pollinating agents.",
      "Wind-pollinated plants: Anemophily",
      "Insect-pollinated plants: Entomophily",
      "Water-pollinated plants: Hydrophily",
      "Animal-pollinated plants: Zoophily"
    ],
    "finalAnswer": "C. Anemophily",
    "explanation": "Different types of pollination exist based on pollinating agents. Wind-pollinated plants: Anemophily. Insect-pollinated plants: Entomophily. Water-pollinated plants: Hydrophily. Animal-pollinated plants: Zoophily. Therefore, the correct answer is C. Anemophily.",
    "isCompetencyBased": false,
    "pyqYear": "2021",
    "pyqSet": "Delhi",
    "ncertRef": "NCERT Ch8 InText"
  },
  {
    "id": "REP2-031",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Sexual Reproduction in Plants",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Why do flowers have brightly colored petals? Explain with reference to pollination.",
    "options": [],
    "answer": "Brightly colored petals attract insects which help in pollination by transferring pollen.",
    "solutionSteps": [
      "Flowers produce nectar and have attractive features.",
      "Brightly colored petals are an adaptation to attract insects.",
      "Insects visit flowers for nectar and pollen.",
      "During this, they transfer pollen from one flower to another.",
      "This is insect pollination or entomophily."
    ],
    "finalAnswer": "Brightly colored petals attract insects which help in pollination by transferring pollen.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch8 Exercise"
  },
  {
    "id": "REP2-032",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Sexual Reproduction in Plants",
    "section": "B",
    "marks": 2,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A flower is self-pollinated. This means:",
    "options": [
      "A. Pollen from one flower pollinates another flower of different plant",
      "B. Pollen from anther of the same flower pollinates its own stigma",
      "C. Pollination occurs without any external agent",
      "D. Only wind can pollinate the flower"
    ],
    "answer": "B. Pollen from anther of the same flower pollinates its own stigma",
    "solutionSteps": [
      "Self-pollination occurs when pollen from the anther of one flower reaches the stigma of the same flower.",
      "This can be within the same flower or between flowers of the same plant.",
      "Cross-pollination is when pollen transfers between different plants."
    ],
    "finalAnswer": "B. Pollen from anther of the same flower pollinates its own stigma",
    "isCompetencyBased": true,
    "pyqYear": "2019",
    "pyqSet": "All India",
    "ncertRef": "NCERT Ch8 InText"
  },
  {
    "id": "REP2-033",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Human Reproductive System",
    "section": "C",
    "marks": 3,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "The site of sperm production in males is:",
    "options": [
      "A. Prostate gland",
      "B. Seminal vesicle",
      "C. Testis",
      "D. Epididymis"
    ],
    "answer": "C. Testis",
    "solutionSteps": [
      "The male reproductive system produces sperms.",
      "Testes are the site of sperm production (spermatogenesis).",
      "Prostate and seminal vesicles add secretions to semen.",
      "Epididymis stores and matures sperms."
    ],
    "finalAnswer": "C. Testis",
    "explanation": "The male reproductive system produces sperms. Testes are the site of sperm production (spermatogenesis). Prostate and seminal vesicles add secretions to semen. Epididymis stores and matures sperms. Therefore, the correct answer is C. Testis.",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch8 InText"
  },
  {
    "id": "REP2-034",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Human Reproductive System",
    "section": "C",
    "marks": 3,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "Where does fertilization occur in humans?",
    "options": [
      "A. Uterus",
      "B. Vagina",
      "C. Fallopian tube",
      "D. Ovary"
    ],
    "answer": "C. Fallopian tube",
    "solutionSteps": [
      "Fertilization is the fusion of egg and sperm.",
      "The ovum is released from the ovary during ovulation.",
      "It travels through the fallopian tube.",
      "If sperm meets the ovum in the fallopian tube, fertilization occurs there."
    ],
    "finalAnswer": "C. Fallopian tube",
    "explanation": "Fertilization is the fusion of egg and sperm. The ovum is released from the ovary during ovulation. It travels through the fallopian tube. If sperm meets the ovum in the fallopian tube, fertilization occurs there. Therefore, the correct answer is C. Fallopian tube.",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch8 InText"
  },
  {
    "id": "REP2-035",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Human Reproductive System",
    "section": "C",
    "marks": 3,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "What is the function of the placenta?",
    "options": [],
    "answer": "The placenta provides nutrients, oxygen, and hormones to the fetus; removes wastes; and provides immunity.",
    "solutionSteps": [
      "The placenta is an organ that develops in the uterus during pregnancy.",
      "It acts as a barrier and interface between maternal and fetal circulation.",
      "Functions: Supply nutrients, oxygen, and antibodies to the fetus",
      "Remove CO2 and other wastes from the fetus",
      "Hormonal secretion for pregnancy maintenance"
    ],
    "finalAnswer": "The placenta is a specialised disc-shaped organ that develops in the uterus during pregnancy and serves as the interface between the mother's blood supply and the developing fetus. It performs three main functions: first, it supplies the fetus with oxygen (by diffusion from the mother's blood) and nutrients such as glucose, amino acids, and vitamins, which the fetus needs for growth and development; second, it removes metabolic waste products generated by the fetus — including carbon dioxide and urea — and transfers them to the mother's blood for elimination via the mother's lungs and kidneys; and third, it allows maternal antibodies (immunoglobulins) to cross into the fetal blood, providing the fetus with passive immunity that protects the newborn baby in the early months of life. The placenta also produces hormones such as progesterone and oestrogen that are essential to maintaining the pregnancy.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch8 Exercise"
  },
  {
    "id": "REP2-036",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Human Reproductive System",
    "section": "C",
    "marks": 3,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "The menstrual cycle in humans occurs approximately every:",
    "options": [
      "A. 14 days",
      "B. 21 days",
      "C. 28 days",
      "D. 35 days"
    ],
    "answer": "C. 28 days",
    "solutionSteps": [
      "The menstrual cycle is the monthly reproductive cycle in females.",
      "It occurs approximately every 28 days (range: 21-35 days).",
      "The cycle includes menstruation, proliferation, ovulation, and secretion phases."
    ],
    "finalAnswer": "C. 28 days",
    "isCompetencyBased": false,
    "pyqYear": "2020",
    "pyqSet": "Delhi",
    "ncertRef": "NCERT Ch8 InText"
  },
  {
    "id": "REP2-037",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Human Reproductive System",
    "section": "C",
    "marks": 3,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "During the female menstrual cycle, ovulation occurs around day:",
    "options": [
      "A. 7",
      "B. 14",
      "C. 21",
      "D. 28"
    ],
    "answer": "B. 14",
    "solutionSteps": [
      "The menstrual cycle is approximately 28 days.",
      "Ovulation (release of mature ovum) occurs around the middle of the cycle.",
      "This is approximately on day 14 of a 28-day cycle.",
      "This marks the start of the luteal phase."
    ],
    "finalAnswer": "B. 14",
    "isCompetencyBased": true,
    "pyqYear": "2022",
    "pyqSet": "All India",
    "ncertRef": "NCERT Ch8 Exercise"
  },
  {
    "id": "REP2-038",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Reproductive Health",
    "section": "D",
    "marks": 5,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Which of the following is a sexually transmitted infection (STI)?",
    "options": [
      "A. Diabetes",
      "B. Syphilis",
      "C. Asthma",
      "D. Arthritis"
    ],
    "answer": "B. Syphilis",
    "solutionSteps": [
      "Sexually transmitted infections spread through sexual contact.",
      "Syphilis is caused by the bacterium Treponema pallidum.",
      "Other STIs include gonorrhea, chlamydia, and HIV/AIDS.",
      "Diabetes, asthma, and arthritis are not sexually transmitted."
    ],
    "finalAnswer": "B. Syphilis",
    "explanation": "Sexually transmitted infections spread through sexual contact. Syphilis is caused by the bacterium Treponema pallidum. Other STIs include gonorrhea, chlamydia, and HIV/AIDS. Diabetes, asthma, and arthritis are not sexually transmitted. Therefore, the correct answer is B. Syphilis.",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch8 InText"
  },
  {
    "id": "REP2-039",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Reproductive Health",
    "section": "D",
    "marks": 5,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Name two contraceptive methods.",
    "options": [],
    "answer": "Any two valid methods: Condoms, contraceptive pills, IUD, tubectomy, vasectomy, etc.",
    "solutionSteps": [
      "Contraceptive methods prevent unwanted pregnancies.",
      "Barrier methods: Condoms, diaphragm",
      "Hormonal methods: Birth control pills, patches, injections",
      "Mechanical methods: IUD, copper T",
      "Surgical methods: Tubectomy (female), Vasectomy (male)"
    ],
    "finalAnswer": "Any two valid methods: Condoms, contraceptive pills, IUD, tubectomy, vasectomy, etc.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch8 Exercise"
  },
  {
    "id": "REP2-040",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Reproductive Health",
    "section": "D",
    "marks": 5,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Assertion (A): Condoms are 100% effective in preventing STIs. Reason (R): Condoms act as a barrier between sexual partners.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "D. A is false, R is true.",
    "solutionSteps": [
      "The reason is correct: Condoms do act as a barrier.",
      "However, condoms are not 100% effective - they reduce risk significantly but are not absolute.",
      "Effectiveness depends on proper use, material quality, and potential breakage.",
      "Therefore, A is false but R is true."
    ],
    "finalAnswer": "D. A is false, R is true.",
    "explanation": "The Assertion contains an incorrect claim. The Reason, however, is a true and valid statement on its own.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch8 InText"
  },
  {
    "id": "REP2-041",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Reproductive Health",
    "section": "D",
    "marks": 5,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Which of the following practices is most important for maintaining reproductive health?",
    "options": [
      "A. Consuming sugary foods",
      "B. Regular exercise and balanced diet",
      "C. Avoiding healthcare checkups",
      "D. Ignoring personal hygiene"
    ],
    "answer": "B. Regular exercise and balanced diet",
    "solutionSteps": [
      "Reproductive health requires overall physical and mental well-being.",
      "Regular exercise and balanced diet support healthy reproductive function.",
      "Good nutrition provides essential micronutrients for reproductive hormones.",
      "Exercise improves circulation and hormonal balance."
    ],
    "finalAnswer": "B. Regular exercise and balanced diet",
    "explanation": "Reproductive health requires overall physical and mental well-being. Regular exercise and balanced diet support healthy reproductive function. Good nutrition provides essential micronutrients for reproductive hormones. Exercise improves circulation and hormonal balance. Therefore, the correct answer is B. Regular exercise and balanced diet.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch8 Exercise"
  },
  {
    "id": "REP2-042",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Sexual Reproduction in Plants",
    "section": "B",
    "marks": 2,
    "format": "Assertion-Reasoning",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Assertion (A): Self-pollination leads to genetic variation in offspring. Reason (R): Self-pollination involves transfer of pollen within the same flower or plant.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "D. A is false, R is true.",
    "solutionSteps": [
      "The reason is correct: Self-pollination involves pollen transfer within the same plant.",
      "However, self-pollination reduces genetic variation, not increases it.",
      "Self-pollination leads to homozygosity and less genetic diversity.",
      "Cross-pollination increases genetic variation.",
      "Therefore, A is false but R is true."
    ],
    "finalAnswer": "D. A is false, R is true.",
    "explanation": "The Assertion contains an incorrect claim. The Reason, however, is a true and valid statement on its own.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch8 Exercise"
  },
  {
    "id": "REP2-043",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Human Reproductive System",
    "section": "C",
    "marks": 3,
    "format": "Assertion-Reasoning",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Assertion (A): The umbilical cord connects the fetus directly to the mother's blood vessels. Reason (R): The umbilical cord contains blood vessels for nutrient and waste exchange.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "B. Both A and R are true, but R is not the correct explanation of A.",
    "solutionSteps": [
      "Both statements are true.",
      "The umbilical cord does connect the fetus to placental circulation.",
      "However, fetal and maternal blood do NOT directly mix.",
      "The placenta acts as a barrier; exchange occurs through the placental membrane.",
      "The reason is true but doesn't fully explain why the assertion is misleading.",
      "A is slightly imprecise (not 'direct' blood vessels but through placenta), R is true but independent."
    ],
    "finalAnswer": "B. Both A and R are true, but R is not the correct explanation of A.",
    "explanation": "Both statements are individually correct. However, the Reason does not directly cause or explain the Assertion — they are independent true facts about the same concept.",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": "All India",
    "ncertRef": "NCERT Ch8 InText"
  },
  {
    "id": "REP2-044",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Sexual Reproduction in Plants",
    "section": "E",
    "marks": 4,
    "format": "Case-Based",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "A farmer noticed that when he grows tomato plants closely together, the fruit set is poor. However, when he allows bees to visit the field, the fruit set improves significantly.\n\n(i) What is the role of bees in improving fruit set?\n(ii) Name the process that occurs in tomato flowers due to bee activity.\n(iii) What would happen if bees did not visit the tomato flowers?\n(iv) How can the farmer ensure good fruit set without bees?",
    "options": [],
    "answer": "Bees act as pollinators enabling cross-pollination in tomato flowers, which is essential for fruit development. Without pollination, fruits cannot form. Manual pollination is an alternative.",
    "solutionSteps": [
      "(i) Bees are pollinators that transfer pollen between flowers.",
      "They carry pollen on their body from one flower to another.",
      "This enables pollination and fertilization, leading to fruit development.",
      "(ii) The process is called pollination, specifically cross-pollination (pollen from different flowers).",
      "(iii) Without bee visits: Flowers may not get pollinated, fertilization won't occur, fruits won't develop.",
      "(iv) The farmer can manually pollinate flowers using a brush or hand-pollinate using cotton swabs."
    ],
    "finalAnswer": "Bees act as pollinators enabling cross-pollination in tomato flowers, which is essential for fruit development. Without pollination, fruits cannot form. Manual pollination is an alternative.",
    "isCompetencyBased": true,
    "pyqYear": "2024",
    "pyqSet": "Regional",
    "ncertRef": "NCERT Ch8 Exercise"
  },
  {
    "id": "REP2-045",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Asexual Reproduction",
    "section": "A",
    "marks": 1,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Compare asexual and sexual reproduction in terms of genetic variation and adaptability to environmental changes.",
    "options": [],
    "answer": "Asexual reproduction produces genetically identical offspring with no variation, making species less adaptable. Sexual reproduction creates genetic variation through combination of parental genes, enabling better adaptation to environmental changes and evolution.",
    "solutionSteps": [
      "Asexual Reproduction:",
      "- Involves one parent",
      "- No genetic recombination",
      "- All offspring are clones (genetically identical)",
      "- No variation means limited adaptability",
      "- Vulnerable to same diseases/environmental stress",
      "",
      "Sexual Reproduction:",
      "- Involves two parents",
      "- Genetic recombination during meiosis",
      "- High genetic variation among offspring",
      "- Variation allows better adaptability",
      "- Some offspring may survive environmental changes",
      "",
      "Evolutionary advantage of sexual reproduction through genetic diversity."
    ],
    "finalAnswer": "Asexual reproduction produces genetically identical offspring with no variation, making species less adaptable. Sexual reproduction creates genetic variation through combination of parental genes, enabling better adaptation to environmental changes and evolution.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch8 Exercise"
  },
  {
    "id": "REP2-046",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Sexual Reproduction in Plants",
    "section": "B",
    "marks": 2,
    "format": "Long",
    "difficulty": "Hard",
    "bloomSkill": "Creating",
    "questionText": "Explain the process of double fertilization in flowering plants. What are its consequences?",
    "options": [],
    "answer": "Double fertilization is the fusion of two sperm cells with egg and polar nuclei respectively, resulting in zygote (embryo) and endosperm (food storage). This ensures viable, well-nourished seeds and fruit formation, a key feature of flowering plants.",
    "solutionSteps": [
      "Double Fertilization Process:",
      "1. After pollen grain lands on stigma, pollen tube grows through style to ovule",
      "2. Pollen tube contains two sperm cells (male gametes)",
      "3. One sperm fuses with egg cell → forms zygote (diploid)",
      "4. Second sperm fuses with polar nuclei → forms primary endosperm nucleus (triploid)",
      "",
      "Consequences of Double Fertilization:",
      "1. Formation of Zygote:",
      "   - Develops into embryo",
      "   - Further develops into new plant",
      "",
      "2. Formation of Endosperm:",
      "   - Provides nutrition to developing embryo",
      "   - Stored in seed as reserve food",
      "   - Examples: Starch in rice, protein in legumes, oil in sunflower",
      "",
      "3. Formation of Seed:",
      "   - Protective covering of embryo",
      "   - Contains endosperm for nourishment",
      "",
      "4. Formation of Fruit:",
      "   - Ovary wall develops into fruit",
      "   - Protects seeds",
      "   - Aids in seed dispersal",
      "",
      "Significance: Double fertilization is unique to flowering plants and ensures efficient seed production with adequate nutrition."
    ],
    "finalAnswer": "Double fertilization is the fusion of two sperm cells with egg and polar nuclei respectively, resulting in zygote (embryo) and endosperm (food storage). This ensures viable, well-nourished seeds and fruit formation, a key feature of flowering plants.",
    "isCompetencyBased": true,
    "pyqYear": "2025",
    "pyqSet": "All India",
    "ncertRef": "NCERT Ch8 InText"
  },
  {
    "id": "REP2-047",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Human Reproductive System",
    "section": "C",
    "marks": 3,
    "format": "Long",
    "difficulty": "Hard",
    "bloomSkill": "Creating",
    "questionText": "Describe the development of a human fetus from fertilization to birth. Mention the role of the placenta and umbilical cord.",
    "options": [],
    "answer": "Fertilization → Cleavage → Blastocyst → Implantation → Embryonic development → Fetal development → Birth. Placenta provides nutrition; umbilical cord transports nutrients and removes wastes.",
    "solutionSteps": [
      "Stages of Human Development:",
      "",
      "1. Fertilization (Day 0):",
      "   - Sperm fuses with ovum",
      "   - Forms zygote (2n chromosomes)",
      "   - Occurs in fallopian tube",
      "",
      "2. Cleavage (Days 1-3):",
      "   - Zygote divides mitotically",
      "   - Forms 2, 4, 8, 16 celled embryo",
      "   - Moves toward uterus",
      "",
      "3. Blastocyst Formation (Days 4-5):",
      "   - Hollow ball of cells",
      "   - Inner cell mass (becomes embryo)",
      "   - Outer trophoblast cells",
      "",
      "4. Implantation (Days 6-12):",
      "   - Blastocyst embeds in uterine wall",
      "   - Trophoblast develops into placenta",
      "",
      "5. Embryonic Period (Weeks 1-8):",
      "   - Formation of germ layers (ectoderm, mesoderm, endoderm)",
      "   - Development of organs (organogenesis)",
      "   - Formation of limbs, facial features",
      "",
      "6. Fetal Period (Weeks 9-40):",
      "   - Growth and maturation of organs",
      "   - Development of bones, muscles",
      "   - Development of nervous system",
      "   - Quickening (fetal movements felt)",
      "",
      "7. Birth (Week 40, ~280 days):",
      "   - Contractions of uterus",
      "   - Cervix dilation",
      "   - Expulsion of fetus and placenta",
      "",
      "Role of Placenta:",
      "- Provides O₂ and nutrients from mother's blood",
      "- Removes CO₂ and nitrogenous wastes",
      "- Secretes hormones (progesterone, estrogen)",
      "- Acts as barrier against harmful substances",
      "- Transfers antibodies from mother",
      "",
      "Role of Umbilical Cord:",
      "- Contains 2 arteries and 1 vein",
      "- Carries deoxygenated blood from fetus to placenta",
      "- Carries oxygenated blood from placenta to fetus",
      "- Transports nutrients and removes wastes"
    ],
    "finalAnswer": "Human fetal development begins at fertilisation, when a sperm cell fuses with an egg cell in the fallopian tube to form a zygote; the zygote undergoes rapid cell divisions (cleavage) to form a morula and then a blastocyst, which travels to the uterus and implants into the uterine wall in a process called implantation; the inner cell mass of the blastocyst develops into the embryo, and organogenesis (formation of organs and body systems) occurs during the first two months; from the third month onwards the developing organism is called a fetus and continues to grow until birth at approximately 40 weeks; the placenta is a specialised organ that connects the mother and fetus and provides the fetus with oxygen, glucose, and nutrients from the mother's blood while removing carbon dioxide and metabolic wastes; the umbilical cord connects the fetus to the placenta and contains blood vessels that carry nutrients and oxygen to the fetus and return waste products to the placenta.",
    "isCompetencyBased": true,
    "pyqYear": "2024",
    "pyqSet": "All India",
    "ncertRef": "NCERT Ch8 Exercise"
  },
  {
    "id": "REP2-048",
    "subject": "Science",
    "topicKey": "How do Organisms Reproduce?",
    "subtopic": "Reproductive Health",
    "section": "D",
    "marks": 5,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Why is reproductive health education important for adolescents?",
    "options": [],
    "answer": "Reproductive health education empowers adolescents to make informed decisions, prevent STIs and unwanted pregnancies, understand their changing bodies, and develop healthy relationships and behaviors.",
    "solutionSteps": [
      "Reproductive health education for adolescents is crucial because:",
      "1. Awareness about physical and emotional changes during puberty",
      "2. Understanding reproductive anatomy and physiology",
      "3. Knowledge about STIs and prevention methods",
      "4. Information about contraception and family planning",
      "5. Development of responsible sexual behavior",
      "6. Understanding consent and healthy relationships",
      "7. Prevention of early/unwanted pregnancies",
      "8. Promotion of mental health and self-esteem"
    ],
    "finalAnswer": "Reproductive health education empowers adolescents to make informed decisions, prevent STIs and unwanted pregnancies, understand their changing bodies, and develop healthy relationships and behaviors.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "NCERT Ch8 Exercise"
  }
];
