// GENERATED by lazytopper/scripts/generateBankChapters.ts (BANK-SPLIT-1 PR-2). DO NOT EDIT BY HAND.
// Regenerate from lazytopper/ with: pnpm run gen:bank-chapters
// src/data/bankChapters/bankChapters.guard.test.ts fails when this file disagrees with the aggregator.

// Chapter "acids-bases-and-salts" (Science): 550 served rows from 22 source arrays, 18 withheld.
// Each source is [spread position in RAW_CANONICAL_QUESTION_BANK, the array, is it an AI pack].

import { defineChapter } from "./defineChapter";
import { ACIDS_BASES_SALTS_PACK1 } from "../questionBanks/class10/science/acidsBasesSalts.pack1";
import { ABS2_PACK2 } from "../questionBanks/class10/science/acidsBasesSalts.pack2";
import { ACIDS_BASES_SALTS_NCERT } from "../questionBanks/class10/science/acidsBasesSalts.ncert";
import { ACIDS_BASES_SALTS_EXEMPLAR } from "../questionBanks/class10/science/acidsBasesSalts.exemplar";
import { ABS_EXPAND_EXTRACT } from "../questionBanks/class10/science/acidsBasesSalts.expand.extract";
import { ABS_EXPAND_LONG_D } from "../questionBanks/class10/science/acidsBasesSalts.expand.longD";
import { ABS_EXPAND_CASE_E } from "../questionBanks/class10/science/acidsBasesSalts.expand.caseE";
import { ACIDS_BASES_SALTS_SQP } from "../questionBanks/class10/science/acids-bases-and-salts.sqp";
import { ACID_CBE } from "../questionBanks/class10/science/acids-bases-and-salts.cbe";
import { ACID_SP } from "../questionBanks/class10/science/acids-bases-and-salts.sp";
import { ACIDS_BASES_SALTS_APQ } from "../questionBanks/class10/science/acids-bases-and-salts.additionalPQ";
import { CHEMICAL_REACTIONS_CHAPTERWISE } from "../questionBanks/class10/science/chemical-reactions-and-equations.chapterwise";
import { ACIDS_BASES_SALTS_CHAPTERWISE } from "../questionBanks/class10/science/acids-bases-and-salts.chapterwise";
import { ACIDS_BASES_SALTS_PYQ } from "../questionBanks/class10/science/acids-bases-and-salts.pyq";
import { CARBON_COMPOUNDS_PYQ } from "../questionBanks/class10/science/carbon-and-its-compounds.pyq";
import { acidsBasesSaltsPYQ2026 } from "../questionBanks/class10/science/acidsBasesSalts.pyq2026";
import { acidsBasesSaltsPYQ2025 } from "../questionBanks/class10/science/acidsBasesSalts.pyq2025";
import { acidsBasesSaltsPYQ2024 } from "../questionBanks/class10/science/acidsBasesSalts.pyq2024";
import { ABS_CFPQ } from "../questionBanks/class10/science/acids-bases-and-salts.cfpq";
import { CURATED_INLINE_QUESTIONS } from "../questionBanks/class10/curatedInline";
import { ACIDS_CBQ_B1_LT_GENERATED } from "../questionBanks/class10/science/acids-bases-and-salts.b1.cbq.ltgen";
import { ACIDS_BASES_AND_SALTS_C3_CBQ_LT_GENERATED } from "../questionBanks/class10/science/acids-bases-and-salts.c3.cbq.ltgen";

export default defineChapter("acids-bases-and-salts", [
  [30, ACIDS_BASES_SALTS_PACK1, true],
  [31, ABS2_PACK2, true],
  [76, ACIDS_BASES_SALTS_NCERT, false],
  [77, ACIDS_BASES_SALTS_EXEMPLAR, false],
  [78, ABS_EXPAND_EXTRACT, false],
  [79, ABS_EXPAND_LONG_D, false],
  [80, ABS_EXPAND_CASE_E, false],
  [180, ACIDS_BASES_SALTS_SQP, false],
  [205, ACID_CBE, false],
  [231, ACID_SP, false],
  [270, ACIDS_BASES_SALTS_APQ, false],
  [282, CHEMICAL_REACTIONS_CHAPTERWISE, false],
  [283, ACIDS_BASES_SALTS_CHAPTERWISE, false],
  [296, ACIDS_BASES_SALTS_PYQ, false],
  [298, CARBON_COMPOUNDS_PYQ, false],
  [360, acidsBasesSaltsPYQ2026, false],
  [373, acidsBasesSaltsPYQ2025, false],
  [386, acidsBasesSaltsPYQ2024, false],
  [398, ABS_CFPQ, false],
  [415, CURATED_INLINE_QUESTIONS, false],
  [434, ACIDS_CBQ_B1_LT_GENERATED, false],
  [456, ACIDS_BASES_AND_SALTS_C3_CBQ_LT_GENERATED, false],
], [
  "ABS-E04",
  "ACID-EXMPLR-2-MCQ-015",
  "SCO-S-ACID-005",
  "SCO-S-ACID-014",
  "SCO-S-ACID-015",
  "SCO-S-ACID-018",
  "SCO-S-ACID-019",
  "SCQ-S-ACID-034",
  "SCQ-S-ACID-044",
  "PYQ-S-ACID-001",
  "PYQ-S-ACID-011",
  "PYQ-S-ACID-013",
  "PYQ-S-2026-ACID-012",
  "PYQ-S-2025-ACID-006",
  "PYQ-S-2025-ACID-008",
  "PYQ-S-2025-ACID-009",
  "PYQ-S-2025-ACID-011",
  "PYQ-S-2025-ACID-012",
]);
