// GENERATED by lazytopper/scripts/generateBankChapters.ts (BANK-SPLIT-1 PR-2). DO NOT EDIT BY HAND.
// Regenerate from lazytopper/ with: pnpm run gen:bank-chapters
// src/data/bankChapters/bankChapters.guard.test.ts fails when this file disagrees with the aggregator.

// Chapter "areas-related-to-circles" (Maths): 219 served rows from 16 source arrays, 8 withheld.
// Each source is [spread position in RAW_CANONICAL_QUESTION_BANK, the array, is it an AI pack].

import { defineChapter } from "./defineChapter";
import { AREAS_RELATED_TO_CIRCLES_PACK1 } from "../questionBanks/class10/maths/areasRelatedToCircles.pack1";
import { ARC2_PACK2 } from "../questionBanks/class10/maths/areasRelatedToCircles.pack2";
import { ARC_NCERT } from "../questionBanks/class10/maths/areasRelatedToCircles.ncert";
import { ARC_EXEMPLAR } from "../questionBanks/class10/maths/areasRelatedToCircles.exemplar";
import { ARC_EXEMPLAR2 } from "../questionBanks/class10/maths/areasRelatedToCircles.exemplar2";
import { Z3_COMPETENCY_QUESTIONS } from "../questionBanks/class10/maths/competency.z3";
import { AREAS_RELATED_TO_CIRCLES_SQP } from "../questionBanks/class10/maths/areas-related-to-circles.sqp";
import { ARC_CBE } from "../questionBanks/class10/maths/areas-related-to-circles.cbe";
import { ARC_SP } from "../questionBanks/class10/maths/areas-related-to-circles.sp";
import { ARC_PREBOARD } from "../questionBanks/class10/maths/areas-related-to-circles.preboard";
import { AREAS_RELATED_TO_CIRCLES_APQ } from "../questionBanks/class10/maths/areas-related-to-circles.additionalPQ";
import { AREAS_RELATED_TO_CIRCLES_PYQ } from "../questionBanks/class10/maths/areas-related-to-circles.pyq";
import { AREAS_RELATED_TO_CIRCLES_PYQ_2026 } from "../questionBanks/class10/maths/areas-related-to-circles.pyq2026";
import { AREAS_RELATED_TO_CIRCLES_PYQ_2024 } from "../questionBanks/class10/maths/areas-related-to-circles.pyq2024";
import { AREAS_RELATED_TO_CIRCLES_PYQ_2025 } from "../questionBanks/class10/maths/areas-related-to-circles.pyq2025";
import { CURATED_INLINE_QUESTIONS } from "../questionBanks/class10/curatedInline";

export default defineChapter("areas-related-to-circles", [
  [20, AREAS_RELATED_TO_CIRCLES_PACK1, true],
  [21, ARC2_PACK2, true],
  [142, ARC_NCERT, false],
  [143, ARC_EXEMPLAR, false],
  [152, ARC_EXEMPLAR2, false],
  [153, Z3_COMPETENCY_QUESTIONS, false],
  [175, AREAS_RELATED_TO_CIRCLES_SQP, false],
  [199, ARC_CBE, false],
  [226, ARC_SP, false],
  [252, ARC_PREBOARD, false],
  [265, AREAS_RELATED_TO_CIRCLES_APQ, false],
  [317, AREAS_RELATED_TO_CIRCLES_PYQ, false],
  [330, AREAS_RELATED_TO_CIRCLES_PYQ_2026, false],
  [343, AREAS_RELATED_TO_CIRCLES_PYQ_2024, false],
  [355, AREAS_RELATED_TO_CIRCLES_PYQ_2025, false],
  [415, CURATED_INLINE_QUESTIONS, false],
], [
  "ARC-M15",
  "ARC-H08",
  "ARC2-007",
  "ARC2-017",
  "ARC2-021",
  "ARC2-037",
  "PYQ-M-ARC-002",
  "PYQ-M-ARC-003",
]);
