// GENERATED by lazytopper/scripts/generateBankChapters.ts (BANK-SPLIT-1 PR-2). DO NOT EDIT BY HAND.
// Regenerate from lazytopper/ with: pnpm run gen:bank-chapters
// src/data/bankChapters/bankChapters.guard.test.ts fails when this file disagrees with the aggregator.

// Chapter "areas-related-to-circles" (Maths): 291 served rows from 19 source arrays, 41 withheld.
// Each source is [spread position in RAW_CANONICAL_QUESTION_BANK, the array, is it an AI pack].

import { defineChapter } from "./defineChapter";
import { AREAS_RELATED_TO_CIRCLES_PACK1 } from "../questionBanks/class10/maths/areasRelatedToCircles.pack1";
import { ARC2_PACK2 } from "../questionBanks/class10/maths/areasRelatedToCircles.pack2";
import { ARC_NCERT } from "../questionBanks/class10/maths/areasRelatedToCircles.ncert";
import { ARC_EXEMPLAR } from "../questionBanks/class10/maths/areasRelatedToCircles.exemplar";
import { ARC_EXEMPLAR2 } from "../questionBanks/class10/maths/areasRelatedToCircles.exemplar2";
import { Z3_COMPETENCY_QUESTIONS } from "../questionBanks/class10/maths/competency.z3";
import { AREAS_RELATED_TO_CIRCLES_SQP } from "../questionBanks/class10/maths/areas-related-to-circles.sqp";
import { ARC_CBE } from "../questionBanks/class10/maths/areas-related-to-circles.cbe";
import { ARC_SP } from "../questionBanks/class10/maths/areas-related-to-circles.sp";
import { ARC_PREBOARD } from "../questionBanks/class10/maths/areas-related-to-circles.preboard";
import { AREAS_RELATED_TO_CIRCLES_APQ } from "../questionBanks/class10/maths/areas-related-to-circles.additionalPQ";
import { AREAS_RELATED_TO_CIRCLES_PYQ } from "../questionBanks/class10/maths/areas-related-to-circles.pyq";
import { CIRCLES_PYQ_2026 } from "../questionBanks/class10/maths/circles.pyq2026";
import { AREAS_RELATED_TO_CIRCLES_PYQ_2026 } from "../questionBanks/class10/maths/areas-related-to-circles.pyq2026";
import { AREAS_RELATED_TO_CIRCLES_PYQ_2024 } from "../questionBanks/class10/maths/areas-related-to-circles.pyq2024";
import { CIRCLES_PYQ_2025 } from "../questionBanks/class10/maths/circles.pyq2025";
import { AREAS_RELATED_TO_CIRCLES_PYQ_2025 } from "../questionBanks/class10/maths/areas-related-to-circles.pyq2025";
import { CURATED_INLINE_QUESTIONS } from "../questionBanks/class10/curatedInline";
import { AREAS_RELATED_TO_CIRCLES_CBQ_LT_GENERATED } from "../questionBanks/class10/maths/areas-related-to-circles.cbq.ltgen";

export default defineChapter("areas-related-to-circles", [
  [20, AREAS_RELATED_TO_CIRCLES_PACK1, true],
  [21, ARC2_PACK2, true],
  [142, ARC_NCERT, false],
  [143, ARC_EXEMPLAR, false],
  [152, ARC_EXEMPLAR2, false],
  [153, Z3_COMPETENCY_QUESTIONS, false],
  [175, AREAS_RELATED_TO_CIRCLES_SQP, false],
  [199, ARC_CBE, false],
  [226, ARC_SP, false],
  [252, ARC_PREBOARD, false],
  [265, AREAS_RELATED_TO_CIRCLES_APQ, false],
  [317, AREAS_RELATED_TO_CIRCLES_PYQ, false],
  [329, CIRCLES_PYQ_2026, false],
  [330, AREAS_RELATED_TO_CIRCLES_PYQ_2026, false],
  [343, AREAS_RELATED_TO_CIRCLES_PYQ_2024, false],
  [354, CIRCLES_PYQ_2025, false],
  [355, AREAS_RELATED_TO_CIRCLES_PYQ_2025, false],
  [415, CURATED_INLINE_QUESTIONS, false],
  [440, AREAS_RELATED_TO_CIRCLES_CBQ_LT_GENERATED, false],
], [
  "ARC-E10",
  "ARC-M06",
  "ARC-M14",
  "ARC-M15",
  "ARC-M18",
  "ARC-M20",
  "ARC-H01",
  "ARC-H03",
  "ARC-H08",
  "ARC-H12",
  "ARC-H15",
  "ARC2-007",
  "ARC2-008",
  "ARC2-017",
  "ARC2-018",
  "ARC2-021",
  "ARC2-022",
  "ARC2-030",
  "ARC2-035",
  "ARC2-037",
  "ARC2-038",
  "ARC2-041",
  "ARC-N-NCERT-11-LA-001",
  "ARC-N-NCERT-11-LA-002",
  "ARC-N-NCERT-11-CRE-001",
  "ARC-N-EXEM2-11-LA-001",
  "Z3-ARC-004",
  "SQP-M-ARC-003",
  "CBE-M-ARC-C-001",
  "CBE-M-ARC-C-002",
  "CBE-M-ARC-E-001",
  "APQ-M-ARC-001",
  "APQ-M-ARC-002",
  "APQ-M-ARC-003",
  "APQ-M-ARC-004",
  "APQ-M-ARC-006",
  "APQ-M-ARC-008",
  "APQ-M-ARC-010",
  "PYQ-M-ARC-002",
  "PYQ-M-ARC-003",
  "PYQ-M-ARC-005",
]);
