// GENERATED by lazytopper/scripts/generateBankChapters.ts (BANK-SPLIT-1 PR-2). DO NOT EDIT BY HAND.
// Regenerate from lazytopper/ with: pnpm run gen:bank-chapters
// src/data/bankChapters/bankChapters.guard.test.ts fails when this file disagrees with the aggregator.

// Chapter "arithmetic-progression" (Maths): 346 served rows from 20 source arrays, 4 withheld.
// Each source is [spread position in RAW_CANONICAL_QUESTION_BANK, the array, is it an AI pack].

import { defineChapter } from "./defineChapter";
import { ARITHMETIC_PROGRESSION_PACK1 } from "../questionBanks/class10/maths/arithmeticProgression.pack1";
import { AP2_PACK2 } from "../questionBanks/class10/maths/arithmeticProgression.pack2";
import { AP_NCERT } from "../questionBanks/class10/maths/arithmeticProgression.ncert";
import { AP_EXEMPLAR } from "../questionBanks/class10/maths/arithmeticProgression.exemplar";
import { AP_EXPAND_EXTRACT } from "../questionBanks/class10/maths/arithmeticProgression.expand.extract";
import { AP_EXPAND_LONG_D } from "../questionBanks/class10/maths/arithmeticProgression.expand.longD";
import { AP_EXPAND_CASE_E } from "../questionBanks/class10/maths/arithmeticProgression.expand.caseE";
import { AP_EXEMPLAR2 } from "../questionBanks/class10/maths/arithmeticProgression.exemplar2";
import { Z3_COMPETENCY_QUESTIONS } from "../questionBanks/class10/maths/competency.z3";
import { MATHS_CASE_BASED_QUESTIONS } from "../questionBanks/class10/maths/maths.caseBased";
import { ARITHMETIC_PROGRESSION_SQP } from "../questionBanks/class10/maths/arithmetic-progression.sqp";
import { AP_CBE } from "../questionBanks/class10/maths/arithmetic-progression.cbe";
import { AP_SP } from "../questionBanks/class10/maths/arithmetic-progression.sp";
import { AP_PREBOARD } from "../questionBanks/class10/maths/arithmetic-progression.preboard";
import { ARITHMETIC_PROGRESSION_APQ } from "../questionBanks/class10/maths/arithmetic-progression.additionalPQ";
import { ARITHMETIC_PROGRESSION_PYQ } from "../questionBanks/class10/maths/arithmetic-progression.pyq";
import { ARITHMETIC_PROGRESSION_PYQ_2026 } from "../questionBanks/class10/maths/arithmetic-progression.pyq2026";
import { ARITHMETIC_PROGRESSION_PYQ_2024 } from "../questionBanks/class10/maths/arithmetic-progression.pyq2024";
import { ARITHMETIC_PROGRESSION_PYQ_2025 } from "../questionBanks/class10/maths/arithmetic-progression.pyq2025";
import { CURATED_INLINE_QUESTIONS } from "../questionBanks/class10/curatedInline";

export default defineChapter("arithmetic-progression", [
  [14, ARITHMETIC_PROGRESSION_PACK1, true],
  [15, AP2_PACK2, true],
  [135, AP_NCERT, false],
  [136, AP_EXEMPLAR, false],
  [137, AP_EXPAND_EXTRACT, false],
  [138, AP_EXPAND_LONG_D, false],
  [139, AP_EXPAND_CASE_E, false],
  [148, AP_EXEMPLAR2, false],
  [153, Z3_COMPETENCY_QUESTIONS, false],
  [163, MATHS_CASE_BASED_QUESTIONS, false],
  [170, ARITHMETIC_PROGRESSION_SQP, false],
  [195, AP_CBE, false],
  [221, AP_SP, false],
  [247, AP_PREBOARD, false],
  [260, ARITHMETIC_PROGRESSION_APQ, false],
  [312, ARITHMETIC_PROGRESSION_PYQ, false],
  [325, ARITHMETIC_PROGRESSION_PYQ_2026, false],
  [338, ARITHMETIC_PROGRESSION_PYQ_2024, false],
  [351, ARITHMETIC_PROGRESSION_PYQ_2025, false],
  [415, CURATED_INLINE_QUESTIONS, false],
], [
  "AP-E12",
  "AP-N-EXEM2-5-MCQ-006",
  "PYQ-M-AP-003",
  "PYQ-M-AP-007",
]);
