// GENERATED by lazytopper/scripts/generateBankChapters.ts (BANK-SPLIT-1 PR-2). DO NOT EDIT BY HAND.
// Regenerate from lazytopper/ with: pnpm run gen:bank-chapters
// src/data/bankChapters/bankChapters.guard.test.ts fails when this file disagrees with the aggregator.

// The chapter list, each chapter's subject, and ONE literal import() per chapter, so the
// bundler emits a separate chunk for every chapter. Only the loader imports this file.

import type { BankChapter } from "./defineChapter";

export const BANK_CHAPTER_SLUGS = [
  "real-numbers",
  "polynomials",
  "pair-of-linear-equations",
  "quadratic-equations",
  "arithmetic-progression",
  "triangles",
  "coordinate-geometry",
  "trigonometry",
  "circles",
  "areas-related-to-circles",
  "surface-areas-and-volumes",
  "statistics",
  "probability",
  "chemical-reactions-and-equations",
  "acids-bases-and-salts",
  "metals-and-non-metals",
  "carbon-and-its-compounds",
  "light-reflection-and-refraction",
  "human-eye-and-colourful-world",
  "electricity",
  "magnetic-effects-of-electric-current",
  "life-processes",
  "control-and-coordination",
  "how-do-organisms-reproduce",
  "heredity",
  "our-environment",
] as const;

export type BankChapterSlug = (typeof BANK_CHAPTER_SLUGS)[number];

export const BANK_CHAPTER_SUBJECT: Readonly<Record<BankChapterSlug, "Maths" | "Science">> = {
  "real-numbers": "Maths",
  "polynomials": "Maths",
  "pair-of-linear-equations": "Maths",
  "quadratic-equations": "Maths",
  "arithmetic-progression": "Maths",
  "triangles": "Maths",
  "coordinate-geometry": "Maths",
  "trigonometry": "Maths",
  "circles": "Maths",
  "areas-related-to-circles": "Maths",
  "surface-areas-and-volumes": "Maths",
  "statistics": "Maths",
  "probability": "Maths",
  "chemical-reactions-and-equations": "Science",
  "acids-bases-and-salts": "Science",
  "metals-and-non-metals": "Science",
  "carbon-and-its-compounds": "Science",
  "light-reflection-and-refraction": "Science",
  "human-eye-and-colourful-world": "Science",
  "electricity": "Science",
  "magnetic-effects-of-electric-current": "Science",
  "life-processes": "Science",
  "control-and-coordination": "Science",
  "how-do-organisms-reproduce": "Science",
  "heredity": "Science",
  "our-environment": "Science",
};

export const BANK_CHAPTER_LOADERS: Readonly<Record<BankChapterSlug, () => Promise<{ default: BankChapter }>>> = {
  "real-numbers": () => import("./real-numbers"),
  "polynomials": () => import("./polynomials"),
  "pair-of-linear-equations": () => import("./pair-of-linear-equations"),
  "quadratic-equations": () => import("./quadratic-equations"),
  "arithmetic-progression": () => import("./arithmetic-progression"),
  "triangles": () => import("./triangles"),
  "coordinate-geometry": () => import("./coordinate-geometry"),
  "trigonometry": () => import("./trigonometry"),
  "circles": () => import("./circles"),
  "areas-related-to-circles": () => import("./areas-related-to-circles"),
  "surface-areas-and-volumes": () => import("./surface-areas-and-volumes"),
  "statistics": () => import("./statistics"),
  "probability": () => import("./probability"),
  "chemical-reactions-and-equations": () => import("./chemical-reactions-and-equations"),
  "acids-bases-and-salts": () => import("./acids-bases-and-salts"),
  "metals-and-non-metals": () => import("./metals-and-non-metals"),
  "carbon-and-its-compounds": () => import("./carbon-and-its-compounds"),
  "light-reflection-and-refraction": () => import("./light-reflection-and-refraction"),
  "human-eye-and-colourful-world": () => import("./human-eye-and-colourful-world"),
  "electricity": () => import("./electricity"),
  "magnetic-effects-of-electric-current": () => import("./magnetic-effects-of-electric-current"),
  "life-processes": () => import("./life-processes"),
  "control-and-coordination": () => import("./control-and-coordination"),
  "how-do-organisms-reproduce": () => import("./how-do-organisms-reproduce"),
  "heredity": () => import("./heredity"),
  "our-environment": () => import("./our-environment"),
};
