// GENERATED by lazytopper/scripts/generateBankChapters.ts (BANK-SPLIT-1 PR-2). DO NOT EDIT BY HAND.
// Regenerate from lazytopper/ with: pnpm run gen:bank-chapters
// src/data/bankChapters/bankChapters.guard.test.ts fails when this file disagrees with the aggregator.

// Chapter "chemical-reactions-and-equations" (Science): 526 served rows from 22 source arrays, 54 withheld.
// Each source is [spread position in RAW_CANONICAL_QUESTION_BANK, the array, is it an AI pack].

import { defineChapter } from "./defineChapter";
import { CHEMICAL_REACTIONS_PACK1 } from "../questionBanks/class10/science/chemicalReactions.pack1";
import { CR2_PACK2 } from "../questionBanks/class10/science/chemicalReactions.pack2";
import { MNM2_PACK2 } from "../questionBanks/class10/science/metalsNonMetals.pack2";
import { CHEM_REACTIONS_EXPAND_EXTRACT } from "../questionBanks/class10/science/chemicalReactions.expand.extract";
import { CHEM_REACTIONS_EXPAND_LONG_D } from "../questionBanks/class10/science/chemicalReactions.expand.longD";
import { CHEM_REACTIONS_EXPAND_CASE_E } from "../questionBanks/class10/science/chemicalReactions.expand.caseE";
import { CHEM_REACTIONS_NCERT } from "../questionBanks/class10/science/chemicalReactions.ncert";
import { CHEM_REACTIONS_EXEMPLAR } from "../questionBanks/class10/science/chemicalReactions.exemplar";
import { CHEMICAL_REACTIONS_SQP } from "../questionBanks/class10/science/chemical-reactions-and-equations.sqp";
import { CHEM_CBE } from "../questionBanks/class10/science/chemical-reactions-and-equations.cbe";
import { CHEM_SP } from "../questionBanks/class10/science/chemical-reactions-and-equations.sp";
import { CHEMICAL_REACTIONS_APQ } from "../questionBanks/class10/science/chemical-reactions-and-equations.additionalPQ";
import { CHEMICAL_REACTIONS_CHAPTERWISE } from "../questionBanks/class10/science/chemical-reactions-and-equations.chapterwise";
import { OUR_ENVIRONMENT_CHAPTERWISE } from "../questionBanks/class10/science/our-environment.chapterwise";
import { CHEMICAL_REACTIONS_PYQ } from "../questionBanks/class10/science/chemical-reactions-and-equations.pyq";
import { chemicalReactionsPYQ2026 } from "../questionBanks/class10/science/chemicalReactions.pyq2026";
import { chemicalReactionsPYQ2025 } from "../questionBanks/class10/science/chemicalReactions.pyq2025";
import { chemicalReactionsPYQ2024 } from "../questionBanks/class10/science/chemicalReactions.pyq2024";
import { CHEM_CFPQ } from "../questionBanks/class10/science/chemical-reactions-and-equations.cfpq";
import { CURATED_INLINE_QUESTIONS } from "../questionBanks/class10/curatedInline";
import { CHEM_REACTIONS_CBQ_B1_LT_GENERATED } from "../questionBanks/class10/science/chemical-reactions-and-equations.b1.cbq.ltgen";
import { CHEMICAL_REACTIONS_AND_EQUATIONS_C3_CBQ_LT_GENERATED } from "../questionBanks/class10/science/chemical-reactions-and-equations.c3.cbq.ltgen";

export default defineChapter("chemical-reactions-and-equations", [
  [28, CHEMICAL_REACTIONS_PACK1, true],
  [29, CR2_PACK2, true],
  [33, MNM2_PACK2, true],
  [65, CHEM_REACTIONS_EXPAND_EXTRACT, false],
  [66, CHEM_REACTIONS_EXPAND_LONG_D, false],
  [67, CHEM_REACTIONS_EXPAND_CASE_E, false],
  [74, CHEM_REACTIONS_NCERT, false],
  [75, CHEM_REACTIONS_EXEMPLAR, false],
  [179, CHEMICAL_REACTIONS_SQP, false],
  [204, CHEM_CBE, false],
  [230, CHEM_SP, false],
  [269, CHEMICAL_REACTIONS_APQ, false],
  [282, CHEMICAL_REACTIONS_CHAPTERWISE, false],
  [294, OUR_ENVIRONMENT_CHAPTERWISE, false],
  [295, CHEMICAL_REACTIONS_PYQ, false],
  [359, chemicalReactionsPYQ2026, false],
  [372, chemicalReactionsPYQ2025, false],
  [385, chemicalReactionsPYQ2024, false],
  [397, CHEM_CFPQ, false],
  [415, CURATED_INLINE_QUESTIONS, false],
  [441, CHEM_REACTIONS_CBQ_B1_LT_GENERATED, false],
  [453, CHEMICAL_REACTIONS_AND_EQUATIONS_C3_CBQ_LT_GENERATED, false],
], [
  "CR-E10",
  "CR-E13",
  "CR-M10",
  "CR-H09",
  "CR2-010",
  "CR2-014",
  "CR2-021",
  "CR2-035",
  "CR2-046",
  "CR2-054",
  "BX-CHEM-EX-A-012",
  "BX-CHEM-D-012",
  "BX-CHEM-D-013",
  "BX-CHEM-D-034",
  "BX-CHEM-E-011",
  "BX-CHEM-E-012",
  "BX-CHEM-E-013",
  "BX-CHEM-E-014",
  "BX-CHEM-E-015",
  "CHEM-NCERT-1-VSA-008",
  "CHEM-NCERT-1-SA-015",
  "CHEM-EXMPLR-1-MCQ-014",
  "CHEM-EXMPLR-1-MCQ-018",
  "CBE-S-CHEM-C-003",
  "SCQ-S-CHEM-026",
  "SCQ-S-CHEM-039",
  "PYQ-S-CHEM-002",
  "PYQ-S-CHEM-006",
  "PYQ-S-CHEM-013",
  "PYQ-S-CHEM-016",
  "PYQ-S-2026-CHEMRXN-009",
  "PYQ-S-2026-CHEMRXN-010",
  "PYQ-S-2026-CHEMRXN-013",
  "PYQ-S-2026-CHEMRXN-015",
  "PYQ-S-2026-CHEMRXN-017",
  "PYQ-S-2026-CHEMRXN-022",
  "PYQ-S-2025-CHEMRXN-008",
  "PYQ-S-2025-CHEMRXN-010",
  "PYQ-S-2025-CHEMRXN-014",
  "PYQ-S-2025-CHEMRXN-015",
  "PYQ-S-2025-CHEMRXN-016",
  "PYQ-S-2025-CHEMRXN-017",
  "PYQ-S-2025-CHEMRXN-018",
  "PYQ-S-2025-CHEMRXN-019",
  "PYQ-S-2025-CHEMRXN-022",
  "PYQ-S-2025-CHEMRXN-023",
  "PYQ-S-2024-CHEMRXN-006",
  "PYQ-S-2024-CHEMRXN-007",
  "PYQ-S-2024-CHEMRXN-010",
  "PYQ-S-2024-CHEMRXN-012",
  "PYQ-S-2024-CHEMRXN-014",
  "PYQ-S-2024-CHEMRXN-015",
  "PYQ-S-2024-CHEMRXN-016",
  "PYQ-S-2024-CHEMRXN-017",
]);
