// GENERATED by lazytopper/scripts/generateBankChapters.ts (BANK-SPLIT-1 PR-2). DO NOT EDIT BY HAND.
// Regenerate from lazytopper/ with: pnpm run gen:bank-chapters
// src/data/bankChapters/bankChapters.guard.test.ts fails when this file disagrees with the aggregator.

// Chapter "control-and-coordination" (Science): 290 served rows from 16 source arrays, 3 withheld.
// Each source is [spread position in RAW_CANONICAL_QUESTION_BANK, the array, is it an AI pack].

import { defineChapter } from "./defineChapter";
import { CONTROL_AND_COORDINATION_PACK1 } from "../questionBanks/class10/science/controlAndCoordination.pack1";
import { CNC2_PACK2 } from "../questionBanks/class10/science/controlAndCoordination.pack2";
import { CONTROL_COORDINATION_NCERT } from "../questionBanks/class10/science/controlAndCoordination.ncert";
import { CONTROL_COORDINATION_EXEMPLAR } from "../questionBanks/class10/science/controlAndCoordination.exemplar";
import { CONTROL_COORDINATION_SQP } from "../questionBanks/class10/science/control-and-coordination.sqp";
import { CTRL_CBE } from "../questionBanks/class10/science/control-and-coordination.cbe";
import { CTRL_SP } from "../questionBanks/class10/science/control-and-coordination.sp";
import { CONTROL_COORDINATION_APQ } from "../questionBanks/class10/science/control-and-coordination.additionalPQ";
import { CONTROL_COORDINATION_CHAPTERWISE } from "../questionBanks/class10/science/control-and-coordination.chapterwise";
import { CONTROL_COORDINATION_PYQ } from "../questionBanks/class10/science/control-and-coordination.pyq";
import { controlCoordinationPYQ2026 } from "../questionBanks/class10/science/controlCoordination.pyq2026";
import { controlCoordinationPYQ2025 } from "../questionBanks/class10/science/controlCoordination.pyq2025";
import { controlCoordinationPYQ2024 } from "../questionBanks/class10/science/controlCoordination.pyq2024";
import { CTRL_CFPQ } from "../questionBanks/class10/science/control-and-coordination.cfpq";
import { CURATED_INLINE_QUESTIONS } from "../questionBanks/class10/curatedInline";
import { CONTROL_COORDINATION_CBQ_LT_GENERATED } from "../questionBanks/class10/science/control-and-coordination.cbq.ltgen";

export default defineChapter("control-and-coordination", [
  [38, CONTROL_AND_COORDINATION_PACK1, true],
  [39, CNC2_PACK2, true],
  [93, CONTROL_COORDINATION_NCERT, false],
  [94, CONTROL_COORDINATION_EXEMPLAR, false],
  [184, CONTROL_COORDINATION_SQP, false],
  [209, CTRL_CBE, false],
  [235, CTRL_SP, false],
  [274, CONTROL_COORDINATION_APQ, false],
  [287, CONTROL_COORDINATION_CHAPTERWISE, false],
  [300, CONTROL_COORDINATION_PYQ, false],
  [364, controlCoordinationPYQ2026, false],
  [377, controlCoordinationPYQ2025, false],
  [390, controlCoordinationPYQ2024, false],
  [402, CTRL_CFPQ, false],
  [415, CURATED_INLINE_QUESTIONS, false],
  [422, CONTROL_COORDINATION_CBQ_LT_GENERATED, false],
], [
  "CTRL-EXMPLR-6-MCQ-025",
  "PYQ-S-CTRL-003",
  "PYQ-S-2025-CTRL-008",
]);
