// GENERATED by lazytopper/scripts/generateBankChapters.ts (BANK-SPLIT-1 PR-2). DO NOT EDIT BY HAND.
// Regenerate from lazytopper/ with: pnpm run gen:bank-chapters
// src/data/bankChapters/bankChapters.guard.test.ts fails when this file disagrees with the aggregator.

// Chapter "coordinate-geometry" (Maths): 364 served rows from 23 source arrays, 44 withheld.
// Each source is [spread position in RAW_CANONICAL_QUESTION_BANK, the array, is it an AI pack].

import { defineChapter } from "./defineChapter";
import { COORDINATE_GEOMETRY_PACK1 } from "../questionBanks/class10/maths/coordinateGeometry.pack1";
import { CG2_PACK2 } from "../questionBanks/class10/maths/coordinateGeometry.pack2";
import { CG_NCERT } from "../questionBanks/class10/maths/coordinateGeometry.ncert";
import { COORD_EXPAND_EXTRACT } from "../questionBanks/class10/maths/coordinateGeometry.expand.extract";
import { COORD_EXPAND_LONG_D } from "../questionBanks/class10/maths/coordinateGeometry.expand.longD";
import { COORD_EXPAND_CASE_E } from "../questionBanks/class10/maths/coordinateGeometry.expand.caseE";
import { CG_EXEMPLAR } from "../questionBanks/class10/maths/coordinateGeometry.exemplar";
import { CG_EXEMPLAR2 } from "../questionBanks/class10/maths/coordinateGeometry.exemplar2";
import { Z3_COMPETENCY_QUESTIONS } from "../questionBanks/class10/maths/competency.z3";
import { COORDINATE_GEOMETRY_SQP } from "../questionBanks/class10/maths/coordinate-geometry.sqp";
import { CG_CBE } from "../questionBanks/class10/maths/coordinate-geometry.cbe";
import { CG_SP } from "../questionBanks/class10/maths/coordinate-geometry.sp";
import { CG_PREBOARD } from "../questionBanks/class10/maths/coordinate-geometry.preboard";
import { COORDINATE_GEOMETRY_APQ } from "../questionBanks/class10/maths/coordinate-geometry.additionalPQ";
import { COORDINATE_GEOMETRY_PYQ } from "../questionBanks/class10/maths/coordinate-geometry.pyq";
import { CIRCLES_PYQ } from "../questionBanks/class10/maths/circles.pyq";
import { TRIANGLES_PYQ_2026 } from "../questionBanks/class10/maths/triangles.pyq2026";
import { COORDINATE_GEOMETRY_PYQ_2026 } from "../questionBanks/class10/maths/coordinate-geometry.pyq2026";
import { TRIANGLES_PYQ_2024 } from "../questionBanks/class10/maths/triangles.pyq2024";
import { COORDINATE_GEOMETRY_PYQ_2024 } from "../questionBanks/class10/maths/coordinate-geometry.pyq2024";
import { COORDINATE_GEOMETRY_PYQ_2025 } from "../questionBanks/class10/maths/coordinate-geometry.pyq2025";
import { CURATED_INLINE_QUESTIONS } from "../questionBanks/class10/curatedInline";
import { COORDINATE_GEOMETRY_CBQ_LT_GENERATED } from "../questionBanks/class10/maths/coordinate-geometry.cbq.ltgen";

export default defineChapter("coordinate-geometry", [
  [16, COORDINATE_GEOMETRY_PACK1, true],
  [17, CG2_PACK2, true],
  [124, CG_NCERT, false],
  [125, COORD_EXPAND_EXTRACT, false],
  [126, COORD_EXPAND_LONG_D, false],
  [127, COORD_EXPAND_CASE_E, false],
  [128, CG_EXEMPLAR, false],
  [151, CG_EXEMPLAR2, false],
  [153, Z3_COMPETENCY_QUESTIONS, false],
  [172, COORDINATE_GEOMETRY_SQP, false],
  [198, CG_CBE, false],
  [223, CG_SP, false],
  [249, CG_PREBOARD, false],
  [262, COORDINATE_GEOMETRY_APQ, false],
  [314, COORDINATE_GEOMETRY_PYQ, false],
  [316, CIRCLES_PYQ, false],
  [326, TRIANGLES_PYQ_2026, false],
  [327, COORDINATE_GEOMETRY_PYQ_2026, false],
  [339, TRIANGLES_PYQ_2024, false],
  [340, COORDINATE_GEOMETRY_PYQ_2024, false],
  [352, COORDINATE_GEOMETRY_PYQ_2025, false],
  [415, CURATED_INLINE_QUESTIONS, false],
  [454, COORDINATE_GEOMETRY_CBQ_LT_GENERATED, false],
], [
  "CG-E15",
  "CG-E16",
  "CG-E19",
  "CG-M01",
  "CG-M11",
  "CG-H05",
  "CG-H11",
  "CG-L01",
  "CG-N05",
  "CG-ND02",
  "CG2-044",
  "CG2-046",
  "CG2-048",
  "CG2-052",
  "CG2-057",
  "CG2-058",
  "CG-N-NCERT-7-EX-011",
  "CG-N-NCERT-7-EX-026",
  "CG-N-NCERT-7-EX-027",
  "CG-N-NCERT-7-EX-028",
  "CG-N-NCERT-7-EX-029",
  "CG-N-NCERT-7-EX-030",
  "BX-COORD-D-007",
  "BX-COORD-E-017",
  "BX-COORD-E-027",
  "BX-COORD-E-036",
  "CG-N-EXMPLR-7-EX-006",
  "CG-N-EXMPLR-7-EX-010",
  "CG-N-EXMPLR-7-EX-012",
  "CG-N-EXMPLR-7-EX-013",
  "CG-N-EXMPLR-7-EX-018",
  "CG-N-EXMPLR-7-EX-019",
  "CG-N-EXMPLR-7-EX-021",
  "CG-N-EXMPLR-7-EX-025",
  "CG-N-EXEM2-7-LA-001",
  "SP-M-2022-CG-A-001",
  "SP-M-2022-CG-A-002",
  "APQ-M-CG-005",
  "APQ-M-CG-006",
  "PYQ-M-CG-002",
  "PYQ-M-2026-TRI-004",
  "PYQ-M-2024-CG-006",
  "PYQ-M-2024-CG-007",
  "PYQ-M-2025-CG-003",
]);
