// GENERATED by lazytopper/scripts/generateBankChapters.ts (BANK-SPLIT-1 PR-2). DO NOT EDIT BY HAND.
// Regenerate from lazytopper/ with: pnpm run gen:bank-chapters
// src/data/bankChapters/bankChapters.guard.test.ts fails when this file disagrees with the aggregator.

// Chapter "electricity" (Science): 396 served rows from 19 source arrays, 19 withheld.
// Each source is [spread position in RAW_CANONICAL_QUESTION_BANK, the array, is it an AI pack].

import { defineChapter } from "./defineChapter";
import { ELECTRICITY_PACK1 } from "../questionBanks/class10/science/electricity.pack1";
import { EL2_PACK2 } from "../questionBanks/class10/science/electricity.pack2";
import { ELEC_NCERT } from "../questionBanks/class10/science/electricity.ncert";
import { ELEC_EXEMPLAR } from "../questionBanks/class10/science/electricity.exemplar";
import { SCIENCE_AR_QUESTIONS } from "../questionBanks/class10/science/science.assertionReasoning";
import { SCIENCE_CASE_BASED_QUESTIONS } from "../questionBanks/class10/science/science.caseBased";
import { ELECTRICITY_SQP } from "../questionBanks/class10/science/electricity.sqp";
import { ELEC_CBE } from "../questionBanks/class10/science/electricity.cbe";
import { ELEC_SP } from "../questionBanks/class10/science/electricity.sp";
import { ELECTRICITY_APQ } from "../questionBanks/class10/science/electricity.additionalPQ";
import { ELECTRICITY_CHAPTERWISE } from "../questionBanks/class10/science/electricity.chapterwise";
import { ELECTRICITY_PYQ } from "../questionBanks/class10/science/electricity.pyq";
import { electricityPYQ2026 } from "../questionBanks/class10/science/electricity.pyq2026";
import { metalsNonMetalsPYQ2025 } from "../questionBanks/class10/science/metalsNonMetals.pyq2025";
import { electricityPYQ2025 } from "../questionBanks/class10/science/electricity.pyq2025";
import { ELEC_CFPQ } from "../questionBanks/class10/science/electricity.cfpq";
import { electricityPYQ2024 } from "../questionBanks/class10/science/electricity.pyq2024";
import { CURATED_INLINE_QUESTIONS } from "../questionBanks/class10/curatedInline";
import { ELECTRICITY_CBQ_B1_LT_GENERATED } from "../questionBanks/class10/science/electricity.b1.cbq.ltgen";

export default defineChapter("electricity", [
  [48, ELECTRICITY_PACK1, true],
  [49, EL2_PACK2, true],
  [103, ELEC_NCERT, false],
  [104, ELEC_EXEMPLAR, false],
  [162, SCIENCE_AR_QUESTIONS, false],
  [164, SCIENCE_CASE_BASED_QUESTIONS, false],
  [189, ELECTRICITY_SQP, false],
  [214, ELEC_CBE, false],
  [240, ELEC_SP, false],
  [279, ELECTRICITY_APQ, false],
  [292, ELECTRICITY_CHAPTERWISE, false],
  [305, ELECTRICITY_PYQ, false],
  [369, electricityPYQ2026, false],
  [374, metalsNonMetalsPYQ2025, false],
  [382, electricityPYQ2025, false],
  [405, ELEC_CFPQ, false],
  [412, electricityPYQ2024, false],
  [415, CURATED_INLINE_QUESTIONS, false],
  [432, ELECTRICITY_CBQ_B1_LT_GENERATED, false],
], [
  "EL2-002",
  "CBE-S-ELEC-A-003",
  "APQ-S-ELEC-001",
  "SCO-S-ELEC-003",
  "SCO-S-ELEC-011",
  "SCO-S-ELEC-014",
  "SCQ-S-ELEC-034",
  "SCQ-S-ELEC-036",
  "SCQ-S-ELEC-037",
  "SCQ-S-ELEC-038",
  "PYQ-S-ELEC-001",
  "PYQ-S-ELEC-003",
  "PYQ-S-ELEC-004",
  "PYQ-S-ELEC-005",
  "PYQ-S-ELEC-007",
  "PYQ-S-2026-ELEC-013",
  "PYQ-S-2025-ELEC-008",
  "PYQ-S-2025-ELEC-009",
  "PYQ-S-2024-ELEC-001",
]);
