// GENERATED by lazytopper/scripts/generateBankChapters.ts (BANK-SPLIT-1 PR-2). DO NOT EDIT BY HAND.
// Regenerate from lazytopper/ with: pnpm run gen:bank-chapters
// src/data/bankChapters/bankChapters.guard.test.ts fails when this file disagrees with the aggregator.

// Chapter "heredity" (Science): 237 served rows from 18 source arrays, 6 withheld.
// Each source is [spread position in RAW_CANONICAL_QUESTION_BANK, the array, is it an AI pack].

import { defineChapter } from "./defineChapter";
import { HEREDITY_PACK1 } from "../questionBanks/class10/science/heredity.pack1";
import { HE2_PACK2 } from "../questionBanks/class10/science/heredity.pack2";
import { HEREDITY_EXPAND_EXTRACT } from "../questionBanks/class10/science/heredity.expand.extract";
import { HEREDITY_EXPAND_LONG_D } from "../questionBanks/class10/science/heredity.expand.longD";
import { HEREDITY_EXPAND_CASE_E1 } from "../questionBanks/class10/science/heredity.expand.caseE1";
import { HEREDITY_EXPAND_CASE_E2 } from "../questionBanks/class10/science/heredity.expand.caseE2";
import { HEREDITY_NCERT } from "../questionBanks/class10/science/heredity.ncert";
import { HEREDITY_EXEMPLAR } from "../questionBanks/class10/science/heredity.exemplar";
import { HEREDITY_SQP } from "../questionBanks/class10/science/heredity.sqp";
import { HERD_CBE } from "../questionBanks/class10/science/heredity.cbe";
import { HERD_SP } from "../questionBanks/class10/science/heredity.sp";
import { HEREDITY_APQ } from "../questionBanks/class10/science/heredity.additionalPQ";
import { HEREDITY_CHAPTERWISE } from "../questionBanks/class10/science/heredity.chapterwise";
import { HEREDITY_PYQ } from "../questionBanks/class10/science/heredity.pyq";
import { heredityPYQ2026 } from "../questionBanks/class10/science/heredity.pyq2026";
import { heredityPYQ2025 } from "../questionBanks/class10/science/heredity.pyq2025";
import { heredityPYQ2024 } from "../questionBanks/class10/science/heredity.pyq2024";
import { CURATED_INLINE_QUESTIONS } from "../questionBanks/class10/curatedInline";

export default defineChapter("heredity", [
  [42, HEREDITY_PACK1, true],
  [43, HE2_PACK2, true],
  [61, HEREDITY_EXPAND_EXTRACT, false],
  [62, HEREDITY_EXPAND_LONG_D, true],
  [63, HEREDITY_EXPAND_CASE_E1, true],
  [64, HEREDITY_EXPAND_CASE_E2, true],
  [97, HEREDITY_NCERT, false],
  [98, HEREDITY_EXEMPLAR, false],
  [186, HEREDITY_SQP, false],
  [211, HERD_CBE, false],
  [237, HERD_SP, false],
  [276, HEREDITY_APQ, false],
  [289, HEREDITY_CHAPTERWISE, false],
  [302, HEREDITY_PYQ, false],
  [366, heredityPYQ2026, false],
  [379, heredityPYQ2025, false],
  [392, heredityPYQ2024, false],
  [415, CURATED_INLINE_QUESTIONS, false],
], [
  "SCO-S-HERED-005",
  "PYQ-S-2026-HERED-006",
  "PYQ-S-2026-HERED-007",
  "PYQ-S-2026-HERED-011",
  "PYQ-S-2025-HERED-004",
  "PYQ-S-2025-HERED-008",
]);
