// GENERATED by lazytopper/scripts/generateBankChapters.ts (BANK-SPLIT-1 PR-2). DO NOT EDIT BY HAND.
// Regenerate from lazytopper/ with: pnpm run gen:bank-chapters
// src/data/bankChapters/bankChapters.guard.test.ts fails when this file disagrees with the aggregator.

// Chapter "how-do-organisms-reproduce" (Science): 527 served rows from 21 source arrays, 5 withheld.
// Each source is [spread position in RAW_CANONICAL_QUESTION_BANK, the array, is it an AI pack].

import { defineChapter } from "./defineChapter";
import { REPRODUCTION_PACK1 } from "../questionBanks/class10/science/reproduction.pack1";
import { REP2_PACK2 } from "../questionBanks/class10/science/reproduction.pack2";
import { REPRODUCE_EXPAND_EXTRACT } from "../questionBanks/class10/science/how-do-organisms-reproduce.expand.extract";
import { REPRODUCE_EXPAND_LONG_D } from "../questionBanks/class10/science/how-do-organisms-reproduce.expand.longD";
import { REPRODUCE_EXPAND_CASE_E1 } from "../questionBanks/class10/science/how-do-organisms-reproduce.expand.caseE1";
import { REPRODUCE_EXPAND_CASE_E2 } from "../questionBanks/class10/science/how-do-organisms-reproduce.expand.caseE2";
import { REPRODUCTION_NCERT } from "../questionBanks/class10/science/reproduction.ncert";
import { REPRODUCTION_EXEMPLAR } from "../questionBanks/class10/science/reproduction.exemplar";
import { HOW_DO_ORGANISMS_REPRODUCE_SQP } from "../questionBanks/class10/science/how-do-organisms-reproduce.sqp";
import { REPR_CBE } from "../questionBanks/class10/science/how-do-organisms-reproduce.cbe";
import { REPR_SP } from "../questionBanks/class10/science/how-do-organisms-reproduce.sp";
import { HOW_DO_ORGANISMS_REPRODUCE_APQ } from "../questionBanks/class10/science/how-do-organisms-reproduce.additionalPQ";
import { HOW_DO_ORGANISMS_REPRODUCE_CHAPTERWISE } from "../questionBanks/class10/science/how-do-organisms-reproduce.chapterwise";
import { HOW_DO_ORGANISMS_REPRODUCE_PYQ } from "../questionBanks/class10/science/how-do-organisms-reproduce.pyq";
import { howOrganismsReproducePYQ2026 } from "../questionBanks/class10/science/howOrganismsReproduce.pyq2026";
import { howOrganismsReproducePYQ2025 } from "../questionBanks/class10/science/howOrganismsReproduce.pyq2025";
import { howOrganismsReproducePYQ2024 } from "../questionBanks/class10/science/howOrganismsReproduce.pyq2024";
import { REPR_CFPQ } from "../questionBanks/class10/science/how-do-organisms-reproduce.cfpq";
import { CURATED_INLINE_QUESTIONS } from "../questionBanks/class10/curatedInline";
import { REPRODUCTION_CBQ_LT_GENERATED } from "../questionBanks/class10/science/how-do-organisms-reproduce.cbq.ltgen";
import { REPRODUCTION_CBQ_B1_LT_GENERATED } from "../questionBanks/class10/science/how-do-organisms-reproduce.b1.cbq.ltgen";

export default defineChapter("how-do-organisms-reproduce", [
  [40, REPRODUCTION_PACK1, true],
  [41, REP2_PACK2, true],
  [57, REPRODUCE_EXPAND_EXTRACT, false],
  [58, REPRODUCE_EXPAND_LONG_D, true],
  [59, REPRODUCE_EXPAND_CASE_E1, true],
  [60, REPRODUCE_EXPAND_CASE_E2, true],
  [95, REPRODUCTION_NCERT, false],
  [96, REPRODUCTION_EXEMPLAR, false],
  [185, HOW_DO_ORGANISMS_REPRODUCE_SQP, false],
  [210, REPR_CBE, false],
  [236, REPR_SP, false],
  [275, HOW_DO_ORGANISMS_REPRODUCE_APQ, false],
  [288, HOW_DO_ORGANISMS_REPRODUCE_CHAPTERWISE, false],
  [301, HOW_DO_ORGANISMS_REPRODUCE_PYQ, false],
  [365, howOrganismsReproducePYQ2026, false],
  [378, howOrganismsReproducePYQ2025, false],
  [391, howOrganismsReproducePYQ2024, false],
  [403, REPR_CFPQ, false],
  [415, CURATED_INLINE_QUESTIONS, false],
  [421, REPRODUCTION_CBQ_LT_GENERATED, false],
  [443, REPRODUCTION_CBQ_B1_LT_GENERATED, false],
], [
  "REP-H10",
  "REP2-022",
  "PYQ-S-2025-REPR-006",
  "PYQ-S-2025-REPR-009",
  "PYQ-S-2025-REPR-010",
]);
