// GENERATED by lazytopper/scripts/generateBankChapters.ts (BANK-SPLIT-1 PR-2). DO NOT EDIT BY HAND.
// Regenerate from lazytopper/ with: pnpm run gen:bank-chapters
// src/data/bankChapters/bankChapters.guard.test.ts fails when this file disagrees with the aggregator.

// Chapter "human-eye-and-colourful-world" (Science): 309 served rows from 23 source arrays, 27 withheld.
// Each source is [spread position in RAW_CANONICAL_QUESTION_BANK, the array, is it an AI pack].

import { defineChapter } from "./defineChapter";
import { HUMAN_EYE_PACK1 } from "../questionBanks/class10/science/humanEyeAndColourfulWorld.pack1";
import { HEC2_PACK2 } from "../questionBanks/class10/science/humanEyeAndColourfulWorld.pack2";
import { EYE_NCERT } from "../questionBanks/class10/science/humanEye.ncert";
import { EYE_EXEMPLAR } from "../questionBanks/class10/science/humanEye.exemplar";
import { HUMAN_EYE_SQP } from "../questionBanks/class10/science/human-eye-and-colourful-world.sqp";
import { HEYE_CBE } from "../questionBanks/class10/science/human-eye-and-colourful-world.cbe";
import { HEYE_SP } from "../questionBanks/class10/science/human-eye-and-colourful-world.sp";
import { HUMAN_EYE_APQ } from "../questionBanks/class10/science/human-eye-and-colourful-world.additionalPQ";
import { LIGHT_REFLECTION_CHAPTERWISE } from "../questionBanks/class10/science/light-reflection-and-refraction.chapterwise";
import { HUMAN_EYE_CHAPTERWISE } from "../questionBanks/class10/science/human-eye-and-colourful-world.chapterwise";
import { LIGHT_REFLECTION_PYQ } from "../questionBanks/class10/science/light-reflection-and-refraction.pyq";
import { HUMAN_EYE_PYQ } from "../questionBanks/class10/science/human-eye-and-colourful-world.pyq";
import { lightReflectionPYQ2026 } from "../questionBanks/class10/science/lightReflection.pyq2026";
import { humanEyePYQ2026 } from "../questionBanks/class10/science/humanEye.pyq2026";
import { lightReflectionPYQ2025 } from "../questionBanks/class10/science/lightReflection.pyq2025";
import { humanEyePYQ2025 } from "../questionBanks/class10/science/humanEye.pyq2025";
import { lightReflectionPYQ2024 } from "../questionBanks/class10/science/lightReflection.pyq2024";
import { LGHT_FND_BEYOND_BOARD } from "../questionBanks/class10/science/light-reflection-and-refraction.fnd";
import { EYE_CFPQ } from "../questionBanks/class10/science/human-eye-and-colourful-world.cfpq";
import { humanEyePYQ2024 } from "../questionBanks/class10/science/humanEye.pyq2024";
import { CURATED_INLINE_QUESTIONS } from "../questionBanks/class10/curatedInline";
import { HUMAN_EYE_CBQ_LT_GENERATED } from "../questionBanks/class10/science/human-eye-and-colourful-world.cbq.ltgen";
import { HUMAN_EYE_CBQ_B1_LT_GENERATED } from "../questionBanks/class10/science/human-eye-and-colourful-world.b1.cbq.ltgen";

export default defineChapter("human-eye-and-colourful-world", [
  [46, HUMAN_EYE_PACK1, true],
  [47, HEC2_PACK2, true],
  [101, EYE_NCERT, false],
  [102, EYE_EXEMPLAR, false],
  [188, HUMAN_EYE_SQP, false],
  [213, HEYE_CBE, false],
  [239, HEYE_SP, false],
  [278, HUMAN_EYE_APQ, false],
  [290, LIGHT_REFLECTION_CHAPTERWISE, false],
  [291, HUMAN_EYE_CHAPTERWISE, false],
  [303, LIGHT_REFLECTION_PYQ, false],
  [304, HUMAN_EYE_PYQ, false],
  [367, lightReflectionPYQ2026, false],
  [368, humanEyePYQ2026, false],
  [380, lightReflectionPYQ2025, false],
  [381, humanEyePYQ2025, false],
  [393, lightReflectionPYQ2024, false],
  [395, LGHT_FND_BEYOND_BOARD, false],
  [404, EYE_CFPQ, false],
  [411, humanEyePYQ2024, false],
  [415, CURATED_INLINE_QUESTIONS, false],
  [426, HUMAN_EYE_CBQ_LT_GENERATED, false],
  [443, HUMAN_EYE_CBQ_B1_LT_GENERATED, false],
], [
  "HEY-E10",
  "HEY-M08",
  "HEY-H03",
  "HEY-H07",
  "HEC2-013",
  "HEC2-021",
  "HEC2-023",
  "HEC2-041",
  "HEC2-046",
  "HEC2-048",
  "EYE-EXMPLR-10-MCQ-010",
  "EYE-EXMPLR-10-SA-010",
  "EYE-EXMPLR-10-LA-004",
  "SCO-S-EYE-001",
  "SCO-S-EYE-002",
  "SCO-S-EYE-006",
  "SCO-S-EYE-019",
  "SCQ-S-EYE-034",
  "SCQ-S-EYE-038",
  "PYQ-S-EYE-002",
  "PYQ-S-EYE-005",
  "PYQ-S-2026-EYE-003",
  "PYQ-S-2025-EYE-002",
  "LTG-S-EYE-202",
  "LTG-S-EYE-207",
  "LTG-S-EYE-212",
  "LTG-S-EYE-215",
]);
