// GENERATED by lazytopper/scripts/generateBankChapters.ts (BANK-SPLIT-1 PR-2). DO NOT EDIT BY HAND.
// Regenerate from lazytopper/ with: pnpm run gen:bank-chapters
// src/data/bankChapters/bankChapters.guard.test.ts fails when this file disagrees with the aggregator.

// Chapter "life-processes" (Science): 578 served rows from 22 source arrays, 26 withheld.
// Each source is [spread position in RAW_CANONICAL_QUESTION_BANK, the array, is it an AI pack].

import { defineChapter } from "./defineChapter";
import { LIFE_PROCESSES_PACK1 } from "../questionBanks/class10/science/lifeProcesses.pack1";
import { LP2_PACK2 } from "../questionBanks/class10/science/lifeProcesses.pack2";
import { LIFE_PROCESSES_NCERT } from "../questionBanks/class10/science/lifeProcesses.ncert";
import { LIFE_PROCESSES_EXEMPLAR } from "../questionBanks/class10/science/lifeProcesses.exemplar";
import { LP_EXTRACT } from "../questionBanks/class10/science/lifeProcesses.extract";
import { LP_SCARCE_D } from "../questionBanks/class10/science/lifeProcesses.scarceD";
import { LP_SCARCE_E } from "../questionBanks/class10/science/lifeProcesses.scarceE";
import { SCIENCE_AR_QUESTIONS } from "../questionBanks/class10/science/science.assertionReasoning";
import { SCIENCE_CASE_BASED_QUESTIONS } from "../questionBanks/class10/science/science.caseBased";
import { LIFE_PROCESSES_SQP } from "../questionBanks/class10/science/life-processes.sqp";
import { LIFE_CBE } from "../questionBanks/class10/science/life-processes.cbe";
import { LIFE_SP } from "../questionBanks/class10/science/life-processes.sp";
import { LIFE_PROCESSES_APQ } from "../questionBanks/class10/science/life-processes.additionalPQ";
import { LIFE_PROCESSES_CHAPTERWISE } from "../questionBanks/class10/science/life-processes.chapterwise";
import { LIFE_PROCESSES_PYQ } from "../questionBanks/class10/science/life-processes.pyq";
import { chemicalReactionsPYQ2026 } from "../questionBanks/class10/science/chemicalReactions.pyq2026";
import { lifeProcessesPYQ2026 } from "../questionBanks/class10/science/lifeProcesses.pyq2026";
import { lifeProcessesPYQ2025 } from "../questionBanks/class10/science/lifeProcesses.pyq2025";
import { lifeProcessesPYQ2024 } from "../questionBanks/class10/science/lifeProcesses.pyq2024";
import { LIFE_CFPQ } from "../questionBanks/class10/science/life-processes.cfpq";
import { CURATED_INLINE_QUESTIONS } from "../questionBanks/class10/curatedInline";
import { LIFE_PROCESSES_CBQ_B1_LT_GENERATED } from "../questionBanks/class10/science/life-processes.b1.cbq.ltgen";

export default defineChapter("life-processes", [
  [36, LIFE_PROCESSES_PACK1, true],
  [37, LP2_PACK2, true],
  [88, LIFE_PROCESSES_NCERT, false],
  [89, LIFE_PROCESSES_EXEMPLAR, false],
  [90, LP_EXTRACT, false],
  [91, LP_SCARCE_D, true],
  [92, LP_SCARCE_E, true],
  [162, SCIENCE_AR_QUESTIONS, false],
  [164, SCIENCE_CASE_BASED_QUESTIONS, false],
  [183, LIFE_PROCESSES_SQP, false],
  [208, LIFE_CBE, false],
  [234, LIFE_SP, false],
  [273, LIFE_PROCESSES_APQ, false],
  [286, LIFE_PROCESSES_CHAPTERWISE, false],
  [299, LIFE_PROCESSES_PYQ, false],
  [359, chemicalReactionsPYQ2026, false],
  [363, lifeProcessesPYQ2026, false],
  [376, lifeProcessesPYQ2025, false],
  [389, lifeProcessesPYQ2024, false],
  [401, LIFE_CFPQ, false],
  [415, CURATED_INLINE_QUESTIONS, false],
  [433, LIFE_PROCESSES_CBQ_B1_LT_GENERATED, false],
], [
  "LP2-007",
  "LP2-014",
  "LP2-025",
  "LP2-054",
  "LP2-043",
  "LIFE-EXMPLR-5-MCQ-034",
  "LPX-A-035",
  "LPX-A-063",
  "APQ-S-LIFE-002",
  "APQ-S-LIFE-012",
  "SCO-S-LIFE-003",
  "SCO-S-LIFE-020",
  "PYQ-S-LIFE-002",
  "PYQ-S-LIFE-010",
  "PYQ-S-LIFE-012",
  "PYQ-S-LIFE-014",
  "PYQ-S-LIFE-015",
  "PYQ-S-LIFE-016",
  "PYQ-S-LIFE-017",
  "PYQ-S-2026-LIFEP-006",
  "PYQ-S-2026-LIFEP-007",
  "PYQ-S-2026-LIFEP-011",
  "PYQ-S-2026-LIFEP-012",
  "PYQ-S-2025-LIFEP-004",
  "PYQ-S-2025-LIFEP-006",
  "PYQ-S-2025-LIFEP-008",
]);
