// GENERATED by lazytopper/scripts/generateBankChapters.ts (BANK-SPLIT-1 PR-2). DO NOT EDIT BY HAND.
// Regenerate from lazytopper/ with: pnpm run gen:bank-chapters
// src/data/bankChapters/bankChapters.guard.test.ts fails when this file disagrees with the aggregator.

// Chapter "light-reflection-and-refraction" (Science): 779 served rows from 21 source arrays, 75 withheld.
// Each source is [spread position in RAW_CANONICAL_QUESTION_BANK, the array, is it an AI pack].

import { defineChapter } from "./defineChapter";
import { LIGHT_PACK1 } from "../questionBanks/class10/science/light.pack1";
import { LT2_PACK2 } from "../questionBanks/class10/science/light.pack2";
import { LIGHT_NCERT } from "../questionBanks/class10/science/light.ncert";
import { LIGHT_EXEMPLAR } from "../questionBanks/class10/science/light.exemplar";
import { LIGHT_REFLECTION_SQP } from "../questionBanks/class10/science/light-reflection-and-refraction.sqp";
import { LGHT_CBE } from "../questionBanks/class10/science/light-reflection-and-refraction.cbe";
import { LGHT_SP } from "../questionBanks/class10/science/light-reflection-and-refraction.sp";
import { LIGHT_REFLECTION_APQ } from "../questionBanks/class10/science/light-reflection-and-refraction.additionalPQ";
import { LIGHT_REFLECTION_CHAPTERWISE } from "../questionBanks/class10/science/light-reflection-and-refraction.chapterwise";
import { LIGHT_REFLECTION_PYQ } from "../questionBanks/class10/science/light-reflection-and-refraction.pyq";
import { lightReflectionPYQ2026 } from "../questionBanks/class10/science/lightReflection.pyq2026";
import { lightReflectionPYQ2025 } from "../questionBanks/class10/science/lightReflection.pyq2025";
import { lightReflectionPYQ2024 } from "../questionBanks/class10/science/lightReflection.pyq2024";
import { LGHT_FND, LGHT_FND_BEYOND_BOARD } from "../questionBanks/class10/science/light-reflection-and-refraction.fnd";
import { LGHT_CFPQ_SQP25 } from "../questionBanks/class10/science/light-reflection-and-refraction.cfpq-sqp25";
import { LGHT_GDR, LGHT_GDR_BEYOND_BOARD } from "../questionBanks/class10/science/light-reflection-and-refraction.gdr";
import { CURATED_INLINE_QUESTIONS } from "../questionBanks/class10/curatedInline";
import { LIGHT_CBQ_LT_GENERATED } from "../questionBanks/class10/science/light-reflection-and-refraction.cbq.ltgen";
import { LIGHT_CBQ_B1_LT_GENERATED } from "../questionBanks/class10/science/light-reflection-and-refraction.b1.cbq.ltgen";

export default defineChapter("light-reflection-and-refraction", [
  [44, LIGHT_PACK1, true],
  [45, LT2_PACK2, true],
  [99, LIGHT_NCERT, false],
  [100, LIGHT_EXEMPLAR, false],
  [187, LIGHT_REFLECTION_SQP, false],
  [212, LGHT_CBE, false],
  [238, LGHT_SP, false],
  [277, LIGHT_REFLECTION_APQ, false],
  [290, LIGHT_REFLECTION_CHAPTERWISE, false],
  [303, LIGHT_REFLECTION_PYQ, false],
  [367, lightReflectionPYQ2026, false],
  [380, lightReflectionPYQ2025, false],
  [393, lightReflectionPYQ2024, false],
  [394, LGHT_FND, false],
  [395, LGHT_FND_BEYOND_BOARD, false],
  [396, LGHT_CFPQ_SQP25, false],
  [409, LGHT_GDR, false],
  [410, LGHT_GDR_BEYOND_BOARD, false],
  [415, CURATED_INLINE_QUESTIONS, false],
  [429, LIGHT_CBQ_LT_GENERATED, false],
  [431, LIGHT_CBQ_B1_LT_GENERATED, false],
], [
  "LT-H05",
  "LT2-013",
  "LT2-019",
  "LT2-025",
  "LIGHT-EXMPLR-9-MCQ-004",
  "SCO-S-LIGHT-002",
  "SCO-S-LIGHT-008",
  "SCO-S-LIGHT-009",
  "SCO-S-LIGHT-010",
  "SCO-S-LIGHT-011",
  "SCO-S-LIGHT-017",
  "SCO-S-LIGHT-018",
  "SCO-S-LIGHT-020",
  "SCQ-S-LIGHT-022",
  "SCQ-S-LIGHT-034",
  "SCQ-S-LIGHT-036",
  "SCQ-S-LIGHT-037",
  "PYQ-S-LIGHT-010",
  "PYQ-S-LIGHT-011",
  "PYQ-S-LIGHT-012",
  "PYQ-S-LIGHT-013",
  "PYQ-S-LIGHT-014",
  "PYQ-S-LIGHT-015",
  "PYQ-S-2026-LIGHT-008",
  "PYQ-S-2026-LIGHT-014",
  "PYQ-S-2025-LIGHT-005",
  "PYQ-S-2025-LIGHT-007",
  "PYQ-S-2025-LIGHT-009",
  "PYQ-S-2025-LIGHT-012",
  "PYQ-S-2025-LIGHT-013",
  "PYQ-S-2025-LIGHT-014",
  "PYQ-S-2025-LIGHT-018",
  "PYQ-S-2025-LIGHT-021",
  "PYQ-S-2024-LIGHT-001",
  "PYQ-S-2024-LIGHT-002",
  "PYQ-S-2024-LIGHT-003",
  "FND-L-SPM-044",
  "FND-L-QB-078",
  "FND-L-QB-117",
  "FND-L-QB-136",
  "FND-L-QB-175",
  "FND-L-SPX-001",
  "FND-L-SPX-003",
  "FND-L-SPX-004",
  "FND-L-SPX-005",
  "FND-L-SPX-007",
  "FND-L-SPX-016",
  "FND-L-SPX-017",
  "FND-L-SPX-024",
  "FND-L-SPX-037",
  "FND-L-SPX-038",
  "FND-L-SPX-042",
  "FND-L-SPX-043",
  "FND-L-SPM-003",
  "FND-L-SPM-004",
  "FND-L-SPM-006",
  "FND-L-SPM-014",
  "FND-L-SPM-021",
  "FND-L-SPM-022",
  "FND-L-SPM-031",
  "FND-L-SPM-032",
  "FND-L-SPM-033",
  "FND-L-SPM-034",
  "FND-L-SPM-035",
  "FND-L-SPM-036",
  "FND-L-WS4-101",
  "FND-L-WS4-102",
  "FND-L-WS4-202",
  "FND-L-WS4-204",
  "FND-L-WS4-207",
  "FND-L-WSF-17",
  "FND-L-WSF-18",
  "GDR-L-EQ-13",
  "GDR-L-NUM-022",
  "GDR-L-NUM-095",
]);
