// GENERATED by lazytopper/scripts/generateBankChapters.ts (BANK-SPLIT-1 PR-2). DO NOT EDIT BY HAND.
// Regenerate from lazytopper/ with: pnpm run gen:bank-chapters
// src/data/bankChapters/bankChapters.guard.test.ts fails when this file disagrees with the aggregator.

// Chapter "magnetic-effects-of-electric-current" (Science): 216 served rows from 18 source arrays, 7 withheld.
// Each source is [spread position in RAW_CANONICAL_QUESTION_BANK, the array, is it an AI pack].

import { defineChapter } from "./defineChapter";
import { MAGNETIC_EFFECTS_PACK1 } from "../questionBanks/class10/science/magneticEffects.pack1";
import { ME2_PACK2 } from "../questionBanks/class10/science/magneticEffects.pack2";
import { MAG_NCERT } from "../questionBanks/class10/science/magneticEffects.ncert";
import { MAG_EXEMPLAR } from "../questionBanks/class10/science/magneticEffects.exemplar";
import { MAGNETIC_EFFECTS_SQP } from "../questionBanks/class10/science/magnetic-effects-of-electric-current.sqp";
import { MAGN_CBE } from "../questionBanks/class10/science/magnetic-effects-of-electric-current.cbe";
import { MAGN_SP } from "../questionBanks/class10/science/magnetic-effects-of-electric-current.sp";
import { MAGNETIC_EFFECTS_APQ } from "../questionBanks/class10/science/magnetic-effects-of-electric-current.additionalPQ";
import { MAGNETIC_EFFECTS_CHAPTERWISE } from "../questionBanks/class10/science/magnetic-effects-of-electric-current.chapterwise";
import { ELECTRICITY_PYQ } from "../questionBanks/class10/science/electricity.pyq";
import { MAGNETIC_EFFECTS_PYQ } from "../questionBanks/class10/science/magnetic-effects-of-electric-current.pyq";
import { acidsBasesSaltsPYQ2026 } from "../questionBanks/class10/science/acidsBasesSalts.pyq2026";
import { electricityPYQ2026 } from "../questionBanks/class10/science/electricity.pyq2026";
import { magneticEffectsPYQ2026 } from "../questionBanks/class10/science/magneticEffects.pyq2026";
import { magneticEffectsPYQ2025 } from "../questionBanks/class10/science/magneticEffects.pyq2025";
import { metalsNonMetalsPYQ2024 } from "../questionBanks/class10/science/metalsNonMetals.pyq2024";
import { magneticEffectsPYQ2024 } from "../questionBanks/class10/science/magneticEffects.pyq2024";
import { CURATED_INLINE_QUESTIONS } from "../questionBanks/class10/curatedInline";

export default defineChapter("magnetic-effects-of-electric-current", [
  [50, MAGNETIC_EFFECTS_PACK1, true],
  [51, ME2_PACK2, true],
  [105, MAG_NCERT, false],
  [106, MAG_EXEMPLAR, false],
  [190, MAGNETIC_EFFECTS_SQP, false],
  [215, MAGN_CBE, false],
  [241, MAGN_SP, false],
  [280, MAGNETIC_EFFECTS_APQ, false],
  [293, MAGNETIC_EFFECTS_CHAPTERWISE, false],
  [305, ELECTRICITY_PYQ, false],
  [306, MAGNETIC_EFFECTS_PYQ, false],
  [360, acidsBasesSaltsPYQ2026, false],
  [369, electricityPYQ2026, false],
  [370, magneticEffectsPYQ2026, false],
  [383, magneticEffectsPYQ2025, false],
  [387, metalsNonMetalsPYQ2024, false],
  [413, magneticEffectsPYQ2024, false],
  [415, CURATED_INLINE_QUESTIONS, false],
], [
  "SCO-S-MAG-005",
  "SCO-S-MAG-007",
  "PYQ-S-ELEC-002",
  "PYQ-S-MAG-008",
  "PYQ-S-2026-ELEC-008",
  "PYQ-S-2026-ELEC-009",
  "PYQ-S-2024-MAG-002",
]);
