// GENERATED by lazytopper/scripts/generateBankChapters.ts (BANK-SPLIT-1 PR-2). DO NOT EDIT BY HAND.
// Regenerate from lazytopper/ with: pnpm run gen:bank-chapters
// src/data/bankChapters/bankChapters.guard.test.ts fails when this file disagrees with the aggregator.

// Chapter "magnetic-effects-of-electric-current" (Science): 270 served rows from 21 source arrays, 81 withheld.
// Each source is [spread position in RAW_CANONICAL_QUESTION_BANK, the array, is it an AI pack].

import { defineChapter } from "./defineChapter";
import { MAGNETIC_EFFECTS_PACK1 } from "../questionBanks/class10/science/magneticEffects.pack1";
import { ME2_PACK2 } from "../questionBanks/class10/science/magneticEffects.pack2";
import { MAG_NCERT } from "../questionBanks/class10/science/magneticEffects.ncert";
import { MAG_EXEMPLAR } from "../questionBanks/class10/science/magneticEffects.exemplar";
import { MAGNETIC_EFFECTS_SQP } from "../questionBanks/class10/science/magnetic-effects-of-electric-current.sqp";
import { MAGN_CBE } from "../questionBanks/class10/science/magnetic-effects-of-electric-current.cbe";
import { MAGN_SP } from "../questionBanks/class10/science/magnetic-effects-of-electric-current.sp";
import { MAGNETIC_EFFECTS_APQ } from "../questionBanks/class10/science/magnetic-effects-of-electric-current.additionalPQ";
import { MAGNETIC_EFFECTS_CHAPTERWISE } from "../questionBanks/class10/science/magnetic-effects-of-electric-current.chapterwise";
import { ELECTRICITY_PYQ } from "../questionBanks/class10/science/electricity.pyq";
import { MAGNETIC_EFFECTS_PYQ } from "../questionBanks/class10/science/magnetic-effects-of-electric-current.pyq";
import { acidsBasesSaltsPYQ2026 } from "../questionBanks/class10/science/acidsBasesSalts.pyq2026";
import { electricityPYQ2026 } from "../questionBanks/class10/science/electricity.pyq2026";
import { magneticEffectsPYQ2026 } from "../questionBanks/class10/science/magneticEffects.pyq2026";
import { magneticEffectsPYQ2025 } from "../questionBanks/class10/science/magneticEffects.pyq2025";
import { metalsNonMetalsPYQ2024 } from "../questionBanks/class10/science/metalsNonMetals.pyq2024";
import { magneticEffectsPYQ2024 } from "../questionBanks/class10/science/magneticEffects.pyq2024";
import { CURATED_INLINE_QUESTIONS } from "../questionBanks/class10/curatedInline";
import { MAGNETIC_EFFECTS_LT_GENERATED } from "../questionBanks/class10/science/magnetic-effects-of-electric-current.ltgen";
import { MAGNETIC_EFFECTS_CBQ_LT_GENERATED } from "../questionBanks/class10/science/magnetic-effects-of-electric-current.cbq.ltgen";
import { MAGNETIC_EFFECTS_CBQ_B1_LT_GENERATED } from "../questionBanks/class10/science/magnetic-effects-of-electric-current.b1.cbq.ltgen";

export default defineChapter("magnetic-effects-of-electric-current", [
  [50, MAGNETIC_EFFECTS_PACK1, true],
  [51, ME2_PACK2, true],
  [105, MAG_NCERT, false],
  [106, MAG_EXEMPLAR, false],
  [190, MAGNETIC_EFFECTS_SQP, false],
  [215, MAGN_CBE, false],
  [241, MAGN_SP, false],
  [280, MAGNETIC_EFFECTS_APQ, false],
  [293, MAGNETIC_EFFECTS_CHAPTERWISE, false],
  [305, ELECTRICITY_PYQ, false],
  [306, MAGNETIC_EFFECTS_PYQ, false],
  [360, acidsBasesSaltsPYQ2026, false],
  [369, electricityPYQ2026, false],
  [370, magneticEffectsPYQ2026, false],
  [383, magneticEffectsPYQ2025, false],
  [387, metalsNonMetalsPYQ2024, false],
  [413, magneticEffectsPYQ2024, false],
  [415, CURATED_INLINE_QUESTIONS, false],
  [419, MAGNETIC_EFFECTS_LT_GENERATED, false],
  [420, MAGNETIC_EFFECTS_CBQ_LT_GENERATED, false],
  [430, MAGNETIC_EFFECTS_CBQ_B1_LT_GENERATED, false],
], [
  "ME-M01",
  "ME-M02",
  "ME-M05",
  "ME-M08",
  "ME-H01",
  "ME-H02",
  "ME-H03",
  "ME-H05",
  "ME-H07",
  "ME-H09",
  "ME-D03",
  "ME2-005",
  "ME2-008",
  "ME2-009",
  "ME2-010",
  "ME2-011",
  "ME2-012",
  "ME2-013",
  "ME2-014",
  "ME2-015",
  "ME2-016",
  "ME2-019",
  "ME2-020",
  "ME2-021",
  "ME2-022",
  "ME2-024",
  "ME2-025",
  "ME2-031",
  "ME2-032",
  "ME2-033",
  "ME2-034",
  "ME2-035",
  "ME2-036",
  "ME2-037",
  "ME2-038",
  "ME2-040",
  "ME2-042",
  "ME2-044",
  "ME2-045",
  "ME2-051",
  "ME2-054",
  "MAG-NCERT-12-LA-001",
  "MAG-EXMPLR-12-MCQ-006",
  "MAG-EXMPLR-12-MCQ-007",
  "MAG-EXMPLR-12-MCQ-008",
  "MAG-EXMPLR-12-SA-009",
  "MAG-EXMPLR-12-SA-010",
  "MAG-EXMPLR-12-LA-005",
  "MAG-EXMPLR-12-LA-006",
  "CBE-S-MAGN-A-002",
  "CBE-S-MAGN-A-003",
  "CBE-S-MAGN-B-002",
  "CBE-S-MAGN-B-004",
  "CBE-S-MAGN-B-005",
  "CBE-S-MAGN-D-001",
  "CBE-S-MAGN-E-001",
  "SQP-S-2023-MAGN-C-001",
  "SCO-S-MAG-001",
  "SCO-S-MAG-002",
  "SCO-S-MAG-004",
  "SCO-S-MAG-005",
  "SCO-S-MAG-006",
  "SCO-S-MAG-007",
  "SCO-S-MAG-009",
  "SCO-S-MAG-012",
  "SCO-S-MAG-013",
  "SCO-S-MAG-014",
  "SCO-S-MAG-016",
  "SCO-S-MAG-019",
  "SCQ-S-MAG-024",
  "SCQ-S-MAG-041",
  "PYQ-S-ELEC-002",
  "PYQ-S-MAG-001",
  "PYQ-S-MAG-002",
  "PYQ-S-MAG-003",
  "PYQ-S-MAG-008",
  "PYQ-S-2026-ELEC-008",
  "PYQ-S-2026-ELEC-009",
  "PYQ-S-2026-MAG-001",
  "PYQ-S-2025-MAG-006",
  "PYQ-S-2024-MAG-002",
]);
