// GENERATED by lazytopper/scripts/generateBankChapters.ts (BANK-SPLIT-1 PR-2). DO NOT EDIT BY HAND.
// Regenerate from lazytopper/ with: pnpm run gen:bank-chapters
// src/data/bankChapters/bankChapters.guard.test.ts fails when this file disagrees with the aggregator.

// Chapter "metals-and-non-metals" (Science): 417 served rows from 21 source arrays, 17 withheld.
// Each source is [spread position in RAW_CANONICAL_QUESTION_BANK, the array, is it an AI pack].

import { defineChapter } from "./defineChapter";
import { METALS_NON_METALS_PACK1 } from "../questionBanks/class10/science/metalsNonMetals.pack1";
import { MNM2_PACK2 } from "../questionBanks/class10/science/metalsNonMetals.pack2";
import { METALS_NON_METALS_NCERT } from "../questionBanks/class10/science/metalsNonMetals.ncert";
import { MNM_EXPAND_EXTRACT } from "../questionBanks/class10/science/metalsNonMetals.expand.extract";
import { MNM_EXPAND_LONG_D } from "../questionBanks/class10/science/metalsNonMetals.expand.longD";
import { MNM_EXPAND_CASE_E } from "../questionBanks/class10/science/metalsNonMetals.expand.caseE";
import { METALS_NON_METALS_EXEMPLAR } from "../questionBanks/class10/science/metalsNonMetals.exemplar";
import { METALS_NON_METALS_SQP } from "../questionBanks/class10/science/metals-and-non-metals.sqp";
import { MNM_CBE } from "../questionBanks/class10/science/metals-and-non-metals.cbe";
import { MNM_SP } from "../questionBanks/class10/science/metals-and-non-metals.sp";
import { METALS_NON_METALS_APQ } from "../questionBanks/class10/science/metals-and-non-metals.additionalPQ";
import { METALS_NON_METALS_CHAPTERWISE } from "../questionBanks/class10/science/metals-and-non-metals.chapterwise";
import { ACIDS_BASES_SALTS_PYQ } from "../questionBanks/class10/science/acids-bases-and-salts.pyq";
import { METALS_NON_METALS_PYQ } from "../questionBanks/class10/science/metals-and-non-metals.pyq";
import { acidsBasesSaltsPYQ2026 } from "../questionBanks/class10/science/acidsBasesSalts.pyq2026";
import { metalsNonMetalsPYQ2026 } from "../questionBanks/class10/science/metalsNonMetals.pyq2026";
import { chemicalReactionsPYQ2025 } from "../questionBanks/class10/science/chemicalReactions.pyq2025";
import { metalsNonMetalsPYQ2025 } from "../questionBanks/class10/science/metalsNonMetals.pyq2025";
import { metalsNonMetalsPYQ2024 } from "../questionBanks/class10/science/metalsNonMetals.pyq2024";
import { MNM_CFPQ } from "../questionBanks/class10/science/metals-and-non-metals.cfpq";
import { CURATED_INLINE_QUESTIONS } from "../questionBanks/class10/curatedInline";

export default defineChapter("metals-and-non-metals", [
  [32, METALS_NON_METALS_PACK1, true],
  [33, MNM2_PACK2, true],
  [81, METALS_NON_METALS_NCERT, false],
  [82, MNM_EXPAND_EXTRACT, false],
  [83, MNM_EXPAND_LONG_D, false],
  [84, MNM_EXPAND_CASE_E, false],
  [85, METALS_NON_METALS_EXEMPLAR, false],
  [181, METALS_NON_METALS_SQP, false],
  [206, MNM_CBE, false],
  [232, MNM_SP, false],
  [271, METALS_NON_METALS_APQ, false],
  [284, METALS_NON_METALS_CHAPTERWISE, false],
  [296, ACIDS_BASES_SALTS_PYQ, false],
  [297, METALS_NON_METALS_PYQ, false],
  [360, acidsBasesSaltsPYQ2026, false],
  [361, metalsNonMetalsPYQ2026, false],
  [372, chemicalReactionsPYQ2025, false],
  [374, metalsNonMetalsPYQ2025, false],
  [387, metalsNonMetalsPYQ2024, false],
  [399, MNM_CFPQ, false],
  [415, CURATED_INLINE_QUESTIONS, false],
], [
  "METAL-EXMPLR-3-MCQ-036",
  "METAL-EXMPLR-3-SA-014",
  "METAL-EXMPLR-3-LONG-001",
  "CBE-S-MNM-B-006",
  "SCO-S-METAL-002",
  "SCO-S-METAL-003",
  "SCO-S-METAL-016",
  "SCQ-S-METAL-034",
  "SCQ-S-METAL-044",
  "PYQ-S-METAL-003",
  "PYQ-S-2026-METAL-004",
  "PYQ-S-2026-METAL-009",
  "PYQ-S-2026-METAL-010",
  "PYQ-S-2026-METAL-011",
  "PYQ-S-2025-METAL-005",
  "PYQ-S-2025-METAL-006",
  "PYQ-S-2024-METAL-001",
]);
