// GENERATED by lazytopper/scripts/generateBankChapters.ts (BANK-SPLIT-1 PR-2). DO NOT EDIT BY HAND.
// Regenerate from lazytopper/ with: pnpm run gen:bank-chapters
// src/data/bankChapters/bankChapters.guard.test.ts fails when this file disagrees with the aggregator.

// Chapter "our-environment" (Science): 340 served rows from 18 source arrays, 31 withheld.
// Each source is [spread position in RAW_CANONICAL_QUESTION_BANK, the array, is it an AI pack].

import { defineChapter } from "./defineChapter";
import { OUR_ENVIRONMENT_PACK1 } from "../questionBanks/class10/science/ourEnvironment.pack1";
import { OE2_PACK2 } from "../questionBanks/class10/science/ourEnvironment.pack2";
import { OE_EXTRACT } from "../questionBanks/class10/science/ourEnvironment.extract";
import { OE_SCARCE_D } from "../questionBanks/class10/science/ourEnvironment.scarceD";
import { OE_SCARCE_E } from "../questionBanks/class10/science/ourEnvironment.scarceE";
import { ENVI_CBE } from "../questionBanks/class10/science/our-environment.cbe";
import { ENVI_SP } from "../questionBanks/class10/science/our-environment.sp";
import { OUR_ENVIRONMENT_APQ } from "../questionBanks/class10/science/our-environment.additionalPQ";
import { OUR_ENVIRONMENT_CHAPTERWISE } from "../questionBanks/class10/science/our-environment.chapterwise";
import { OUR_ENVIRONMENT_PYQ } from "../questionBanks/class10/science/our-environment.pyq";
import { ourEnvironmentPYQ2026 } from "../questionBanks/class10/science/ourEnvironment.pyq2026";
import { ourEnvironmentPYQ2025 } from "../questionBanks/class10/science/ourEnvironment.pyq2025";
import { ENV_CFPQ } from "../questionBanks/class10/science/our-environment.cfpq";
import { ourEnvironmentPYQ2024 } from "../questionBanks/class10/science/ourEnvironment.pyq2024";
import { CURATED_INLINE_QUESTIONS } from "../questionBanks/class10/curatedInline";
import { OUR_ENVIRONMENT_CBQ_LT_GENERATED } from "../questionBanks/class10/science/our-environment.cbq.ltgen";
import { ENVIRONMENT_CBQ_B1_LT_GENERATED } from "../questionBanks/class10/science/our-environment.b1.cbq.ltgen";
import { OUR_ENVIRONMENT_C3_CBQ_LT_GENERATED } from "../questionBanks/class10/science/our-environment.c3.cbq.ltgen";

export default defineChapter("our-environment", [
  [52, OUR_ENVIRONMENT_PACK1, true],
  [53, OE2_PACK2, true],
  [54, OE_EXTRACT, false],
  [55, OE_SCARCE_D, true],
  [56, OE_SCARCE_E, true],
  [216, ENVI_CBE, false],
  [242, ENVI_SP, false],
  [281, OUR_ENVIRONMENT_APQ, false],
  [294, OUR_ENVIRONMENT_CHAPTERWISE, false],
  [307, OUR_ENVIRONMENT_PYQ, false],
  [371, ourEnvironmentPYQ2026, false],
  [384, ourEnvironmentPYQ2025, false],
  [406, ENV_CFPQ, false],
  [414, ourEnvironmentPYQ2024, false],
  [415, CURATED_INLINE_QUESTIONS, false],
  [427, OUR_ENVIRONMENT_CBQ_LT_GENERATED, false],
  [450, ENVIRONMENT_CBQ_B1_LT_GENERATED, false],
  [458, OUR_ENVIRONMENT_C3_CBQ_LT_GENERATED, false],
], [
  "OEX-A-005",
  "SCO-S-ENV-002",
  "SCO-S-ENV-003",
  "SCO-S-ENV-004",
  "SCO-S-ENV-005",
  "SCO-S-ENV-006",
  "SCO-S-ENV-007",
  "SCO-S-ENV-010",
  "SCO-S-ENV-012",
  "SCO-S-ENV-013",
  "SCO-S-ENV-014",
  "SCO-S-ENV-015",
  "SCO-S-ENV-016",
  "SCO-S-ENV-017",
  "SCO-S-ENV-018",
  "SCO-S-ENV-019",
  "SCO-S-ENV-020",
  "SCQ-S-ENV-022",
  "SCQ-S-ENV-024",
  "SCQ-S-ENV-028",
  "SCQ-S-ENV-029",
  "SCQ-S-ENV-032",
  "SCQ-S-ENV-033",
  "SCQ-S-ENV-034",
  "SCQ-S-ENV-035",
  "SCQ-S-ENV-036",
  "SCQ-S-ENV-037",
  "PYQ-S-ENV-003",
  "PYQ-S-ENV-004",
  "PYQ-S-2026-ENV-001",
  "PYQ-S-2025-ENV-003",
]);
