// GENERATED by lazytopper/scripts/generateBankChapters.ts (BANK-SPLIT-1 PR-2). DO NOT EDIT BY HAND.
// Regenerate from lazytopper/ with: pnpm run gen:bank-chapters
// src/data/bankChapters/bankChapters.guard.test.ts fails when this file disagrees with the aggregator.

// Chapter "pair-of-linear-equations" (Maths): 438 served rows from 21 source arrays, 51 withheld.
// Each source is [spread position in RAW_CANONICAL_QUESTION_BANK, the array, is it an AI pack].

import { defineChapter } from "./defineChapter";
import { PAIR_LINEAR_EQUATIONS_PACK1 } from "../questionBanks/class10/maths/pairOfLinearEquations.pack1";
import { PLE2_PACK2 } from "../questionBanks/class10/maths/pairOfLinearEquations.pack2";
import { PLE_NCERT } from "../questionBanks/class10/maths/pairOfLinearEquations.ncert";
import { PLE_EXEMPLAR } from "../questionBanks/class10/maths/pairOfLinearEquations.exemplar";
import { PLE_EXPAND_EXTRACT } from "../questionBanks/class10/maths/pairOfLinearEquations.expand.extract";
import { PLE_EXPAND_LONG_D } from "../questionBanks/class10/maths/pairOfLinearEquations.expand.longD";
import { PLE_EXPAND_CASE_E } from "../questionBanks/class10/maths/pairOfLinearEquations.expand.caseE";
import { PLE_EXPAND_REDUCIBLE } from "../questionBanks/class10/maths/pairOfLinearEquations.expand.reducible";
import { Z3_COMPETENCY_QUESTIONS } from "../questionBanks/class10/maths/competency.z3";
import { PAIR_OF_LINEAR_EQUATIONS_SQP } from "../questionBanks/class10/maths/pair-of-linear-equations.sqp";
import { PLE_CBE } from "../questionBanks/class10/maths/pair-of-linear-equations.cbe";
import { PLE_SP } from "../questionBanks/class10/maths/pair-of-linear-equations.sp";
import { PLE_PREBOARD } from "../questionBanks/class10/maths/pair-of-linear-equations.preboard";
import { PAIR_OF_LINEAR_EQUATIONS_APQ } from "../questionBanks/class10/maths/pair-of-linear-equations.additionalPQ";
import { PAIR_LINEAR_EQUATIONS_PYQ } from "../questionBanks/class10/maths/pair-of-linear-equations.pyq";
import { PAIR_LINEAR_EQUATIONS_PYQ_2026 } from "../questionBanks/class10/maths/pair-of-linear-equations.pyq2026";
import { PAIR_LINEAR_EQUATIONS_PYQ_2024 } from "../questionBanks/class10/maths/pair-of-linear-equations.pyq2024";
import { PAIR_LINEAR_EQUATIONS_PYQ_2025 } from "../questionBanks/class10/maths/pair-of-linear-equations.pyq2025";
import { PROBABILITY_PYQ_2025 } from "../questionBanks/class10/maths/probability.pyq2025";
import { CURATED_INLINE_QUESTIONS } from "../questionBanks/class10/curatedInline";
import { PAIR_OF_LINEAR_EQUATIONS_CBQ_LT_GENERATED } from "../questionBanks/class10/maths/pair-of-linear-equations.cbq.ltgen";

export default defineChapter("pair-of-linear-equations", [
  [10, PAIR_LINEAR_EQUATIONS_PACK1, true],
  [11, PLE2_PACK2, true],
  [114, PLE_NCERT, false],
  [115, PLE_EXEMPLAR, false],
  [116, PLE_EXPAND_EXTRACT, false],
  [117, PLE_EXPAND_LONG_D, false],
  [118, PLE_EXPAND_CASE_E, false],
  [119, PLE_EXPAND_REDUCIBLE, false],
  [153, Z3_COMPETENCY_QUESTIONS, false],
  [168, PAIR_OF_LINEAR_EQUATIONS_SQP, false],
  [193, PLE_CBE, false],
  [219, PLE_SP, false],
  [245, PLE_PREBOARD, false],
  [258, PAIR_OF_LINEAR_EQUATIONS_APQ, false],
  [310, PAIR_LINEAR_EQUATIONS_PYQ, false],
  [323, PAIR_LINEAR_EQUATIONS_PYQ_2026, false],
  [336, PAIR_LINEAR_EQUATIONS_PYQ_2024, false],
  [349, PAIR_LINEAR_EQUATIONS_PYQ_2025, false],
  [358, PROBABILITY_PYQ_2025, false],
  [415, CURATED_INLINE_QUESTIONS, false],
  [446, PAIR_OF_LINEAR_EQUATIONS_CBQ_LT_GENERATED, false],
], [
  "PLE-M02",
  "PLE-M03",
  "PLE-M04",
  "PLE-M14",
  "PLE-H01",
  "PLE-H05",
  "PLE-H07",
  "PLE-H10",
  "PLE2-012",
  "PLE2-039",
  "PLE2-041",
  "PLE2-R01",
  "PLE-N-NCERT-3-LA-004",
  "PLE-N-EXMPLR-3-MCQ-001",
  "PLE-N-EXMPLR-3-MCQ-005",
  "PLE-N-EXMPLR-3-SA-008",
  "PLE-N-EXMPLR-3-CB-001",
  "PLE-N-EXMPLR-3-CB-002",
  "BX-PLE-RED-EX-A-001",
  "BX-PLE-RED-EX-A-002",
  "BX-PLE-RED-EX-A-003",
  "BX-PLE-RED-EX-B-001",
  "BX-PLE-RED-EX-B-002",
  "BX-PLE-RED-EX-C-001",
  "BX-PLE-RED-EX-C-002",
  "BX-PLE-RED-EX-C-003",
  "BX-PLE-RED-D-001",
  "BX-PLE-RED-D-002",
  "BX-PLE-RED-D-004",
  "BX-PLE-RED-D-005",
  "BX-PLE-RED-D-007",
  "BX-PLE-RED-D-008",
  "BX-PLE-RED-D-009",
  "BX-PLE-RED-D-010",
  "BX-PLE-RED-D-011",
  "BX-PLE-RED-E-001",
  "BX-PLE-RED-E-002",
  "BX-PLE-RED-E-003",
  "BX-PLE-RED-E-004",
  "BX-PLE-RED-E-005",
  "BX-PLE-RED-E-006",
  "BX-PLE-RED-E-007",
  "BX-PLE-RED-E-008",
  "BX-PLE-RED-E-009",
  "BX-PLE-RED-E-010",
  "BX-PLE-RED-E-011",
  "BX-PLE-RED-E-012",
  "BX-PLE-RED-E-013",
  "APQ-M-PLE-002",
  "PYQ-M-PLE-003",
  "PYQ-M-2026-PLE-001",
]);
