// GENERATED by lazytopper/scripts/generateBankChapters.ts (BANK-SPLIT-1 PR-2). DO NOT EDIT BY HAND.
// Regenerate from lazytopper/ with: pnpm run gen:bank-chapters
// src/data/bankChapters/bankChapters.guard.test.ts fails when this file disagrees with the aggregator.

// Chapter "polynomials" (Maths): 345 served rows from 20 source arrays, 32 withheld.
// Each source is [spread position in RAW_CANONICAL_QUESTION_BANK, the array, is it an AI pack].

import { defineChapter } from "./defineChapter";
import { POLYNOMIALS_PACK1 } from "../questionBanks/class10/maths/polynomials.pack1";
import { PL2_PACK2 } from "../questionBanks/class10/maths/polynomials.pack2";
import { QUADRATIC_EQUATIONS_PACK1 } from "../questionBanks/class10/maths/quadraticEquations.pack1";
import { QE2_PACK2 } from "../questionBanks/class10/maths/quadraticEquations.pack2";
import { POLYNOMIALS_EXPAND_EXTRACT } from "../questionBanks/class10/maths/polynomials.expand.extract";
import { POLYNOMIALS_EXPAND_LONG_D } from "../questionBanks/class10/maths/polynomials.expand.longD";
import { POLYNOMIALS_EXPAND_CASE_E } from "../questionBanks/class10/maths/polynomials.expand.caseE";
import { POLY_NCERT } from "../questionBanks/class10/maths/polynomials.ncert";
import { POLY_EXEMPLAR } from "../questionBanks/class10/maths/polynomials.exemplar";
import { POLYNOMIALS_SQP } from "../questionBanks/class10/maths/polynomials.sqp";
import { POLY_CBE } from "../questionBanks/class10/maths/polynomials.cbe";
import { POLY_SP } from "../questionBanks/class10/maths/polynomials.sp";
import { POLY_PREBOARD } from "../questionBanks/class10/maths/polynomials.preboard";
import { POLYNOMIALS_APQ } from "../questionBanks/class10/maths/polynomials.additionalPQ";
import { POLYNOMIALS_PYQ } from "../questionBanks/class10/maths/polynomials.pyq";
import { POLYNOMIALS_PYQ_2026 } from "../questionBanks/class10/maths/polynomials.pyq2026";
import { POLYNOMIALS_PYQ_2024 } from "../questionBanks/class10/maths/polynomials.pyq2024";
import { POLYNOMIALS_PYQ_2025 } from "../questionBanks/class10/maths/polynomials.pyq2025";
import { POLYNOMIALS_CFPQ } from "../questionBanks/class10/maths/polynomials.cfpq";
import { POLYNOMIALS_CBQ_LT_GENERATED } from "../questionBanks/class10/maths/polynomials.cbq.ltgen";

export default defineChapter("polynomials", [
  [8, POLYNOMIALS_PACK1, true],
  [9, PL2_PACK2, true],
  [12, QUADRATIC_EQUATIONS_PACK1, true],
  [13, QE2_PACK2, true],
  [71, POLYNOMIALS_EXPAND_EXTRACT, false],
  [72, POLYNOMIALS_EXPAND_LONG_D, false],
  [73, POLYNOMIALS_EXPAND_CASE_E, false],
  [133, POLY_NCERT, false],
  [134, POLY_EXEMPLAR, false],
  [167, POLYNOMIALS_SQP, false],
  [192, POLY_CBE, false],
  [218, POLY_SP, false],
  [244, POLY_PREBOARD, false],
  [257, POLYNOMIALS_APQ, false],
  [309, POLYNOMIALS_PYQ, false],
  [322, POLYNOMIALS_PYQ_2026, false],
  [335, POLYNOMIALS_PYQ_2024, false],
  [348, POLYNOMIALS_PYQ_2025, false],
  [408, POLYNOMIALS_CFPQ, false],
  [439, POLYNOMIALS_CBQ_LT_GENERATED, false],
], [
  "POLY-M04",
  "POLY-M06",
  "POLY-H01",
  "POLY-H02",
  "POLY-H03",
  "POLY-H09",
  "POLY-H11",
  "POLY-H12",
  "POLY-M13-R",
  "POLY-ND01",
  "PL2-003",
  "PL2-015",
  "PL2-018",
  "PL2-021",
  "PL2-035",
  "PL2-040",
  "PL2-R04",
  "PL2-R12",
  "PL2-R18",
  "POLY-N-NCERT-2-LA-001",
  "POLY-N-EXEM-2-MCQ-005",
  "POLY-N-EXEM-2-VSA-003",
  "POLY-N-EXEM-2-SA-005",
  "POLY-N-EXEM-2-LA-001",
  "POLY-N-EXEM-2-LA-002",
  "POLY-N-EXEM-2-CRE-001",
  "SQP-M-POLY-001",
  "APQ-M-POLY-001",
  "PYQ-M-POLY-001",
  "PYQ-M-POLY-006",
  "PYQ-M-2026-POLY-005",
  "PYQ-M-2025-POLY-003",
]);
