// GENERATED by lazytopper/scripts/generateBankChapters.ts (BANK-SPLIT-1 PR-2). DO NOT EDIT BY HAND.
// Regenerate from lazytopper/ with: pnpm run gen:bank-chapters
// src/data/bankChapters/bankChapters.guard.test.ts fails when this file disagrees with the aggregator.

// Chapter "probability" (Maths): 325 served rows from 16 source arrays, 9 withheld.
// Each source is [spread position in RAW_CANONICAL_QUESTION_BANK, the array, is it an AI pack].

import { defineChapter } from "./defineChapter";
import { PROBABILITY_PACK1 } from "../questionBanks/class10/maths/probability.pack1";
import { PR2_PACK2 } from "../questionBanks/class10/maths/probability.pack2";
import { PROB_NCERT } from "../questionBanks/class10/maths/probability.ncert";
import { PROB_EXEMPLAR } from "../questionBanks/class10/maths/probability.exemplar";
import { Z3_COMPETENCY_QUESTIONS } from "../questionBanks/class10/maths/competency.z3";
import { PROBABILITY_SQP } from "../questionBanks/class10/maths/probability.sqp";
import { PROB_CBE } from "../questionBanks/class10/maths/probability.cbe";
import { PROB_SP } from "../questionBanks/class10/maths/probability.sp";
import { PROB_PREBOARD } from "../questionBanks/class10/maths/probability.preboard";
import { PROBABILITY_APQ } from "../questionBanks/class10/maths/probability.additionalPQ";
import { PROBABILITY_PYQ } from "../questionBanks/class10/maths/probability.pyq";
import { PROBABILITY_PYQ_2026 } from "../questionBanks/class10/maths/probability.pyq2026";
import { PROBABILITY_PYQ_2024 } from "../questionBanks/class10/maths/probability.pyq2024";
import { PROBABILITY_PYQ_2025 } from "../questionBanks/class10/maths/probability.pyq2025";
import { CURATED_INLINE_QUESTIONS } from "../questionBanks/class10/curatedInline";
import { PROBABILITY_CBQ_LT_GENERATED } from "../questionBanks/class10/maths/probability.cbq.ltgen";

export default defineChapter("probability", [
  [26, PROBABILITY_PACK1, true],
  [27, PR2_PACK2, true],
  [146, PROB_NCERT, false],
  [147, PROB_EXEMPLAR, false],
  [153, Z3_COMPETENCY_QUESTIONS, false],
  [178, PROBABILITY_SQP, false],
  [202, PROB_CBE, false],
  [229, PROB_SP, false],
  [255, PROB_PREBOARD, false],
  [268, PROBABILITY_APQ, false],
  [320, PROBABILITY_PYQ, false],
  [333, PROBABILITY_PYQ_2026, false],
  [346, PROBABILITY_PYQ_2024, false],
  [358, PROBABILITY_PYQ_2025, false],
  [415, CURATED_INLINE_QUESTIONS, false],
  [438, PROBABILITY_CBQ_LT_GENERATED, false],
], [
  "PROB-H15",
  "PR2-014",
  "PR2-045",
  "PYQ-M-PROB-002",
  "PYQ-M-PROB-003",
  "PYQ-M-PROB-005",
  "PYQ-M-PROB-006",
  "PYQ-M-PROB-008",
  "PYQ-M-PROB-010",
]);
