// GENERATED by lazytopper/scripts/generateBankChapters.ts (BANK-SPLIT-1 PR-2). DO NOT EDIT BY HAND.
// Regenerate from lazytopper/ with: pnpm run gen:bank-chapters
// src/data/bankChapters/bankChapters.guard.test.ts fails when this file disagrees with the aggregator.

// Chapter "quadratic-equations" (Maths): 421 served rows from 22 source arrays, 18 withheld.
// Each source is [spread position in RAW_CANONICAL_QUESTION_BANK, the array, is it an AI pack].

import { defineChapter } from "./defineChapter";
import { PAIR_LINEAR_EQUATIONS_PACK1 } from "../questionBanks/class10/maths/pairOfLinearEquations.pack1";
import { QUADRATIC_EQUATIONS_PACK1 } from "../questionBanks/class10/maths/quadraticEquations.pack1";
import { QE2_PACK2 } from "../questionBanks/class10/maths/quadraticEquations.pack2";
import { QUADRATIC_EQUATIONS_EXPAND_EXTRACT } from "../questionBanks/class10/maths/quadraticEquations.expand.extract";
import { QUADRATIC_EQUATIONS_EXPAND_LONG_D } from "../questionBanks/class10/maths/quadraticEquations.expand.longD";
import { QUADRATIC_EQUATIONS_EXPAND_CASE_E } from "../questionBanks/class10/maths/quadraticEquations.expand.caseE";
import { QE_NCERT } from "../questionBanks/class10/maths/quadraticEquations.ncert";
import { QE_EXEMPLAR } from "../questionBanks/class10/maths/quadraticEquations.exemplar";
import { TRI_EXEMPLAR } from "../questionBanks/class10/maths/triangles.exemplar";
import { Z3_COMPETENCY_QUESTIONS } from "../questionBanks/class10/maths/competency.z3";
import { MATHS_CASE_BASED_QUESTIONS } from "../questionBanks/class10/maths/maths.caseBased";
import { QUADRATIC_EQUATIONS_SQP } from "../questionBanks/class10/maths/quadratic-equations.sqp";
import { QE_CBE } from "../questionBanks/class10/maths/quadratic-equations.cbe";
import { QE_SP } from "../questionBanks/class10/maths/quadratic-equations.sp";
import { QE_PREBOARD } from "../questionBanks/class10/maths/quadratic-equations.preboard";
import { QUADRATIC_EQUATIONS_APQ } from "../questionBanks/class10/maths/quadratic-equations.additionalPQ";
import { QUADRATIC_EQUATIONS_PYQ } from "../questionBanks/class10/maths/quadratic-equations.pyq";
import { QUADRATIC_EQUATIONS_PYQ_2026 } from "../questionBanks/class10/maths/quadratic-equations.pyq2026";
import { QUADRATIC_EQUATIONS_PYQ_2024 } from "../questionBanks/class10/maths/quadratic-equations.pyq2024";
import { QUADRATIC_EQUATIONS_PYQ_2025 } from "../questionBanks/class10/maths/quadratic-equations.pyq2025";
import { CURATED_INLINE_QUESTIONS } from "../questionBanks/class10/curatedInline";
import { QUADRATIC_EQUATIONS_CBQ_LT_GENERATED } from "../questionBanks/class10/maths/quadratic-equations.cbq.ltgen";

export default defineChapter("quadratic-equations", [
  [10, PAIR_LINEAR_EQUATIONS_PACK1, true],
  [12, QUADRATIC_EQUATIONS_PACK1, true],
  [13, QE2_PACK2, true],
  [68, QUADRATIC_EQUATIONS_EXPAND_EXTRACT, false],
  [69, QUADRATIC_EQUATIONS_EXPAND_LONG_D, false],
  [70, QUADRATIC_EQUATIONS_EXPAND_CASE_E, false],
  [120, QE_NCERT, false],
  [121, QE_EXEMPLAR, false],
  [123, TRI_EXEMPLAR, false],
  [153, Z3_COMPETENCY_QUESTIONS, false],
  [163, MATHS_CASE_BASED_QUESTIONS, false],
  [169, QUADRATIC_EQUATIONS_SQP, false],
  [194, QE_CBE, false],
  [220, QE_SP, false],
  [246, QE_PREBOARD, false],
  [259, QUADRATIC_EQUATIONS_APQ, false],
  [311, QUADRATIC_EQUATIONS_PYQ, false],
  [324, QUADRATIC_EQUATIONS_PYQ_2026, false],
  [337, QUADRATIC_EQUATIONS_PYQ_2024, false],
  [350, QUADRATIC_EQUATIONS_PYQ_2025, false],
  [415, CURATED_INLINE_QUESTIONS, false],
  [453, QUADRATIC_EQUATIONS_CBQ_LT_GENERATED, false],
], [
  "QE-E13",
  "QE-M06",
  "QE-M12",
  "QE-M13",
  "QE-M16",
  "QE2-004",
  "QE2-005",
  "QE2-017",
  "QE2-033",
  "QE2-043",
  "QE-N-NCERT-4-SH-003",
  "QE-N-EXMPLR-4-MCQ-005",
  "QE-N-EXMPLR-4-MCQ-007",
  "Z3-QE-003",
  "PYQ-M-QE-001",
  "PYQ-M-QE-007",
  "PYQ-M-2025-QE-001",
  "LTG-M-QE-284",
]);
