// GENERATED by lazytopper/scripts/generateBankChapters.ts (BANK-SPLIT-1 PR-2). DO NOT EDIT BY HAND.
// Regenerate from lazytopper/ with: pnpm run gen:bank-chapters
// src/data/bankChapters/bankChapters.guard.test.ts fails when this file disagrees with the aggregator.

// Chapter "real-numbers" (Maths): 229 served rows from 20 source arrays, 21 withheld.
// Each source is [spread position in RAW_CANONICAL_QUESTION_BANK, the array, is it an AI pack].

import { defineChapter } from "./defineChapter";
import { REAL_NUMBERS_PACK1 } from "../questionBanks/class10/maths/realNumbers.pack1";
import { RN2_PACK2 } from "../questionBanks/class10/maths/realNumbers.pack2";
import { RN_NCERT } from "../questionBanks/class10/maths/realNumbers.ncert";
import { RN_EXEMPLAR } from "../questionBanks/class10/maths/realNumbers.exemplar";
import { RN_EXTRACT } from "../questionBanks/class10/maths/realNumbers.extract";
import { RN_SCARCE_D } from "../questionBanks/class10/maths/realNumbers.scarceD";
import { RN_SCARCE_E } from "../questionBanks/class10/maths/realNumbers.scarceE";
import { RN_EXTRACT2 } from "../questionBanks/class10/maths/realNumbers.extract2";
import { RN_SCARCE2 } from "../questionBanks/class10/maths/realNumbers.scarce2";
import { Z3_COMPETENCY_QUESTIONS } from "../questionBanks/class10/maths/competency.z3";
import { REAL_NUMBERS_SQP } from "../questionBanks/class10/maths/real-numbers.sqp";
import { RN_CBE } from "../questionBanks/class10/maths/real-numbers.cbe";
import { RN_SP } from "../questionBanks/class10/maths/real-numbers.sp";
import { RN_PREBOARD } from "../questionBanks/class10/maths/real-numbers.preboard";
import { REAL_NUMBERS_APQ } from "../questionBanks/class10/maths/real-numbers.additionalPQ";
import { REAL_NUMBERS_PYQ } from "../questionBanks/class10/maths/real-numbers.pyq";
import { REAL_NUMBERS_PYQ_2026 } from "../questionBanks/class10/maths/real-numbers.pyq2026";
import { REAL_NUMBERS_PYQ_2024 } from "../questionBanks/class10/maths/real-numbers.pyq2024";
import { REAL_NUMBERS_PYQ_2025 } from "../questionBanks/class10/maths/real-numbers.pyq2025";
import { REAL_NUMBERS_CFPQ } from "../questionBanks/class10/maths/real-numbers.cfpq";

export default defineChapter("real-numbers", [
  [6, REAL_NUMBERS_PACK1, true],
  [7, RN2_PACK2, true],
  [107, RN_NCERT, false],
  [108, RN_EXEMPLAR, false],
  [109, RN_EXTRACT, false],
  [110, RN_SCARCE_D, true],
  [111, RN_SCARCE_E, true],
  [112, RN_EXTRACT2, false],
  [113, RN_SCARCE2, true],
  [153, Z3_COMPETENCY_QUESTIONS, false],
  [166, REAL_NUMBERS_SQP, false],
  [191, RN_CBE, false],
  [217, RN_SP, false],
  [243, RN_PREBOARD, false],
  [256, REAL_NUMBERS_APQ, false],
  [308, REAL_NUMBERS_PYQ, false],
  [321, REAL_NUMBERS_PYQ_2026, false],
  [334, REAL_NUMBERS_PYQ_2024, false],
  [347, REAL_NUMBERS_PYQ_2025, false],
  [407, REAL_NUMBERS_CFPQ, false],
], [
  "RN-E14",
  "RN-H07",
  "RN2-016",
  "RN2-035",
  "RN2-056",
  "RN2-057",
  "RN2-058",
  "RN-N-NCERT-1-MCQ-003",
  "RN-N-NCERT-1-AR-001",
  "RN-N-NCERT-1-SA-004",
  "RN-N-NCERT-1-CB-002",
  "RN-N-EXMPLR-1-MCQ-005",
  "RN-N-EXMPLR-1-SA-004",
  "RN-N-EXMPLR-1-SA-005",
  "RN-N-EXMPLR-1-SA-007",
  "RN-N-EXMPLR-1-LA-002",
  "RN-N-EXMPLR-1-CB-002",
  "RNSP-001",
  "PYQ-M-2024-REALNUM-004",
  "PYQ-M-2024-REALNUM-005b",
  "PYQ-M-2025-REALNUM-003",
]);
