// GENERATED by lazytopper/scripts/generateBankChapters.ts (BANK-SPLIT-1 PR-2). DO NOT EDIT BY HAND.
// Regenerate from lazytopper/ with: pnpm run gen:bank-chapters
// src/data/bankChapters/bankChapters.guard.test.ts fails when this file disagrees with the aggregator.

// Chapter "statistics" (Maths): 304 served rows from 17 source arrays, 7 withheld.
// Each source is [spread position in RAW_CANONICAL_QUESTION_BANK, the array, is it an AI pack].

import { defineChapter } from "./defineChapter";
import { STATISTICS_PACK1 } from "../questionBanks/class10/maths/statistics.pack1";
import { ST2_PACK2 } from "../questionBanks/class10/maths/statistics.pack2";
import { STAT_NCERT } from "../questionBanks/class10/maths/statistics.ncert";
import { STAT_EXEMPLAR } from "../questionBanks/class10/maths/statistics.exemplar";
import { STAT_EXEMPLAR2 } from "../questionBanks/class10/maths/statistics.exemplar2";
import { Z3_COMPETENCY_QUESTIONS } from "../questionBanks/class10/maths/competency.z3";
import { STATISTICS_SQP } from "../questionBanks/class10/maths/statistics.sqp";
import { STAT_CBE } from "../questionBanks/class10/maths/statistics.cbe";
import { STAT_SP } from "../questionBanks/class10/maths/statistics.sp";
import { STAT_PREBOARD } from "../questionBanks/class10/maths/statistics.preboard";
import { STATISTICS_APQ } from "../questionBanks/class10/maths/statistics.additionalPQ";
import { STATISTICS_PYQ } from "../questionBanks/class10/maths/statistics.pyq";
import { STATISTICS_PYQ_2026 } from "../questionBanks/class10/maths/statistics.pyq2026";
import { STATISTICS_PYQ_2024 } from "../questionBanks/class10/maths/statistics.pyq2024";
import { STATISTICS_PYQ_2025 } from "../questionBanks/class10/maths/statistics.pyq2025";
import { CURATED_INLINE_QUESTIONS } from "../questionBanks/class10/curatedInline";
import { STATISTICS_CBQ_LT_GENERATED } from "../questionBanks/class10/maths/statistics.cbq.ltgen";

export default defineChapter("statistics", [
  [24, STATISTICS_PACK1, true],
  [25, ST2_PACK2, true],
  [144, STAT_NCERT, false],
  [145, STAT_EXEMPLAR, false],
  [149, STAT_EXEMPLAR2, false],
  [153, Z3_COMPETENCY_QUESTIONS, false],
  [177, STATISTICS_SQP, false],
  [201, STAT_CBE, false],
  [228, STAT_SP, false],
  [254, STAT_PREBOARD, false],
  [267, STATISTICS_APQ, false],
  [319, STATISTICS_PYQ, false],
  [332, STATISTICS_PYQ_2026, false],
  [345, STATISTICS_PYQ_2024, false],
  [357, STATISTICS_PYQ_2025, false],
  [415, CURATED_INLINE_QUESTIONS, false],
  [445, STATISTICS_CBQ_LT_GENERATED, false],
], [
  "STAT-M17",
  "APQ-M-STAT-003",
  "APQ-M-STAT-008",
  "PYQ-M-STAT-004",
  "PYQ-M-STAT-007",
  "PYQ-M-2025-STAT-004",
  "PYQ-M-2025-STAT-005",
]);
