// GENERATED by lazytopper/scripts/generateBankChapters.ts (BANK-SPLIT-1 PR-2). DO NOT EDIT BY HAND.
// Regenerate from lazytopper/ with: pnpm run gen:bank-chapters
// src/data/bankChapters/bankChapters.guard.test.ts fails when this file disagrees with the aggregator.

// Chapter "surface-areas-and-volumes" (Maths): 176 served rows from 16 source arrays, 21 withheld.
// Each source is [spread position in RAW_CANONICAL_QUESTION_BANK, the array, is it an AI pack].

import { defineChapter } from "./defineChapter";
import { SURFACE_AREAS_VOLUMES_PACK1 } from "../questionBanks/class10/maths/surfaceAreasVolumes.pack1";
import { SAV2_PACK2 } from "../questionBanks/class10/maths/surfaceAreasVolumes.pack2";
import { SAV_NCERT } from "../questionBanks/class10/maths/surfaceAreasAndVolumes.ncert";
import { SAV_EXEMPLAR } from "../questionBanks/class10/maths/surfaceAreasAndVolumes.exemplar";
import { SAV_EXEMPLAR2 } from "../questionBanks/class10/maths/surfaceAreasAndVolumes.exemplar2";
import { Z3_COMPETENCY_QUESTIONS } from "../questionBanks/class10/maths/competency.z3";
import { SURFACE_AREAS_AND_VOLUMES_SQP } from "../questionBanks/class10/maths/surface-areas-and-volumes.sqp";
import { SAV_CBE } from "../questionBanks/class10/maths/surface-areas-and-volumes.cbe";
import { SAV_SP } from "../questionBanks/class10/maths/surface-areas-and-volumes.sp";
import { SAV_PREBOARD } from "../questionBanks/class10/maths/surface-areas-and-volumes.preboard";
import { SURFACE_AREAS_AND_VOLUMES_APQ } from "../questionBanks/class10/maths/surface-areas-and-volumes.additionalPQ";
import { SURFACE_AREAS_AND_VOLUMES_PYQ } from "../questionBanks/class10/maths/surface-areas-and-volumes.pyq";
import { SURFACE_AREAS_AND_VOLUMES_PYQ_2026 } from "../questionBanks/class10/maths/surface-areas-and-volumes.pyq2026";
import { SURFACE_AREAS_AND_VOLUMES_PYQ_2024 } from "../questionBanks/class10/maths/surface-areas-and-volumes.pyq2024";
import { SURFACE_AREAS_AND_VOLUMES_PYQ_2025 } from "../questionBanks/class10/maths/surface-areas-and-volumes.pyq2025";
import { CURATED_INLINE_QUESTIONS } from "../questionBanks/class10/curatedInline";

export default defineChapter("surface-areas-and-volumes", [
  [22, SURFACE_AREAS_VOLUMES_PACK1, true],
  [23, SAV2_PACK2, true],
  [131, SAV_NCERT, false],
  [132, SAV_EXEMPLAR, false],
  [150, SAV_EXEMPLAR2, false],
  [153, Z3_COMPETENCY_QUESTIONS, false],
  [176, SURFACE_AREAS_AND_VOLUMES_SQP, false],
  [200, SAV_CBE, false],
  [227, SAV_SP, false],
  [253, SAV_PREBOARD, false],
  [266, SURFACE_AREAS_AND_VOLUMES_APQ, false],
  [318, SURFACE_AREAS_AND_VOLUMES_PYQ, false],
  [331, SURFACE_AREAS_AND_VOLUMES_PYQ_2026, false],
  [344, SURFACE_AREAS_AND_VOLUMES_PYQ_2024, false],
  [356, SURFACE_AREAS_AND_VOLUMES_PYQ_2025, false],
  [415, CURATED_INLINE_QUESTIONS, false],
], [
  "SAV-E09",
  "SAV-E20",
  "SAV-M03",
  "SAV-M09",
  "SAV-M11",
  "SAV-M19",
  "SAV-H04",
  "SAV-H13",
  "SAV2P1-R01",
  "SAV2-R01",
  "SAV2-R07",
  "SAV2-R08",
  "SAV2-R09",
  "SAV2-R10",
  "SAV2-R13",
  "SAV2-R14",
  "SAV2-R17",
  "SAV-N-EXMPLR-12-MCQ-005",
  "SAV-N-EXMPLR-12-CB-001",
  "SAV-N-EXEM2-12-LA-008",
  "CBE-M-SAV-D-001",
]);
