// GENERATED by lazytopper/scripts/generateBankChapters.ts (BANK-SPLIT-1 PR-2). DO NOT EDIT BY HAND.
// Regenerate from lazytopper/ with: pnpm run gen:bank-chapters
// src/data/bankChapters/bankChapters.guard.test.ts fails when this file disagrees with the aggregator.

// Chapter "triangles" (Maths): 309 served rows from 21 source arrays, 112 withheld.
// Each source is [spread position in RAW_CANONICAL_QUESTION_BANK, the array, is it an AI pack].

import { defineChapter } from "./defineChapter";
import { TRIANGLES_PACK1_QUESTIONS } from "../questionBanks/class10/maths/triangles.pack1";
import { trianglesPack2Questions } from "../questionBanks/class10/maths/triangles.pack2";
import { TR3_PACK3 } from "../questionBanks/class10/maths/triangles.pack3";
import { TRI_NCERT } from "../questionBanks/class10/maths/triangles.ncert";
import { TRI_EXEMPLAR } from "../questionBanks/class10/maths/triangles.exemplar";
import { Z3_COMPETENCY_QUESTIONS } from "../questionBanks/class10/maths/competency.z3";
import { TRIANGLES_AR_QUESTIONS } from "../questionBanks/class10/maths/triangles.assertionReasoning";
import { TRIANGLES_PROOF_QUESTIONS } from "../questionBanks/class10/maths/triangles.proof";
import { TRI_EXPAND_EXTRACT } from "../questionBanks/class10/maths/triangles.expand.extract";
import { TRI_EXPAND_LONG_D } from "../questionBanks/class10/maths/triangles.expand.longD";
import { TRI_EXPAND_PROOF } from "../questionBanks/class10/maths/triangles.expand.proof";
import { TRI_EXPAND_CASE_E } from "../questionBanks/class10/maths/triangles.expand.caseE";
import { MATHS_CASE_BASED_QUESTIONS } from "../questionBanks/class10/maths/maths.caseBased";
import { TRIANGLES_SQP } from "../questionBanks/class10/maths/triangles.sqp";
import { TRI_CBE } from "../questionBanks/class10/maths/triangles.cbe";
import { TRI_SP } from "../questionBanks/class10/maths/triangles.sp";
import { TRI_PREBOARD } from "../questionBanks/class10/maths/triangles.preboard";
import { TRIANGLES_APQ } from "../questionBanks/class10/maths/triangles.additionalPQ";
import { TRIANGLES_PYQ } from "../questionBanks/class10/maths/triangles.pyq";
import { TRIANGLES_PYQ_2026 } from "../questionBanks/class10/maths/triangles.pyq2026";
import { TRIANGLES_PYQ_2024 } from "../questionBanks/class10/maths/triangles.pyq2024";

export default defineChapter("triangles", [
  [0, TRIANGLES_PACK1_QUESTIONS, true],
  [1, trianglesPack2Questions, true],
  [2, TR3_PACK3, true],
  [122, TRI_NCERT, false],
  [123, TRI_EXEMPLAR, false],
  [153, Z3_COMPETENCY_QUESTIONS, false],
  [154, TRIANGLES_AR_QUESTIONS, false],
  [156, TRIANGLES_PROOF_QUESTIONS, false],
  [157, TRI_EXPAND_EXTRACT, false],
  [158, TRI_EXPAND_LONG_D, false],
  [159, TRI_EXPAND_PROOF, false],
  [160, TRI_EXPAND_CASE_E, false],
  [163, MATHS_CASE_BASED_QUESTIONS, false],
  [171, TRIANGLES_SQP, false],
  [196, TRI_CBE, false],
  [222, TRI_SP, false],
  [248, TRI_PREBOARD, false],
  [261, TRIANGLES_APQ, false],
  [313, TRIANGLES_PYQ, false],
  [326, TRIANGLES_PYQ_2026, false],
  [339, TRIANGLES_PYQ_2024, false],
], [
  "2026-TRI-P1-A-004",
  "2026-TRI-P1-A-009",
  "2026-TRI-P1-A-015",
  "2026-TRI-P1-A-016",
  "2026-TRI-P1-A-018",
  "2026-TRI-P1-B-006",
  "2026-TRI-P1-C-003",
  "2026-TRI-P1-C-008",
  "2026-TRI-P1-D-001",
  "2026-TRI-P1-D-002",
  "2026-TRI-P1-E-001",
  "2026-TRI-P1-E-004",
  "2026-TRI-P1-E-006",
  "TRI2-E08",
  "TRI2-E09",
  "TRI2-AR01",
  "TRI2-AR03",
  "TRI2-M03",
  "TRI2-H03",
  "TRI2-H04",
  "TRI2-E12",
  "TRI2-H06",
  "TRI2-CB01",
  "TRI2-E15",
  "TRI2-E20",
  "TR3-011",
  "TR3-013",
  "TR3-016",
  "TR3-017",
  "TR3-018",
  "TR3-019",
  "TR3-022",
  "TR3-024",
  "TR3-025",
  "TR3-027",
  "TR3-042",
  "TR3-044",
  "TR3-045",
  "TR3-046",
  "TR3-047",
  "TR3-053",
  "TR3-058",
  "TR3-061",
  "TR3-064",
  "TRI-N-NCERT-6-MCQ-003",
  "TRI-N-NCERT-6-LA-007",
  "TRI-N-NCERT-6-MCQ-004",
  "TRI-N-NCERT-6-AR-002",
  "TRI-N-EXMPLR-6-MCQ-008",
  "TRI-N-EXMPLR-6-SA-001",
  "AR-TRI-004",
  "AR-TRI-005",
  "AR-TRI-008",
  "AR-TRI-010",
  "TRI-PRF-D-002",
  "TRI-PRF-D-003",
  "TRI-PRF-D-004",
  "TRI-PRF-D-007",
  "TRI-PRF-C-003",
  "BX-TRI-EX-A-001",
  "BX-TRI-EX-A-004",
  "BX-TRI-EX-A-006",
  "BX-TRI-EX-A-009",
  "BX-TRI-EX-C-002",
  "BX-TRI-D-004",
  "BX-TRI-D-005",
  "BX-TRI-D-006",
  "BX-TRI-D-016",
  "BX-TRI-D-032",
  "BX-TRI-D-041",
  "BX-TRI-D-043",
  "BX-TRI-PF-001",
  "BX-TRI-PF-002",
  "BX-TRI-PF-004",
  "BX-TRI-PF-006",
  "BX-TRI-PF-008",
  "BX-TRI-PF-009",
  "BX-TRI-PF-010",
  "BX-TRI-PF-011",
  "BX-TRI-PF-013",
  "BX-TRI-PF-019",
  "BX-TRI-PF-020",
  "BX-TRI-E-004",
  "BX-TRI-E-006",
  "BX-TRI-E-008",
  "BX-TRI-E-010",
  "BX-TRI-E-014",
  "BX-TRI-E-015",
  "BX-TRI-E-017",
  "BX-TRI-E-021",
  "BX-TRI-E-023",
  "BX-TRI-E-024",
  "BX-TRI-E-029",
  "BX-TRI-E-030",
  "BX-TRI-E-033",
  "BX-TRI-E-034",
  "BX-TRI-E-035",
  "BX-TRI-E-038",
  "BX-TRI-E-039",
  "BX-TRI-E-040",
  "BX-TRI-E-044",
  "BX-TRI-E-045",
  "CASE-MATHS-TRI-001",
  "CASE-MATHS-TRI-002",
  "CBE-M-TRI-A-004",
  "CBE-M-TRI-C-006",
  "SP-M-2022-TRI-A-001",
  "SP-M-2022-TRI-A-003",
  "PB-M-1-TRI-A-001",
  "PB-M-1-TRI-C-001",
  "PB-M-2-TRI-A-001",
  "PYQ-M-TRI-001",
]);
