// GENERATED by lazytopper/scripts/generateBankChapters.ts (BANK-SPLIT-1 PR-2). DO NOT EDIT BY HAND.
// Regenerate from lazytopper/ with: pnpm run gen:bank-chapters
// src/data/bankChapters/bankChapters.guard.test.ts fails when this file disagrees with the aggregator.

// Chapter "triangles" (Maths): 420 served rows from 21 source arrays, 1 withheld.
// Each source is [spread position in RAW_CANONICAL_QUESTION_BANK, the array, is it an AI pack].

import { defineChapter } from "./defineChapter";
import { TRIANGLES_PACK1_QUESTIONS } from "../questionBanks/class10/maths/triangles.pack1";
import { trianglesPack2Questions } from "../questionBanks/class10/maths/triangles.pack2";
import { TR3_PACK3 } from "../questionBanks/class10/maths/triangles.pack3";
import { TRI_NCERT } from "../questionBanks/class10/maths/triangles.ncert";
import { TRI_EXEMPLAR } from "../questionBanks/class10/maths/triangles.exemplar";
import { Z3_COMPETENCY_QUESTIONS } from "../questionBanks/class10/maths/competency.z3";
import { TRIANGLES_AR_QUESTIONS } from "../questionBanks/class10/maths/triangles.assertionReasoning";
import { TRIANGLES_PROOF_QUESTIONS } from "../questionBanks/class10/maths/triangles.proof";
import { TRI_EXPAND_EXTRACT } from "../questionBanks/class10/maths/triangles.expand.extract";
import { TRI_EXPAND_LONG_D } from "../questionBanks/class10/maths/triangles.expand.longD";
import { TRI_EXPAND_PROOF } from "../questionBanks/class10/maths/triangles.expand.proof";
import { TRI_EXPAND_CASE_E } from "../questionBanks/class10/maths/triangles.expand.caseE";
import { MATHS_CASE_BASED_QUESTIONS } from "../questionBanks/class10/maths/maths.caseBased";
import { TRIANGLES_SQP } from "../questionBanks/class10/maths/triangles.sqp";
import { TRI_CBE } from "../questionBanks/class10/maths/triangles.cbe";
import { TRI_SP } from "../questionBanks/class10/maths/triangles.sp";
import { TRI_PREBOARD } from "../questionBanks/class10/maths/triangles.preboard";
import { TRIANGLES_APQ } from "../questionBanks/class10/maths/triangles.additionalPQ";
import { TRIANGLES_PYQ } from "../questionBanks/class10/maths/triangles.pyq";
import { TRIANGLES_PYQ_2026 } from "../questionBanks/class10/maths/triangles.pyq2026";
import { TRIANGLES_PYQ_2024 } from "../questionBanks/class10/maths/triangles.pyq2024";

export default defineChapter("triangles", [
  [0, TRIANGLES_PACK1_QUESTIONS, true],
  [1, trianglesPack2Questions, true],
  [2, TR3_PACK3, true],
  [122, TRI_NCERT, false],
  [123, TRI_EXEMPLAR, false],
  [153, Z3_COMPETENCY_QUESTIONS, false],
  [154, TRIANGLES_AR_QUESTIONS, false],
  [156, TRIANGLES_PROOF_QUESTIONS, false],
  [157, TRI_EXPAND_EXTRACT, false],
  [158, TRI_EXPAND_LONG_D, false],
  [159, TRI_EXPAND_PROOF, false],
  [160, TRI_EXPAND_CASE_E, false],
  [163, MATHS_CASE_BASED_QUESTIONS, false],
  [171, TRIANGLES_SQP, false],
  [196, TRI_CBE, false],
  [222, TRI_SP, false],
  [248, TRI_PREBOARD, false],
  [261, TRIANGLES_APQ, false],
  [313, TRIANGLES_PYQ, false],
  [326, TRIANGLES_PYQ_2026, false],
  [339, TRIANGLES_PYQ_2024, false],
], [
  "PYQ-M-TRI-001",
]);
