// GENERATED by lazytopper/scripts/generateBankChapters.ts (BANK-SPLIT-1 PR-2). DO NOT EDIT BY HAND.
// Regenerate from lazytopper/ with: pnpm run gen:bank-chapters
// src/data/bankChapters/bankChapters.guard.test.ts fails when this file disagrees with the aggregator.

// Chapter "trigonometry" (Maths): 417 served rows from 18 source arrays, 14 withheld.
// Each source is [spread position in RAW_CANONICAL_QUESTION_BANK, the array, is it an AI pack].

import { defineChapter } from "./defineChapter";
import { TRIG_PACK1_QUESTIONS } from "../questionBanks/class10/maths/trigonometry.pack1";
import { trigonometryPack2Questions } from "../questionBanks/class10/maths/trigonometry.pack2";
import { TG3_PACK3 } from "../questionBanks/class10/maths/trigonometry.pack3";
import { TRIG_NCERT } from "../questionBanks/class10/maths/trigonometry.ncert";
import { TRIG_EXEMPLAR } from "../questionBanks/class10/maths/trigonometry.exemplar";
import { Z3_COMPETENCY_QUESTIONS } from "../questionBanks/class10/maths/competency.z3";
import { TRIGONOMETRY_AR_QUESTIONS } from "../questionBanks/class10/maths/trigonometry.assertionReasoning";
import { TRIGONOMETRY_PROOF_QUESTIONS } from "../questionBanks/class10/maths/trigonometry.proof";
import { TRIGONOMETRY_SQP } from "../questionBanks/class10/maths/trigonometry.sqp";
import { TRIG_CBE } from "../questionBanks/class10/maths/trigonometry.cbe";
import { TRIG_SP } from "../questionBanks/class10/maths/trigonometry.sp";
import { TRIG_PREBOARD } from "../questionBanks/class10/maths/trigonometry.preboard";
import { TRIGONOMETRY_APQ } from "../questionBanks/class10/maths/trigonometry.additionalPQ";
import { TRIGONOMETRY_PYQ } from "../questionBanks/class10/maths/trigonometry.pyq";
import { TRIGONOMETRY_PYQ_2026 } from "../questionBanks/class10/maths/trigonometry.pyq2026";
import { TRIGONOMETRY_PYQ_2024 } from "../questionBanks/class10/maths/trigonometry.pyq2024";
import { TRIGONOMETRY_PYQ_2025 } from "../questionBanks/class10/maths/trigonometry.pyq2025";
import { CURATED_INLINE_QUESTIONS } from "../questionBanks/class10/curatedInline";

export default defineChapter("trigonometry", [
  [3, TRIG_PACK1_QUESTIONS, true],
  [4, trigonometryPack2Questions, true],
  [5, TG3_PACK3, true],
  [129, TRIG_NCERT, false],
  [130, TRIG_EXEMPLAR, false],
  [153, Z3_COMPETENCY_QUESTIONS, false],
  [155, TRIGONOMETRY_AR_QUESTIONS, false],
  [161, TRIGONOMETRY_PROOF_QUESTIONS, false],
  [173, TRIGONOMETRY_SQP, false],
  [203, TRIG_CBE, false],
  [224, TRIG_SP, false],
  [250, TRIG_PREBOARD, false],
  [263, TRIGONOMETRY_APQ, false],
  [315, TRIGONOMETRY_PYQ, false],
  [328, TRIGONOMETRY_PYQ_2026, false],
  [341, TRIGONOMETRY_PYQ_2024, false],
  [353, TRIGONOMETRY_PYQ_2025, false],
  [415, CURATED_INLINE_QUESTIONS, false],
], [
  "TRIG2-H09",
  "TRIG2-E12",
  "PYQ-M-TRIG-002",
  "PYQ-M-TRIG-003",
  "PYQ-M-TRIG-005",
  "PYQ-M-TRIG-006",
  "PYQ-M-TRIG-007",
  "PYQ-M-2024-TRIG-010a",
  "PYQ-M-2024-TRIG-010b",
  "PYQ-M-2024-TRIG-011a",
  "PYQ-M-2024-TRIG-012",
  "PYQ-M-2024-TRIG-013",
  "PYQ-M-2024-TRIG-019",
  "PYQ-M-2025-TRIG-001",
]);
