// GENERATED by lazytopper/scripts/generateBankChapters.ts (BANK-SPLIT-1 PR-2). DO NOT EDIT BY HAND.
// Regenerate from lazytopper/ with: pnpm run gen:bank-chapters
// src/data/bankChapters/bankChapters.guard.test.ts fails when this file disagrees with the aggregator.

// Chapter "trigonometry" (Maths): 488 served rows from 20 source arrays, 48 withheld.
// Each source is [spread position in RAW_CANONICAL_QUESTION_BANK, the array, is it an AI pack].

import { defineChapter } from "./defineChapter";
import { TR3_PACK3 } from "../questionBanks/class10/maths/triangles.pack3";
import { TRIG_PACK1_QUESTIONS } from "../questionBanks/class10/maths/trigonometry.pack1";
import { trigonometryPack2Questions } from "../questionBanks/class10/maths/trigonometry.pack2";
import { TG3_PACK3 } from "../questionBanks/class10/maths/trigonometry.pack3";
import { TRIG_NCERT } from "../questionBanks/class10/maths/trigonometry.ncert";
import { TRIG_EXEMPLAR } from "../questionBanks/class10/maths/trigonometry.exemplar";
import { Z3_COMPETENCY_QUESTIONS } from "../questionBanks/class10/maths/competency.z3";
import { TRIGONOMETRY_AR_QUESTIONS } from "../questionBanks/class10/maths/trigonometry.assertionReasoning";
import { TRIGONOMETRY_PROOF_QUESTIONS } from "../questionBanks/class10/maths/trigonometry.proof";
import { TRIGONOMETRY_SQP } from "../questionBanks/class10/maths/trigonometry.sqp";
import { TRIG_CBE } from "../questionBanks/class10/maths/trigonometry.cbe";
import { TRIG_SP } from "../questionBanks/class10/maths/trigonometry.sp";
import { TRIG_PREBOARD } from "../questionBanks/class10/maths/trigonometry.preboard";
import { TRIGONOMETRY_APQ } from "../questionBanks/class10/maths/trigonometry.additionalPQ";
import { TRIGONOMETRY_PYQ } from "../questionBanks/class10/maths/trigonometry.pyq";
import { TRIGONOMETRY_PYQ_2026 } from "../questionBanks/class10/maths/trigonometry.pyq2026";
import { TRIGONOMETRY_PYQ_2024 } from "../questionBanks/class10/maths/trigonometry.pyq2024";
import { TRIGONOMETRY_PYQ_2025 } from "../questionBanks/class10/maths/trigonometry.pyq2025";
import { CURATED_INLINE_QUESTIONS } from "../questionBanks/class10/curatedInline";
import { TRIGONOMETRY_CBQ_LT_GENERATED } from "../questionBanks/class10/maths/trigonometry.cbq.ltgen";

export default defineChapter("trigonometry", [
  [2, TR3_PACK3, true],
  [3, TRIG_PACK1_QUESTIONS, true],
  [4, trigonometryPack2Questions, true],
  [5, TG3_PACK3, true],
  [129, TRIG_NCERT, false],
  [130, TRIG_EXEMPLAR, false],
  [153, Z3_COMPETENCY_QUESTIONS, false],
  [155, TRIGONOMETRY_AR_QUESTIONS, false],
  [161, TRIGONOMETRY_PROOF_QUESTIONS, false],
  [173, TRIGONOMETRY_SQP, false],
  [203, TRIG_CBE, false],
  [224, TRIG_SP, false],
  [250, TRIG_PREBOARD, false],
  [263, TRIGONOMETRY_APQ, false],
  [315, TRIGONOMETRY_PYQ, false],
  [328, TRIGONOMETRY_PYQ_2026, false],
  [341, TRIGONOMETRY_PYQ_2024, false],
  [353, TRIGONOMETRY_PYQ_2025, false],
  [415, CURATED_INLINE_QUESTIONS, false],
  [436, TRIGONOMETRY_CBQ_LT_GENERATED, false],
], [
  "TRIG2-E08",
  "TRIG2-E09",
  "TRIG2-M01",
  "TRIG2-M05",
  "TRIG2-M07",
  "TRIG2-H02",
  "TRIG2-H06",
  "TRIG2-H09",
  "TRIG2-E12",
  "TG3-019",
  "TG3-023",
  "TG3-047",
  "TRIG-N-NCERT-8-SA-009",
  "TRIG-N-NCERT-8-SA-010",
  "TRIG-N-NCERT-8-SA-011",
  "TRIG-N-NCERT-8-SA-012",
  "TRIG-N-EXMPLR-8-MCQ-003",
  "TRIG-N-EXMPLR-8-MCQ-005",
  "TRIG-N-EXMPLR-8-MCQ-006",
  "TRIG-N-EXMPLR-8-SA-001",
  "TRIG-N-EXMPLR-9-LA-002",
  "TRIG-N-EXMPLR-9-LA-006",
  "Z3-TG-110",
  "AR-TRIG-001",
  "TRIG-PRF-D-005",
  "TRIG-PRF-C-005",
  "PB-M-1-TRIG-C-001",
  "PB-M-1-TRIG-C-002",
  "PB-M-2-TRIG-C-001",
  "PB-M-2-TRIG-C-002",
  "APQ-M-TRIG-001",
  "APQ-M-TRIG-003",
  "APQ-M-TRIG-010",
  "APQ-M-TRIG-017",
  "PYQ-M-TRIG-002",
  "PYQ-M-TRIG-003",
  "PYQ-M-TRIG-005",
  "PYQ-M-TRIG-006",
  "PYQ-M-TRIG-007",
  "PYQ-M-2026-TRIG-002",
  "PYQ-M-2024-TRIG-010a",
  "PYQ-M-2024-TRIG-010b",
  "PYQ-M-2024-TRIG-011a",
  "PYQ-M-2024-TRIG-012",
  "PYQ-M-2024-TRIG-013",
  "PYQ-M-2024-TRIG-019",
  "PYQ-M-2025-TRIG-001",
  "PYQ-M-2025-TRIG-004",
]);
