kind = "api"
previewPath = "/shared-api"
title = "API Server"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "API Server"
paths = ["/shared-api", "/"]

[services.development]
run = "pnpm --filter @workspace/api-server run dev"

[services.production]

[services.production.build]
args = ["bash", "-c", "pnpm --filter @workspace/api-server run build && pnpm --filter @workspace/lazytopper-app run build && cp -r artifacts/lazytopper-app/dist/public artifacts/api-server/dist/public"]

[services.production.build.env]
NODE_ENV = "production"

[services.production.run]
args = ["node", "--enable-source-maps", "artifacts/api-server/dist/index.mjs"]

[services.production.run.env]
PORT = "8080"
NODE_ENV = "production"

[services.production.health.startup]
path = "/shared-api/healthz"
