/**
 * renderBankChapters — the PURE half of the BANK-SPLIT-1 PR-2 generator (L2 + L3).
 *
 * Given the aggregator's SOURCE TEXT (src/data/canonicalQuestionBank.ts), the exported
 * array behind every name it spreads, and its withheld id set, this computes the exact
 * text of every generated file under src/data/bankChapters/:
 *
 *   <slug>.ts                       one per chapter: imports ONLY the pack arrays that hold
 *                                   rows of that chapter, in aggregator spread order, and
 *                                   lists that chapter's withheld ids. No row data.
 *   chapterRegistry.generated.ts    the 26 slugs, their subject, and one literal import()
 *                                   per chapter (so the bundler emits one chunk each).
 *   bankIdIndex.generated.ts        served id -> {topicKey, subtopic, section}, aggregator
 *                                   order, for the id lookups that must not load the bank.
 *
 * Both the CLI (scripts/generateBankChapters.ts) and the guard
 * (src/data/bankChapters/bankChapters.guard.test.ts) call this, so "the committed files
 * are what the generator produces from the aggregator RIGHT NOW" is a byte compare.
 * No I/O here.
 */

import type { CanonicalQuestion } from "../../src/data/predictionTypes";

export interface AggregatorShape {
  /** exported name -> module specifier, as written in the aggregator (relative to src/data). */
  imports: Map<string, string>;
  /** identifiers spread into RAW_CANONICAL_QUESTION_BANK, in order. */
  spreads: string[];
  /** identifiers listed in AI_GENERATED_PACK_SOURCES. */
  aiSources: Set<string>;
}

export interface ChapterInfo {
  slug: string;
  subject: "Maths" | "Science";
}

export interface ChapterSourcePlan {
  spreadIndex: number;
  name: string;
  /** specifier relative to src/data/bankChapters/ */
  spec: string;
  ai: boolean;
}

export interface ChapterPlan {
  slug: string;
  subject: "Maths" | "Science";
  sources: ChapterSourcePlan[];
  withheld: string[];
  servedRows: number;
}

const GENERATED_BANNER =
  "// GENERATED by lazytopper/scripts/generateBankChapters.ts (BANK-SPLIT-1 PR-2). DO NOT EDIT BY HAND.\n" +
  "// Regenerate from lazytopper/ with: pnpm run gen:bank-chapters\n" +
  "// src/data/bankChapters/bankChapters.guard.test.ts fails when this file disagrees with the aggregator.\n";

function between(src: string, startMarker: string, endMarker: string): string {
  const start = src.indexOf(startMarker);
  if (start < 0) throw new Error(`aggregator: marker not found: ${startMarker}`);
  const from = start + startMarker.length;
  const end = src.indexOf(endMarker, from);
  if (end < 0) throw new Error(`aggregator: end marker not found after: ${startMarker}`);
  return src.slice(from, end);
}

function stripLineComments(block: string): string {
  return block
    .split("\n")
    .map((l) => l.replace(/\/\/.*$/, ""))
    .join("\n");
}

/** Parse the three facts the generator needs out of canonicalQuestionBank.ts. */
export function parseAggregator(src: string): AggregatorShape {
  const imports = new Map<string, string>();
  const importRe = /^import\s+\{([^}]*)\}\s+from\s+['"](\.\/questionBanks\/[^'"]+)['"];?\s*$/gm;
  for (const m of src.matchAll(importRe)) {
    for (const raw of m[1].split(",")) {
      const part = raw.trim();
      if (!part) continue;
      if (/\s+as\s+/.test(part)) throw new Error(`aggregator: aliased import not supported: ${part}`);
      imports.set(part, m[2]);
    }
  }
  const rawBlock = stripLineComments(
    between(src, "export const RAW_CANONICAL_QUESTION_BANK: CanonicalQuestion[] = [", "\n];"),
  );
  const spreads: string[] = [];
  for (const line of rawBlock.split("\n")) {
    const t = line.trim();
    if (!t) continue;
    const m = /^\.\.\.([A-Za-z_$][\w$]*),?$/.exec(t);
    if (!m) throw new Error(`aggregator: RAW entry is not a plain spread: ${t.slice(0, 80)}`);
    spreads.push(m[1]);
  }
  const aiBlock = stripLineComments(
    between(src, "const AI_GENERATED_PACK_SOURCES: ReadonlyArray<ReadonlyArray<CanonicalQuestion>> = [", "\n];"),
  );
  const aiSources = new Set<string>();
  for (const line of aiBlock.split("\n")) {
    const t = line.trim().replace(/,$/, "");
    if (!t) continue;
    if (!/^[A-Za-z_$][\w$]*$/.test(t)) throw new Error(`aggregator: AI source is not an identifier: ${t}`);
    aiSources.add(t);
  }
  for (const name of [...spreads, ...aiSources]) {
    if (!imports.has(name)) throw new Error(`aggregator: ${name} is not imported from a pack file`);
  }
  return { imports, spreads, aiSources };
}

/**
 * Plan every chapter. `arrays` maps each spread name to its exported array; `slugOf`
 * resolves a row's topicKey to its canonical slug (resolveCanonicalSlug).
 */
export function planChapters(
  shape: AggregatorShape,
  arrays: ReadonlyMap<string, readonly CanonicalQuestion[]>,
  withheld: ReadonlySet<string>,
  chapters: readonly ChapterInfo[],
  slugOf: (topicKey: string) => string,
): ChapterPlan[] {
  const known = new Set(chapters.map((c) => c.slug));
  const plans = new Map<string, ChapterPlan>(
    chapters.map((c) => [c.slug, { slug: c.slug, subject: c.subject, sources: [], withheld: [], servedRows: 0 }]),
  );
  shape.spreads.forEach((name, spreadIndex) => {
    const rows = arrays.get(name);
    if (!rows) throw new Error(`no array loaded for spread ${name}`);
    const touched = new Set<string>();
    for (const q of rows) {
      const slug = slugOf(q.topicKey);
      if (!known.has(slug)) throw new Error(`row ${q.id} (${name}) has topicKey ${q.topicKey} -> ${slug}, not a registry chapter`);
      const plan = plans.get(slug)!;
      if (q.subject !== plan.subject) throw new Error(`row ${q.id} is ${q.subject} but chapter ${slug} is ${plan.subject}`);
      touched.add(slug);
      if (withheld.has(q.id)) plan.withheld.push(q.id);
      else plan.servedRows += 1;
    }
    const spec = shape.imports.get(name)!.replace(/^\.\//, "../");
    for (const slug of touched) {
      plans.get(slug)!.sources.push({ spreadIndex, name, spec, ai: shape.aiSources.has(name) });
    }
  });
  return chapters.map((c) => plans.get(c.slug)!);
}

export function renderChapterModule(plan: ChapterPlan): string {
  const bySpec = new Map<string, string[]>();
  for (const s of plan.sources) {
    const names = bySpec.get(s.spec) ?? [];
    if (!names.includes(s.name)) names.push(s.name);
    bySpec.set(s.spec, names);
  }
  const lines: string[] = [GENERATED_BANNER];
  lines.push(
    `// Chapter "${plan.slug}" (${plan.subject}): ${plan.servedRows} served rows from ${plan.sources.length} source arrays, ${plan.withheld.length} withheld.`,
  );
  lines.push("// Each source is [spread position in RAW_CANONICAL_QUESTION_BANK, the array, is it an AI pack].");
  lines.push("");
  lines.push('import { defineChapter } from "./defineChapter";');
  for (const [spec, names] of bySpec) lines.push(`import { ${names.join(", ")} } from "${spec}";`);
  lines.push("");
  lines.push(`export default defineChapter(${JSON.stringify(plan.slug)}, [`);
  for (const s of plan.sources) lines.push(`  [${s.spreadIndex}, ${s.name}, ${s.ai}],`);
  lines.push("], [");
  for (const id of plan.withheld) lines.push(`  ${JSON.stringify(id)},`);
  lines.push("]);");
  lines.push("");
  return lines.join("\n");
}

export function renderChapterRegistry(plans: readonly ChapterPlan[]): string {
  const lines: string[] = [GENERATED_BANNER];
  lines.push("// The chapter list, each chapter's subject, and ONE literal import() per chapter, so the");
  lines.push("// bundler emits a separate chunk for every chapter. Only the loader imports this file.");
  lines.push("");
  lines.push('import type { BankChapter } from "./defineChapter";');
  lines.push("");
  lines.push("export const BANK_CHAPTER_SLUGS = [");
  for (const p of plans) lines.push(`  ${JSON.stringify(p.slug)},`);
  lines.push("] as const;");
  lines.push("");
  lines.push("export type BankChapterSlug = (typeof BANK_CHAPTER_SLUGS)[number];");
  lines.push("");
  lines.push('export const BANK_CHAPTER_SUBJECT: Readonly<Record<BankChapterSlug, "Maths" | "Science">> = {');
  for (const p of plans) lines.push(`  ${JSON.stringify(p.slug)}: ${JSON.stringify(p.subject)},`);
  lines.push("};");
  lines.push("");
  lines.push(
    "export const BANK_CHAPTER_LOADERS: Readonly<Record<BankChapterSlug, () => Promise<{ default: BankChapter }>>> = {",
  );
  for (const p of plans) lines.push(`  ${JSON.stringify(p.slug)}: () => import("./${p.slug}"),`);
  lines.push("};");
  lines.push("");
  return lines.join("\n");
}

/** The id index: served rows, aggregator order. Values are stored raw; readers trim. */
export function renderBankIdIndex(served: readonly CanonicalQuestion[]): string {
  const tables = { topicKeys: [] as string[], subtopics: [] as string[], sections: [] as string[] };
  const ix = { topicKeys: new Map<string, number>(), subtopics: new Map<string, number>(), sections: new Map<string, number>() };
  const intern = (k: keyof typeof tables, v: string): number => {
    let n = ix[k].get(v);
    if (n === undefined) {
      n = tables[k].length;
      tables[k].push(v);
      ix[k].set(v, n);
    }
    return n;
  };
  const rows: string[] = [];
  for (const q of served) {
    if (!q || typeof q.id !== "string" || !q.id) continue;
    const t = intern("topicKeys", String(q.topicKey || ""));
    const s = intern("subtopics", typeof q.subtopic === "string" ? q.subtopic : "");
    const c = intern("sections", typeof q.section === "string" ? q.section : "");
    rows.push(`  [${JSON.stringify(q.id)}, ${t}, ${s}, ${c}],`);
  }
  const list = (name: string, values: string[]) =>
    [`export const ${name}: readonly string[] = [`, ...values.map((v) => `  ${JSON.stringify(v)},`), "];", ""];
  return [
    GENERATED_BANNER,
    `// Served bank id -> {topicKey, subtopic, section} for ${rows.length} rows, in aggregator order.`,
    "// Ids and tags only, never question content. Read through ./bankIdIndex.ts.",
    "",
    ...list("BANK_ID_INDEX_TOPIC_KEYS", tables.topicKeys),
    ...list("BANK_ID_INDEX_SUBTOPICS", tables.subtopics),
    ...list("BANK_ID_INDEX_SECTIONS", tables.sections),
    "/** [id, topicKey index, subtopic index, section index] */",
    "export const BANK_ID_INDEX_ROWS: ReadonlyArray<readonly [string, number, number, number]> = [",
    ...rows,
    "];",
    "",
  ].join("\n");
}

/** Every generated file, by path relative to src/data/bankChapters/. */
export function renderAll(plans: readonly ChapterPlan[], served: readonly CanonicalQuestion[]): Map<string, string> {
  const out = new Map<string, string>();
  for (const p of plans) out.set(`${p.slug}.ts`, renderChapterModule(p));
  out.set("chapterRegistry.generated.ts", renderChapterRegistry(plans));
  out.set("bankIdIndex.generated.ts", renderBankIdIndex(served));
  return out;
}
