/**
 * Areas related to circles — computed SOLUTION figures (DIAGRAMS-1 PR-2d).
 *
 * One entry per served row whose solution is a figure the row's OWN numbers fix
 * exactly (tangents from an external point, concentric circles, an inscribed circle,
 * BPT, plotted points, a sector or segment). Every row was read in full (question,
 * steps, answer) and its rendered figure eye-checked. Rows read and REFUSED (not fixed
 * by the row, no builder template, an official question figure already bound, the
 * row's own solution inconsistent, ...) are listed in the PR, not here — an unbound
 * row shows no figure, never a lookalike.
 *
 * `params` holds only numbers read from the row (each quoted in `provenance`, an exact
 * substring of the served row); `draw` holds display choices; `expect` is the row's own
 * answer. computedFigures.provenance.test.ts enforces both.
 *
 * GENERATED from the PR-2d decision table; edit the decisions, not this file by hand.
 */
import type { ComputedFigureBinding } from "./computedFigureTypes";

export const AREAS_RELATED_TO_CIRCLES_SOLUTION_FIGURES: ComputedFigureBinding[] = [
  {
    kind: "computed",
    questionId: "ARC-E02",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "6", "theta": 60},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 6 cm"},
      {"param": "theta", "field": "questionText", "quote": "angle 60°"},
    ],
    expect: [
      {"quantity": "sector", "value": 18.8496, "tolPct": 0.5, "quote": "6π cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC-E04",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "14", "theta": 90},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 14 cm"},
      {"param": "theta", "field": "questionText", "quote": "angle 90°"},
    ],
    expect: [
      {"quantity": "arc", "value": 22, "tolPct": 0.5, "quote": "22 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC-E05",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "4", "theta": 30},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 4 cm"},
      {"param": "theta", "field": "questionText", "quote": "angle 30°"},
    ],
    expect: [
      {"quantity": "sector", "value": 4.18879, "tolPct": 0.5, "quote": "4π/3 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC-E09",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "7", "theta": 90},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 7 cm"},
      {"param": "theta", "field": "questionText", "quote": "a quadrant", "derived": "a quadrant is a sector of 90°"},
    ],
    expect: [
      {"quantity": "perimeterSector", "value": 25, "tolPct": 0.5, "quote": "25 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC-E12",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "12", "theta": 120},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "12 cm long"},
      {"param": "theta", "field": "questionText", "quote": "in 20 minutes", "derived": "20 minutes × 6° per minute = 120°"},
    ],
    expect: [
      {"quantity": "sector", "value": 150.796, "tolPct": 0.5, "quote": "48π cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC-E15",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "21", "theta": 120},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 21 cm"},
      {"param": "theta", "field": "questionText", "quote": "angle 120°"},
    ],
    expect: [
      {"quantity": "sector", "value": 462, "tolPct": 0.5, "quote": "462 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC-E16",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "10", "theta": 90},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 10 cm"},
      {"param": "theta", "field": "questionText", "quote": "subtends a right angle", "derived": "a right angle = 90°"},
    ],
    expect: [
      {"quantity": "sector", "value": 78.5398, "tolPct": 0.5, "quote": "25π cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC-E18",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "21", "arc": "22"},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius is 21 cm"},
      {"param": "arc", "field": "questionText", "quote": "arc length is 22 cm"},
    ],
    expect: [
      {"quantity": "sector", "value": 231, "tolPct": 0.5, "quote": "231 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC-M01",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "14", "theta": 60},
    draw: {"shade": "segment"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 14 cm"},
      {"param": "theta", "field": "questionText", "quote": "central angle of 60°"},
    ],
    expect: [
      {"quantity": "segment", "value": 17.8, "tolPct": 0.5, "quote": "17.8 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC-M03",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "12", "theta": 120},
    draw: {"shade": "segment"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 12 cm"},
      {"param": "theta", "field": "questionText", "quote": "angle of 120°"},
    ],
    expect: [
      {"quantity": "segment", "value": 88.44, "tolPct": 0.5, "quote": "88.44 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC-M07",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "mm", "r": "17.5", "theta": 36},
    draw: {"shade": "sector"},
    part: "(ii)–(iv)",
    provenance: [
      {"param": "r", "field": "solutionSteps", "quote": "π(17.5)²", "derived": "radius = half the 35 mm diameter"},
      {"param": "theta", "field": "finalAnswer", "quote": "(iii) 36°", "derived": "the row's own answer: 360°/10"},
    ],
    expect: [
      {"quantity": "sector", "value": 96.25, "tolPct": 0.5, "quote": "(ii) 96.25 mm²"},
      {"quantity": "arc", "value": 11, "tolPct": 0.5, "quote": "(iv) 11 mm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC-M08",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "21", "theta": 60},
    draw: {"shade": "segment"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 21 cm"},
      {"param": "theta", "field": "questionText", "quote": "subtends 60°"},
    ],
    expect: [
      {"quantity": "arc", "value": 22, "tolPct": 0.5, "quote": "(i) 22 cm"},
      {"quantity": "sector", "value": 231, "tolPct": 0.5, "quote": "(ii) 231 cm²"},
      {"quantity": "segment", "value": 40.05, "tolPct": 0.5, "quote": "≈ 40.05 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC-M10",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "7", "theta": 90},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 7 cm"},
      {"param": "theta", "field": "questionText", "quote": "angle 90°"},
    ],
    expect: [
      {"quantity": "sector", "value": 38.5, "tolPct": 0.5, "quote": "38.5 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC-M13",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "14", "theta": 30},
    draw: {"shade": "sector"},
    part: "(i)",
    provenance: [
      {"param": "r", "field": "questionText", "quote": "14 cm long"},
      {"param": "theta", "field": "solutionSteps", "quote": "θ = 30°", "derived": "5 minutes × 6° per minute"},
    ],
    expect: [
      {"quantity": "sector", "value": 51.33, "tolPct": 0.5, "quote": "(i) ≈51.33"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC-H02",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "7", "theta": 60},
    draw: {"shade": "segment"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 7 cm"},
      {"param": "theta", "field": "questionText", "quote": "angle of 60°"},
    ],
    expect: [
      {"quantity": "segment", "value": 4.45, "tolPct": 0.5, "quote": "Minor ≈ 4.45 cm²"},
      {"quantity": "majorSegment", "value": 149.55, "tolPct": 0.5, "quote": "Major ≈ 149.55 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC-H06",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "5.2", "arc": "6"},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 5.2 cm"},
      {"param": "arc", "field": "solutionSteps", "quote": "Arc = 16.4 − 10.4 = 6 cm"},
    ],
    expect: [
      {"quantity": "sector", "value": 15.6, "tolPct": 0.5, "quote": "15.6 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC-H07",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "10", "theta": 60},
    draw: {"shade": "segment"},
    labels: {"O": "O", "A": "P", "B": "Q"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 10 cm"},
      {"param": "theta", "field": "questionText", "quote": "angle of 60°"},
    ],
    expect: [
      {"quantity": "segment", "value": 9.08, "tolPct": 0.5, "quote": "Minor ≈ 9.08 cm²"},
      {"quantity": "majorSegment", "value": 304.92, "tolPct": 0.5, "quote": "Major ≈ 304.92 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC-H11",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "21", "theta": 150},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 21 cm"},
      {"param": "theta", "field": "questionText", "quote": "is 150°"},
    ],
    expect: [
      {"quantity": "arc", "value": 55, "tolPct": 0.5, "quote": "Arc = 55 cm"},
      {"quantity": "sector", "value": 577.5, "tolPct": 0.5, "quote": "Area = 577.5 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC-H14",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "10", "theta": 90},
    draw: {"shade": "segment"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 10 cm"},
      {"param": "theta", "field": "questionText", "quote": "angle of 90°"},
    ],
    expect: [
      {"quantity": "sector", "value": 78.5398, "tolPct": 0.5, "quote": "(i) 25π"},
      {"quantity": "triangle", "value": 50, "tolPct": 0.5, "quote": "(ii) 50"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC-N01",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "12", "theta": 60},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 12 cm"},
      {"param": "theta", "field": "questionText", "quote": "angle of 60°"},
    ],
    expect: [
      {"quantity": "sector", "value": 75.398, "tolPct": 0.5, "quote": "24π cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC2-001",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "7", "theta": 60},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 7 cm"},
      {"param": "theta", "field": "questionText", "quote": "central angle 60°"},
    ],
    expect: [
      {"quantity": "sector", "value": 25.667, "tolPct": 0.5, "quote": "154/6 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC2-002",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "10", "theta": 90},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 10 cm"},
      {"param": "theta", "field": "questionText", "quote": "central angle 90°"},
    ],
    expect: [
      {"quantity": "arc", "value": 15.708, "tolPct": 0.5, "quote": "5π cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC2-003",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "6", "theta": 60},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 6 cm"},
      {"param": "theta", "field": "finalAnswer", "quote": "C) 60°", "derived": "the row's own answer"},
    ],
    expect: [
      {"quantity": "sector", "value": 18.84, "tolPct": 0.5, "quote": "18.84 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC2-005",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "14", "theta": 45},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 14 cm"},
      {"param": "theta", "field": "questionText", "quote": "central angle 45°"},
    ],
    expect: [
      {"quantity": "sector", "value": 77, "tolPct": 0.5, "quote": "77 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC2-006",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "21", "theta": 120},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 21 cm"},
      {"param": "theta", "field": "questionText", "quote": "central angle 120°"},
    ],
    expect: [
      {"quantity": "arc", "value": 44, "tolPct": 0.5, "quote": "44 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC2-010",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "21", "arc": "22"},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius is 21 cm"},
      {"param": "arc", "field": "questionText", "quote": "arc length of a sector is 22 cm"},
    ],
    expect: [
      {"quantity": "theta", "value": 60, "tolPct": 0.5, "quote": "C) 60°"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC2-011",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "5", "theta": 90},
    draw: {"shade": "segment"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 5 cm"},
      {"param": "theta", "field": "questionText", "quote": "sector is 90°"},
    ],
    expect: [
      {"quantity": "segment", "value": 7.125, "tolPct": 0.5, "quote": "7.125 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC2-012",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "14", "theta": 60},
    draw: {"shade": "sector"},
    part: "(ii)",
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 14 cm"},
      {"param": "theta", "field": "questionText", "quote": "central angle 60°"},
    ],
    expect: [
      {"quantity": "sector", "value": 102.67, "tolPct": 0.5, "quote": "(ii) ≈ 102.67 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC2-026",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "14", "theta": 60},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius of a circle is 14 cm"},
      {"param": "theta", "field": "finalAnswer", "quote": "60°", "derived": "the row's own answer"},
    ],
    expect: [
      {"quantity": "sector", "value": 102.67, "tolPct": 0.5, "quote": "102.67 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC2-028",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "12", "theta": 90},
    draw: {"shade": "segment"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 12 cm"},
      {"param": "theta", "field": "questionText", "quote": "central angle 90°"},
    ],
    expect: [
      {"quantity": "segment", "value": 41.14, "tolPct": 0.5, "quote": "41.14 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC2-034",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "10", "theta": 90},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 10 cm"},
      {"param": "theta", "field": "questionText", "quote": "in 15 minutes", "derived": "15 minutes × 6° per minute = 90°"},
    ],
    expect: [
      {"quantity": "sector", "value": 78.5, "tolPct": 0.5, "quote": "78.5 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC2-042",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "8", "theta": 90},
    draw: {"shade": "segment"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 8 cm"},
      {"param": "theta", "field": "questionText", "quote": "an angle of 90°"},
    ],
    expect: [
      {"quantity": "segment", "value": 18.29, "tolPct": 0.5, "quote": "18.29 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC2-043",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "10.5", "theta": 120},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "finalAnswer", "quote": "10.5 cm", "derived": "the row's own answer"},
      {"param": "theta", "field": "questionText", "quote": "an angle of 120°"},
    ],
    expect: [
      {"quantity": "arc", "value": 22, "tolPct": 0.5, "quote": "has length 22 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC2-045",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "21", "theta": 60},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "finalAnswer", "quote": "21 cm", "derived": "the row's own answer"},
      {"param": "theta", "field": "questionText", "quote": "central angle 60°"},
    ],
    expect: [
      {"quantity": "sector", "value": 231, "tolPct": 0.5, "quote": "area 231 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC2-048",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "14", "theta": 90},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 14 cm"},
      {"param": "theta", "field": "questionText", "quote": "a quadrant", "derived": "a quadrant is a sector of 90°"},
    ],
    expect: [
      {"quantity": "sector", "value": 154, "tolPct": 0.5, "quote": "154 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC2-049",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "7", "theta": 90},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 7 cm"},
      {"param": "theta", "field": "questionText", "quote": "central angle 90°"},
    ],
    expect: [
      {"quantity": "arc", "value": 11, "tolPct": 0.5, "quote": "= 11"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC2-050",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "14", "theta": 90},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 14 cm"},
      {"param": "theta", "field": "questionText", "quote": "central angle 90°"},
    ],
    expect: [
      {"quantity": "sector", "value": 154, "tolPct": 0.5, "quote": "154 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC2-057",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "21", "theta": 90},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 21 cm"},
      {"param": "theta", "field": "questionText", "quote": "in 15 minutes", "derived": "15 minutes × 6° per minute = 90°"},
    ],
    expect: [
      {"quantity": "sector", "value": 346.5, "tolPct": 0.5, "quote": "346.5"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC-N-NCERT-11-MCQ-005",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "6", "theta": 60},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 6 cm"},
      {"param": "theta", "field": "questionText", "quote": "angle 60°"},
    ],
    expect: [
      {"quantity": "sector", "value": 18.857, "tolPct": 0.5, "quote": "132/7 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC-N-NCERT-11-VSA-001",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "7/2", "theta": 90},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "solutionSteps", "quote": "r = 22/(2π) = 22 × 7/(2 × 22) = 7/2 cm", "derived": "solved from the circumference 22 cm"},
      {"param": "theta", "field": "questionText", "quote": "a quadrant", "derived": "a quadrant is a sector of 90°"},
    ],
    expect: [
      {"quantity": "sector", "value": 9.625, "tolPct": 0.5, "quote": "9.625 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC-N-NCERT-11-VSA-002",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "14", "theta": 30},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "14 cm long"},
      {"param": "theta", "field": "questionText", "quote": "in 5 minutes", "derived": "5 minutes × 6° per minute = 30°"},
    ],
    expect: [
      {"quantity": "sector", "value": 51.33, "tolPct": 0.5, "quote": "≈ 51.33 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC-N-NCERT-11-SA-001",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "21", "theta": 60},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 21 cm"},
      {"param": "theta", "field": "questionText", "quote": "an angle of 60°"},
    ],
    expect: [
      {"quantity": "arc", "value": 22, "tolPct": 0.5, "quote": "(i) 22 cm"},
      {"quantity": "sector", "value": 231, "tolPct": 0.5, "quote": "(ii) 231 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC-N-NCERT-11-SA-002",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "10", "theta": 90},
    draw: {"shade": "segment"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 10 cm"},
      {"param": "theta", "field": "questionText", "quote": "subtends a right angle", "derived": "a right angle = 90°"},
    ],
    expect: [
      {"quantity": "segment", "value": 28.5, "tolPct": 0.5, "quote": "Minor segment = 28.5 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC-N-NCERT-11-SA-003",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "15", "theta": 60},
    draw: {"shade": "segment"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 15 cm"},
      {"param": "theta", "field": "questionText", "quote": "an angle of 60°"},
    ],
    expect: [
      {"quantity": "segment", "value": 20.44, "tolPct": 0.5, "quote": "≈ 20.44 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC-N-NCERT-11-SA-005",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "25", "theta": 115},
    draw: {"shade": "sector"},
    caption: "One wiper's sweep (the row has two).",
    provenance: [
      {"param": "r", "field": "questionText", "quote": "length 25 cm"},
      {"param": "theta", "field": "questionText", "quote": "an angle of 115°"},
    ],
    expect: [
      {"quantity": "sector", "value": 1254.96, "tolPct": 0.5, "quote": "≈ 1254.96 cm²", "factor": 2},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC-N-EXEM-11-SA-002",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "28", "theta": 45},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 28 cm"},
      {"param": "theta", "field": "questionText", "quote": "central angle 45°"},
    ],
    expect: [
      {"quantity": "sector", "value": 308, "tolPct": 0.5, "quote": "Area = 308 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC-N-EXEM-11-SA-005",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "14", "theta": 60},
    draw: {"shade": "segment"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 14 cm"},
      {"param": "theta", "field": "questionText", "quote": "is 60°"},
    ],
    expect: [
      {"quantity": "segment", "value": 17.8, "tolPct": 0.5, "quote": "≈ 17.80 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC-N-EXEM-11-SA-006",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "210/11", "theta": 60},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "finalAnswer", "quote": "r = 210/11 cm", "derived": "the row's own answer"},
      {"param": "theta", "field": "questionText", "quote": "an angle of 60°"},
    ],
    expect: [
      {"quantity": "arc", "value": 20, "tolPct": 0.5, "quote": "20 cm long"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC-N-EXEM-11-LA-001",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "10", "theta": 90},
    draw: {"shade": "majorSegment"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 10 cm"},
      {"param": "theta", "field": "questionText", "quote": "an angle of 90°"},
    ],
    expect: [
      {"quantity": "majorSegment", "value": 285.5, "tolPct": 0.5, "quote": "Major segment = 285.5 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC-N-EXEM-11-CRE-001",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "2√7", "theta": 45},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "finalAnswer", "quote": "radius r = 2√7 cm", "derived": "the row's own design"},
      {"param": "theta", "field": "questionText", "quote": "central angle equals 45°"},
    ],
    expect: [
      {"quantity": "sector", "value": 11, "tolPct": 0.5, "quote": "exactly 11 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC-N-EXEM2-11-SA-004",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "12", "theta": 60},
    draw: {"shade": "segment"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 12 cm"},
      {"param": "theta", "field": "questionText", "quote": "central angle of 60°"},
    ],
    expect: [
      {"quantity": "segment", "value": 13.04, "tolPct": 0.5, "quote": "≈ 13.04 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "ARC-N-EXEM2-11-SA-006",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "5", "arc": "3.5"},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 5 cm"},
      {"param": "arc", "field": "questionText", "quote": "arc length is 3.5 cm"},
    ],
    expect: [
      {"quantity": "sector", "value": 8.75, "tolPct": 0.5, "quote": "8.75 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "PB-M-1-ARC-A-001",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "14", "theta": 45},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 14 cm"},
      {"param": "theta", "field": "questionText", "quote": "angle 45°"},
    ],
    expect: [
      {"quantity": "arc", "value": 11, "tolPct": 0.5, "quote": "11 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "APQ-M-ARC-009",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "3.5", "theta": 60},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "A 3.5 cm chord", "derived": "a 60° chord equals the radius (equilateral triangle)"},
      {"param": "theta", "field": "questionText", "quote": "an angle of 60°"},
    ],
    expect: [
      {"quantity": "arc", "value": 3.6667, "tolPct": 0.5, "quote": "11/3 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "PYQ-M-ARC-001",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "14", "theta": 90},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 14 cm"},
      {"param": "theta", "field": "questionText", "quote": "central angle 90°"},
    ],
    expect: [
      {"quantity": "arc", "value": 22, "tolPct": 0.5, "quote": "(a) 22 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "PYQ-M-ARC-004",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "21", "theta": 120},
    draw: {"shade": "sector"},
    caption: "One wiper's sweep (the row has two).",
    provenance: [
      {"param": "r", "field": "questionText", "quote": "length 21 cm"},
      {"param": "theta", "field": "questionText", "quote": "an angle of 120°"},
    ],
    expect: [
      {"quantity": "sector", "value": 924, "tolPct": 0.5, "quote": "924 cm²", "factor": 2},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "PYQ-M-ARC-006",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "14", "theta": 60},
    draw: {"shade": "segment"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 14 cm"},
      {"param": "theta", "field": "questionText", "quote": "an angle of 60°"},
    ],
    expect: [
      {"quantity": "segment", "value": 17.8, "tolPct": 0.5, "quote": "17.8 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "PYQ-M-2026-CIRC-004",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "14", "theta": 60},
    draw: {"shade": "segment"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 14 cm"},
      {"param": "theta", "field": "questionText", "quote": "an angle of 60°"},
    ],
    expect: [
      {"quantity": "sector", "value": 102.67, "tolPct": 0.5, "quote": "≈ 102.67 cm²"},
      {"quantity": "perimeterSegment", "value": 28.67, "tolPct": 0.5, "quote": "≈ 28.67 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "PYQ-M-2026-ARC-001",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "21", "theta": 60},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 21 cm"},
      {"param": "theta", "field": "questionText", "quote": "an angle of 60°"},
    ],
    expect: [
      {"quantity": "arc", "value": 22, "tolPct": 0.5, "quote": "an arc of length 22 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "PYQ-M-2024-ARC-002",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "21", "theta": 60},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "21 cm long"},
      {"param": "theta", "field": "questionText", "quote": "in 10 minutes", "derived": "10 minutes × 6° per minute = 60°"},
    ],
    expect: [
      {"quantity": "sector", "value": 231, "tolPct": 0.5, "quote": "(c) 231 cm2"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "PYQ-M-2024-ARC-003",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "12", "theta": 150},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 12 cm"},
      {"param": "theta", "field": "finalAnswer", "quote": "(d) 150°", "derived": "the row's own answer"},
    ],
    expect: [
      {"quantity": "sector", "value": 188.496, "tolPct": 0.5, "quote": "60π cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "PYQ-M-2024-ARC-004",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "21", "theta": 60},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 21 cm"},
      {"param": "theta", "field": "questionText", "quote": "an angle of 60°"},
    ],
    expect: [
      {"quantity": "perimeterSector", "value": 64, "tolPct": 0.5, "quote": "(c) 64 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "PYQ-M-2024-ARC-005",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "12", "theta": 150},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 12 cm"},
      {"param": "theta", "field": "finalAnswer", "quote": "(d) 150°", "derived": "the row's own answer"},
    ],
    expect: [
      {"quantity": "arc", "value": 31.416, "tolPct": 0.5, "quote": "10π cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "PYQ-M-2024-ARC-006b",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "42", "theta": 60},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 42 cm"},
      {"param": "theta", "field": "questionText", "quote": "an angle of 60°"},
    ],
    expect: [
      {"quantity": "arc", "value": 44, "tolPct": 0.5, "quote": "44 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "PYQ-M-2024-ARC-007",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "10", "theta": 90},
    draw: {"shade": "majorSector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 10 cm"},
      {"param": "theta", "field": "questionText", "quote": "subtends a right angle", "derived": "a right angle = 90°"},
    ],
    expect: [
      {"quantity": "majorSector", "value": 235.5, "tolPct": 0.5, "quote": "235.5 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "PYQ-M-2024-ARC-008",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "21", "theta": 150},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 21 cm"},
      {"param": "theta", "field": "questionText", "quote": "is 150°"},
    ],
    expect: [
      {"quantity": "arc", "value": 55, "tolPct": 0.5, "quote": "Arc length = 55 cm"},
      {"quantity": "sector", "value": 577.5, "tolPct": 0.5, "quote": "Area of sector = 577.5 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "PYQ-M-2025-CIRC-005",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "10", "theta": 90},
    draw: {"shade": "segment"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 10 cm"},
      {"param": "theta", "field": "questionText", "quote": "subtends a right angle", "derived": "a right angle = 90°"},
    ],
    expect: [
      {"quantity": "segment", "value": 28.5, "tolPct": 0.5, "quote": "28.5 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "PYQ-M-2025-ARC-001",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "none", "r": "10√2", "theta": 72},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "finalAnswer", "quote": "(d) 10√2 units", "derived": "the row's own answer"},
      {"param": "theta", "field": "questionText", "quote": "a central angle of 72°"},
    ],
    expect: [
      {"quantity": "sector", "value": 125.664, "tolPct": 0.5, "quote": "40π sq. units"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "PYQ-M-2025-ARC-002",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "5", "theta": 144},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "diameter 10 cm", "derived": "radius = half the 10 cm diameter"},
      {"param": "theta", "field": "questionText", "quote": "an angle of 144°"},
    ],
    expect: [
      {"quantity": "arc", "value": 12.566, "tolPct": 0.5, "quote": "(b) 4π cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "2026-ARC-SA-01",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "7", "theta": 90},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 7 cm"},
      {"param": "theta", "field": "questionText", "quote": "central angle 90°"},
    ],
    expect: [
      {"quantity": "sector", "value": 38.5, "tolPct": 0.5, "quote": "38.5"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-200",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "21", "theta": 120},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "21 cm long"},
      {"param": "theta", "field": "solutionSteps", "quote": "20 × 6° = 120°", "derived": "7:15 to 7:35 = 20 minutes"},
    ],
    expect: [
      {"quantity": "sector", "value": 462, "tolPct": 0.5, "quote": "462 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-201",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "m", "r": "105", "theta": 60},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 105 m"},
      {"param": "theta", "field": "questionText", "quote": "an angle of 60°"},
    ],
    expect: [
      {"quantity": "arc", "value": 110, "tolPct": 0.5, "quote": "110 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-208",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "35", "theta": 36},
    draw: {"shade": "sector", "down": true},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "35 cm long"},
      {"param": "theta", "field": "finalAnswer", "quote": "36°", "derived": "the row's own answer"},
    ],
    expect: [
      {"quantity": "arc", "value": 22, "tolPct": 0.5, "quote": "an arc 22 cm long"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-210",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "km", "r": "9", "theta": 80},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "a distance of 9 km"},
      {"param": "theta", "field": "questionText", "quote": "a sector of angle 80°"},
    ],
    expect: [
      {"quantity": "sector", "value": 56.5487, "tolPct": 0.5, "quote": "18π km²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-217",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "m", "r": "15", "theta": 120},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 15 m"},
      {"param": "theta", "field": "finalAnswer", "quote": "120°", "derived": "the row's own answer"},
    ],
    expect: [
      {"quantity": "sector", "value": 235.619, "tolPct": 0.5, "quote": "75π m²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-223",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "m", "r": "21", "theta": 90},
    draw: {"shade": "segment"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 21 m"},
      {"param": "theta", "field": "questionText", "quote": "make a right angle at the centre", "derived": "a right angle = 90°"},
    ],
    expect: [
      {"quantity": "segment", "value": 126, "tolPct": 0.5, "quote": "126 m²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-224",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "21", "theta": 60},
    draw: {"shade": "sector", "down": true},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "21 cm long"},
      {"param": "theta", "field": "questionText", "quote": "an angle of 60°"},
    ],
    expect: [
      {"quantity": "arc", "value": 22, "tolPct": 0.5, "quote": "= 22 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-230",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "m", "r": "21", "theta": 60},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 21 m"},
      {"param": "theta", "field": "questionText", "quote": "angle 60°"},
    ],
    expect: [
      {"quantity": "perimeterSector", "value": 64, "tolPct": 0.5, "quote": "is 64 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-231",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "m", "r": "630", "theta": 40},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 630 m"},
      {"param": "theta", "field": "questionText", "quote": "an angle of 40°"},
    ],
    expect: [
      {"quantity": "arc", "value": 440, "tolPct": 0.5, "quote": "440 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-232",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "m", "r": "42", "theta": 80},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 42 m"},
      {"param": "theta", "field": "questionText", "quote": "central angle of 80°"},
    ],
    expect: [
      {"quantity": "sector", "value": 1232, "tolPct": 0.5, "quote": "1232 m²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-233",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "35", "theta": 72},
    draw: {"shade": "sector", "down": true},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "length 35 cm"},
      {"param": "theta", "field": "questionText", "quote": "an angle of 72°"},
    ],
    expect: [
      {"quantity": "arc", "value": 44, "tolPct": 0.5, "quote": "44 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-234",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "m", "r": "84", "theta": 45},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "finalAnswer", "quote": "84 m", "derived": "the row's own answer"},
      {"param": "theta", "field": "questionText", "quote": "an angle of 45°"},
    ],
    expect: [
      {"quantity": "arc", "value": 66, "tolPct": 0.5, "quote": "covers 66 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-235",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "m", "r": "21", "theta": 120},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "up to 21 m"},
      {"param": "theta", "field": "finalAnswer", "quote": "120°", "derived": "the row's own answer"},
    ],
    expect: [
      {"quantity": "sector", "value": 462, "tolPct": 0.5, "quote": "462 m²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-236",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "14", "theta": 90},
    draw: {"shade": "segment"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 14 cm"},
      {"param": "theta", "field": "questionText", "quote": "subtends a right angle", "derived": "a right angle = 90°"},
    ],
    expect: [
      {"quantity": "segment", "value": 56, "tolPct": 0.5, "quote": "56 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-238",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "m", "r": "28", "theta": 45},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 28 m"},
      {"param": "theta", "field": "questionText", "quote": "central angle of 45°"},
    ],
    expect: [
      {"quantity": "perimeterSector", "value": 2340, "tolPct": 0.5, "quote": "₹2340", "factor": 30},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-239",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "m", "r": "4.2", "theta": 120},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "4.2 m long"},
      {"param": "theta", "field": "questionText", "quote": "from 12 noon to 4 p.m.", "derived": "4 hours × 30° per hour = 120°"},
    ],
    expect: [
      {"quantity": "arc", "value": 8.8, "tolPct": 0.5, "quote": "8.8 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-241",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "14", "arc": "33"},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 14 cm"},
      {"param": "arc", "field": "questionText", "quote": "is 33 cm long"},
    ],
    expect: [
      {"quantity": "sector", "value": 231, "tolPct": 0.5, "quote": "231 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-242",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "35", "theta": 90},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 35 cm"},
      {"param": "theta", "field": "questionText", "quote": "a quadrant", "derived": "a quadrant is a sector of 90°"},
    ],
    expect: [
      {"quantity": "perimeterSector", "value": 125, "tolPct": 0.5, "quote": "125 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-243",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "m", "r": "21", "theta": 40},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 21 m"},
      {"param": "theta", "field": "questionText", "quote": "central angle of 40°"},
    ],
    expect: [
      {"quantity": "sector", "value": 154, "tolPct": 0.5, "quote": "154 m²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-245",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "30", "theta": 60},
    draw: {"shade": "segment"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 30 cm"},
      {"param": "theta", "field": "questionText", "quote": "an angle of 60°"},
    ],
    expect: [
      {"quantity": "segment", "value": 81.75, "tolPct": 0.5, "quote": "81.75 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-246",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "18", "theta": 120},
    draw: {"shade": "segment"},
    labels: {"O": "O", "A": "P", "B": "Q"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 18 cm"},
      {"param": "theta", "field": "questionText", "quote": "an angle of 120°"},
    ],
    expect: [
      {"quantity": "segment", "value": 198.99, "tolPct": 0.5, "quote": "198.99 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-247",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "m", "r": "20", "theta": 90},
    draw: {"shade": "segment"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 20 m"},
      {"param": "theta", "field": "questionText", "quote": "subtends a right angle", "derived": "a right angle = 90°"},
    ],
    expect: [
      {"quantity": "segment", "value": 4560, "tolPct": 0.5, "quote": "₹4560", "factor": 40},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-248",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "m", "r": "7", "theta": 90},
    draw: {"shade": "majorSegment"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 7 m"},
      {"param": "theta", "field": "questionText", "quote": "an angle of 90°"},
    ],
    expect: [
      {"quantity": "majorSegment", "value": 140, "tolPct": 0.5, "quote": "140 m²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-259",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "10.5", "theta": 120},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "10.5 cm long"},
      {"param": "theta", "field": "questionText", "quote": "from 9:10 a.m. to 9:30 a.m.", "derived": "20 minutes × 6° per minute = 120°"},
    ],
    expect: [
      {"quantity": "sector", "value": 115.5, "tolPct": 0.5, "quote": "(i) 115.5 cm²"},
      {"quantity": "arc", "value": 22, "tolPct": 0.5, "quote": "(ii) 22 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-260",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "km", "r": "28", "theta": 135},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "within 28 km"},
      {"param": "theta", "field": "questionText", "quote": "central angle of 135°"},
    ],
    expect: [
      {"quantity": "sector", "value": 924, "tolPct": 0.5, "quote": "(i) 924 km²"},
      {"quantity": "perimeterSector", "value": 122, "tolPct": 0.5, "quote": "(ii) 122 km"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-263",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "m", "r": "3.5", "theta": 144},
    draw: {"shade": "sector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 3.5 m"},
      {"param": "theta", "field": "questionText", "quote": "central angle of 144°"},
    ],
    expect: [
      {"quantity": "sector", "value": 308, "tolPct": 0.5, "quote": "₹308", "factor": 20},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-264",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "m", "r": "14", "arc": "11"},
    draw: {"shade": "majorSector"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 14 m"},
      {"param": "arc", "field": "questionText", "quote": "is 11 m long"},
    ],
    expect: [
      {"quantity": "majorSector", "value": 539, "tolPct": 0.5, "quote": "539 m²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-270",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "6", "theta": 120},
    draw: {"shade": "segment"},
    labels: {"O": "O", "A": "P", "B": "Q"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 6 cm"},
      {"param": "theta", "field": "questionText", "quote": "∠POQ = 120°"},
    ],
    expect: [
      {"quantity": "segment", "value": 22.11, "tolPct": 0.5, "quote": "(12π − 9√3) cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-271",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "m", "r": "28", "theta": 90},
    draw: {"shade": "segment"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 28 m"},
      {"param": "theta", "field": "questionText", "quote": "make a right angle at O", "derived": "a right angle = 90°"},
    ],
    expect: [
      {"quantity": "arc", "value": 44, "tolPct": 0.5, "quote": "(i) 44 m"},
      {"quantity": "segment", "value": 224, "tolPct": 0.5, "quote": "(ii) 224 m²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-276",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "km", "r": "14", "theta": 90},
    draw: {"shade": "sector"},
    part: "(i), (ii)",
    provenance: [
      {"param": "r", "field": "questionText", "quote": "up to 14 km"},
      {"param": "theta", "field": "questionText", "quote": "angle 90°"},
    ],
    expect: [
      {"quantity": "arc", "value": 22, "tolPct": 0.5, "quote": "(i) 22 km"},
      {"quantity": "sector", "value": 154, "tolPct": 0.5, "quote": "(ii) 154 km²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-277",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "m", "r": "6", "theta": 150},
    draw: {"shade": "sector"},
    part: "(i), (ii)",
    provenance: [
      {"param": "r", "field": "questionText", "quote": "a distance of 6 m"},
      {"param": "theta", "field": "questionText", "quote": "an angle of 150°"},
    ],
    expect: [
      {"quantity": "sector", "value": 47.1, "tolPct": 0.5, "quote": "(i) 47.1 m²"},
      {"quantity": "arc", "value": 15.7, "tolPct": 0.5, "quote": "(ii) 15.7 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-278",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "21", "theta": 30},
    draw: {"shade": "sector"},
    part: "(i), (ii)",
    provenance: [
      {"param": "r", "field": "questionText", "quote": "diameter 42 cm", "derived": "radius = half the 42 cm diameter"},
      {"param": "theta", "field": "finalAnswer", "quote": "(i) 30°", "derived": "the row's own answer: 360°/12"},
    ],
    expect: [
      {"quantity": "arc", "value": 11, "tolPct": 0.5, "quote": "(ii) 11 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-284",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "42", "theta": 90},
    draw: {"shade": "segment"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 42 cm"},
      {"param": "theta", "field": "questionText", "quote": "subtends a right angle", "derived": "a right angle = 90°"},
    ],
    expect: [
      {"quantity": "sector", "value": 1386, "tolPct": 0.5, "quote": "(i) 1386 cm²"},
      {"quantity": "triangle", "value": 882, "tolPct": 0.5, "quote": "(ii) 882 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-285",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "14", "theta": 60},
    draw: {"shade": "segment", "down": true},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 14 cm"},
      {"param": "theta", "field": "questionText", "quote": "an angle of 60°"},
    ],
    expect: [
      {"quantity": "chord", "value": 14, "tolPct": 0.5, "quote": "(i) 14 cm"},
      {"quantity": "sector", "value": 102.67, "tolPct": 0.5, "quote": "(ii) 102.67 cm²"},
      {"quantity": "segment", "value": 17.9, "tolPct": 1.0, "quote": "(iii) 17.90 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-286",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "m", "r": "21", "theta": 120},
    draw: {"shade": "segment"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 21 m"},
      {"param": "theta", "field": "questionText", "quote": "an angle of 120°"},
    ],
    expect: [
      {"quantity": "arc", "value": 44, "tolPct": 0.5, "quote": "(i) 44 m"},
      {"quantity": "sector", "value": 462, "tolPct": 0.5, "quote": "(ii) 462 m²"},
      {"quantity": "segment", "value": 271.27, "tolPct": 0.5, "quote": "(iii) 271.27 m²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-ARC-297",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "m", "r": "28", "theta": 90},
    draw: {"shade": "segment"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 28 m"},
      {"param": "theta", "field": "questionText", "quote": "a quadrant", "derived": "a quadrant is a sector of 90°"},
    ],
    expect: [
      {"quantity": "arc", "value": 44, "tolPct": 0.5, "quote": "(i) 44 m"},
      {"quantity": "triangle", "value": 392, "tolPct": 0.5, "quote": "(ii) 392 m²"},
      {"quantity": "segment", "value": 5600, "tolPct": 0.5, "quote": "(iii) ₹5600", "factor": 25},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "arc-comp-01",
    slot: "solution",
    builder: "circleSector",
    params: {"template": "sector", "unit": "cm", "r": "28", "theta": 90},
    draw: {"shade": "sector"},
    part: "(i), (ii)",
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 28 cm"},
      {"param": "theta", "field": "questionText", "quote": "central angle 90°"},
    ],
    expect: [
      {"quantity": "sector", "value": 616, "tolPct": 0.5, "quote": "(i) 616 cm²"},
      {"quantity": "arc", "value": 44, "tolPct": 0.5, "quote": "(ii) 44 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
];
