/**
 * Circles — computed SOLUTION figures (DIAGRAMS-1 PR-2d).
 *
 * One entry per served row whose solution is a figure the row's OWN numbers fix
 * exactly (tangents from an external point, concentric circles, an inscribed circle,
 * BPT, plotted points, a sector or segment). Every row was read in full (question,
 * steps, answer) and its rendered figure eye-checked. Rows read and REFUSED (not fixed
 * by the row, no builder template, an official question figure already bound, the
 * row's own solution inconsistent, ...) are listed in the PR, not here — an unbound
 * row shows no figure, never a lookalike.
 *
 * `params` holds only numbers read from the row (each quoted in `provenance`, an exact
 * substring of the served row); `draw` holds display choices; `expect` is the row's own
 * answer. computedFigures.provenance.test.ts enforces both.
 *
 * GENERATED from the PR-2d decision table; edit the decisions, not this file by hand.
 */
import type { ComputedFigureBinding } from "./computedFigureTypes";

export const CIRCLES_SOLUTION_FIGURES: ComputedFigureBinding[] = [
  {
    kind: "computed",
    questionId: "CIR-E02",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "t": "8", "d": "10"},
    draw: {"single": true},
    provenance: [
      {"param": "t", "field": "questionText", "quote": "The length of a tangent from an external point to a circle is 8 cm"},
      {"param": "d", "field": "questionText", "quote": "the distance of the point from the centre is 10 cm"},
    ],
    expect: [
      {"quantity": "r", "value": 6, "tolPct": 0.5, "quote": "6 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIR-E04",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "scaleFree": true, "angleP": 80},
    provenance: [
      {"param": "angleP", "field": "questionText", "quote": "inclined to each other at 80°"},
    ],
    expect: [
      {"quantity": "angleAOP", "value": 50, "tolPct": 0.5, "quote": "50°"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIR-E07",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "r": "5", "t": "12"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "a circle of radius 5 cm"},
      {"param": "t", "field": "questionText", "quote": "PA = 12 cm"},
    ],
    expect: [
      {"quantity": "d", "value": 13, "tolPct": 0.5, "quote": "13 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIR-E09",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "scaleFree": true, "angleP": 70},
    labels: {"O": "O", "P": "T", "A": "P", "B": "Q"},
    provenance: [
      {"param": "angleP", "field": "questionText", "quote": "∠PTQ = 70°"},
    ],
    expect: [
      {"quantity": "angleO", "value": 110, "tolPct": 0.5, "quote": "110°"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIR-E10",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "concentricChord", "unit": "cm", "R": "5", "r": "3"},
    provenance: [
      {"param": "R", "field": "questionText", "quote": "radii 5 cm and 3 cm"},
      {"param": "r", "field": "questionText", "quote": "radii 5 cm and 3 cm"},
    ],
    expect: [
      {"quantity": "chord", "value": 8, "tolPct": 0.5, "quote": "8 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIR-E14",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "scaleFree": true, "angleP": 60},
    labels: {"q.r": "r"},
    provenance: [
      {"param": "angleP", "field": "questionText", "quote": "centre O is 60°"},
    ],
    expect: [
      {"quantity": "d", "value": 2, "tolPct": 0.5, "quote": "OP = 2r"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIR-E16",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "r": "5", "d": "13"},
    draw: {"single": true},
    labels: {"O": "O", "P": "P", "A": "Q"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "OQ = 5 cm"},
      {"param": "d", "field": "questionText", "quote": "OP = 13 cm"},
    ],
    expect: [
      {"quantity": "t", "value": 12, "tolPct": 0.5, "quote": "12 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIR-E19",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "scaleFree": true, "angleP": 50},
    draw: {"chord": true},
    provenance: [
      {"param": "angleP", "field": "questionText", "quote": "∠APB = 50°"},
    ],
    expect: [
      {"quantity": "angleOAB", "value": 25, "tolPct": 0.5, "quote": "25°"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIR-M02",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "incircle", "unit": "cm", "AB": "12", "BC": "8", "CA": "10"},
    provenance: [
      {"param": "AB", "field": "questionText", "quote": "AB = 12 cm"},
      {"param": "BC", "field": "questionText", "quote": "BC = 8 cm"},
      {"param": "CA", "field": "questionText", "quote": "AC = 10 cm"},
    ],
    expect: [
      {"quantity": "x", "value": 7, "tolPct": 0.5, "quote": "AF = 7 cm"},
      {"quantity": "y", "value": 5, "tolPct": 0.5, "quote": "BD = 5 cm"},
      {"quantity": "z", "value": 3, "tolPct": 0.5, "quote": "CE = 3 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIR-M06",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "r": "5", "angleP": 60},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 5 cm"},
      {"param": "angleP", "field": "questionText", "quote": "∠APB = 60°"},
    ],
    expect: [
      {"quantity": "angleO", "value": 120, "tolPct": 0.5, "quote": "(i) 120°"},
      {"quantity": "t", "value": 8.660254, "tolPct": 0.5, "quote": "(ii) 5√3 cm"},
      {"quantity": "d", "value": 10, "tolPct": 0.5, "quote": "(iii) 10 cm"},
      {"quantity": "areaOAPB", "value": 43.30127, "tolPct": 0.5, "quote": "(iv) 25√3 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIR-M13",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "t": "6", "d": "10"},
    provenance: [
      {"param": "t", "field": "questionText", "quote": "of length 6 cm each"},
      {"param": "d", "field": "questionText", "quote": "OP = 10 cm"},
    ],
    expect: [
      {"quantity": "r", "value": 8, "tolPct": 0.5, "quote": "8 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIR-M18",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "t": "10", "angleP": 60},
    draw: {"chord": true},
    provenance: [
      {"param": "t", "field": "questionText", "quote": "PA = 10 cm"},
      {"param": "angleP", "field": "questionText", "quote": "∠APB = 60°"},
    ],
    expect: [
      {"quantity": "chord", "value": 10, "tolPct": 0.5, "quote": "10 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIR-H08",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "scaleFree": true, "angleP": 120},
    provenance: [
      {"param": "angleP", "field": "solutionSteps", "quote": "y = 60°, x = 120°", "derived": "∠APB = x solved by the row's own solution"},
    ],
    expect: [
      {"quantity": "angleO", "value": 60, "tolPct": 0.5, "quote": "y = 60°"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIR-H14",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "r": "5", "d": "13"},
    draw: {"single": true},
    labels: {"O": "O", "P": "P", "A": "T"},
    provenance: [
      {"param": "d", "field": "questionText", "quote": "a point 13 cm away"},
      {"param": "r", "field": "questionText", "quote": "radius 5 cm"},
    ],
    expect: [
      {"quantity": "t", "value": 12, "tolPct": 0.5, "quote": "12 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIR-N01",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "r": "5", "t": "12"},
    draw: {"single": true},
    labels: {"O": "O", "P": "P", "A": "T"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 5 cm"},
      {"param": "t", "field": "questionText", "quote": "is 12 cm long"},
    ],
    expect: [
      {"quantity": "d", "value": 13, "tolPct": 0.5, "quote": "OP = 13 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CI2-002",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentChord", "unit": "cm", "scaleFree": true, "angleT": 65},
    labels: {"O": "O", "P": "P", "Q": "Q"},
    provenance: [
      {"param": "angleT", "field": "questionText", "quote": "an angle of 65°"},
    ],
    expect: [
      {"quantity": "angleOPQ", "value": 25, "tolPct": 0.5, "quote": "25°"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CI2-006",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "scaleFree": true, "angleP": 60},
    provenance: [
      {"param": "angleP", "field": "questionText", "quote": "∠APB = 60°"},
    ],
    expect: [
      {"quantity": "angleO", "value": 120, "tolPct": 0.5, "quote": "120°"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CI2-007",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "r": "5", "d": "13"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 5 cm"},
      {"param": "d", "field": "questionText", "quote": "OP = 13 cm"},
    ],
    expect: [
      {"quantity": "t", "value": 12, "tolPct": 0.5, "quote": "12 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CI2-012",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "r": "6", "angleP": 40},
    provenance: [
      {"param": "angleP", "field": "questionText", "quote": "The angle between the two tangents is 40°"},
      {"param": "r", "field": "questionText", "quote": "The radius of the circle is 6 cm"},
    ],
    expect: [
      {"quantity": "d", "value": 17.54, "tolPct": 0.5, "quote": "OP ≈ 17.54 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CI2-016",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "m", "r": "2", "d": "4", "angleP": 60},
    part: "(i), (iii)",
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 2 m"},
      {"param": "angleP", "field": "questionText", "quote": "∠APB = 60°"},
      {"param": "d", "field": "questionText", "quote": "OP = 4 m"},
    ],
    expect: [
      {"quantity": "angleO", "value": 120, "tolPct": 0.5, "quote": "(i) 120°"},
      {"quantity": "t", "value": 3.4641, "tolPct": 0.5, "quote": "(iii) 2√3 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CI2-016",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "m", "r": "2", "angleP": 90},
    labels: {"O": "O", "P": "Q", "A": "C", "B": "D"},
    part: "(ii)",
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 2 m"},
      {"param": "angleP", "field": "questionText", "quote": "∠CQD = 90°"},
    ],
    expect: [
      {"quantity": "angleO", "value": 90, "tolPct": 0.5, "quote": "(ii) 90°"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CI2-017",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "incircle", "unit": "cm", "x": "4", "y": "5", "z": "6"},
    labels: {"A": "A", "B": "B", "C": "C", "D": "X", "E": "Y", "F": "Z"},
    provenance: [
      {"param": "x", "field": "questionText", "quote": "AZ = 4 cm"},
      {"param": "y", "field": "questionText", "quote": "BX = 5 cm"},
      {"param": "z", "field": "questionText", "quote": "CY = 6 cm"},
    ],
    expect: [
      {"quantity": "AB", "value": 9, "tolPct": 0.5, "quote": "AB = 9 cm"},
      {"quantity": "BC", "value": 11, "tolPct": 0.5, "quote": "BC = 11 cm"},
      {"quantity": "CA", "value": 10, "tolPct": 0.5, "quote": "CA = 10 cm"},
      {"quantity": "s", "value": 15, "tolPct": 0.5, "quote": "s = 15 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CI2-022",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "r": "6", "angleP": 50},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 6 cm"},
      {"param": "angleP", "field": "questionText", "quote": "make an angle of 50° at P"},
    ],
    expect: [
      {"quantity": "angleO", "value": 130, "tolPct": 0.5, "quote": "130°"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CI2-029",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "r": "6", "d": "10"},
    provenance: [
      {"param": "d", "field": "questionText", "quote": "the distance from P to the center O is 10 cm"},
      {"param": "r", "field": "questionText", "quote": "the radius is 6 cm"},
    ],
    expect: [
      {"quantity": "t", "value": 8, "tolPct": 0.5, "quote": "8 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CI2-031",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "scaleFree": true, "angleP": 50},
    provenance: [
      {"param": "angleP", "field": "questionText", "quote": "the angle between the tangents is 50°"},
    ],
    expect: [
      {"quantity": "angleO", "value": 130, "tolPct": 0.5, "quote": "130°"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CI2-032",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "r": "7", "d": "25"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 7 cm"},
      {"param": "d", "field": "questionText", "quote": "distance 25 cm from O"},
    ],
    expect: [
      {"quantity": "t", "value": 24, "tolPct": 0.5, "quote": "24 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CI2-036",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentChord", "unit": "cm", "scaleFree": true, "angleT": 30},
    labels: {"O": "O", "P": "P", "Q": "Q"},
    provenance: [
      {"param": "angleT", "field": "questionText", "quote": "making angle 30° with the tangent"},
    ],
    expect: [
      {"quantity": "angleO", "value": 60, "tolPct": 0.5, "quote": "60°"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CI2-042",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "scaleFree": true, "angleO": 100},
    provenance: [
      {"param": "angleO", "field": "questionText", "quote": "∠AOB = 100°"},
    ],
    expect: [
      {"quantity": "angleP", "value": 80, "tolPct": 0.5, "quote": "80°"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CI2-044",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "concentricChord", "unit": "cm", "R": "8", "r": "5"},
    labels: {"O": "O", "M": "P", "A": "A", "B": "B"},
    provenance: [
      {"param": "R", "field": "questionText", "quote": "radii 8 cm and 5 cm"},
      {"param": "r", "field": "questionText", "quote": "radii 8 cm and 5 cm"},
    ],
    expect: [
      {"quantity": "chord", "value": 12.49, "tolPct": 0.5, "quote": "AB = 2√39 cm ≈ 12.49 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CI2-046",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "r": "6", "d": "10"},
    draw: {"single": true},
    labels: {"O": "O", "P": "P", "A": "T"},
    provenance: [
      {"param": "d", "field": "questionText", "quote": "10 cm from the centre"},
      {"param": "r", "field": "questionText", "quote": "radius 6 cm"},
    ],
    expect: [
      {"quantity": "t", "value": 8, "tolPct": 0.5, "quote": "PT = 8 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIRC-N-NCERT-10-MCQ-001",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "r": "5", "d": "12"},
    draw: {"single": true},
    labels: {"O": "O", "P": "Q", "A": "P"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 5 cm"},
      {"param": "d", "field": "questionText", "quote": "OQ = 12 cm"},
    ],
    expect: [
      {"quantity": "t", "value": 10.909, "tolPct": 0.5, "quote": "PQ = √119 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIRC-N-NCERT-10-MCQ-002",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "t": "24", "d": "25"},
    draw: {"single": true},
    labels: {"O": "O", "P": "Q", "A": "P"},
    provenance: [
      {"param": "t", "field": "questionText", "quote": "the length of the tangent to a circle is 24 cm"},
      {"param": "d", "field": "questionText", "quote": "the distance of Q from the centre is 25 cm"},
    ],
    expect: [
      {"quantity": "r", "value": 7, "tolPct": 0.5, "quote": "7 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIRC-N-NCERT-10-MCQ-004",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "scaleFree": true, "angleP": 80},
    provenance: [
      {"param": "angleP", "field": "questionText", "quote": "an angle of 80°"},
    ],
    expect: [
      {"quantity": "angleAOP", "value": 50, "tolPct": 0.5, "quote": "50°"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIRC-N-NCERT-10-VSA-002",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "t": "4", "d": "5"},
    draw: {"single": true},
    labels: {"O": "O", "P": "A", "A": "P"},
    provenance: [
      {"param": "d", "field": "questionText", "quote": "at distance 5 cm from the centre"},
      {"param": "t", "field": "questionText", "quote": "is 4 cm"},
    ],
    expect: [
      {"quantity": "r", "value": 3, "tolPct": 0.5, "quote": "Radius = 3 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIRC-N-NCERT-10-SA-003",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "r": "5", "chord": "8"},
    labels: {"O": "O", "P": "T", "A": "P", "B": "Q", "M": "R"},
    provenance: [
      {"param": "chord", "field": "questionText", "quote": "a chord of length 8 cm"},
      {"param": "r", "field": "questionText", "quote": "a circle of radius 5 cm"},
    ],
    expect: [
      {"quantity": "t", "value": 6.6667, "tolPct": 0.5, "quote": "TP = 20/3 cm"},
      {"quantity": "OM", "value": 3, "tolPct": 0.5, "quote": "OR = 3"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIRC-N-NCERT-10-CB-001",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "r": "5", "d": "13"},
    labels: {"O": "O", "P": "T", "A": "P", "B": "Q"},
    part: "(i)–(iii)",
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 5 cm"},
      {"param": "d", "field": "questionText", "quote": "equals 13 cm"},
    ],
    expect: [
      {"quantity": "t", "value": 12, "tolPct": 0.5, "quote": "(ii) 12 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIRC-N-NCERT-10-CB-001",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "scaleFree": true, "angleO": 110},
    labels: {"O": "O′", "P": "S", "A": "A", "B": "B"},
    part: "(iv)",
    provenance: [
      {"param": "angleO", "field": "questionText", "quote": "∠AO′B = 110°"},
    ],
    expect: [
      {"quantity": "angleP", "value": 70, "tolPct": 0.5, "quote": "(iv) 70°"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIRC-N-NCERT-10-CRE-001",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "r": "3", "angleP": 60},
    labels: {"O": "O", "P": "T", "A": "P", "B": "Q"},
    provenance: [
      {"param": "angleP", "field": "questionText", "quote": "exactly 60°"},
      {"param": "r", "field": "solutionSteps", "quote": "pick r = 3 cm", "derived": "the row's own design chooses r = 3 cm"},
    ],
    expect: [
      {"quantity": "d", "value": 6, "tolPct": 0.5, "quote": "OT = 6 cm"},
      {"quantity": "t", "value": 5.19615, "tolPct": 0.5, "quote": "TP = TQ = 3√3 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIRC-N-EXEM-10-MCQ-001",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "concentricChord", "unit": "cm", "R": "5", "r": "4"},
    labels: {"O": "O", "M": "P", "A": "A", "B": "B"},
    provenance: [
      {"param": "R", "field": "questionText", "quote": "4 cm and 5 cm"},
      {"param": "r", "field": "questionText", "quote": "4 cm and 5 cm"},
    ],
    expect: [
      {"quantity": "chord", "value": 6, "tolPct": 0.5, "quote": "6 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIRC-N-EXEM-10-MCQ-002",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "r": "3", "angleP": 60},
    labels: {"O": "O", "P": "T", "A": "P"},
    provenance: [
      {"param": "angleP", "field": "questionText", "quote": "inclined at an angle 60°"},
      {"param": "r", "field": "questionText", "quote": "radius 3 cm"},
    ],
    expect: [
      {"quantity": "t", "value": 5.19615, "tolPct": 0.5, "quote": "3√3 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIRC-N-EXEM-10-MCQ-003",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "r": "5", "d": "13"},
    labels: {"O": "O", "P": "P", "A": "Q", "B": "R"},
    provenance: [
      {"param": "d", "field": "questionText", "quote": "a distance of 13 cm"},
      {"param": "r", "field": "questionText", "quote": "radius 5 cm"},
    ],
    expect: [
      {"quantity": "areaOAPB", "value": 60, "tolPct": 0.5, "quote": "60 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIRC-N-EXEM-10-MCQ-005",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "d": "4", "angleOPA": 30},
    draw: {"single": true},
    labels: {"O": "O", "P": "T", "A": "A"},
    provenance: [
      {"param": "d", "field": "questionText", "quote": "OT = 4 cm"},
      {"param": "angleOPA", "field": "questionText", "quote": "∠OTA = 30°"},
    ],
    expect: [
      {"quantity": "t", "value": 3.4641, "tolPct": 0.5, "quote": "2√3 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIRC-N-EXEM-10-MCQ-006",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "scaleFree": true, "angleP": 50},
    draw: {"chord": true},
    provenance: [
      {"param": "angleP", "field": "questionText", "quote": "∠APB = 50°"},
    ],
    expect: [
      {"quantity": "angleOAB", "value": 25, "tolPct": 0.5, "quote": "25°"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIRC-N-EXEM-10-AR-001",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "scaleFree": true, "angleP": 90},
    labels: {"q.r": "a"},
    provenance: [
      {"param": "angleP", "field": "questionText", "quote": "is 90°"},
    ],
    expect: [
      {"quantity": "d", "value": 1.414214, "tolPct": 0.5, "quote": "OP = a√2"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIRC-N-EXEM-10-AR-002",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "scaleFree": true, "angleO": 60},
    draw: {"chord": true},
    provenance: [
      {"param": "angleO", "field": "questionText", "quote": "an angle of 60° at the centre"},
    ],
    expect: [
      {"quantity": "angleP", "value": 120, "tolPct": 0.5, "quote": "180° − 60° = 120°"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIRC-N-EXEM-10-SA-001",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "concentricChord", "unit": "cm", "R": "5", "chord": "8"},
    labels: {"O": "O", "M": "P", "A": "A", "B": "C"},
    provenance: [
      {"param": "R", "field": "questionText", "quote": "the radius of the outer circle is 5 cm"},
      {"param": "chord", "field": "questionText", "quote": "the chord AC of length 8 cm"},
    ],
    expect: [
      {"quantity": "r", "value": 3, "tolPct": 0.5, "quote": "Radius of inner circle = 3 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIRC-N-EXEM-10-SA-003",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "scaleFree": true, "angleP": 120},
    labels: {"O": "O", "P": "B", "A": "C", "B": "D"},
    provenance: [
      {"param": "angleP", "field": "questionText", "quote": "∠DBC = 120°"},
    ],
    expect: [
      {"quantity": "dOverT", "value": 2, "tolPct": 0.5, "quote": "BO = 2BC"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIRC-N-EXEM-10-CB-001",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "r": "5", "d": "13"},
    labels: {"O": "O", "P": "A", "A": "P", "B": "Q"},
    part: "(i)",
    provenance: [
      {"param": "d", "field": "questionText", "quote": "a distance 13 cm from the centre O"},
      {"param": "r", "field": "questionText", "quote": "radius 5 cm"},
    ],
    expect: [
      {"quantity": "t", "value": 12, "tolPct": 0.5, "quote": "(i) AP = 12 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIRC-N-EXEM-10-CRE-001",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "r": "6", "angleP": 90},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "has radius 6 cm"},
      {"param": "angleP", "field": "solutionSteps", "quote": "Since ∠APB = 90°", "derived": "the row's 'perpendicular to each other'"},
    ],
    expect: [
      {"quantity": "d", "value": 8.485281, "tolPct": 0.5, "quote": "OP = 6√2 cm"},
      {"quantity": "t", "value": 6, "tolPct": 0.5, "quote": "each tangent length = 6 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIR-PRF-D-001",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "scaleFree": true, "angleAOP": 40},
    draw: {"single": true},
    part: "find ∠OPA",
    provenance: [
      {"param": "angleAOP", "field": "questionText", "quote": "∠AOP = 40°"},
    ],
    expect: [
      {"quantity": "angleOPA", "value": 50, "tolPct": 0.5, "quote": "∠OPA = 50°"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIR-PRF-D-002",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "scaleFree": true, "angleP": 70},
    part: "find ∠AOB",
    provenance: [
      {"param": "angleP", "field": "questionText", "quote": "∠APB = 70°"},
    ],
    expect: [
      {"quantity": "angleO", "value": 110, "tolPct": 0.5, "quote": "∠AOB = 110°"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIR-PRF-C-001",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "r": "5", "t": "12"},
    provenance: [
      {"param": "t", "field": "questionText", "quote": "PA = 12 cm"},
      {"param": "r", "field": "questionText", "quote": "OA = 5 cm"},
    ],
    expect: [
      {"quantity": "d", "value": 13, "tolPct": 0.5, "quote": "OP = 13 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "SQP-M-CI-001",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentChord", "unit": "cm", "scaleFree": true, "angleT": 50},
    labels: {"O": "O", "P": "P", "Q": "Q", "T": "R"},
    provenance: [
      {"param": "angleT", "field": "questionText", "quote": "makes an angle 50° with the tangent PR"},
    ],
    expect: [
      {"quantity": "angleO", "value": 100, "tolPct": 0.5, "quote": "(B) 100°"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "SQP-M-CI-004",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "chord": "6", "angleOAB": 30},
    part: "Main",
    provenance: [
      {"param": "chord", "field": "questionText", "quote": "length of the chord is 6 cm"},
      {"param": "angleOAB", "field": "questionText", "quote": "an angle of 30°"},
    ],
    expect: [
      {"quantity": "t", "value": 6, "tolPct": 0.5, "quote": "PA = 6 cm"},
      {"quantity": "r", "value": 3.4641, "tolPct": 0.5, "quote": "OA = 2√3 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "APQ-M-CIRC-003",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "d": "4", "angleOPA": 30},
    draw: {"single": true},
    labels: {"O": "O", "P": "T", "A": "A"},
    provenance: [
      {"param": "d", "field": "questionText", "quote": "OT = 4 cm"},
      {"param": "angleOPA", "field": "questionText", "quote": "∠OTA = 30°"},
    ],
    expect: [
      {"quantity": "t", "value": 3.4641, "tolPct": 0.5, "quote": "(c) 2√3 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "PYQ-M-CIRC-005",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "r": "9", "d": "41"},
    draw: {"single": true},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 9 cm"},
      {"param": "d", "field": "questionText", "quote": "a point 41 cm from the centre"},
    ],
    expect: [
      {"quantity": "t", "value": 40, "tolPct": 0.5, "quote": "(a) 40 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "PYQ-M-CIRC-015",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "concentricChord", "unit": "cm", "R": "5", "r": "3"},
    labels: {"O": "O", "M": "P", "A": "A", "B": "B"},
    provenance: [
      {"param": "R", "field": "questionText", "quote": "radii 5 cm and 3 cm"},
      {"param": "r", "field": "questionText", "quote": "radii 5 cm and 3 cm"},
    ],
    expect: [
      {"quantity": "chord", "value": 8, "tolPct": 0.5, "quote": "AB = 8 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "PYQ-M-2026-CIRC-006",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "r": "5", "d": "13"},
    draw: {"third": true},
    labels: {"O": "O", "P": "P", "A": "Q", "B": "R", "E": "C", "C": "A", "D": "B"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 5 cm"},
      {"param": "d", "field": "questionText", "quote": "OP = 13 cm"},
    ],
    expect: [
      {"quantity": "thirdCD", "value": 6.6667, "tolPct": 0.5, "quote": "AB = 20/3 cm ≈ 6.67 cm"},
      {"quantity": "thirdPC", "value": 8.6667, "tolPct": 0.5, "quote": "PA = 26/3 cm ≈ 8.67 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "PYQ-M-2024-CIRC-001",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "r": "5", "angleP": 60},
    provenance: [
      {"param": "angleP", "field": "questionText", "quote": "inclined at an angle of 60º"},
      {"param": "r", "field": "questionText", "quote": "radius 5 cm"},
    ],
    expect: [
      {"quantity": "t", "value": 8.660254, "tolPct": 0.5, "quote": "(d) 5√3 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "PYQ-M-2024-CIRC-008a",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "r": "3", "angleP": 60},
    provenance: [
      {"param": "angleP", "field": "questionText", "quote": "inclined at an angle of 60°"},
      {"param": "r", "field": "questionText", "quote": "radius 3 cm"},
    ],
    expect: [
      {"quantity": "t", "value": 5.19615, "tolPct": 0.5, "quote": "AP = 3√3 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "PYQ-M-2025-CIRC-002",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "m", "t": "10", "d": "26"},
    provenance: [
      {"param": "d", "field": "questionText", "quote": "a distance of 26 m from the centre"},
      {"param": "t", "field": "questionText", "quote": "are 10 m"},
    ],
    expect: [
      {"quantity": "r", "value": 24, "tolPct": 0.5, "quote": "radius = 24 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "PYQ-M-2025-CIRC-003",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "parallelChord", "unit": "cm", "r": "10", "h": "16"},
    labels: {"O": "O", "P": "A", "M": "P", "C": "C", "D": "D"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 10 cm"},
      {"param": "h", "field": "questionText", "quote": "at a distance of 16 cm from A"},
    ],
    expect: [
      {"quantity": "chord", "value": 16, "tolPct": 0.5, "quote": "2 × 8 = 16 cm"},
      {"quantity": "OM", "value": 6, "tolPct": 0.5, "quote": "OP = 16 – 10 = 6 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-001",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "scaleFree": true, "anglePAB": 65},
    provenance: [
      {"param": "anglePAB", "field": "questionText", "quote": "∠PAB = 65°"},
    ],
    expect: [
      {"quantity": "angleP", "value": 50, "tolPct": 0.5, "quote": "50°"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-005",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "scaleFree": true, "angleP": 80},
    provenance: [
      {"param": "angleP", "field": "questionText", "quote": "∠APB = 80°"},
    ],
    expect: [
      {"quantity": "angleOPA", "value": 40, "tolPct": 0.5, "quote": "∠OPA = 40°"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-008",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "scaleFree": true, "angleP": 50},
    draw: {"chord": true},
    labels: {"O": "O", "P": "T", "A": "P", "B": "Q"},
    provenance: [
      {"param": "angleP", "field": "questionText", "quote": "∠PTQ = 50°"},
    ],
    expect: [
      {"quantity": "anglePAB", "value": 65, "tolPct": 0.5, "quote": "∠TPQ = 65°"},
      {"quantity": "angleOAB", "value": 25, "tolPct": 0.5, "quote": "∠OPQ = 25°"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-010",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "r": "5", "d": "13"},
    draw: {"chord": true},
    labels: {"O": "O", "P": "T", "A": "A", "B": "B"},
    part: "(b)",
    provenance: [
      {"param": "d", "field": "questionText", "quote": "13 cm from the centre O"},
      {"param": "r", "field": "questionText", "quote": "radius 5 cm"},
    ],
    expect: [
      {"quantity": "t", "value": 12, "tolPct": 0.5, "quote": "TA = 12 cm"},
      {"quantity": "chord", "value": 9.2308, "tolPct": 0.5, "quote": "AB = 120/13 cm ≈ 9.23 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-220",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "m", "r": "5", "d": "13"},
    draw: {"single": true},
    provenance: [
      {"param": "d", "field": "questionText", "quote": "13 m from the centre O"},
      {"param": "r", "field": "questionText", "quote": "radius 5 m"},
    ],
    expect: [
      {"quantity": "t", "value": 12, "tolPct": 0.5, "quote": "PA = √(13² − 5²) = √144 = 12 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-221",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "m", "t": "24", "d": "25"},
    draw: {"single": true},
    labels: {"O": "O", "P": "P", "A": "T"},
    provenance: [
      {"param": "d", "field": "questionText", "quote": "25 m from the centre O"},
      {"param": "t", "field": "questionText", "quote": "PT = 24 m"},
    ],
    expect: [
      {"quantity": "r", "value": 7, "tolPct": 0.5, "quote": "OT = √(25² − 24²) = √49 = 7 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-224",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "m", "scaleFree": true, "angleP": 80},
    provenance: [
      {"param": "angleP", "field": "questionText", "quote": "∠APB = 80°"},
    ],
    expect: [
      {"quantity": "angleO", "value": 100, "tolPct": 0.5, "quote": "∠AOB = 360° − 180° − 80° = 100°"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-226",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "km", "r": "6", "d": "10"},
    draw: {"single": true},
    labels: {"O": "O", "P": "P", "A": "T"},
    provenance: [
      {"param": "d", "field": "questionText", "quote": "10 km from the centre O"},
      {"param": "r", "field": "questionText", "quote": "radius 6 km"},
    ],
    expect: [
      {"quantity": "t", "value": 8, "tolPct": 0.5, "quote": "PT = √(10² − 6²) = √64 = 8 km"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-285",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "m", "r": "9", "t": "12"},
    part: "(b), (c)",
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 9 m"},
      {"param": "t", "field": "questionText", "quote": "The guide-line PA is 12 m long"},
    ],
    expect: [
      {"quantity": "d", "value": 15, "tolPct": 0.5, "quote": "OP = 15 m"},
      {"quantity": "perimeterOAPB", "value": 3360, "tolPct": 0.5, "quote": "cost = ₹3360", "factor": 80},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-288",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "concentricChord", "unit": "m", "R": "65", "r": "33"},
    labels: {"O": "O", "M": "P", "A": "A", "B": "B"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 33 m"},
      {"param": "R", "field": "questionText", "quote": "radius 65 m"},
    ],
    expect: [
      {"quantity": "chord", "value": 112, "tolPct": 0.5, "quote": "AB = 112 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIR-M15",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "incircle", "unit": "cm", "AB": "12", "BC": "12", "CA": "12"},
    provenance: [
      {"param": "AB", "field": "questionText", "quote": "an equilateral triangle of side 12 cm"},
      {"param": "BC", "field": "questionText", "quote": "an equilateral triangle of side 12 cm"},
      {"param": "CA", "field": "questionText", "quote": "an equilateral triangle of side 12 cm"},
    ],
    expect: [
      {"quantity": "r", "value": 3.4641, "tolPct": 0.5, "quote": "2√3 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIR-H03",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "incircle", "unit": "cm", "AB": "6", "BC": "8", "angleB": 90},
    provenance: [
      {"param": "AB", "field": "questionText", "quote": "legs 6 cm and 8 cm"},
      {"param": "BC", "field": "questionText", "quote": "legs 6 cm and 8 cm"},
      {"param": "angleB", "field": "questionText", "quote": "a right triangle with legs", "derived": "the right angle is between the two legs (drawn at B)"},
    ],
    expect: [
      {"quantity": "r", "value": 2, "tolPct": 0.5, "quote": "2 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIR-H07",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "incircle", "unit": "cm", "AB": "6", "BC": "8", "CA": "10"},
    provenance: [
      {"param": "AB", "field": "questionText", "quote": "AB = 6 cm"},
      {"param": "BC", "field": "questionText", "quote": "BC = 8 cm"},
      {"param": "CA", "field": "questionText", "quote": "CA = 10 cm"},
    ],
    expect: [
      {"quantity": "r", "value": 2, "tolPct": 0.5, "quote": "r = 2 cm"},
      {"quantity": "area", "value": 24, "tolPct": 0.5, "quote": "Area = r × s = 24 cm²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CI2-013",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "incircle", "unit": "cm", "x": "5", "y": "7", "z": "8"},
    labels: {"A": "A", "B": "B", "C": "C", "D": "X", "E": "Y", "F": "Z"},
    provenance: [
      {"param": "x", "field": "questionText", "quote": "AZ = 5 cm"},
      {"param": "y", "field": "questionText", "quote": "BX = 7 cm"},
      {"param": "z", "field": "questionText", "quote": "CY = 8 cm"},
    ],
    expect: [
      {"quantity": "perimeter", "value": 40, "tolPct": 0.5, "quote": "40 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CIRC-N-NCERT-10-LA-001",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "incircle", "unit": "cm", "r": "4", "y": "8", "z": "6"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "a circle of radius 4 cm"},
      {"param": "y", "field": "questionText", "quote": "are of lengths 8 cm and 6 cm"},
      {"param": "z", "field": "questionText", "quote": "are of lengths 8 cm and 6 cm"},
    ],
    expect: [
      {"quantity": "AB", "value": 15, "tolPct": 0.5, "quote": "AB = 15 cm"},
      {"quantity": "CA", "value": 13, "tolPct": 0.5, "quote": "AC = 13 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "PYQ-M-2026-TRI-002",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "incircle", "unit": "cm", "AB": "8", "BC": "15", "angleB": 90},
    provenance: [
      {"param": "AB", "field": "questionText", "quote": "are 8 cm and 15 cm"},
      {"param": "BC", "field": "questionText", "quote": "are 8 cm and 15 cm"},
      {"param": "angleB", "field": "questionText", "quote": "right angled at B", "derived": "right angle at B"},
    ],
    expect: [
      {"quantity": "r", "value": 3, "tolPct": 0.5, "quote": "r = 3 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "PYQ-M-2024-TRI-004a",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "incircle", "unit": "cm", "AB": "24", "BC": "7", "angleB": 90},
    provenance: [
      {"param": "AB", "field": "questionText", "quote": "AB = 24 cm"},
      {"param": "BC", "field": "questionText", "quote": "BC = 7 cm"},
      {"param": "angleB", "field": "questionText", "quote": "right-angled at B", "derived": "right angle at B"},
    ],
    expect: [
      {"quantity": "r", "value": 3, "tolPct": 0.5, "quote": "r = 3 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-007",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "incircle", "unit": "cm", "AB": "10", "BC": "8", "CA": "12"},
    labels: {"A": "A", "B": "B", "C": "C", "D": "Q", "E": "R", "F": "P"},
    provenance: [
      {"param": "AB", "field": "questionText", "quote": "AB = 10 cm"},
      {"param": "BC", "field": "questionText", "quote": "BC = 8 cm"},
      {"param": "CA", "field": "questionText", "quote": "CA = 12 cm"},
    ],
    expect: [
      {"quantity": "x", "value": 7, "tolPct": 0.5, "quote": "AP = 7 cm"},
      {"quantity": "y", "value": 3, "tolPct": 0.5, "quote": "BQ = 3 cm"},
      {"quantity": "z", "value": 5, "tolPct": 0.5, "quote": "CR = 5 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-104",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "incircle", "unit": "m", "AB": "500", "BC": "700", "CA": "600"},
    labels: {"A": "A", "B": "B", "C": "C", "D": "Q", "E": "R", "F": "P"},
    provenance: [
      {"param": "AB", "field": "questionText", "quote": "AB = 500 m"},
      {"param": "BC", "field": "questionText", "quote": "BC = 700 m"},
      {"param": "CA", "field": "questionText", "quote": "CA = 600 m"},
    ],
    expect: [
      {"quantity": "x", "value": 200, "tolPct": 0.5, "quote": "AP = 200 m"},
      {"quantity": "y", "value": 300, "tolPct": 0.5, "quote": "BQ = 300 m"},
      {"quantity": "z", "value": 400, "tolPct": 0.5, "quote": "CR = 400 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-105",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "incircle", "unit": "m", "x": "20", "z": "6", "angleB": 90},
    draw: {"xOnAE": true},
    labels: {"A": "A", "B": "B", "C": "C", "D": "Q", "E": "R", "F": "P", "O": "O"},
    provenance: [
      {"param": "x", "field": "questionText", "quote": "AR = 20 m"},
      {"param": "z", "field": "questionText", "quote": "CR = 6 m"},
      {"param": "angleB", "field": "questionText", "quote": "right-angled at B", "derived": "right angle at B"},
    ],
    expect: [
      {"quantity": "r", "value": 4, "tolPct": 0.5, "quote": "Radius = 4 m"},
      {"quantity": "perimeter", "value": 60, "tolPct": 0.5, "quote": "perimeter 60 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-106",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "m", "r": "1.5", "d": "2.5"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 1.5 m"},
      {"param": "d", "field": "questionText", "quote": "2.5 m from O"},
    ],
    expect: [
      {"quantity": "t", "value": 2, "tolPct": 0.5, "quote": "PA = 2 m"},
      {"quantity": "areaOAPB", "value": 3, "tolPct": 0.5, "quote": "(iii) 3 m²"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-107",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "r": "16", "d": "34"},
    labels: {"O": "O", "P": "N", "A": "A", "B": "B"},
    part: "(ii)",
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 16 cm"},
      {"param": "d", "field": "questionText", "quote": "ON = 34 cm"},
    ],
    expect: [
      {"quantity": "t", "value": 30, "tolPct": 0.5, "quote": "NA = 30 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-107",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "r": "16", "angleP": 60},
    labels: {"O": "O", "P": "N", "A": "A", "B": "B"},
    part: "(iii)",
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 16 cm"},
      {"param": "angleP", "field": "questionText", "quote": "∠ANB = 60°"},
    ],
    expect: [
      {"quantity": "d", "value": 32, "tolPct": 0.5, "quote": "ON = 32 cm"},
      {"quantity": "t", "value": 27.7128, "tolPct": 0.5, "quote": "NA = 16√3 cm ≈ 27.7 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-109",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "m", "r": "6", "d": "10"},
    draw: {"third": true},
    labels: {"O": "O", "P": "P", "A": "Q", "B": "R", "E": "C", "C": "A", "D": "B"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 6 m"},
      {"param": "d", "field": "questionText", "quote": "The main gate P is 10 m from O"},
    ],
    expect: [
      {"quantity": "t", "value": 8, "tolPct": 0.5, "quote": "(i) PQ = 8 m"},
      {"quantity": "pToCircle", "value": 4, "tolPct": 0.5, "quote": "(ii) PC = 4 m"},
      {"quantity": "thirdCD", "value": 6, "tolPct": 0.5, "quote": "(iii) AB = 6 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-110",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "commonTangent", "unit": "cm", "R": "30", "r": "10", "d": "52"},
    draw: {"kind": "direct"},
    labels: {"O": "O", "C": "C", "A": "A", "B": "B"},
    provenance: [
      {"param": "R", "field": "questionText", "quote": "radius 30 cm"},
      {"param": "r", "field": "questionText", "quote": "radius 10 cm"},
      {"param": "d", "field": "questionText", "quote": "OC = 52 cm"},
    ],
    expect: [
      {"quantity": "L", "value": 48, "tolPct": 0.5, "quote": "AB = 48 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-200",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "r": "35", "t": "84"},
    draw: {"single": true},
    labels: {"O": "O", "P": "Q", "A": "P"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 35 cm"},
      {"param": "t", "field": "questionText", "quote": "84 cm from P"},
    ],
    expect: [
      {"quantity": "d", "value": 91, "tolPct": 0.5, "quote": "OQ = 91 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-201",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "m", "t": "20", "d": "29"},
    draw: {"single": true},
    labels: {"O": "O", "P": "P", "A": "T"},
    provenance: [
      {"param": "t", "field": "questionText", "quote": "The rope PT is 20 m long"},
      {"param": "d", "field": "questionText", "quote": "29 m from the centre"},
    ],
    expect: [
      {"quantity": "r", "value": 21, "tolPct": 0.5, "quote": "Radius = 21 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-202",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "m", "scaleFree": true, "angleP": 64},
    provenance: [
      {"param": "angleP", "field": "questionText", "quote": "∠APB = 64°"},
    ],
    expect: [
      {"quantity": "angleO", "value": 116, "tolPct": 0.5, "quote": "∠AOB = 116°"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-205",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "incircle", "unit": "m", "x": "3.5", "y": "4.5", "z": "6"},
    labels: {"A": "A", "B": "B", "C": "C", "D": "Q", "E": "R", "F": "P"},
    provenance: [
      {"param": "x", "field": "questionText", "quote": "AP = 3.5 m"},
      {"param": "y", "field": "questionText", "quote": "BQ = 4.5 m"},
      {"param": "z", "field": "questionText", "quote": "CR = 6 m"},
    ],
    expect: [
      {"quantity": "perimeter", "value": 28, "tolPct": 0.5, "quote": "Perimeter = 28 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-206",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "concentricChord", "unit": "m", "R": "17", "r": "15"},
    labels: {"O": "O"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 15 m"},
      {"param": "R", "field": "questionText", "quote": "radius 17 m"},
    ],
    expect: [
      {"quantity": "chord", "value": 16, "tolPct": 0.5, "quote": "Length of rope = 16 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-207",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "commonTangent", "unit": "mm", "R": "9", "r": "4", "d": "13"},
    draw: {"kind": "direct"},
    labels: {"A": "A", "B": "B"},
    provenance: [
      {"param": "R", "field": "questionText", "quote": "radius 9 mm"},
      {"param": "r", "field": "questionText", "quote": "radius 4 mm"},
      {"param": "d", "field": "questionText", "quote": "13 mm apart"},
    ],
    expect: [
      {"quantity": "L", "value": 12, "tolPct": 0.5, "quote": "AB = 12 mm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-210",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "m", "scaleFree": true, "angleO": 140},
    draw: {"chord": true},
    provenance: [
      {"param": "angleO", "field": "questionText", "quote": "∠AOB = 140°"},
    ],
    expect: [
      {"quantity": "anglePAB", "value": 70, "tolPct": 0.5, "quote": "∠PAB = 70°"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-211",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "r": "12", "t": "16"},
    labels: {"O": "O", "P": "N", "A": "A", "B": "B"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 12 cm"},
      {"param": "t", "field": "questionText", "quote": "each straight part is 16 cm long"},
    ],
    expect: [
      {"quantity": "d", "value": 20, "tolPct": 0.5, "quote": "ON = 20 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-212",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "m", "r": "300", "angleP": 90},
    provenance: [
      {"param": "angleP", "field": "questionText", "quote": "∠APB = 90°"},
      {"param": "r", "field": "questionText", "quote": "the radius of the island is 300 m"},
    ],
    expect: [
      {"quantity": "d", "value": 424.264, "tolPct": 0.5, "quote": "OP = 300√2 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-213",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "m", "r": "15", "angleP": 60},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 15 m"},
      {"param": "angleP", "field": "questionText", "quote": "∠APB = 60°"},
    ],
    expect: [
      {"quantity": "d", "value": 30, "tolPct": 0.5, "quote": "OP = 30 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-215",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "m", "d": "26", "t": "24"},
    draw: {"single": true},
    labels: {"O": "O", "P": "P", "A": "T"},
    provenance: [
      {"param": "d", "field": "questionText", "quote": "26 m from the centre O"},
      {"param": "t", "field": "finalAnswer", "quote": "PT = 24 m", "derived": "the row's own answer"},
    ],
    expect: [
      {"quantity": "r", "value": 10, "tolPct": 0.5, "quote": "OT = √(676 − 576) = 10 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-229",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "m", "r": "20", "d": "29"},
    draw: {"single": true},
    labels: {"O": "O", "P": "C", "A": "T"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 20 m"},
      {"param": "d", "field": "questionText", "quote": "29 m from O"},
    ],
    expect: [
      {"quantity": "t", "value": 21, "tolPct": 0.5, "quote": "CT = 21 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-230",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "m", "d": "17", "t": "15"},
    labels: {"O": "O", "P": "K", "A": "A", "B": "B"},
    provenance: [
      {"param": "d", "field": "questionText", "quote": "17 m from the centre O"},
      {"param": "t", "field": "questionText", "quote": "KA = KB = 15 m"},
    ],
    expect: [
      {"quantity": "r", "value": 8, "tolPct": 0.5, "quote": "Radius = 8 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-231",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "km", "r": "9", "t": "40"},
    draw: {"single": true},
    labels: {"O": "O", "P": "S", "A": "T"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 9 km"},
      {"param": "t", "field": "questionText", "quote": "it has travelled 40 km from T"},
    ],
    expect: [
      {"quantity": "d", "value": 41, "tolPct": 0.5, "quote": "OS = 41 km"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-232",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "concentricChord", "unit": "m", "R": "25", "r": "7"},
    provenance: [
      {"param": "R", "field": "questionText", "quote": "a circle of radius 25 m"},
      {"param": "r", "field": "questionText", "quote": "has radius 7 m"},
    ],
    expect: [
      {"quantity": "chord", "value": 48, "tolPct": 0.5, "quote": "Footpath = 48 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-233",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "m", "r": "12", "d": "37"},
    draw: {"single": true},
    labels: {"O": "O", "P": "D", "A": "T"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 12 m"},
      {"param": "d", "field": "questionText", "quote": "37 m from O"},
    ],
    expect: [
      {"quantity": "t", "value": 35, "tolPct": 0.5, "quote": "DT = 35 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-238",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "r": "45", "angleP": 90},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 45 cm"},
      {"param": "angleP", "field": "questionText", "quote": "meet at the corner P at right angles", "derived": "∠APB = 90°"},
    ],
    expect: [
      {"quantity": "t", "value": 45, "tolPct": 0.5, "quote": "PA = 45 cm"},
      {"quantity": "d", "value": 63.63, "tolPct": 0.5, "quote": "OP = 45√2 cm ≈ 63.63 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-239",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "incircle", "unit": "m", "AB": "20", "BC": "21", "angleB": 90},
    provenance: [
      {"param": "AB", "field": "questionText", "quote": "AB = 20 m"},
      {"param": "BC", "field": "questionText", "quote": "BC = 21 m"},
      {"param": "angleB", "field": "questionText", "quote": "∠B = 90°"},
    ],
    expect: [
      {"quantity": "r", "value": 6, "tolPct": 0.5, "quote": "Radius = 6 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-240",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "incircle", "unit": "m", "AB": "15", "BC": "17", "x": "6"},
    labels: {"A": "A", "B": "B", "C": "C", "D": "Q", "E": "R", "F": "P"},
    provenance: [
      {"param": "AB", "field": "questionText", "quote": "AB = 15 m"},
      {"param": "BC", "field": "questionText", "quote": "BC = 17 m"},
      {"param": "x", "field": "questionText", "quote": "AP = 6 m"},
    ],
    expect: [
      {"quantity": "CA", "value": 14, "tolPct": 0.5, "quote": "CA = 14 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-241",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "parallelChord", "unit": "cm", "r": "13", "h": "8"},
    labels: {"O": "O", "P": "A", "M": "M", "C": "C", "D": "D"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 13 cm"},
      {"param": "h", "field": "questionText", "quote": "8 cm above A"},
    ],
    expect: [
      {"quantity": "chord", "value": 24, "tolPct": 0.5, "quote": "CD = 24 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-242",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "m", "t": "24", "gap": "16"},
    draw: {"single": true},
    labels: {"O": "O", "P": "P", "A": "T", "E": "E"},
    provenance: [
      {"param": "t", "field": "questionText", "quote": "24 m from the gate T"},
      {"param": "gap", "field": "questionText", "quote": "is 16 m from her"},
    ],
    expect: [
      {"quantity": "r", "value": 10, "tolPct": 0.5, "quote": "Radius = 10 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-244",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "m", "r": "8", "d": "17"},
    draw: {"chord": true},
    labels: {"O": "O", "P": "S", "A": "A", "B": "B"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 8 m"},
      {"param": "d", "field": "questionText", "quote": "17 m from O"},
    ],
    expect: [
      {"quantity": "t", "value": 15, "tolPct": 0.5, "quote": "SA = 15 m"},
      {"quantity": "chord", "value": 14.1176, "tolPct": 0.5, "quote": "AB = 240/17 m ≈ 14.12 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-245",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "m", "chord": "20", "angleOAB": 30},
    provenance: [
      {"param": "chord", "field": "questionText", "quote": "A straight wooden bridge AB, 20 m long"},
      {"param": "angleOAB", "field": "questionText", "quote": "∠OAB = 30°"},
    ],
    expect: [
      {"quantity": "t", "value": 20, "tolPct": 0.5, "quote": "PA = 20 m"},
      {"quantity": "r", "value": 11.547, "tolPct": 0.5, "quote": "radius = 20√3/3 m ≈ 11.55 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-246",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "incircle", "unit": "m", "r": "3", "x": "12", "angleB": 90},
    draw: {"xOnAE": true},
    labels: {"A": "A", "B": "B", "C": "C", "D": "Q", "E": "R", "F": "P", "O": "O"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 3 m"},
      {"param": "x", "field": "questionText", "quote": "The distance from corner A to R is 12 m"},
      {"param": "angleB", "field": "questionText", "quote": "∠B = 90°"},
    ],
    expect: [
      {"quantity": "z", "value": 5, "tolPct": 0.5, "quote": "CR = 5 m"},
      {"quantity": "perimeter", "value": 40, "tolPct": 0.5, "quote": "perimeter = 40 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-248",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "m", "r": "10", "t": "10√3"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 10 m"},
      {"param": "t", "field": "questionText", "quote": "PA = 10√3 m"},
    ],
    expect: [
      {"quantity": "d", "value": 20, "tolPct": 0.5, "quote": "OP = 20 m"},
      {"quantity": "angleP", "value": 60, "tolPct": 0.5, "quote": "∠APB = 60°"},
      {"quantity": "angleO", "value": 120, "tolPct": 0.5, "quote": "∠AOB = 120°"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-249",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "commonTangent", "unit": "cm", "R": "9", "r": "4", "d": "13"},
    draw: {"kind": "direct"},
    labels: {"O": "O₁", "C": "O₂", "A": "A", "B": "B"},
    provenance: [
      {"param": "R", "field": "questionText", "quote": "radii 9 cm and 4 cm"},
      {"param": "r", "field": "questionText", "quote": "radii 9 cm and 4 cm"},
      {"param": "d", "field": "solutionSteps", "quote": "O₁O₂ = 9 + 4 = 13 cm", "derived": "the circles touch, so the centres are R + r apart"},
    ],
    expect: [
      {"quantity": "L", "value": 12, "tolPct": 0.5, "quote": "AB = 12 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-252",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "incircle", "unit": "cm", "y": "7", "z": "9", "perimeter": "50"},
    labels: {"A": "A", "B": "B", "C": "C", "D": "Q", "E": "R", "F": "P"},
    provenance: [
      {"param": "y", "field": "questionText", "quote": "BQ = 7 cm"},
      {"param": "z", "field": "questionText", "quote": "CR = 9 cm"},
      {"param": "perimeter", "field": "questionText", "quote": "the three sides of the frame is 50 cm"},
    ],
    expect: [
      {"quantity": "AB", "value": 16, "tolPct": 0.5, "quote": "AB = 16 cm"},
      {"quantity": "BC", "value": 16, "tolPct": 0.5, "quote": "BC = 16 cm"},
      {"quantity": "CA", "value": 18, "tolPct": 0.5, "quote": "CA = 18 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-254",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "m", "scaleFree": true, "angleP": 64},
    draw: {"chord": true},
    labels: {"O": "O", "P": "T", "A": "A", "B": "B"},
    provenance: [
      {"param": "angleP", "field": "questionText", "quote": "∠ATB = 64°"},
    ],
    expect: [
      {"quantity": "anglePAB", "value": 58, "tolPct": 0.5, "quote": "∠TAB = 58°"},
      {"quantity": "angleOAB", "value": 32, "tolPct": 0.5, "quote": "∠OAB = 32°"},
      {"quantity": "angleO", "value": 116, "tolPct": 0.5, "quote": "∠AOB = 116°"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-255",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "r": "30", "angleP": 60},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 30 cm"},
      {"param": "angleP", "field": "questionText", "quote": "at an angle of 60°"},
    ],
    expect: [
      {"quantity": "d", "value": 60, "tolPct": 0.5, "quote": "OP = 60 cm"},
      {"quantity": "t", "value": 51.96, "tolPct": 0.5, "quote": "PA = 30√3 cm ≈ 51.96 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-260",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "concentricChord", "unit": "m", "R": "29", "r": "20"},
    provenance: [
      {"param": "R", "field": "questionText", "quote": "radius 29 m"},
      {"param": "r", "field": "questionText", "quote": "radius 20 m"},
    ],
    expect: [
      {"quantity": "half", "value": 21, "tolPct": 0.5, "quote": "AM = 21 m"},
      {"quantity": "chord", "value": 42, "tolPct": 0.5, "quote": "AB = 42 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-261",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "commonTangent", "unit": "cm", "R": "9", "r": "6", "d": "25"},
    draw: {"kind": "transverse"},
    labels: {"O": "O", "C": "C", "A": "A", "B": "B", "X": "X"},
    provenance: [
      {"param": "R", "field": "questionText", "quote": "radius 9 cm"},
      {"param": "r", "field": "questionText", "quote": "radius 6 cm"},
      {"param": "d", "field": "questionText", "quote": "OC = 25 cm"},
    ],
    expect: [
      {"quantity": "OX", "value": 15, "tolPct": 0.5, "quote": "OX = 15 cm"},
      {"quantity": "L", "value": 20, "tolPct": 0.5, "quote": "AB = 20 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-262",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "incircle", "unit": "m", "AB": "21", "BC": "20", "CA": "29", "angleB": 90},
    labels: {"A": "A", "B": "B", "C": "C", "D": "Q", "E": "R", "F": "P", "O": "O"},
    provenance: [
      {"param": "AB", "field": "questionText", "quote": "AB = 21 m"},
      {"param": "BC", "field": "questionText", "quote": "BC = 20 m"},
      {"param": "CA", "field": "questionText", "quote": "CA = 29 m"},
      {"param": "angleB", "field": "questionText", "quote": "right-angled at B", "derived": "right angle at B"},
    ],
    expect: [
      {"quantity": "r", "value": 6, "tolPct": 0.5, "quote": "r = 6 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-263",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "m", "r": "250", "angleP": 90},
    part: "(i), (ii)",
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 250 m"},
      {"param": "angleP", "field": "questionText", "quote": "∠APB = 90°"},
    ],
    expect: [
      {"quantity": "angleO", "value": 90, "tolPct": 0.5, "quote": "∠AOB = 90°"},
      {"quantity": "t", "value": 250, "tolPct": 0.5, "quote": "PA = 250 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-264",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "mm", "r": "9", "angleP": 120},
    provenance: [
      {"param": "angleP", "field": "questionText", "quote": "an angle of 120°"},
      {"param": "r", "field": "questionText", "quote": "radius 9 mm"},
    ],
    expect: [
      {"quantity": "angleOPA", "value": 60, "tolPct": 0.5, "quote": "∠OPA = 60°"},
      {"quantity": "d", "value": 10.392, "tolPct": 0.5, "quote": "OP = 6√3 mm ≈ 10.392 mm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-266",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "m", "r": "15", "d": "39"},
    labels: {"O": "O", "P": "A", "A": "P", "B": "Q"},
    part: "(i)",
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 15 m"},
      {"param": "d", "field": "questionText", "quote": "39 m from O"},
    ],
    expect: [
      {"quantity": "t", "value": 36, "tolPct": 0.5, "quote": "AP = 36 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-268",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "km", "r": "10", "d": "20"},
    labels: {"O": "O", "P": "P", "A": "T", "B": "T'"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 10 km"},
      {"param": "d", "field": "questionText", "quote": "20 km from O"},
    ],
    expect: [
      {"quantity": "angleP", "value": 60, "tolPct": 0.5, "quote": "∠TPT' = 60°"},
      {"quantity": "t", "value": 17.32, "tolPct": 0.5, "quote": "PT = 10√3 km ≈ 17.32 km"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-271",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "m", "scaleFree": true, "angleP": 64},
    draw: {"chord": true},
    labels: {"O": "O", "P": "T", "A": "P", "B": "Q"},
    provenance: [
      {"param": "angleP", "field": "questionText", "quote": "∠PTQ = 64°"},
    ],
    expect: [
      {"quantity": "angleO", "value": 116, "tolPct": 0.5, "quote": "∠POQ = 116°"},
      {"quantity": "anglePAB", "value": 58, "tolPct": 0.5, "quote": "∠TPQ = 58°"},
      {"quantity": "angleOAB", "value": 32, "tolPct": 0.5, "quote": "∠OPQ = 32°"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-272",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "r": "15", "angleP": 90},
    part: "(i), (ii)",
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 15 cm"},
      {"param": "angleP", "field": "questionText", "quote": "which are at right angles", "derived": "∠APB = 90°"},
    ],
    expect: [
      {"quantity": "t", "value": 15, "tolPct": 0.5, "quote": "PA = 15 cm"},
      {"quantity": "d", "value": 21.21, "tolPct": 0.5, "quote": "OP = 15√2 cm ≈ 21.21 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-273",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "concentricChord", "unit": "cm", "r": "9", "chord": "24"},
    part: "(i), (ii)",
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 9 cm"},
      {"param": "chord", "field": "questionText", "quote": "24 cm long"},
    ],
    expect: [
      {"quantity": "half", "value": 12, "tolPct": 0.5, "quote": "AM = 12 cm"},
      {"quantity": "R", "value": 15, "tolPct": 0.5, "quote": "outer radius = 15 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-274",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "incircle", "unit": "m", "AB": "18", "BC": "18", "CA": "18"},
    labels: {"A": "A", "B": "B", "C": "C", "D": "Q", "E": "R", "F": "P", "O": "O"},
    provenance: [
      {"param": "AB", "field": "questionText", "quote": "equilateral triangle ABC of side 18 m"},
      {"param": "BC", "field": "questionText", "quote": "equilateral triangle ABC of side 18 m"},
      {"param": "CA", "field": "questionText", "quote": "equilateral triangle ABC of side 18 m"},
    ],
    expect: [
      {"quantity": "x", "value": 9, "tolPct": 0.5, "quote": "AP = 9 m"},
      {"quantity": "r", "value": 5.196, "tolPct": 0.5, "quote": "radius = 3√3 m ≈ 5.196 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-276",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "m", "r": "12", "d": "20"},
    draw: {"chord": true},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 12 m"},
      {"param": "d", "field": "questionText", "quote": "The gate P is 20 m from O"},
    ],
    expect: [
      {"quantity": "t", "value": 16, "tolPct": 0.5, "quote": "PA = 16 m"},
      {"quantity": "chord", "value": 19.2, "tolPct": 0.5, "quote": "AB = 19.2 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-277",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "m", "r": "15", "chord": "24"},
    labels: {"O": "O", "P": "T", "A": "P", "B": "Q", "M": "M"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 15 m"},
      {"param": "chord", "field": "questionText", "quote": "it is 24 m long"},
    ],
    expect: [
      {"quantity": "OM", "value": 9, "tolPct": 0.5, "quote": "OM = 9 m"},
      {"quantity": "d", "value": 25, "tolPct": 0.5, "quote": "OT = 25 m"},
      {"quantity": "t", "value": 20, "tolPct": 0.5, "quote": "TP = 20 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-278",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "t": "40", "d": "41"},
    draw: {"single": true},
    provenance: [
      {"param": "d", "field": "questionText", "quote": "41 cm from O"},
      {"param": "t", "field": "questionText", "quote": "The straight thread PA is 40 cm long"},
    ],
    expect: [
      {"quantity": "r", "value": 9, "tolPct": 0.5, "quote": "radius = 9 cm"},
      {"quantity": "pToCircle", "value": 32, "tolPct": 0.5, "quote": "shortest 32 cm"},
      {"quantity": "pFar", "value": 50, "tolPct": 0.5, "quote": "longest 50 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-279",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "m", "r": "40", "angleO": 120},
    draw: {"chord": true},
    labels: {"O": "O", "P": "T", "A": "P", "B": "Q"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 40 m"},
      {"param": "angleO", "field": "questionText", "quote": "∠POQ = 120°"},
    ],
    expect: [
      {"quantity": "angleP", "value": 60, "tolPct": 0.5, "quote": "∠PTQ = 60°"},
      {"quantity": "chord", "value": 69.28, "tolPct": 0.5, "quote": "PQ = TP = 40√3 m ≈ 69.28 m"},
      {"quantity": "t", "value": 69.28, "tolPct": 0.5, "quote": "PQ = TP = 40√3 m ≈ 69.28 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-281",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "m", "r": "10", "d": "26"},
    labels: {"O": "O", "P": "Z"},
    part: "(iii)",
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 10 m"},
      {"param": "d", "field": "questionText", "quote": "at Z, 26 m from O"},
    ],
    expect: [
      {"quantity": "t", "value": 24, "tolPct": 0.5, "quote": "two, each 24 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-284",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentChord", "unit": "cm", "scaleFree": true, "angleT": 40},
    labels: {"O": "O", "P": "A", "Q": "C", "T": "T"},
    provenance: [
      {"param": "angleT", "field": "questionText", "quote": "∠CAT = 40°"},
    ],
    expect: [
      {"quantity": "angleOPQ", "value": 50, "tolPct": 0.5, "quote": "∠OAC = ∠OCA = 50°"},
      {"quantity": "angleO", "value": 80, "tolPct": 0.5, "quote": "∠AOC = 80°"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-287",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "incircle", "unit": "cm", "r": "30", "AB": "150", "x": "120", "angleB": 90},
    draw: {"xOnAE": true},
    labels: {"A": "A", "B": "B", "C": "C", "D": "Q", "E": "R", "F": "P", "O": "O"},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 30 cm"},
      {"param": "AB", "field": "questionText", "quote": "The edge AB is 150 cm long"},
      {"param": "x", "field": "questionText", "quote": "AR = 120 cm"},
      {"param": "angleB", "field": "questionText", "quote": "right-angled at B", "derived": "right angle at B"},
    ],
    expect: [
      {"quantity": "z", "value": 50, "tolPct": 0.5, "quote": "x = 50"},
      {"quantity": "BC", "value": 80, "tolPct": 0.5, "quote": "BC = 80 cm"},
      {"quantity": "CA", "value": 170, "tolPct": 0.5, "quote": "CA = 170 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-289",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "cm", "r": "10", "angleP": 60},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 10 cm"},
      {"param": "angleP", "field": "questionText", "quote": "∠APB = 60°"},
    ],
    expect: [
      {"quantity": "angleO", "value": 120, "tolPct": 0.5, "quote": "∠AOB = 120°"},
      {"quantity": "d", "value": 20, "tolPct": 0.5, "quote": "OP = 20 cm"},
      {"quantity": "t", "value": 17.32, "tolPct": 0.5, "quote": "PA = 10√3 ≈ 17.32 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-291",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "m", "r": "15", "d": "25"},
    draw: {"chord": true},
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 15 m"},
      {"param": "d", "field": "questionText", "quote": "25 m from O"},
    ],
    expect: [
      {"quantity": "t", "value": 20, "tolPct": 0.5, "quote": "PA = PB = 20 m"},
      {"quantity": "areaOAPB", "value": 300, "tolPct": 0.5, "quote": "area = 300 m²"},
      {"quantity": "chord", "value": 24, "tolPct": 0.5, "quote": "AB = 24 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-292",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "incircle", "unit": "cm", "AB": "10", "CA": "10", "BC": "12"},
    provenance: [
      {"param": "AB", "field": "questionText", "quote": "AB = AC = 10 cm"},
      {"param": "CA", "field": "questionText", "quote": "AB = AC = 10 cm"},
      {"param": "BC", "field": "questionText", "quote": "BC = 12 cm"},
    ],
    expect: [
      {"quantity": "x", "value": 4, "tolPct": 0.5, "quote": "AF = 4 cm"},
      {"quantity": "r", "value": 3, "tolPct": 0.5, "quote": "radius = 3 cm"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-293",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "m", "scaleFree": true, "angleP": 70},
    draw: {"chord": true},
    provenance: [
      {"param": "angleP", "field": "questionText", "quote": "∠APB = 70°"},
    ],
    expect: [
      {"quantity": "anglePAB", "value": 55, "tolPct": 0.5, "quote": "∠PAB = 55°"},
      {"quantity": "angleOAB", "value": 35, "tolPct": 0.5, "quote": "∠OAB = 35°"},
      {"quantity": "angleO", "value": 110, "tolPct": 0.5, "quote": "∠AOB = 110°"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CIRC-294",
    slot: "solution",
    builder: "circleTangents",
    params: {"template": "tangentPair", "unit": "m", "r": "7", "d": "25"},
    part: "(a)",
    provenance: [
      {"param": "r", "field": "questionText", "quote": "radius 7 m"},
      {"param": "d", "field": "questionText", "quote": "25 m from O"},
    ],
    expect: [
      {"quantity": "t", "value": 24, "tolPct": 0.5, "quote": "PA = 24 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
];
