/**
 * Coordinate geometry — computed SOLUTION figures (DIAGRAMS-1 PR-2d).
 *
 * One entry per served row whose solution is a figure the row's OWN numbers fix
 * exactly (tangents from an external point, concentric circles, an inscribed circle,
 * BPT, plotted points, a sector or segment). Every row was read in full (question,
 * steps, answer) and its rendered figure eye-checked. Rows read and REFUSED (not fixed
 * by the row, no builder template, an official question figure already bound, the
 * row's own solution inconsistent, ...) are listed in the PR, not here — an unbound
 * row shows no figure, never a lookalike.
 *
 * `params` holds only numbers read from the row (each quoted in `provenance`, an exact
 * substring of the served row); `draw` holds display choices; `expect` is the row's own
 * answer. computedFigures.provenance.test.ts enforces both.
 *
 * GENERATED from the PR-2d decision table; edit the decisions, not this file by hand.
 */
import type { ComputedFigureBinding } from "./computedFigureTypes";

export const COORDINATE_GEOMETRY_SOLUTION_FIGURES: ComputedFigureBinding[] = [
  {
    kind: "computed",
    questionId: "CG-E01",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "U": "(2, 3)", "V": "(5, 7)"},
    draw: {"segs": [["U", "V"]]},
    labels: {"U": "", "V": ""},
    provenance: [
      {"param": "U", "field": "questionText", "quote": "(2, 3)"},
      {"param": "V", "field": "questionText", "quote": "(5, 7)"},
    ],
    expect: [
      {"quantity": "UV", "value": 5, "tolPct": 0.5, "quote": "5"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CG-N01",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "U": "(3, 4)", "V": "(0, 0)"},
    draw: {"segs": [["U", "V"]]},
    labels: {"U": "", "V": ""},
    provenance: [
      {"param": "U", "field": "questionText", "quote": "(3, 4)"},
      {"param": "V", "field": "questionText", "quote": "(0, 0)"},
    ],
    expect: [
      {"quantity": "UV", "value": 5, "tolPct": 0.5, "quote": "= 5 units"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CG2-001",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "A": "(3, 4)", "B": "(0, 0)"},
    draw: {"segs": [["A", "B"]]},
    provenance: [
      {"param": "A", "field": "questionText", "quote": "A(3, 4)"},
      {"param": "B", "field": "questionText", "quote": "B(0, 0)"},
    ],
    expect: [
      {"quantity": "AB", "value": 5, "tolPct": 0.5, "quote": "5"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CG2-024",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "A": "(0, 0)", "B": "(3, 4)"},
    draw: {"segs": [["A", "B"]]},
    provenance: [
      {"param": "A", "field": "questionText", "quote": "A(0, 0)"},
      {"param": "B", "field": "questionText", "quote": "B(3, 4)"},
    ],
    expect: [
      {"quantity": "AB", "value": 5, "tolPct": 0.5, "quote": "5"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CG2-026",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "P": "(2, 3)", "Q": "(5, 7)"},
    draw: {"segs": [["P", "Q"]]},
    provenance: [
      {"param": "P", "field": "questionText", "quote": "P(2, 3)"},
      {"param": "Q", "field": "questionText", "quote": "Q(5, 7)"},
    ],
    expect: [
      {"quantity": "PQ", "value": 5, "tolPct": 0.5, "quote": "PQ = QP = 5"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CG2-051",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "U": "(−5, 7)", "V": "(−1, 3)"},
    draw: {"segs": [["U", "V"]]},
    labels: {"U": "", "V": ""},
    provenance: [
      {"param": "U", "field": "questionText", "quote": "(−5, 7)"},
      {"param": "V", "field": "questionText", "quote": "(−1, 3)"},
    ],
    expect: [
      {"quantity": "UV", "value": 5.656854, "tolPct": 0.5, "quote": "4√2"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CG-N-NCERT-7-EX-012",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "U": "(2, 3)", "V": "(4, 1)"},
    draw: {"segs": [["U", "V"]]},
    labels: {"U": "", "V": ""},
    provenance: [
      {"param": "U", "field": "questionText", "quote": "(2, 3)"},
      {"param": "V", "field": "questionText", "quote": "(4, 1)"},
    ],
    expect: [
      {"quantity": "UV", "value": 2.828427, "tolPct": 0.5, "quote": "2√2 units"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CG-N-NCERT-7-EX-014",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "U": "(0, 0)", "V": "(36, 15)"},
    draw: {"segs": [["U", "V"]]},
    labels: {"U": "", "V": ""},
    provenance: [
      {"param": "U", "field": "questionText", "quote": "(0, 0)"},
      {"param": "V", "field": "questionText", "quote": "(36, 15)"},
    ],
    expect: [
      {"quantity": "UV", "value": 39, "tolPct": 0.5, "quote": "39 units"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CG-N-EXMPLR-7-EX-004",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "U": "(0, 5)", "V": "(−5, 0)"},
    draw: {"segs": [["U", "V"]]},
    labels: {"U": "", "V": ""},
    provenance: [
      {"param": "U", "field": "questionText", "quote": "(0, 5)"},
      {"param": "V", "field": "questionText", "quote": "(−5, 0)"},
    ],
    expect: [
      {"quantity": "UV", "value": 7.071068, "tolPct": 0.5, "quote": "5√2"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CG-233",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "W": "(2, 3)", "H": "(10, 9)"},
    draw: {"segs": [["W", "H"]]},
    provenance: [
      {"param": "W", "field": "questionText", "quote": "W(2, 3)"},
      {"param": "H", "field": "questionText", "quote": "H(10, 9)"},
    ],
    expect: [
      {"quantity": "WH", "value": 10, "tolPct": 0.5, "quote": "10 km"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CG-234",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "T": "(−3, 4)", "V": "(1, 2)"},
    draw: {"segs": [["T", "V"]]},
    provenance: [
      {"param": "T", "field": "questionText", "quote": "T(−3, 4)"},
      {"param": "V", "field": "questionText", "quote": "V(1, 2)"},
    ],
    expect: [
      {"quantity": "TV", "value": 4.4721, "tolPct": 0.5, "quote": "TV = √20 km"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CG-210",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "S": "(-1, 3)", "L": "(5, 11)"},
    draw: {"segs": [["S", "L"]]},
    provenance: [
      {"param": "S", "field": "questionText", "quote": "S(-1, 3)"},
      {"param": "L", "field": "questionText", "quote": "L(5, 11)"},
    ],
    expect: [
      {"quantity": "SL", "value": 20, "tolPct": 0.5, "quote": "20 km", "factor": 2},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CG-E04",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "U": "(1, −2)", "V": "(−3, 4)", "W": "(−3/5, 2/5)", "ratio": "2:3"},
    draw: {"section": {"point": "W", "a": "U", "b": "V"}},
    labels: {"U": "", "V": "", "W": ""},
    provenance: [
      {"param": "U", "field": "questionText", "quote": "(1, −2)"},
      {"param": "V", "field": "questionText", "quote": "(−3, 4)"},
      {"param": "ratio", "field": "questionText", "quote": "in the ratio 2:3"},
      {"param": "W", "field": "finalAnswer", "quote": "(−3/5, 2/5)"},
    ],
    expect: [
      {"quantity": "W.x", "value": -0.6, "tolPct": 0.5, "quote": "(−3/5, 2/5)"},
      {"quantity": "W.y", "value": 0.4, "tolPct": 0.5, "quote": "(−3/5, 2/5)"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CG-H03",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "A": "(2, −2)", "B": "(−7, 4)", "P": "(−1, 0)", "ratio": "1:2"},
    draw: {"section": {"point": "P", "a": "A", "b": "B"}},
    provenance: [
      {"param": "A", "field": "questionText", "quote": "A(2, −2)"},
      {"param": "B", "field": "questionText", "quote": "B(−7, 4)"},
      {"param": "ratio", "field": "questionText", "quote": "in the ratio 1:2"},
      {"param": "P", "field": "finalAnswer", "quote": "P(−1, 0)"},
    ],
    expect: [
      {"quantity": "P.x", "value": -1, "tolPct": 0.5, "quote": "k = −1"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CG-N04",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "A": "(1, 1)", "B": "(7, 4)", "P": "(5, 3)", "ratio": "2:1"},
    draw: {"section": {"point": "P", "a": "A", "b": "B"}},
    provenance: [
      {"param": "A", "field": "questionText", "quote": "A(1, 1)"},
      {"param": "B", "field": "questionText", "quote": "B(7, 4)"},
      {"param": "ratio", "field": "questionText", "quote": "in ratio 2:1"},
      {"param": "P", "field": "finalAnswer", "quote": "(5, 3)"},
    ],
    expect: [
      {"quantity": "P.x", "value": 5, "tolPct": 0.5, "quote": "(5, 3)"},
      {"quantity": "P.y", "value": 3, "tolPct": 0.5, "quote": "(5, 3)"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CG2-006",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "A": "(1, 2)", "B": "(7, 8)", "U": "(5, 6)", "ratio": "2:1"},
    draw: {"section": {"point": "U", "a": "A", "b": "B"}},
    labels: {"U": ""},
    provenance: [
      {"param": "A", "field": "questionText", "quote": "A(1, 2)"},
      {"param": "B", "field": "questionText", "quote": "B(7, 8)"},
      {"param": "ratio", "field": "questionText", "quote": "in the ratio 2:1"},
      {"param": "U", "field": "finalAnswer", "quote": "(5, 6)"},
    ],
    expect: [
      {"quantity": "U.x", "value": 5, "tolPct": 0.5, "quote": "(5, 6)"},
      {"quantity": "U.y", "value": 6, "tolPct": 0.5, "quote": "(5, 6)"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CG2-007",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "A": "(0, 0)", "B": "(10, 5)", "P": "(6, 3)", "ratio": "3:2"},
    draw: {"section": {"point": "P", "a": "A", "b": "B"}},
    provenance: [
      {"param": "A", "field": "questionText", "quote": "A = (0, 0)"},
      {"param": "B", "field": "questionText", "quote": "B = (10, 5)"},
      {"param": "ratio", "field": "questionText", "quote": "in the ratio 3:2"},
      {"param": "P", "field": "finalAnswer", "quote": "(6, 3)"},
    ],
    expect: [
      {"quantity": "P.x", "value": 6, "tolPct": 0.5, "quote": "(6, 3)"},
      {"quantity": "P.y", "value": 3, "tolPct": 0.5, "quote": "(6, 3)"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CG2-030",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "A": "(2, 3)", "B": "(8, 9)", "U": "(4, 5)", "ratio": "1:2"},
    draw: {"section": {"point": "U", "a": "A", "b": "B"}},
    labels: {"U": ""},
    provenance: [
      {"param": "A", "field": "questionText", "quote": "A(2, 3)"},
      {"param": "B", "field": "questionText", "quote": "B(8, 9)"},
      {"param": "ratio", "field": "questionText", "quote": "in ratio 1:2"},
      {"param": "U", "field": "finalAnswer", "quote": "(4, 5)"},
    ],
    expect: [
      {"quantity": "U.x", "value": 4, "tolPct": 0.5, "quote": "(4, 5)"},
      {"quantity": "U.y", "value": 5, "tolPct": 0.5, "quote": "(4, 5)"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CG2-050",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "U": "(1, 3)", "V": "(4, 6)", "W": "(2, 4)", "ratio": "1:2"},
    draw: {"section": {"point": "W", "a": "U", "b": "V"}},
    labels: {"U": "", "V": "", "W": ""},
    provenance: [
      {"param": "U", "field": "questionText", "quote": "(1, 3)"},
      {"param": "V", "field": "questionText", "quote": "(4, 6)"},
      {"param": "ratio", "field": "questionText", "quote": "in ratio 1:2"},
      {"param": "W", "field": "finalAnswer", "quote": "(2, 4)"},
    ],
    expect: [
      {"quantity": "W.x", "value": 2, "tolPct": 0.5, "quote": "(2, 4)"},
      {"quantity": "W.y", "value": 4, "tolPct": 0.5, "quote": "(2, 4)"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CG2-056",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "A": "(−1, 7)", "B": "(4, −3)", "P": "(1, 3)", "ratio": "2:3"},
    draw: {"section": {"point": "P", "a": "A", "b": "B"}},
    provenance: [
      {"param": "A", "field": "questionText", "quote": "A(−1, 7)"},
      {"param": "B", "field": "questionText", "quote": "B(4, −3)"},
      {"param": "ratio", "field": "questionText", "quote": "in the ratio 2:3"},
      {"param": "P", "field": "finalAnswer", "quote": "P = (1, 3)"},
    ],
    expect: [
      {"quantity": "P.x", "value": 1, "tolPct": 0.5, "quote": "P = (1, 3)"},
      {"quantity": "AP", "value": 4.472136, "tolPct": 0.5, "quote": "AP = 2√5 units"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CG-N-NCERT-7-EX-006",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "U": "(4, −3)", "V": "(8, 5)", "W": "(7, 3)", "ratio": "3 : 1"},
    draw: {"section": {"point": "W", "a": "U", "b": "V"}},
    labels: {"U": "", "V": "", "W": ""},
    provenance: [
      {"param": "U", "field": "questionText", "quote": "(4, −3)"},
      {"param": "V", "field": "questionText", "quote": "(8, 5)"},
      {"param": "ratio", "field": "questionText", "quote": "in the ratio 3 : 1"},
      {"param": "W", "field": "finalAnswer", "quote": "(7, 3)"},
    ],
    expect: [
      {"quantity": "W.x", "value": 7, "tolPct": 0.5, "quote": "(7, 3)"},
      {"quantity": "W.y", "value": 3, "tolPct": 0.5, "quote": "(7, 3)"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CG-N-NCERT-7-EX-020",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "U": "(−1, 7)", "V": "(4, −3)", "W": "(1, 3)", "ratio": "2 : 3"},
    draw: {"section": {"point": "W", "a": "U", "b": "V"}},
    labels: {"U": "", "V": "", "W": ""},
    provenance: [
      {"param": "U", "field": "questionText", "quote": "(−1, 7)"},
      {"param": "V", "field": "questionText", "quote": "(4, −3)"},
      {"param": "ratio", "field": "questionText", "quote": "in the ratio 2 : 3"},
      {"param": "W", "field": "finalAnswer", "quote": "(1, 3)"},
    ],
    expect: [
      {"quantity": "W.x", "value": 1, "tolPct": 0.5, "quote": "(1, 3)"},
      {"quantity": "W.y", "value": 3, "tolPct": 0.5, "quote": "(1, 3)"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "BX-COORD-E-023",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "A": "(1, 2)", "B": "(11, 7)", "P": "(7, 5)", "ratio": "3 : 2"},
    draw: {"section": {"point": "P", "a": "A", "b": "B"}},
    provenance: [
      {"param": "A", "field": "questionText", "quote": "A(1, 2)"},
      {"param": "B", "field": "questionText", "quote": "B(11, 7)"},
      {"param": "ratio", "field": "questionText", "quote": "in the ratio 3 : 2"},
      {"param": "P", "field": "finalAnswer", "quote": "P = (7, 5)"},
    ],
    expect: [
      {"quantity": "P.x", "value": 7, "tolPct": 0.5, "quote": "P = (7, 5)"},
      {"quantity": "P.y", "value": 5, "tolPct": 0.5, "quote": "P = (7, 5)"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "BX-COORD-E-032",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "A": "(2, 3)", "B": "(10, 11)", "C": "(8, 9)", "ratio": "3 : 1"},
    draw: {"section": {"point": "C", "a": "A", "b": "B"}},
    provenance: [
      {"param": "A", "field": "questionText", "quote": "A(2, 3)"},
      {"param": "B", "field": "questionText", "quote": "B(10, 11)"},
      {"param": "ratio", "field": "questionText", "quote": "in the ratio 3 : 1"},
      {"param": "C", "field": "finalAnswer", "quote": "C = (8, 9)"},
    ],
    expect: [
      {"quantity": "C.x", "value": 8, "tolPct": 0.5, "quote": "C = (8, 9)"},
      {"quantity": "AC", "value": 8.485281, "tolPct": 0.5, "quote": "AC = 6√2"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "BX-COORD-E-047",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "A": "(−6, 4)", "B": "(9, −11)", "V": "(0, −2)", "ratio": "2 : 3"},
    draw: {"section": {"point": "V", "a": "A", "b": "B"}},
    provenance: [
      {"param": "A", "field": "questionText", "quote": "A(−6, 4)"},
      {"param": "B", "field": "questionText", "quote": "B(9, −11)"},
      {"param": "ratio", "field": "questionText", "quote": "in the ratio 2 : 3"},
      {"param": "V", "field": "finalAnswer", "quote": "V = (0, −2)"},
    ],
    expect: [
      {"quantity": "V.y", "value": -2, "tolPct": 0.5, "quote": "V = (0, −2)"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CG-207",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "A": "(-2, 5)", "B": "(8, -10)", "U": "(2, -1)", "ratio": "2 : 3"},
    draw: {"section": {"point": "U", "a": "A", "b": "B"}},
    labels: {"U": ""},
    provenance: [
      {"param": "A", "field": "questionText", "quote": "A(-2, 5)"},
      {"param": "B", "field": "questionText", "quote": "B(8, -10)"},
      {"param": "ratio", "field": "questionText", "quote": "in the ratio 2 : 3"},
      {"param": "U", "field": "finalAnswer", "quote": "(2, -1)"},
    ],
    expect: [
      {"quantity": "U.x", "value": 2, "tolPct": 0.5, "quote": "(2, -1)"},
      {"quantity": "U.y", "value": -1, "tolPct": 0.5, "quote": "(2, -1)"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CG-236",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "A": "(1, 2)", "B": "(13, 8)", "V": "(5, 4)", "ratio": "1 : 2"},
    draw: {"section": {"point": "V", "a": "A", "b": "B"}},
    provenance: [
      {"param": "A", "field": "questionText", "quote": "A(1, 2)"},
      {"param": "B", "field": "questionText", "quote": "B(13, 8)"},
      {"param": "ratio", "field": "questionText", "quote": "in the ratio 1 : 2"},
      {"param": "V", "field": "finalAnswer", "quote": "(5, 4)"},
    ],
    expect: [
      {"quantity": "V.x", "value": 5, "tolPct": 0.5, "quote": "(5, 4)"},
      {"quantity": "V.y", "value": 4, "tolPct": 0.5, "quote": "(5, 4)"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CG-250",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "A": "(2, 1)", "B": "(14, 9)", "U": "(11, 7)", "ratio": "3 : 1"},
    draw: {"section": {"point": "U", "a": "A", "b": "B"}},
    labels: {"U": ""},
    provenance: [
      {"param": "A", "field": "questionText", "quote": "A(2, 1)"},
      {"param": "B", "field": "questionText", "quote": "B(14, 9)"},
      {"param": "ratio", "field": "questionText", "quote": "in the ratio 3 : 1"},
      {"param": "U", "field": "finalAnswer", "quote": "(11, 7)"},
    ],
    expect: [
      {"quantity": "U.y", "value": 1.75, "tolPct": 0.5, "quote": "1.75 m", "factor": 0.25},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CG-247",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "A": "(−3, 5)", "P": "(1, 3)", "B": "(7, 0)", "ratio": "2 : 3"},
    draw: {"section": {"point": "P", "a": "A", "b": "B"}},
    provenance: [
      {"param": "A", "field": "questionText", "quote": "A(−3, 5)"},
      {"param": "P", "field": "questionText", "quote": "P(1, 3)"},
      {"param": "ratio", "field": "questionText", "quote": "in the ratio 2 : 3"},
      {"param": "B", "field": "finalAnswer", "quote": "B(7, 0)"},
    ],
    expect: [
      {"quantity": "B.x", "value": 7, "tolPct": 0.5, "quote": "B(7, 0)"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CG-277",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "B": "(−4, −7)", "S": "(11, 13)", "M": "(2, 1)", "ratio": "2 : 3"},
    draw: {"section": {"point": "M", "a": "B", "b": "S"}},
    provenance: [
      {"param": "B", "field": "questionText", "quote": "B(−4, −7)"},
      {"param": "S", "field": "questionText", "quote": "S(11, 13)"},
      {"param": "ratio", "field": "questionText", "quote": "in the ratio 2 : 3"},
      {"param": "M", "field": "finalAnswer", "quote": "M(2, 1)"},
    ],
    expect: [
      {"quantity": "BM", "value": 200, "tolPct": 0.5, "quote": "BM = 200 m", "factor": 20},
      {"quantity": "MS", "value": 300, "tolPct": 0.5, "quote": "MS = 300 m", "factor": 20},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CG-298",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "P": "(−2, −1)", "C": "(2, 2)", "Q": "(10, 8)", "ratio": "1 : 2"},
    draw: {"section": {"point": "C", "a": "P", "b": "Q"}},
    provenance: [
      {"param": "P", "field": "questionText", "quote": "P(−2, −1)"},
      {"param": "C", "field": "questionText", "quote": "C(2, 2)"},
      {"param": "ratio", "field": "questionText", "quote": "in the ratio 1 : 2"},
      {"param": "Q", "field": "finalAnswer", "quote": "Q(10, 8)"},
    ],
    expect: [
      {"quantity": "PC", "value": 5, "tolPct": 0.5, "quote": "PC = 5 m"},
      {"quantity": "PQ", "value": 15, "tolPct": 0.5, "quote": "PQ = 15 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CG-288",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "T1": "(2, −3)", "T2": "(10, 3)", "H": "(3.6, −1.8)", "ratio": "1 : 4"},
    draw: {"section": {"point": "H", "a": "T1", "b": "T2"}},
    provenance: [
      {"param": "T1", "field": "questionText", "quote": "T1(2, −3)"},
      {"param": "T2", "field": "questionText", "quote": "T2(10, 3)"},
      {"param": "ratio", "field": "questionText", "quote": "in the ratio 1 : 4"},
      {"param": "H", "field": "finalAnswer", "quote": "H(3.6, −1.8)"},
    ],
    expect: [
      {"quantity": "T1T2", "value": 10, "tolPct": 0.5, "quote": "(i) 10 km"},
      {"quantity": "HT2", "value": 8, "tolPct": 0.5, "quote": "(iii) 8 km"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CG-E02",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "U": "(4, 6)", "V": "(2, 8)", "W": "(3, 7)"},
    draw: {"midpoint": {"point": "W", "a": "U", "b": "V"}},
    labels: {"U": "", "V": "", "W": ""},
    provenance: [
      {"param": "U", "field": "questionText", "quote": "(4, 6)"},
      {"param": "V", "field": "questionText", "quote": "(2, 8)"},
      {"param": "W", "field": "finalAnswer", "quote": "(3, 7)"},
    ],
    expect: [
      {"quantity": "W.x", "value": 3, "tolPct": 0.5, "quote": "(3, 7)"},
      {"quantity": "W.y", "value": 7, "tolPct": 0.5, "quote": "(3, 7)"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CG-N02",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "U": "(2, 6)", "V": "(8, 4)", "W": "(5, 5)"},
    draw: {"midpoint": {"point": "W", "a": "U", "b": "V"}},
    labels: {"U": "", "V": "", "W": ""},
    provenance: [
      {"param": "U", "field": "questionText", "quote": "(2, 6)"},
      {"param": "V", "field": "questionText", "quote": "(8, 4)"},
      {"param": "W", "field": "finalAnswer", "quote": "(5, 5)"},
    ],
    expect: [
      {"quantity": "W.x", "value": 5, "tolPct": 0.5, "quote": "(5, 5)"},
      {"quantity": "W.y", "value": 5, "tolPct": 0.5, "quote": "(5, 5)"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CG2-004",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "A": "(2, 3)", "B": "(4, 7)", "U": "(3, 5)"},
    draw: {"midpoint": {"point": "U", "a": "A", "b": "B"}},
    labels: {"U": ""},
    provenance: [
      {"param": "A", "field": "questionText", "quote": "A(2, 3)"},
      {"param": "B", "field": "questionText", "quote": "B(4, 7)"},
      {"param": "U", "field": "finalAnswer", "quote": "(3, 5)"},
    ],
    expect: [
      {"quantity": "U.x", "value": 3, "tolPct": 0.5, "quote": "(3, 5)"},
      {"quantity": "U.y", "value": 5, "tolPct": 0.5, "quote": "(3, 5)"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CG2-005",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "M": "(5, 6)", "A": "(3, 4)", "B": "(7, 8)"},
    draw: {"midpoint": {"point": "M", "a": "A", "b": "B"}},
    labels: {"M": "", "A": "A", "B": "B"},
    provenance: [
      {"param": "M", "field": "questionText", "quote": "the midpoint of AB is (5, 6)"},
      {"param": "A", "field": "questionText", "quote": "A is (3, 4)"},
      {"param": "B", "field": "finalAnswer", "quote": "(7, 8)"},
    ],
    expect: [
      {"quantity": "B.x", "value": 7, "tolPct": 0.5, "quote": "(7, 8)"},
      {"quantity": "B.y", "value": 8, "tolPct": 0.5, "quote": "(7, 8)"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CG2-027",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "A": "(4, 6)", "B": "(8, 10)", "U": "(6, 8)"},
    draw: {"midpoint": {"point": "U", "a": "A", "b": "B"}},
    labels: {"U": ""},
    provenance: [
      {"param": "A", "field": "questionText", "quote": "A(4, 6)"},
      {"param": "B", "field": "questionText", "quote": "B(8, 10)"},
      {"param": "U", "field": "finalAnswer", "quote": "(6, 8)"},
    ],
    expect: [
      {"quantity": "U.x", "value": 6, "tolPct": 0.5, "quote": "(6, 8)"},
      {"quantity": "U.y", "value": 8, "tolPct": 0.5, "quote": "(6, 8)"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CG2-028",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "M": "(3, 5)", "A": "(1, 3)", "B": "(5, 7)"},
    draw: {"midpoint": {"point": "M", "a": "A", "b": "B"}},
    provenance: [
      {"param": "M", "field": "questionText", "quote": "M(3, 5)"},
      {"param": "A", "field": "questionText", "quote": "A(1, 3)"},
      {"param": "B", "field": "finalAnswer", "quote": "B(5, 7)"},
    ],
    expect: [
      {"quantity": "B.x", "value": 5, "tolPct": 0.5, "quote": "B(5, 7)"},
      {"quantity": "B.y", "value": 7, "tolPct": 0.5, "quote": "B(5, 7)"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "CG2-053",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "U": "(−3, 4)", "V": "(5, −2)", "W": "(1, 1)"},
    draw: {"midpoint": {"point": "W", "a": "U", "b": "V"}},
    labels: {"U": "", "V": "", "W": ""},
    provenance: [
      {"param": "U", "field": "questionText", "quote": "(−3, 4)"},
      {"param": "V", "field": "questionText", "quote": "(5, −2)"},
      {"param": "W", "field": "finalAnswer", "quote": "(1, 1)"},
    ],
    expect: [
      {"quantity": "W.x", "value": 1, "tolPct": 0.5, "quote": "(1, 1)"},
      {"quantity": "W.y", "value": 1, "tolPct": 0.5, "quote": "(1, 1)"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "BX-COORD-E-031",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "S": "(−8, 15)", "O": "(0, 0)", "U": "(−4, 7.5)"},
    draw: {"midpoint": {"point": "U", "a": "O", "b": "S"}},
    labels: {"S": "S", "O": "O", "U": ""},
    provenance: [
      {"param": "S", "field": "questionText", "quote": "S(−8, 15)"},
      {"param": "O", "field": "questionText", "quote": "O(0, 0)"},
      {"param": "U", "field": "finalAnswer", "quote": "(−4, 7.5)"},
    ],
    expect: [
      {"quantity": "OS", "value": 17, "tolPct": 0.5, "quote": "OS = 17"},
      {"quantity": "OU", "value": 8.5, "tolPct": 0.5, "quote": "each half = 8.5"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "BX-COORD-E-039",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "A": "(0, 0)", "B": "(20, 21)", "U": "(10, 10.5)"},
    draw: {"midpoint": {"point": "U", "a": "A", "b": "B"}},
    labels: {"A": "A", "B": "B", "U": ""},
    provenance: [
      {"param": "A", "field": "questionText", "quote": "A(0, 0)"},
      {"param": "B", "field": "questionText", "quote": "B(20, 21)"},
      {"param": "U", "field": "finalAnswer", "quote": "(10, 10.5)"},
    ],
    expect: [
      {"quantity": "AB", "value": 29, "tolPct": 0.5, "quote": "AB = 29"},
      {"quantity": "AU", "value": 14.5, "tolPct": 0.5, "quote": "half-length 14.5"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CG-241",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "M": "(4, −1)", "A": "(−2, 3)", "B": "(10, −5)"},
    draw: {"midpoint": {"point": "M", "a": "A", "b": "B"}},
    provenance: [
      {"param": "M", "field": "questionText", "quote": "M(4, −1)"},
      {"param": "A", "field": "questionText", "quote": "A(−2, 3)"},
      {"param": "B", "field": "finalAnswer", "quote": "B(10, −5)"},
    ],
    expect: [
      {"quantity": "B.x", "value": 10, "tolPct": 0.5, "quote": "B(10, −5)"},
      {"quantity": "B.y", "value": -5, "tolPct": 0.5, "quote": "B(10, −5)"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CG-270",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "H": "(−2, −3)", "S": "(4, 5)", "M": "(1, 1)", "F": "(5, −2)"},
    draw: {"midpoint": {"point": "M", "a": "H", "b": "S"}, "segs": [["M", "F"]]},
    provenance: [
      {"param": "H", "field": "questionText", "quote": "H(−2, −3)"},
      {"param": "S", "field": "questionText", "quote": "S(4, 5)"},
      {"param": "F", "field": "questionText", "quote": "F(5, −2)"},
      {"param": "M", "field": "finalAnswer", "quote": "M(1, 1)"},
    ],
    expect: [
      {"quantity": "HS", "value": 5, "tolPct": 0.5, "quote": "HS = 5 km", "factor": 0.5},
      {"quantity": "MF", "value": 2.5, "tolPct": 0.5, "quote": "MF = 2.5 km", "factor": 0.5},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
  {
    kind: "computed",
    questionId: "LTG-M-CG-299",
    slot: "solution",
    builder: "coordinatePlot",
    params: {"template": "points", "unit": "none", "A": "(1, 4)", "B": "(−5, −1)", "C": "(7, −6)", "D": "(1, −3.5)"},
    draw: {"polygon": ["A", "B", "C"], "midpoint": {"point": "D", "a": "B", "b": "C"}, "segs": [["A", "D"]]},
    provenance: [
      {"param": "A", "field": "questionText", "quote": "A(1, 4)"},
      {"param": "B", "field": "questionText", "quote": "B(−5, −1)"},
      {"param": "C", "field": "questionText", "quote": "C(7, −6)"},
      {"param": "D", "field": "finalAnswer", "quote": "D(1, −3.5)"},
    ],
    expect: [
      {"quantity": "AD", "value": 7.5, "tolPct": 0.5, "quote": "(ii) 7.5 m"},
      {"quantity": "BC", "value": 13, "tolPct": 0.5, "quote": "(iii) 13 m"},
    ],
    confirmedBy: "opus-5.5 builder (PR-2d): row read in full + rendered figure eye-checked 2026-10-07",
  },
];
