/**
 * Trigonometry — heights & distances SOLUTION figures (DIAGRAMS-1 PR-2a).
 *
 * One entry per served row whose CBSE answer would draw a heights-and-distances
 * sketch AND whose scene is fixed, unambiguously, by the row's own numbers. Every
 * row was read (question, steps, answer) and its rendered figure eye-checked.
 * Rows that were read and REFUSED (no numbers, lost degree signs, multi-scene case
 * studies, a question figure already bound, θ = 90°, ...) are listed in the PR,
 * not here — an unbound row shows no figure, never a lookalike.
 *
 * `provenance` quotes are exact substrings of the served row; `expect` is the row's
 * own answer. computedFigures.provenance.test.ts enforces both.
 */
import type { ComputedFigureBinding } from "./computedFigureTypes";

export const TRIGONOMETRY_SOLUTION_FIGURES: ComputedFigureBinding[] = [
  {
    questionId: "2026-TRIG-P1-A-038",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "single", view: "elevation", unit: "m", theta: 60, d: "10"},
    labels: { "q.h": "h"},
    provenance: [
      {param: "theta", field: "questionText", quote: "the angle of elevation of a tower is 60 deg"},
      {param: "d", field: "questionText", quote: "the horizontal distance is 10 m"},
    ],
    expect: [
      {quantity: "h", value: 17.3205, tolPct: 0.5, quote: "h = 10sqrt(3) m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "2026-TRIG-P1-B-021",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "single", view: "elevation", unit: "m", theta: 45, d: "15"},
    labels: { "q.h": "h"},
    provenance: [
      {param: "d", field: "questionText", quote: "15 m away from the foot of a tower"},
      {param: "theta", field: "questionText", quote: "the angle of elevation of its top is 45 deg"},
    ],
    expect: [
      {quantity: "h", value: 15, tolPct: 0.5, quote: "Final answer: 15 m."},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "2026-TRIG-P1-B-023",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "single", view: "depression", unit: "m", theta: 45, h: "18"},
    labels: { "q.d": "d"},
    provenance: [
      {param: "h", field: "questionText", quote: "From the top of an 18 m lighthouse"},
      {param: "theta", field: "questionText", quote: "the angle of depression of a boat is 45 deg"},
    ],
    expect: [
      {quantity: "d", value: 18, tolPct: 0.5, quote: "Final answer: 18 m."},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "2026-TRIG-P1-C-015",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "single", view: "shadow", unit: "m", theta: 30, d: "10√3"},
    labels: { "q.h": "h"},
    provenance: [
      {param: "d", field: "questionText", quote: "casts a shadow 10sqrt(3) m long"},
      {param: "theta", field: "questionText", quote: "the angle of elevation of the sun is 30 deg"},
    ],
    expect: [
      {quantity: "h", value: 10, tolPct: 0.5, quote: "Hence h = 10 m."},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "2026-TRIG-P1-C-016",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "single", view: "elevation", unit: "m", theta: 60, d: "12"},
    labels: { "q.h": "h"},
    provenance: [
      {param: "d", field: "questionText", quote: "12 m away from the foot of a tower"},
      {param: "theta", field: "questionText", quote: "the angle of elevation of the top is 60 deg"},
    ],
    expect: [
      {quantity: "h", value: 20.7846, tolPct: 0.5, quote: "Therefore h = 12sqrt(3) m."},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "2026-TRIG-P1-C-017",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "single", view: "depression", unit: "m", theta: 30, h: "24"},
    labels: { "q.d": "d"},
    provenance: [
      {param: "h", field: "questionText", quote: "From the top of a 24 m building"},
      {param: "theta", field: "questionText", quote: "the angle of depression of a car is 30 deg"},
    ],
    expect: [
      {quantity: "d", value: 41.5692, tolPct: 0.5, quote: "So distance = 24sqrt(3) m."},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "2026-TRIG-P1-C-019",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "single", view: "shadow", unit: "m", h: "8", d: "8/√3"},
    labels: { "q.theta": "θ"},
    provenance: [
      {param: "h", field: "questionText", quote: "A vertical pole 8 m high"},
      {param: "d", field: "questionText", quote: "casts a shadow 8/sqrt(3) m long"},
    ],
    expect: [
      {quantity: "theta", value: 60, tolPct: 0.5, quote: "Hence theta = 60 deg."},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "2026-TRIG-P1-C-020",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "single", view: "elevation", unit: "m", theta: 45, h: "14"},
    labels: { "q.d": "x"},
    provenance: [
      {param: "theta", field: "questionText", quote: "the angle of elevation of the top of a tower is 45 deg"},
      {param: "h", field: "questionText", quote: "the height of the tower is 14 m"},
    ],
    expect: [
      {quantity: "d", value: 14, tolPct: 0.5, quote: "Hence the required distance is 14 m."},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "2026-TRIG-P1-C-025",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "single", view: "elevation", unit: "m", theta: 45, h: "14"},
    labels: { "q.d": "x"},
    provenance: [
      {param: "theta", field: "questionText", quote: "at an angle of elevation of 45 deg"},
      {param: "h", field: "questionText", quote: "the tree is 14 m high"},
    ],
    expect: [
      {quantity: "d", value: 14, tolPct: 0.5, quote: "Hence the boy is 14 m away from the tree."},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "2026-TRIG-P1-D-009",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "single", view: "depression", unit: "m", theta: 30, h: "20"},
    labels: { "q.d": "x"},
    provenance: [
      {param: "h", field: "questionText", quote: "From the top of a 20 m high building"},
      {param: "theta", field: "questionText", quote: "the angle of depression of a car on the road is 30 deg"},
    ],
    expect: [
      {quantity: "d", value: 34.641, tolPct: 0.5, quote: "This gives x = 20sqrt(3) m."},
      {quantity: "L", value: 40, tolPct: 0.5, quote: "the line of sight is 40 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "2026-TRIG-P1-D-010",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "single", view: "elevation", unit: "m", theta: 60, d: "15"},
    labels: { "q.h": "h"},
    provenance: [
      {param: "d", field: "questionText", quote: "15 m from the foot of a tower"},
      {param: "theta", field: "questionText", quote: "the angle of elevation of the top is 60 deg"},
    ],
    expect: [
      {quantity: "h", value: 25.9808, tolPct: 0.5, quote: "we get h = 15sqrt(3) m"},
      {quantity: "L", value: 30, tolPct: 0.5, quote: "So the required slant line is 30 m."},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "2026-TRIG-P1-D-013",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsSameSide", view: "elevation", unit: "m", far: 30, near: 60, gap: "50"},
    labels: { "q.dNear": "x", "q.h": "h"},
    provenance: [
      {param: "far", field: "questionText", quote: "the angle of elevation of the top of a tower is 30 deg"},
      {param: "gap", field: "questionText", quote: "After moving 50 m towards the tower"},
      {param: "near", field: "questionText", quote: "the angle becomes 60 deg"},
    ],
    expect: [
      {quantity: "h", value: 43.3013, tolPct: 0.5, quote: "Hence h = 25sqrt(3) m"},
      {quantity: "dFar", value: 75, tolPct: 0.5, quote: "the original distance is x + 50 = 75 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "2026-TRIG-P1-D-014",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsSameSide", view: "elevation", unit: "m", far: 30, near: 60, gap: "20"},
    labels: {far: "A", near: "B", "q.dNear": "x", "q.h": "h"},
    provenance: [
      {param: "far", field: "questionText", quote: "From point A on the ground, the angle of elevation of the balloon is 30 deg"},
      {param: "gap", field: "questionText", quote: "From point B, 20 m nearer"},
      {param: "near", field: "questionText", quote: "the angle of elevation is 60 deg"},
    ],
    expect: [
      {quantity: "h", value: 17.3205, tolPct: 0.5, quote: "Thus x = 10 and h = 10sqrt(3) m."},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "2026-TRIG-P1-D-015",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "elevDepFromHeight", unit: "m", H1: "12", top: 45, topView: "elevation", foot: 30},
    labels: { "q.d": "x", "q.H2": "H"},
    provenance: [
      {param: "H1", field: "questionText", quote: "on the top of a 12 m building"},
      {param: "top", field: "questionText", quote: "the top of a tower at an angle of elevation of 45 deg"},
      {param: "foot", field: "questionText", quote: "the foot of the tower at an angle of depression of 30 deg"},
    ],
    expect: [
      {quantity: "H2", value: 32.7846, tolPct: 0.5, quote: "so H = 12(1 + sqrt(3)) m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "2026-TRIG-P1-E-002",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsSameSide", view: "shadow", unit: "m", far: 30, near: 45, dFar: "6√3"},
    labels: { "q.h": "h"},
    provenance: [
      {param: "dFar", field: "questionText", quote: "A tree casts a shadow of 6sqrt(3) m"},
      {param: "far", field: "questionText", quote: "If the angle of elevation of the sun is 30 deg"},
      {param: "near", field: "questionText", quote: "if the angle of elevation becomes 45 deg"},
    ],
    expect: [
      {quantity: "h", value: 6, tolPct: 0.5, quote: "gives h = 6 m"},
      {quantity: "dNear", value: 6, tolPct: 0.5, quote: "so shadow = 6 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "2026-TRIG-P1-E-004",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsSameSide", view: "depression", unit: "m", far: 30, near: 45, h: "15"},
    provenance: [
      {param: "h", field: "questionText", quote: "From the top of a 15 m watchtower"},
      {param: "near", field: "questionText", quote: "If the angle of depression is 45 deg"},
      {param: "far", field: "questionText", quote: "the angle becomes 30 deg"},
    ],
    expect: [
      {quantity: "dNear", value: 15, tolPct: 0.5, quote: "distance = 15 m"},
      {quantity: "dFar", value: 25.9808, tolPct: 0.5, quote: "gives new distance = 15sqrt(3) m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "2026-TRIG-P1-E-007",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "elevDepFromHeight", unit: "m", H1: "18", top: 45, topView: "elevation", foot: 30},
    provenance: [
      {param: "H1", field: "questionText", quote: "A student on a terrace 18 m high"},
      {param: "foot", field: "questionText", quote: "the angle of depression to the foot of the lamp post is 30 deg"},
      {param: "top", field: "questionText", quote: "the angle of elevation to the top is 45 deg"},
    ],
    expect: [
      {quantity: "d", value: 31.1769, tolPct: 0.5, quote: "gives distance = 18sqrt(3) m"},
      {quantity: "H2", value: 49.1769, tolPct: 0.5, quote: "lamp post height = 18 + 18sqrt(3) m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "TRIG2-M02",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "slant", object: "string", unit: "m", theta: 60, h: "30"},
    labels: { "q.L": "L"},
    provenance: [
      {param: "h", field: "questionText", quote: "flying at a height of 30 m from the ground"},
      {param: "theta", field: "questionText", quote: "The inclination of the string with the ground is 60°"},
    ],
    expect: [
      {quantity: "L", value: 34.6, tolPct: 0.5, quote: "= 20 × 1.73 = 34.6 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "TRIG2-M05",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "single", view: "elevation", unit: "m", theta: 30, d: "30"},
    labels: { "q.h": "h"},
    provenance: [
      {param: "d", field: "questionText", quote: "which is 30 m from the foot of the tower"},
      {param: "theta", field: "questionText", quote: "is 30°"},
    ],
    expect: [
      {quantity: "h", value: 17.3205, tolPct: 0.5, quote: "h = 30/√3 = 10√3 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "TRIG2-H01",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "elevDepFromHeight", unit: "m", H1: "7", top: 60, topView: "elevation", foot: 45},
    labels: {obs: "", obsFoot: "", foot: "", top: "", meet: ""},
    provenance: [
      {param: "H1", field: "questionText", quote: "From the top of a 7 m high building"},
      {param: "top", field: "questionText", quote: "the angle of elevation of the top of a cable tower is 60°"},
      {param: "foot", field: "questionText", quote: "the angle of depression of its foot is 45°"},
    ],
    expect: [
      {quantity: "d", value: 7, tolPct: 0.5, quote: "BC = 7 m"},
      {quantity: "H2", value: 19.12, tolPct: 0.5, quote: "7(√3 + 1) ≈ 19.12 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "TRIG2-H03",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsSameSide", view: "depression", unit: "m", far: 30, near: 60, scaleFree: true},
    labels: { "q.h": "h", "q.dNear": "d"},
    caption: "Speed and time fix the scene only up to scale: angles are exact, lengths are not drawn to a number.",
    provenance: [
      {param: "far", field: "questionText", quote: "at an angle of depression 30°"},
      {param: "near", field: "questionText", quote: "the angle of depression becomes 60°"},
    ],
    expect: [
      {quantity: "nearOverGap", value: 0.6, tolPct: 0.5, factor: 1.2, quote: "d = 0.6 km"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "TRIG2-H07",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsOppositeSides", view: "depression", unit: "m", left: 45, right: 30, h: "60"},
    labels: {top: "A", foot: "B", left: "C", right: "D"},
    provenance: [
      {param: "h", field: "questionText", quote: "From the top of a 60 m high lighthouse"},
      {param: "left", field: "questionText", quote: "on opposite sides are 30° and 45°"},
      {param: "right", field: "questionText", quote: "on opposite sides are 30° and 45°"},
    ],
    expect: [
      {quantity: "dLeft", value: 60, tolPct: 0.5, quote: "BC = 60 m"},
      {quantity: "total", value: 163.9, tolPct: 0.5, quote: "60(1 + √3) ≈ 163.9 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "TRIG2-H11",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "slant", object: "broken-tree", unit: "m", theta: 30, d: "8"},
    labels: { "q.h": "h", "q.L": "L"},
    provenance: [
      {param: "theta", field: "questionText", quote: "making an angle 30° with it"},
      {param: "d", field: "questionText", quote: "touches the ground is 8 m"},
    ],
    expect: [
      {quantity: "total", value: 13.86, tolPct: 0.5, quote: "8√3 ≈ 13.86 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "TRIG2-H13",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsSameSide", view: "depression", unit: "m", far: 30, near: 45, h: "75"},
    labels: { "q.dNear": "d₁"},
    provenance: [
      {param: "h", field: "questionText", quote: "75 m high lighthouse"},
      {param: "far", field: "questionText", quote: "the angles of depression of two ships are 30° and 45°"},
      {param: "near", field: "questionText", quote: "the angles of depression of two ships are 30° and 45°"},
    ],
    expect: [
      {quantity: "gap", value: 54.9, tolPct: 0.5, quote: "75(√3 − 1) ≈ 54.9 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "TRIG2-CB01",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "objectOnObject", unit: "m", lower: 30, upper: 60, d: "60"},
    labels: { "q.h1": "h₁", "q.h2": "H"},
    provenance: [
      {param: "d", field: "questionText", quote: "From a point on the ground 60 m from the base"},
      {param: "lower", field: "questionText", quote: "the top of the pedestal and the top of the statue are 30° and 60° respectively"},
      {param: "upper", field: "questionText", quote: "the top of the pedestal and the top of the statue are 30° and 60° respectively"},
    ],
    expect: [
      {quantity: "h1", value: 34.641, tolPct: 0.5, quote: "h₁ = 60/√3 = 20√3 m"},
      {quantity: "h2", value: 103.923, tolPct: 0.5, quote: "H = 60√3 m"},
      {quantity: "len", value: 69.282, tolPct: 0.5, quote: "Statue height = 60√3 − 20√3 = 40√3 m"},
      {quantity: "L2", value: 120, tolPct: 0.5, quote: "= 60/(1/2) = 120 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "TRIG2-CB02",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsOppositeSides", view: "depression", unit: "m", left: 60, right: 45, h: "3000√3"},
    labels: {left: "A", right: "B", top: "", foot: "", "q.dLeft": "d₁", "q.dRight": "d₂"},
    provenance: [
      {param: "left", field: "questionText", quote: "A and B on opposite banks of a river are at angles of depression 60° and 45° respectively"},
      {param: "right", field: "questionText", quote: "A and B on opposite banks of a river are at angles of depression 60° and 45° respectively"},
      {param: "h", field: "questionText", quote: "flying at 3000√3 m"},
    ],
    expect: [
      {quantity: "dLeft", value: 3000, tolPct: 0.5, quote: "d₁ = 3000√3/√3 = 3000 m"},
      {quantity: "dRight", value: 5196.1524, tolPct: 0.5, quote: "d₂ = 3000√3 m"},
      {quantity: "total", value: 8196.1524, tolPct: 0.5, quote: "3000(1 + √3) m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "TRIG2-B06",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "single", view: "elevation", unit: "m", theta: 30, h: "30"},
    labels: { "q.d": "d"},
    provenance: [
      {param: "theta", field: "questionText", quote: "the angle of elevation of the top of a vertical tower is 30°"},
      {param: "h", field: "questionText", quote: "the tower is 30 m tall"},
    ],
    expect: [
      {quantity: "d", value: 51.9615, tolPct: 0.5, quote: "d = 30√3 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "TG3-021",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "slant", object: "ladder", unit: "m", theta: 60, d: "5"},
    labels: { "q.L": "L", "q.h": "h"},
    provenance: [
      {param: "theta", field: "questionText", quote: "The ladder makes an angle of 60° with the ground"},
      {param: "d", field: "questionText", quote: "the distance from the base of the ladder to the wall is 5 meters"},
    ],
    expect: [
      {quantity: "L", value: 10, tolPct: 0.5, quote: "L = 10 m"},
      {quantity: "h", value: 8.6603, tolPct: 0.5, quote: "h = 5√3 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "TG3-022",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsSameSide", view: "elevation", unit: "m", far: 30, near: 45, gap: "20"},
    labels: {far: "A", near: "B", "q.h": "h"},
    provenance: [
      {param: "far", field: "questionText", quote: "From point A (ground level), the angle is 30°"},
      {param: "gap", field: "questionText", quote: "which is 20 meters closer to the building"},
      {param: "near", field: "questionText", quote: "the angle is 45°"},
    ],
    expect: [
      {quantity: "h", value: 27.3205, tolPct: 0.5, quote: "h = 10(√3 + 1) meters"},
      {quantity: "dFar", value: 47.3205, tolPct: 0.5, quote: "d = 10(3 + √3) meters"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "TG3-042",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "slant", object: "ladder", unit: "m", theta: 60, L: "10"},
    labels: { "q.h": "h"},
    provenance: [
      {param: "theta", field: "questionText", quote: "A ladder makes an angle of 60° with the ground"},
      {param: "L", field: "questionText", quote: "the ladder is 10 m long"},
    ],
    expect: [
      {quantity: "h", value: 8.6603, tolPct: 0.5, quote: "height = 10 × √3/2 = 5√3 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "TG3-052",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsSameSide", view: "elevation", unit: "m", far: 30, near: 45, dFar: "50"},
    provenance: [
      {param: "dFar", field: "questionText", quote: "From a point 50 m away from the base of the building"},
      {param: "far", field: "questionText", quote: "the angle of elevation to the top is 30°"},
      {param: "near", field: "questionText", quote: "If the angle of elevation increases to 45°"},
    ],
    expect: [
      {quantity: "h", value: 28.8675, tolPct: 0.5, quote: "height = 50/√3 m"},
      {quantity: "dNear", value: 28.8675, tolPct: 0.5, quote: "distance = 50/√3 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "TG3-063",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "elevDepFromHeight", unit: "m", H1: "10", top: 60, topView: "elevation", foot: 45},
    labels: { "q.d": "x", "q.diff": "y"},
    provenance: [
      {param: "H1", field: "questionText", quote: "From the top of a 10 m high building"},
      {param: "top", field: "questionText", quote: "the angle of elevation of the top of a tower is 60°"},
      {param: "foot", field: "questionText", quote: "the angle of depression of the foot of the tower is 45°"},
    ],
    expect: [
      {quantity: "d", value: 10, tolPct: 0.5, quote: "so x = 10 m"},
      {quantity: "H2", value: 27.3205, tolPct: 0.5, quote: "10 + 10√3 = 10(1+√3) m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "TRIG-N-NCERT-9-SA-001",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "single", view: "elevation", unit: "m", theta: 60, d: "15"},
    labels: { "q.h": "h"},
    provenance: [
      {param: "d", field: "questionText", quote: "15 m from the foot of the tower"},
      {param: "theta", field: "questionText", quote: "the angle of elevation of the top of the tower is 60°"},
    ],
    expect: [
      {quantity: "h", value: 25.98, tolPct: 0.5, quote: "15√3 m ≈ 25.98 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "TRIG-N-NCERT-9-LA-001",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "objectOnObject", unit: "m", lower: 30, upper: 45, h1: "10"},
    labels: {foot: "A", mid: "B", top: "D", obs: "P", "q.len": "x"},
    provenance: [
      {param: "h1", field: "questionText", quote: "a 10 m tall building is 30°"},
      {param: "lower", field: "questionText", quote: "a 10 m tall building is 30°"},
      {param: "upper", field: "questionText", quote: "the top of the flagstaff from P is 45°"},
    ],
    expect: [
      {quantity: "len", value: 7.32, tolPct: 0.5, quote: "the flagstaff is 7.32 m long"},
      {quantity: "d", value: 17.32, tolPct: 0.5, quote: "the building is 17.32 m from P"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "TRIG-N-NCERT-9-SA-004",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "single", view: "elevation", unit: "m", theta: 30, d: "30"},
    labels: { "q.h": "h"},
    provenance: [
      {param: "d", field: "questionText", quote: "which is 30 m from the foot of the tower"},
      {param: "theta", field: "questionText", quote: "is 30°"},
    ],
    expect: [
      {quantity: "h", value: 17.32, tolPct: 0.5, quote: "10√3 m ≈ 17.32 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "TRIG-N-NCERT-9-LA-003",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsSameSide", view: "elevation", unit: "m", far: 30, near: 60, h: "30", eye: "1.5"},
    labels: { "q.dNear": "y"},
    provenance: [
      {param: "eye", field: "questionText", quote: "A 1.5 m tall boy"},
      {param: "h", field: "questionText", quote: "a 30 m tall building"},
      {param: "far", field: "questionText", quote: "increases from 30° to 60°"},
      {param: "near", field: "questionText", quote: "increases from 30° to 60°"},
    ],
    expect: [
      {quantity: "gap", value: 32.909, tolPct: 0.5, quote: "Distance walked = 19√3 m"},
      {quantity: "rise", value: 28.5, tolPct: 0.5, quote: "30 − 1.5 = 28.5 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "TRIG-N-NCERT-9-LA-005",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoStructuresCross", unit: "m", atLeftFoot: 60, atRightFoot: 30, rightH: "50"},
    labels: {lTop: "P", lFoot: "Q", rTop: "S", rFoot: "R", "q.leftH": "h", "q.d": "d"},
    provenance: [
      {param: "atRightFoot", field: "questionText", quote: "from the foot of the tower is 30°"},
      {param: "atLeftFoot", field: "questionText", quote: "from the foot of the building is 60°"},
      {param: "rightH", field: "questionText", quote: "If the tower is 50 m high"},
    ],
    expect: [
      {quantity: "leftH", value: 16.6667, tolPct: 0.5, quote: "Height of the building = 50/3 m"},
      {quantity: "d", value: 28.8675, tolPct: 0.5, quote: "d = 50/√3"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "TRIG-N-NCERT-9-CB-001",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsSameSide", view: "depression", unit: "m", far: 30, near: 45, h: "75"},
    labels: {top: "A", foot: "B", near: "C", far: "D"},
    provenance: [
      {param: "h", field: "questionText", quote: "75 m high lighthouse"},
      {param: "far", field: "questionText", quote: "the angles of depression of two ships are 30° and 45° respectively"},
      {param: "near", field: "questionText", quote: "the angles of depression of two ships are 30° and 45° respectively"},
    ],
    expect: [
      {quantity: "dNear", value: 75, tolPct: 0.5, quote: "BC = 75 m"},
      {quantity: "dFar", value: 129.9038, tolPct: 0.5, quote: "BD = 75√3 m"},
      {quantity: "gap", value: 54.9, tolPct: 0.5, quote: "75(√3 − 1) m ≈ 54.9 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "TRIG-N-NCERT-9-LA-006",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsSameSide", view: "elevation", subject: "object", unit: "m", far: 30, near: 60, h: "88.2", eye: "1.2"},
    provenance: [
      {param: "eye", field: "questionText", quote: "A 1.2 m tall girl"},
      {param: "h", field: "questionText", quote: "at a height of 88.2 m from the ground"},
      {param: "near", field: "questionText", quote: "The angle of elevation of the balloon from her eyes at any instant is 60°"},
      {param: "far", field: "questionText", quote: "the angle of elevation reduces to 30°"},
    ],
    expect: [
      {quantity: "gap", value: 100.4589, tolPct: 0.5, quote: "Distance travelled = 58√3 m"},
      {quantity: "rise", value: 87, tolPct: 0.5, quote: "88.2 − 1.2 = 87 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "TRIG-N-NCERT-9-CB-002",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsSameSide", view: "depression", unit: "m", far: 30, near: 60, scaleFree: true},
    labels: { "q.h": "h", far: "C₁", near: "C₂"},
    caption: "The question gives no length: angles are exact, lengths are not drawn to a number.",
    provenance: [
      {param: "far", field: "questionText", quote: "at an angle of depression of 30°"},
      {param: "near", field: "questionText", quote: "the angle of depression of the car becomes 60°"},
    ],
    expect: [
      {quantity: "nearOverGap", value: 3, tolPct: 0.5, factor: 6, quote: "The car takes 3 more seconds"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "TRIG-N-EXMPLR-9-SA-006",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "single", view: "elevation", unit: "m", eye: "1.5", d: "20.5", h: "22"},
    labels: { "q.theta": "θ"},
    provenance: [
      {param: "eye", field: "questionText", quote: "An observer 1.5 m tall"},
      {param: "d", field: "questionText", quote: "is 20.5 m away from a tower"},
      {param: "h", field: "questionText", quote: "a tower 22 m high"},
    ],
    expect: [
      {quantity: "theta", value: 45, tolPct: 0.5, quote: "Angle of elevation = 45°."},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "TRIG-N-EXMPLR-9-LA-001",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsSameSide", view: "elevation", unit: "m", far: 30, near: 45, gap: "20"},
    labels: {top: "A", foot: "B", far: "P", near: "Q", "q.h": "h"},
    provenance: [
      {param: "far", field: "questionText", quote: "from a certain point is 30°"},
      {param: "gap", field: "questionText", quote: "If the observer moves 20 metres towards the tower"},
      {param: "near", field: "questionText", quote: "the angle of elevation increases by 15°", derived: "30° + 15° = 45°"},
    ],
    expect: [
      {quantity: "h", value: 27.32, tolPct: 0.5, quote: "10(√3 + 1) m ≈ 27.32 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "TRIG-N-EXMPLR-9-LA-004",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoStructuresCross", unit: "m", atLeftFoot: 30, atRightFoot: 60, leftH: "30"},
    labels: {lTop: "", lFoot: "", rTop: "", rFoot: "", "q.rightH": "h", "q.d": "d"},
    provenance: [
      {param: "leftH", field: "questionText", quote: "the top of a tower 30 m high from the foot of another tower in the same plane is 60°"},
      {param: "atRightFoot", field: "questionText", quote: "the top of a tower 30 m high from the foot of another tower in the same plane is 60°"},
      {param: "atLeftFoot", field: "questionText", quote: "the top of the second tower from the foot of the first is 30°"},
    ],
    expect: [
      {quantity: "d", value: 17.3205, tolPct: 0.5, quote: "the distance between the towers is 10√3 m"},
      {quantity: "rightH", value: 10, tolPct: 0.5, quote: "the height of the second tower is 10 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "TRIG-N-EXMPLR-9-LA-005",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoVerticalPoints", unit: "m", ground: 60, upper: 45, k: "10"},
    labels: { "q.H": "h", "q.d": "d"},
    provenance: [
      {param: "ground", field: "questionText", quote: "from a point on the ground is 60°"},
      {param: "k", field: "questionText", quote: "From another point 10 m vertically above the first"},
      {param: "upper", field: "questionText", quote: "its angle of elevation is 45°"},
    ],
    expect: [
      {quantity: "H", value: 23.66, tolPct: 0.5, quote: "(15 + 5√3) m ≈ 23.66 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "TRIG-N-EXMPLR-9-CB-001",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsSameSide", view: "depression", unit: "m", far: 45, near: 60, gap: "100"},
    labels: {top: "P", foot: "Q", far: "A", near: "B", "q.h": "h"},
    provenance: [
      {param: "far", field: "questionText", quote: "the angles of depression of two cars at an instant are found to be 45° and 60°"},
      {param: "near", field: "questionText", quote: "the angles of depression of two cars at an instant are found to be 45° and 60°"},
      {param: "gap", field: "questionText", quote: "The cars are 100 m apart on the same side"},
    ],
    expect: [
      {quantity: "h", value: 236.6, tolPct: 0.5, quote: "50(3 + √3) m ≈ 236.6 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "Z3-TG-105",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "single", view: "elevation", unit: "m", theta: 30, h: "25"},
    labels: { "q.d": "d"},
    provenance: [
      {param: "theta", field: "questionText", quote: "The angle of elevation to the top of the lighthouse is 30 deg"},
      {param: "h", field: "questionText", quote: "The lighthouse is 25 m tall"},
    ],
    expect: [
      {quantity: "d", value: 43.3, tolPct: 0.5, quote: "d = 25 * 1.732 = 43.3 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "Z3-TG-108",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "objectOnObject", unit: "m", lower: 45, upper: 60, d: "208"},
    labels: {top: "", mid: "", foot: "", obs: ""},
    provenance: [
      {param: "d", field: "questionText", quote: "From a distance of 208 m"},
      {param: "upper", field: "questionText", quote: "the angle of elevation to the pinnacle of the tower is 60 deg"},
      {param: "lower", field: "questionText", quote: "the angle of elevation to the restaurant from the same vantage point is 45 deg"},
    ],
    expect: [
      {quantity: "h2", value: 360.3, tolPct: 0.5, quote: "208 * sqrt(3) = 360.3 m"},
      {quantity: "len", value: 152, tolPct: 0.5, quote: "360 - 208 = 152 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "APQ-M-TRIG-009",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsSameSide", view: "depression", unit: "m", far: 30, near: 45, scaleFree: true},
    labels: {top: "A", foot: "B", far: "D", near: "C"},
    part: "first alternative (the car)",
    caption: "First alternative (the car). Speed and time fix the scene only up to scale: angles are exact, lengths are not drawn to a number.",
    provenance: [
      {param: "far", field: "questionText", quote: "for the angle of depression to change from 30° to 45°"},
      {param: "near", field: "questionText", quote: "for the angle of depression to change from 30° to 45°"},
    ],
    expect: [
      {quantity: "nearOverGap", value: 16.3923, tolPct: 0.5, factor: 12, quote: "Time = 12/(√3 − 1) = 6(√3 + 1)"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "PYQ-M-TRIG-009",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsOppositeSides", view: "elevation", unit: "m", left: 60, right: 30, total: "100"},
    labels: {top: "B", foot: "A", left: "D", right: "C", "q.dLeft": "x", "q.h": "h"},
    provenance: [
      {param: "left", field: "questionText", quote: "the basket of a hot air balloon to be 60°"},
      {param: "total", field: "questionText", quote: "standing 100 m away from the first on the opposite side of the balloon"},
      {param: "right", field: "questionText", quote: "estimates the angle of elevation to be 30°"},
    ],
    expect: [
      {quantity: "h", value: 43.3, tolPct: 0.5, quote: "h = 25√3 m ≈ 43.3 m"},
      {quantity: "LLeft", value: 50, tolPct: 0.5, quote: "BD = h/sin 60° = 25√3 ÷ (√3/2) = 50 m"},
      {quantity: "dRight", value: 75, tolPct: 0.5, quote: "AC = 100 − x = 75 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "PYQ-M-2026-TRIG-001",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoVerticalPoints", unit: "m", ground: 45, upper: 30, H: "60"},
    labels: {top: "K", foot: "G", P: "T", Q: "R", meet: "S"},
    provenance: [
      {param: "H", field: "questionText", quote: "A kite is flying at a height of 60 m above the ground level"},
      {param: "upper", field: "questionText", quote: "observes the angle of elevation of kite as 30º"},
      {param: "ground", field: "questionText", quote: "From the bottom of the same building, the angle of elevation of kite is 45º"},
    ],
    expect: [
      {quantity: "k", value: 25.4, tolPct: 0.5, quote: "height of roof from the ground = 25.4 m"},
      {quantity: "LQ", value: 69.2, tolPct: 0.5, quote: "Length of the string = 69.2 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "2026-TRIG-APP-01",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "single", view: "depression", unit: "m", theta: 30, h: "20"},
    labels: {top: "A", foot: "B", obs: "C"},
    provenance: [
      {param: "h", field: "questionText", quote: "From the top of a 20 m high building"},
      {param: "theta", field: "questionText", quote: "the angle of depression of a car on the road is 30°"},
    ],
    expect: [
      {quantity: "d", value: 34.6, tolPct: 0.5, quote: "the car is approximately 34.6 m from the foot of the building"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-206",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "single", view: "shadow", unit: "m", theta: 60, h: "9"},
    provenance: [
      {param: "h", field: "questionText", quote: "A 9 m tall vertical lamp post"},
      {param: "theta", field: "questionText", quote: "the angle of elevation of the Sun is 60°"},
    ],
    expect: [
      {quantity: "d", value: 5.1962, tolPct: 0.5, quote: "shadow = 9/√3 = 3√3 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-218",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "single", view: "depression", unit: "m", theta: 30, h: "75"},
    provenance: [
      {param: "h", field: "questionText", quote: "From the top of a vertical cliff 75 m high"},
      {param: "theta", field: "questionText", quote: "at an angle of depression of 30°"},
    ],
    expect: [
      {quantity: "d", value: 129.9038, tolPct: 0.5, quote: "d = 75 ÷ (1/√3) = 75√3 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-220",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "single", view: "depression", unit: "m", h: "4", d: "4√3"},
    labels: { "q.theta": "θ"},
    provenance: [
      {param: "h", field: "questionText", quote: "A lifeguard's eyes are 4 m above a level beach"},
      {param: "d", field: "questionText", quote: "4√3 m from the foot of the lifeguard tower"},
    ],
    expect: [
      {quantity: "theta", value: 30, tolPct: 0.5, quote: "so θ = 30°"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-225",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "single", view: "depression", unit: "m", theta: 45, h: "50"},
    provenance: [
      {param: "h", field: "questionText", quote: "From the top of a 50 m tall tower"},
      {param: "theta", field: "questionText", quote: "at an angle of depression of 45°"},
    ],
    expect: [
      {quantity: "d", value: 50, tolPct: 0.5, quote: "Distance = 50 ÷ tan 45° = 50 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-230",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "single", view: "elevation", unit: "m", theta: 30, h: "30"},
    provenance: [
      {param: "h", field: "questionText", quote: "the top of a 30 m tall building is 30°"},
      {param: "theta", field: "questionText", quote: "the top of a 30 m tall building is 30°"},
    ],
    expect: [
      {quantity: "d", value: 51.9615, tolPct: 0.5, quote: "Distance = 30 ÷ tan 30° = 30√3 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-232",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "single", view: "elevation", unit: "m", theta: 45, d: "20", eye: "1.5"},
    provenance: [
      {param: "eye", field: "questionText", quote: "A girl whose eyes are 1.5 m above level ground"},
      {param: "d", field: "questionText", quote: "stands 20 m from a vertical tree"},
      {param: "theta", field: "questionText", quote: "at an angle of elevation of 45°"},
    ],
    expect: [
      {quantity: "h", value: 21.5, tolPct: 0.5, quote: "the tree is 20 + 1.5 = 21.5 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-233",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "single", view: "elevation", unit: "m", theta: 60, d: "40"},
    labels: { "q.h": "h"},
    provenance: [
      {param: "d", field: "questionText", quote: "Kavya stands on level ground 40 m from the gate"},
      {param: "theta", field: "questionText", quote: "observes the drone at an angle of elevation of 60°"},
    ],
    expect: [
      {quantity: "h", value: 69.28, tolPct: 0.5, quote: "h = 40 × 1.732 = 69.28 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-234",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "single", view: "depression", unit: "m", theta: 30, h: "12"},
    labels: { "q.d": "d"},
    provenance: [
      {param: "h", field: "questionText", quote: "her eyes are 12 m above sea level"},
      {param: "theta", field: "questionText", quote: "at an angle of depression of 30°"},
    ],
    expect: [
      {quantity: "d", value: 20.784, tolPct: 0.5, quote: "d = 12 × 1.732 = 20.784 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-236",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsSameSide", view: "shadow", unit: "m", far: 30, near: 60, h: "9"},
    provenance: [
      {param: "h", field: "questionText", quote: "the shadow of a 9 m tall vertical pole"},
      {param: "near", field: "questionText", quote: "At 10 a.m. the angle of elevation of the Sun is 60°"},
      {param: "far", field: "questionText", quote: "late in the afternoon it is 30°"},
    ],
    expect: [
      {quantity: "dNear", value: 5.1962, tolPct: 0.5, quote: "s₁ = 9/√3 = 3√3 m"},
      {quantity: "dFar", value: 15.5885, tolPct: 0.5, quote: "s₂ = 9√3 m"},
      {quantity: "gap", value: 10.39, tolPct: 0.5, quote: "6√3 m ≈ 10.39 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-245",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "single", view: "depression", unit: "m", theta: 45, h: "15"},
    labels: { "q.d": "d"},
    provenance: [
      {param: "h", field: "questionText", quote: "A kingfisher sits on the top of a 15 m tall vertical pole"},
      {param: "theta", field: "questionText", quote: "at an angle of depression of 45°"},
    ],
    expect: [
      {quantity: "d", value: 15, tolPct: 0.5, quote: "d = 15 m"},
      {quantity: "L", value: 21.21, tolPct: 0.5, quote: "15√2 m ≈ 21.21 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-250",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsOppositeSides", view: "elevation", unit: "m", left: 60, right: 30, h: "30"},
    labels: {top: "", foot: "", left: "", right: "", "q.dLeft": "x", "q.dRight": "y"},
    provenance: [
      {param: "h", field: "questionText", quote: "A 30 m tall floodlight tower"},
      {param: "left", field: "questionText", quote: "Aditi sees the top of the tower at an angle of elevation of 60°"},
      {param: "right", field: "questionText", quote: "Kabir sees it at an angle of elevation of 30°"},
    ],
    expect: [
      {quantity: "total", value: 69.28, tolPct: 0.5, quote: "40√3 m ≈ 69.28 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-251",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsSameSide", view: "depression", unit: "m", far: 30, near: 60, h: "60"},
    labels: { "q.dNear": "x₂"},
    provenance: [
      {param: "h", field: "questionText", quote: "hovers at a fixed height of 60 m"},
      {param: "far", field: "questionText", quote: "changes from 30° to 60°"},
      {param: "near", field: "questionText", quote: "changes from 30° to 60°"},
    ],
    expect: [
      {quantity: "gap", value: 69.282, tolPct: 0.5, quote: "Distance covered = 60√3 − 20√3 = 40√3 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-252",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "elevDepFromHeight", unit: "m", H1: "60", top: 30, topView: "depression", foot: 60},
    labels: { "q.d": "d", "q.H2": "h"},
    provenance: [
      {param: "H1", field: "questionText", quote: "A clock tower is 60 m tall"},
      {param: "foot", field: "questionText", quote: "The angle of depression of the foot of the house is 60°"},
      {param: "top", field: "questionText", quote: "the angle of depression of the top of the house is 30°"},
    ],
    expect: [
      {quantity: "d", value: 34.641, tolPct: 0.5, quote: "d = 60/√3 = 20√3 m"},
      {quantity: "H2", value: 40, tolPct: 0.5, quote: "Height of the house h = 60 − 20 = 40 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-254",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "objectOnObject", unit: "m", lower: 45, upper: 60, len: "12"},
    labels: {obs: "P", top: "", mid: "", foot: "", "q.h1": "h", "q.d": "d"},
    provenance: [
      {param: "len", field: "questionText", quote: "A 12 m tall communication mast"},
      {param: "lower", field: "questionText", quote: "the angle of elevation of the bottom of the mast is 45°"},
      {param: "upper", field: "questionText", quote: "the angle of elevation of the top of the mast is 60°"},
    ],
    expect: [
      {quantity: "h1", value: 16.39, tolPct: 0.5, quote: "6(√3 + 1) m ≈ 16.39 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-255",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsSameSide", view: "depression", unit: "m", far: 30, near: 45, h: "300"},
    provenance: [
      {param: "h", field: "questionText", quote: "hovers 300 m above the sea"},
      {param: "near", field: "questionText", quote: "sees a lifeboat at an angle of depression of 45°"},
      {param: "far", field: "questionText", quote: "a swimmer at an angle of depression of 30°"},
    ],
    expect: [
      {quantity: "gap", value: 219.6, tolPct: 0.5, quote: "300(√3 − 1) m ≈ 219.6 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-263",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "objectOnObject", style: "rising", unit: "m", lower: 30, upper: 60, d: "60"},
    labels: {top: "", mid: "", foot: "", obs: ""},
    provenance: [
      {param: "d", field: "questionText", quote: "An observer stands 60 m from the release point"},
      {param: "lower", field: "questionText", quote: "at an angle of elevation of 30°"},
      {param: "upper", field: "questionText", quote: "at an angle of elevation of 60°"},
    ],
    expect: [
      {quantity: "len", value: 69.28, tolPct: 0.5, quote: "40√3 m ≈ 69.28 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-266",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsSameSide", view: "shadow", unit: "m", far: 30, near: 45, dNear: "12"},
    labels: { "q.h": "h"},
    provenance: [
      {param: "dNear", field: "questionText", quote: "is 12 m long"},
      {param: "near", field: "questionText", quote: "the angle of elevation of the Sun) at that time is 45°"},
      {param: "far", field: "questionText", quote: "In the evening the Sun's altitude is 30°"},
    ],
    expect: [
      {quantity: "h", value: 12, tolPct: 0.5, quote: "so h = 12 m"},
      {quantity: "dFar", value: 20.78, tolPct: 0.5, quote: "12√3 m ≈ 20.78 m"},
      {quantity: "LFar", value: 24, tolPct: 0.5, quote: "(iii) 24 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-267",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsSameSide", view: "elevation", unit: "m", far: 30, near: 60, gap: "40"},
    labels: { "q.dNear": "w", "q.h": "h"},
    provenance: [
      {param: "near", field: "questionText", quote: "finds the angle of elevation of the top of the temple's spire to be 60°"},
      {param: "gap", field: "questionText", quote: "She then walks 40 m straight back"},
      {param: "far", field: "questionText", quote: "finds the angle of elevation to be 30°"},
    ],
    expect: [
      {quantity: "dNear", value: 20, tolPct: 0.5, quote: "width 20 m"},
      {quantity: "h", value: 34.64, tolPct: 0.5, quote: "height 20√3 m ≈ 34.64 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-268",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "single", view: "depression", unit: "m", theta: 30, h: "300"},
    labels: {top: "", foot: "P", obs: "L"},
    provenance: [
      {param: "h", field: "questionText", quote: "a paraglider is flying 300 m directly above a point P"},
      {param: "theta", field: "questionText", quote: "at an angle of depression of 30°"},
    ],
    expect: [
      {quantity: "d", value: 519.6, tolPct: 0.5, quote: "300√3 m ≈ 519.6 m"},
      {quantity: "L", value: 600, tolPct: 0.5, quote: "(ii) 600 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-269",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "objectOnObject", unit: "m", lower: 30, upper: 60, d: "30"},
    labels: {top: "", mid: "", foot: "", obs: "", "q.h1": "b", "q.h2": "H"},
    provenance: [
      {param: "d", field: "questionText", quote: "Ravi stands on level ground 30 m from the foot of the building"},
      {param: "lower", field: "questionText", quote: "the angle of elevation of the bottom of the tower (at roof level) is 30°"},
      {param: "upper", field: "questionText", quote: "the angle of elevation of the top of the tower is 60°"},
    ],
    expect: [
      {quantity: "h1", value: 17.32, tolPct: 0.5, quote: "(i) 10√3 m ≈ 17.32 m"},
      {quantity: "h2", value: 51.96, tolPct: 0.5, quote: "(ii) 30√3 m ≈ 51.96 m"},
      {quantity: "len", value: 34.64, tolPct: 0.5, quote: "(iii) 20√3 m ≈ 34.64 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-273",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsSameSide", view: "depression", unit: "m", far: 30, near: 60, h: "60"},
    labels: { "q.dNear": "b", "q.gap": ""},
    provenance: [
      {param: "h", field: "questionText", quote: "its observation platform is 60 m above sea level"},
      {param: "far", field: "questionText", quote: "spots a swimmer in distress at an angle of depression of 30°"},
      {param: "near", field: "questionText", quote: "is seen at an angle of depression of 60°"},
    ],
    expect: [
      {quantity: "dFar", value: 103.92, tolPct: 0.5, quote: "(i) 60√3 m ≈ 103.92 m"},
      {quantity: "dNear", value: 34.64, tolPct: 0.5, quote: "(ii) 20√3 m ≈ 34.64 m"},
      {quantity: "gap", value: 69.28, tolPct: 0.5, quote: "40√3 m = 40 × 1.732 = 69.28 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-274",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsOppositeSides", view: "elevation", unit: "m", left: 60, right: 30, total: "80"},
    labels: {top: "", foot: "", left: "", right: "", "q.h": "h"},
    provenance: [
      {param: "total", field: "questionText", quote: "Aman and Bela are 80 m apart"},
      {param: "left", field: "questionText", quote: "Aman sees the top of the tower at an angle of elevation of 60°"},
      {param: "right", field: "questionText", quote: "Bela sees it at an angle of elevation of 30°"},
    ],
    expect: [
      {quantity: "h", value: 34.64, tolPct: 0.5, quote: "(iii) 20√3 m ≈ 34.64 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-276",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "elevDepFromHeight", unit: "m", H1: "24", top: 30, topView: "elevation", foot: 60},
    labels: {obs: "", obsFoot: "", foot: "", top: "", meet: "", "q.d": "d"},
    provenance: [
      {param: "H1", field: "questionText", quote: "From the flat roof of a hostel building 24 m high"},
      {param: "top", field: "questionText", quote: "The angle of elevation of the top of the gopuram is 30°"},
      {param: "foot", field: "questionText", quote: "the angle of depression of its foot is 60°"},
    ],
    expect: [
      {quantity: "d", value: 13.86, tolPct: 0.5, quote: "(i) 8√3 m ≈ 13.86 m"},
      {quantity: "H2", value: 32, tolPct: 0.5, quote: "(ii) 32 m"},
      {quantity: "Ltop", value: 16, tolPct: 0.5, quote: "(iii) 16 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-282",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "objectOnObject", style: "rising", unit: "km", lower: 30, upper: 60, d: "3"},
    labels: {top: "", mid: "", foot: "", obs: "", "q.h1": "h₁", "q.h2": "h₂"},
    provenance: [
      {param: "d", field: "questionText", quote: "A tracking camera on level ground 3 km from the launch pad"},
      {param: "lower", field: "questionText", quote: "the angle of elevation of the rocket from the camera is 30°"},
      {param: "upper", field: "questionText", quote: "exactly 10 seconds later it is 60°"},
    ],
    expect: [
      {quantity: "h1", value: 1.732, tolPct: 0.5, quote: "(i) √3 km ≈ 1.732 km"},
      {quantity: "h2", value: 5.196, tolPct: 0.5, quote: "(ii) 3√3 km ≈ 5.196 km"},
      {quantity: "len", value: 3.464, tolPct: 0.5, quote: "= 3.464 km"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-284",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsSameSide", view: "elevation", unit: "m", far: 45, near: 60, dNear: "30", eye: "1.5"},
    provenance: [
      {param: "eye", field: "questionText", quote: "whose eyepiece is 1.5 m above level ground"},
      {param: "dNear", field: "questionText", quote: "at a point 30 m from the foot of a factory chimney"},
      {param: "near", field: "questionText", quote: "measured at the eyepiece, is 60°"},
      {param: "far", field: "questionText", quote: "the angle of elevation of the top is 45°"},
    ],
    expect: [
      {quantity: "rise", value: 51.96, tolPct: 0.5, quote: "(i) 30√3 m ≈ 51.96 m"},
      {quantity: "h", value: 53.46, tolPct: 0.5, quote: "(ii) (30√3 + 1.5) m ≈ 53.46 m"},
      {quantity: "gap", value: 21.96, tolPct: 0.5, quote: "(iii) 30(√3 − 1) m ≈ 21.96 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-285",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsSameSide", view: "depression", unit: "m", far: 30, near: 45, h: "25"},
    labels: { "q.dFar": "x₁", "q.dNear": "x₂"},
    provenance: [
      {param: "h", field: "questionText", quote: "its deck is 25 m above the water"},
      {param: "far", field: "questionText", quote: "At first the angle of depression of the boat is 30°"},
      {param: "near", field: "questionText", quote: "10 seconds later it is 45°"},
    ],
    expect: [
      {quantity: "dFar", value: 43.3, tolPct: 0.5, quote: "(i) 25√3 m ≈ 43.3 m"},
      {quantity: "dNear", value: 25, tolPct: 0.5, quote: "(ii) 25 m"},
      {quantity: "gap", value: 18.3, tolPct: 0.5, quote: "= 25 × 0.732 = 18.3 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-292",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoVerticalPoints", unit: "m", ground: 60, upper: 30, k: "30"},
    labels: { "q.H": "H", "q.d": "d", P: "", Q: "", foot: "", top: ""},
    provenance: [
      {param: "ground", field: "questionText", quote: "sees the top of the tower at an angle of elevation of 60°"},
      {param: "k", field: "questionText", quote: "30 m above the ground"},
      {param: "upper", field: "questionText", quote: "sees the top of the tower at an angle of elevation of 30°"},
    ],
    expect: [
      {quantity: "H", value: 45, tolPct: 0.5, quote: "H = 45 m"},
      {quantity: "d", value: 25.98, tolPct: 0.5, quote: "d = 15√3 m ≈ 25.98 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-293",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "objectOnObject", style: "rising", unit: "m", lower: 30, upper: 60, d: "30"},
    labels: {obs: "G", foot: "F", mid: "A", top: "B"},
    provenance: [
      {param: "d", field: "questionText", quote: "at a point G, 30 m from the foot F of the wall"},
      {param: "lower", field: "questionText", quote: "sees the cradle at an angle of elevation of 30°"},
      {param: "upper", field: "questionText", quote: "when it stops the guard sees it at an angle of elevation of 60°"},
    ],
    expect: [
      {quantity: "h1", value: 17.32, tolPct: 0.5, quote: "(a) 10√3 m ≈ 17.32 m"},
      {quantity: "h2", value: 51.96, tolPct: 0.5, quote: "(b) 30√3 m ≈ 51.96 m"},
      {quantity: "len", value: 34.64, tolPct: 0.5, quote: "rise 20√3 m ≈ 34.64 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-294",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsOppositeSides", view: "depression", unit: "m", left: 60, right: 30, h: "150"},
    labels: {top: "C", foot: "D", left: "P", right: "Q"},
    provenance: [
      {param: "h", field: "questionText", quote: "150 m above D"},
      {param: "left", field: "questionText", quote: "the angle of depression of hut P is 60°"},
      {param: "right", field: "questionText", quote: "the angle of depression of hut Q is 30°"},
    ],
    expect: [
      {quantity: "dLeft", value: 86.6, tolPct: 0.5, quote: "50√3 m ≈ 86.6 m"},
      {quantity: "dRight", value: 259.8, tolPct: 0.5, quote: "150√3 m ≈ 259.8 m"},
      {quantity: "total", value: 346.4, tolPct: 0.5, quote: "(b) 200√3 m ≈ 346.4 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-295",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsSameSide", view: "depression", unit: "m", far: 30, near: 45, gap: "200"},
    labels: {top: "A", foot: "B", far: "C", near: "D", "q.h": "h", "q.dNear": "x"},
    provenance: [
      {param: "far", field: "questionText", quote: "observes the angle of depression of the boat to be 30°"},
      {param: "near", field: "questionText", quote: "exactly 50 seconds later it has become 45°"},
      {param: "gap", field: "questionText", quote: "the boat has covered 200 m"},
    ],
    expect: [
      {quantity: "h", value: 273.2, tolPct: 0.5, quote: "(a) 100(√3 + 1) m ≈ 273.2 m"},
      {quantity: "dNear", value: 273.2, tolPct: 0.5, quote: "(b) 273.2 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-296",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsSameSide", view: "elevation", unit: "m", far: 30, near: 60, gap: "40"},
    labels: {top: "P", foot: "Q", near: "A", far: "B", "q.h": "h", "q.dNear": "x"},
    provenance: [
      {param: "near", field: "questionText", quote: "sees the top of the mast at an angle of elevation of 60°"},
      {param: "gap", field: "questionText", quote: "He walks 40 m directly away from the mast"},
      {param: "far", field: "questionText", quote: "from where the angle of elevation of the top is 30°"},
    ],
    expect: [
      {quantity: "dNear", value: 20, tolPct: 0.5, quote: "(a) 20 m"},
      {quantity: "h", value: 34.64, tolPct: 0.5, quote: "(b) 20√3 m ≈ 34.64 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-297",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsSameSide", view: "shadow", unit: "m", far: 30, near: 60, h: "18"},
    labels: {top: "A", foot: "B", far: "C", near: "D"},
    provenance: [
      {param: "h", field: "questionText", quote: "An 18 m tall vertical clock tower"},
      {param: "far", field: "questionText", quote: "In the morning, the Sun's angle of elevation is 30°"},
      {param: "near", field: "questionText", quote: "around midday it is 60°"},
    ],
    expect: [
      {quantity: "dFar", value: 31.18, tolPct: 0.5, quote: "(a) 18√3 m ≈ 31.18 m"},
      {quantity: "dNear", value: 10.39, tolPct: 0.5, quote: "(b) 6√3 m ≈ 10.39 m"},
      {quantity: "gap", value: 20.78, tolPct: 0.5, quote: "shortened by 12√3 m ≈ 20.78 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-300",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsSameSide", view: "depression", unit: "m", far: 30, near: 60, gap: "600"},
    labels: {top: "H", foot: "O", near: "A", far: "B", "q.h": "h"},
    provenance: [
      {param: "gap", field: "questionText", quote: "are 600 m apart"},
      {param: "near", field: "questionText", quote: "the angle of depression of raft A is 60°"},
      {param: "far", field: "questionText", quote: "that of raft B is 30°"},
    ],
    expect: [
      {quantity: "h", value: 519.6, tolPct: 0.5, quote: "(a) 300√3 m ≈ 519.6 m"},
      {quantity: "dNear", value: 300, tolPct: 0.5, quote: "OA = 300 m"},
      {quantity: "dFar", value: 900, tolPct: 0.5, quote: "OB = 900 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "LTG-M-TRIG-301",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "objectOnObject", unit: "m", lower: 30, upper: 45, len: "8"},
    labels: {foot: "B", mid: "A", top: "C", obs: "P", "q.h1": "h", "q.d": "d"},
    provenance: [
      {param: "len", field: "questionText", quote: "An advertising hoarding 8 m tall"},
      {param: "lower", field: "questionText", quote: "the angle of elevation of the bottom of the hoarding is 30°"},
      {param: "upper", field: "questionText", quote: "that of the top of the hoarding is 45°"},
    ],
    expect: [
      {quantity: "h1", value: 10.93, tolPct: 0.5, quote: "(a) 4(√3 + 1) m ≈ 10.93 m"},
      {quantity: "d", value: 18.93, tolPct: 0.5, quote: "(b) 4(3 + √3) m ≈ 18.93 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
  {
    questionId: "trig-comp-01",
    slot: "solution",
    builder: "heightsDistances",
    params: {template: "twoPointsSameSide", view: "depression", unit: "m", far: 30, near: 60, h: "45"},
    labels: {top: "A", foot: "B", near: "C", far: "D"},
    provenance: [
      {param: "h", field: "questionText", quote: "From the top of a 45 m high lighthouse"},
      {param: "far", field: "questionText", quote: "the angles of depression of two ships on the same side are 30° and 60°"},
      {param: "near", field: "questionText", quote: "the angles of depression of two ships on the same side are 30° and 60°"},
    ],
    expect: [
      {quantity: "dNear", value: 25.9808, tolPct: 0.5, quote: "BC = 45/√3 = 15√3 m"},
      {quantity: "gap", value: 51.96, tolPct: 0.5, quote: "30√3 m ≈ 51.96 m"},
    ],
    confirmedBy: "opus-5.5 builder: row read + rendered figure eye-checked 2026-10-07",
  },
];
