import type { CanonicalQuestion } from "../../types";

export const ARC2_PACK2: CanonicalQuestion[] = [
  {
    "id": "ARC2-001",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Sector Area",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "The area of a sector of a circle with radius 7 cm and central angle 60° is:",
    "options": [
      "A) 77/6 cm²",
      "B) 154/6 cm²",
      "C) 49/6 cm²",
      "D) 98/6 cm²"
    ],
    "answer": "B) 154/6 cm²",
    "solutionSteps": [
      "Area of sector = (θ/360°) × πr²",
      "= (60°/360°) × π × 7²",
      "= (1/6) × 22/7 × 49",
      "= (22/7 × 49)/6 = (22 × 7)/6 = 154/6 cm² ≈ 25.67 cm²"
    ],
    "finalAnswer": "B) 154/6 cm²",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 11.1"
  },
  {
    "id": "ARC2-002",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Arc Length",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "The length of an arc of a circle with radius 10 cm and central angle 90° is:",
    "options": [
      "A) 5π cm",
      "B) 10π cm",
      "C) 15π cm",
      "D) 20π cm"
    ],
    "answer": "A) 5π cm",
    "solutionSteps": [
      "Arc length = (θ/360°) × 2πr",
      "= (90°/360°) × 2π × 10",
      "= (1/4) × 20π",
      "= 5π cm"
    ],
    "finalAnswer": "A) 5π cm",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 11.1"
  },
  {
    "id": "ARC2-003",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Sector Area",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "A sector of a circle has radius 6 cm. If the area of sector is 18.84 cm², then the central angle is (use π = 3.14):",
    "options": [
      "A) 30°",
      "B) 45°",
      "C) 60°",
      "D) 90°"
    ],
    "answer": "C) 60°",
    "solutionSteps": [
      "Area = (θ/360°) × πr²",
      "18.84 = (θ/360°) × 3.14 × 36",
      "18.84 = (θ/360°) × 113.04",
      "θ = 60°"
    ],
    "finalAnswer": "C) 60°",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 11.1"
  },
  {
    "id": "ARC2-004",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Segment Area",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "The area of a segment of a circle is given by the formula:",
    "options": [
      "A) Area of sector + Area of triangle",
      "B) Area of sector - Area of triangle",
      "C) Area of triangle - Area of sector",
      "D) Area of sector × Area of triangle"
    ],
    "answer": "B) Area of sector - Area of triangle",
    "solutionSteps": [
      "A segment is the region between a chord and the arc",
      "Area of segment = Area of sector - Area of triangle formed by two radii and chord"
    ],
    "finalAnswer": "B) Area of sector - Area of triangle",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 11.2"
  },
  {
    "id": "ARC2-005",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Sector Area",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Find the area of a sector of a circle with radius 14 cm and central angle 45°.",
    "options": [],
    "answer": "77 cm²",
    "solutionSteps": [
      "Area of sector = (θ/360°) × πr²",
      "= (45°/360°) × (22/7) × 14²",
      "= (1/8) × (22/7) × 196",
      "= (1/8) × 22 × 28",
      "= (616/8) = 77 cm²"
    ],
    "finalAnswer": "77 cm²",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 11.1"
  },
  {
    "id": "ARC2-006",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Arc Length",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Calculate the arc length of a circle with radius 21 cm and central angle 120°.",
    "options": [],
    "answer": "44 cm",
    "solutionSteps": [
      "Arc length = (θ/360°) × 2πr",
      "= (120°/360°) × 2 × (22/7) × 21",
      "= (1/3) × 2 × 22 × 3",
      "= (1/3) × 132",
      "= 44 cm"
    ],
    "finalAnswer": "44 cm",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 11.1"
  },
  {
    "id": "ARC2-007",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Segment Area",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A circle has radius 10 cm. Find the area of the segment cut off by a chord at a distance of 6 cm from the center.",
    "options": [],
    "answer": "≈ 44.76 cm²",
    "solutionSteps": [
      "cos(θ/2) = 6/10 = 3/5, so θ/2 = cos⁻¹(0.6) ≈ 53.13°",
      "θ ≈ 106.26° or use exact calculation with sin(θ) = 2×6×8/100 = 0.96",
      "Area of segment = (θ/360°) × πr² - (1/2) × r² × sin(θ)",
      "Area ≈ 92.76 - 48 ≈ 44.76 cm²"
    ],
    "finalAnswer": "≈ 44.76 cm²",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 11.2"
  },
  {
    "id": "ARC2-008",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Combined Figures",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A square of side 10 cm is inscribed in a circle. Find the area between the circle and the square (use π = 3.14).",
    "options": [],
    "answer": "57 cm²",
    "solutionSteps": [
      "Diagonal of square = 10√2 cm",
      "Radius of circle = 5√2 cm",
      "Area of circle = π × (5√2)² = 3.14 × 50 = 157 cm²",
      "Area of square = 10² = 100 cm²",
      "Difference = 157 - 100 = 57 cm²"
    ],
    "finalAnswer": "57 cm²",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 11.3"
  },
  {
    "id": "ARC2-009",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Sector Area",
    "section": "B",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Assertion (A): If two sectors of different circles have the same central angle, they will have equal areas.\nReason (R): The area of a sector is given by (θ/360°) × πr², and depends on both the angle and the radius.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "A is false, R is true.",
    "solutionSteps": [
      "Assertion: Two sectors with same angle but different radii will NOT have equal areas",
      "Area = (θ/360°) × πr², so area depends on both θ and r",
      "R is true: Area = (θ/360°) × πr², depends on both θ and r",
      "A is false because area also depends on radius",
      "Since A is false and R is true, answer is option 4"
    ],
    "finalAnswer": "A is false, R is true.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 11.1"
  },
  {
    "id": "ARC2-010",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Arc Length",
    "section": "C",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "If the arc length of a sector is 22 cm and radius is 21 cm, then the central angle is:",
    "options": [
      "A) 30°",
      "B) 45°",
      "C) 60°",
      "D) 90°"
    ],
    "answer": "C) 60°",
    "solutionSteps": [
      "Arc length = (θ/360°) × 2πr",
      "22 = (θ/360°) × 2 × (22/7) × 21",
      "22 = (θ/360°) × 132",
      "θ = (22 × 360°)/132 = 60°"
    ],
    "finalAnswer": "C) 60°",
    "isCompetencyBased": true,
    "pyqYear": "2021",
    "pyqSet": "Delhi",
    "ncertRef": "Ex 11.1"
  },
  {
    "id": "ARC2-011",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Segment Area",
    "section": "C",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Find the area of a segment of a circle with radius 5 cm, if the central angle of the sector is 90°. (Use π = 3.14)",
    "options": [],
    "answer": "7.125 cm²",
    "solutionSteps": [
      "Area of sector = (90°/360°) × π × 5² = (1/4) × 3.14 × 25 = 19.625 cm²",
      "Area of triangle = (1/2) × r² × sin(90°) = (1/2) × 25 × 1 = 12.5 cm²",
      "Area of segment = 19.625 - 12.5 = 7.125 cm²"
    ],
    "finalAnswer": "7.125 cm²",
    "isCompetencyBased": false,
    "pyqYear": "2020",
    "pyqSet": "All India",
    "ncertRef": "Ex 11.2"
  },
  {
    "id": "ARC2-012",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Combined Figures",
    "section": "E",
    "marks": 4,
    "format": "Case-Based",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "A circular pizza of radius 14 cm is cut into two equal parts by a diameter. Each half is then divided into sectors with central angle 60°. A child eats one such sector.\n(i) Find the area of the sector eaten by the child.\n(ii) Find the area of pizza remaining.",
    "options": [],
    "answer": "(i) 102.67 cm² (ii) 513.33 cm²",
    "solutionSteps": [
      "(i) Area of sector with θ = 60°, r = 14 cm:",
      "Area = (60°/360°) × π × 14² = (1/6) × (22/7) × 196",
      "= (1/6) × 22 × 28 = 616/6 ≈ 102.67 cm²",
      "(ii) Total area of pizza = π × 14² = (22/7) × 196 = 616 cm²",
      "Remaining area = 616 - 102.67 = 513.33 cm²"
    ],
    "finalAnswer": "(i) 102.67 cm² (ii) 513.33 cm²",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 11.1, Ex 11.3"
  },
  {
    "id": "ARC2-013",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Combined Figures",
    "section": "E",
    "marks": 4,
    "format": "Case-Based",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "A park has a circular garden of radius 7 m. A path of width 1 m is constructed along the boundary of the garden inside it. Find:\n(i) The area of the path.\n(ii) The area of the inner circular region.",
    "options": [],
    "answer": "(i) ≈40.86 m² (ii) ≈113.14 m²",
    "solutionSteps": [
      "(i) Outer radius = 7 m, Inner radius = 6 m",
      "Area of path = π(R² - r²) = (22/7)(49 - 36)",
      "= (22/7) × 13 = 286/7 ≈ 40.86 m²",
      "(ii) Area of inner circle = π × 6² = (22/7) × 36",
      "= 792/7 ≈ 113.14 m²"
    ],
    "finalAnswer": "(i) ≈40.86 m² (ii) ≈113.14 m²",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": "CBSE",
    "ncertRef": "Ex 11.3"
  },
  {
    "id": "ARC2-014",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Sector Area",
    "section": "C",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Assertion (A): The area of a sector is directly proportional to its central angle.\nReason (R): Area of sector = (θ/360°) × πr², showing area increases with θ at constant r.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "Assertion: When radius is constant, area ∝ θ (central angle)",
      "From formula Area = (θ/360°) × πr², with r constant, Area ∝ θ",
      "Reason: Correctly states the formula showing this proportionality",
      "R is the correct mathematical explanation of A"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 11.1"
  },
  {
    "id": "ARC2-015",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Arc Length",
    "section": "C",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A wheel of radius 35 cm makes 50 complete revolutions. Find the distance covered (use π = 22/7).",
    "options": [],
    "answer": "11000 cm or 110 m",
    "solutionSteps": [
      "In one revolution, distance covered = circumference of wheel",
      "Circumference = 2πr = 2 × (22/7) × 35 = 220 cm",
      "In 50 revolutions, distance = 220 × 50 = 11000 cm = 110 m"
    ],
    "finalAnswer": "11000 cm or 110 m",
    "isCompetencyBased": true,
    "pyqYear": "2022",
    "pyqSet": "All India",
    "ncertRef": "Ex 11.1"
  },
  {
    "id": "ARC2-016",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Combined Figures",
    "section": "D",
    "marks": 3,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "A circle of radius 8 cm is divided into 4 equal sectors. Two opposite sectors are painted red. Find the total area of red painted region.",
    "options": [],
    "answer": "32π cm² or 100.48 cm²",
    "solutionSteps": [
      "Each sector has central angle = 360°/4 = 90°",
      "Two opposite sectors means total angle = 90° + 90° = 180°",
      "Area of two sectors = (180°/360°) × π × 8²",
      "= (1/2) × π × 64 = 32π ≈ 100.48 cm²"
    ],
    "finalAnswer": "32π cm² or 100.48 cm²",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 11.1, Ex 11.3"
  },
  {
    "id": "ARC2-017",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Segment Area",
    "section": "D",
    "marks": 3,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Applying",
    "questionText": "In a circle of radius 13 cm, a chord of length 10 cm is drawn. Find the area of the smaller segment.",
    "options": [],
    "answer": "≈ 21.4 cm²",
    "solutionSteps": [
      "Using chord length formula: 2r sin(θ/2) = 10",
      "2(13) sin(θ/2) = 10, so sin(θ/2) = 5/13",
      "θ/2 ≈ 22.62°, so θ ≈ 45.24°",
      "cos(θ/2) = 12/13",
      "Area of segment = r²[θ(π/360°) - sin(θ)/2]",
      "= 169[45.24(π/360) - sin(45.24°)/2] ≈ 21.4 cm²"
    ],
    "finalAnswer": "≈ 21.4 cm²",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 11.2"
  },
  {
    "id": "ARC2-018",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Combined Figures",
    "section": "D",
    "marks": 5,
    "format": "Long",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "A rectangular plot of dimensions 20 m × 15 m has two semi-circular gardens at the ends of its length. Find the total area of the plot including the gardens. Also find the perimeter of the entire figure. (Use π = 3.14)",
    "options": [],
    "answer": "Area = 476.63 m²; Perimeter = 87.1 m",
    "solutionSteps": [
      "Rectangular plot area = 20 × 15 = 300 m²",
      "Two semi-circular gardens: diameter = 15 m, radius = 7.5 m",
      "Area of each semicircle = (1/2)πr² = (1/2) × 3.14 × 56.25 = 88.31 m²",
      "Area of two semicircles = 2 × 88.31 = 176.63 m² (equals one full circle)",
      "Two semicircles = πr² = 3.14 × 56.25 = 176.63 m²",
      "Total area = 300 + 176.63 = 476.63 m²",
      "Perimeter: Two lengths (20×2) + One length as semicircles circumference + One breadth",
      "= 20 + 20 + 30 + πd/2 + πd/2 = 70 + πd",
      "= 20 + 20 + πd = 40 + 3.14 × 15 = 40 + 47.1 = 87.1 m"
    ],
    "finalAnswer": "Area = 476.63 m²; Perimeter = 87.1 m",
    "isCompetencyBased": true,
    "pyqYear": "2024",
    "pyqSet": "All India",
    "ncertRef": "Ex 11.3"
  },
  {
    "id": "ARC2-019",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Sector Area",
    "section": "D",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Two sectors of the same circle have central angles in the ratio 3:5. If the area of the larger sector is 60 cm², then the area of the smaller sector is:",
    "options": [
      "A) 30 cm²",
      "B) 36 cm²",
      "C) 45 cm²",
      "D) 50 cm²"
    ],
    "answer": "B) 36 cm²",
    "solutionSteps": [
      "For sectors of same circle: Area ∝ Central angle",
      "Let angles be 3x and 5x",
      "Area₁/Area₂ = 3x/5x = 3/5",
      "Area₁/60 = 3/5",
      "Area₁ = (3/5) × 60 = 36 cm²"
    ],
    "finalAnswer": "B) 36 cm²",
    "isCompetencyBased": true,
    "pyqYear": "2019",
    "pyqSet": "Delhi",
    "ncertRef": "Ex 11.1"
  },
  {
    "id": "ARC2-020",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Arc Length",
    "section": "D",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Assertion (A): If two arcs have the same length, they belong to circles of the same radius.\nReason (R): Arc length is given by (θ/360°) × 2πr, so it depends on both the radius and the central angle.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "A is false, R is true.",
    "solutionSteps": [
      "R is true: Arc length = (θ/360°) × 2πr depends on both θ and r",
      "Two arcs with same length can have different r and θ combinations",
      "For example: r₁=10, θ₁=90° and r₂=5, θ₂=180° can give same arc length",
      "Assertion A is false: same arc length doesn't require same radius",
      "Since A is false and R is true, the answer is option (4)"
    ],
    "finalAnswer": "A is false, R is true.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 11.1"
  },
  {
    "id": "ARC2-021",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Combined Figures",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "A chord AB of length 24 cm is drawn in a circle of radius 13 cm. Find the distance of the chord from the center, and hence find the area of the segment.",
    "options": [],
    "answer": "Distance = 5 cm; Area ≈ 34.95 cm²",
    "solutionSteps": [
      "Using perpendicular from center: d² + (24/2)² = 13²",
      "d² + 144 = 169, so d = 5 cm",
      "Finding central angle: sin(θ/2) = 12/13",
      "θ/2 ≈ 67.38°, so θ ≈ 134.76°",
      "Area of segment = (θ/360°) × πr² - (1/2) × r² × sin(θ)",
      "= (134.76/360) × π × 169 - (1/2) × 169 × sin(134.76°)",
      "≈ 315.8 - 60.84 ≈ 254.96 - 220 ≈ 34.95 cm²"
    ],
    "finalAnswer": "Distance = 5 cm; Area ≈ 34.95 cm²",
    "isCompetencyBased": true,
    "pyqYear": "2025",
    "pyqSet": "All India",
    "ncertRef": "Ex 11.2"
  },
  {
    "id": "ARC2-022",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Combined Figures",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "The difference between the area of a circle and the area of its largest inscribed square is (use π = 22/7):",
    "options": [
      "A) (π - 2)r²",
      "B) (π/2 - 1)r²",
      "C) (π - 2)d²/8",
      "D) (11/7 - 1)r²"
    ],
    "answer": "A) (π - 2)r²",
    "solutionSteps": [
      "For largest inscribed square in circle of radius r: diagonal = 2r",
      "Side of square = 2r/√2 = r√2",
      "Area of square = (r√2)² = 2r²",
      "Area of circle = πr²",
      "Difference = πr² - 2r² = (π - 2)r²"
    ],
    "finalAnswer": "A) (π - 2)r²",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 11.3"
  },
  {
    "id": "ARC2-023",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Sector Area",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "A sector of angle θ is cut from a circle of radius 12 cm. If the ratio of arc length to the perimeter of the sector is 2:5, find θ and the area of the sector.",
    "options": [],
    "answer": "θ ≈ 76.4°; Area ≈ 95.9 cm²",
    "solutionSteps": [
      "Arc length = (θ/360°) × 2πr = (θ/360°) × 24π",
      "Perimeter of sector = Arc + 2r = (θ/360°) × 24π + 24",
      "Given: Arc/Perimeter = 2/5",
      "5 × Arc = 2 × (Arc + 24), so 3 × Arc = 48, Arc = 16 cm",
      "(θ/360°) × 24π = 16, so θ = (16 × 360)/(24π) = 240/π",
      "Using π = 22/7: θ = 240 × 7/22 = 1680/22 ≈ 76.4°",
      "Area = (θ/360°) × πr² = (76.4/360) × 3.14 × 144 ≈ 95.9 cm²"
    ],
    "finalAnswer": "θ ≈ 76.4°; Area ≈ 95.9 cm²",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 11.1"
  },
  {
    "id": "ARC2-024",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Sector Area",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "The area of a sector of a circle with radius 7 cm and central angle 60° is:",
    "options": [
      "25.67 cm²",
      "51.33 cm²",
      "77 cm²",
      "154 cm²"
    ],
    "answer": "25.67 cm²",
    "solutionSteps": [
      "Area of sector = (θ/360°) × πr²",
      "= (60°/360°) × π × 7²",
      "= (1/6) × 22/7 × 49",
      "= 25.67 cm²"
    ],
    "finalAnswer": "25.67 cm²",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 11.1"
  },
  {
    "id": "ARC2-025",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Arc Length",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "The length of an arc of a circle with radius 10 cm and central angle 90° is:",
    "options": [
      "15.71 cm",
      "20.94 cm",
      "31.42 cm",
      "62.84 cm"
    ],
    "answer": "15.71 cm",
    "solutionSteps": [
      "Arc length = (θ/360°) × 2πr",
      "= (90°/360°) × 2 × 22/7 × 10",
      "= (1/4) × 2 × 22/7 × 10",
      "= 15.71 cm"
    ],
    "finalAnswer": "15.71 cm",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 11.1"
  },
  {
    "id": "ARC2-026",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Sector Area",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "If the radius of a circle is 14 cm and the area of a sector is 102.67 cm², then the central angle is:",
    "options": [
      "30°",
      "45°",
      "60°",
      "90°"
    ],
    "answer": "60°",
    "solutionSteps": [
      "Area of sector = (θ/360°) × πr²",
      "102.67 = (θ/360°) × 22/7 × 196",
      "102.67 = (θ/360°) × 616",
      "θ = 60°"
    ],
    "finalAnswer": "60°",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 11.1"
  },
  {
    "id": "ARC2-027",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Segment Area",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "The area of a segment of a circle is the difference between the areas of:",
    "options": [
      "Arc and radius",
      "Sector and triangle",
      "Circle and sector",
      "Chord and radius"
    ],
    "answer": "Sector and triangle",
    "solutionSteps": [
      "Area of segment = Area of sector - Area of triangle",
      "This is the standard formula for segment area"
    ],
    "finalAnswer": "Sector and triangle",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 11.2"
  },
  {
    "id": "ARC2-028",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Segment Area",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Find the area of a segment of a circle with radius 12 cm and central angle 90°.",
    "options": [],
    "answer": "41.14 cm²",
    "solutionSteps": [
      "Area of sector = (90°/360°) × π × 12²",
      "= (1/4) × 22/7 × 144 = 113.14 cm²",
      "Area of triangle = (1/2) × 12 × 12 × sin(90°) = 72 cm²",
      "Area of segment = 113.14 - 72 = 41.14 cm²"
    ],
    "finalAnswer": "41.14 cm²",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 11.2"
  },
  {
    "id": "ARC2-029",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Arc Length",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "If the arc length of a sector is 22 cm and radius is 7 cm, find the central angle.",
    "options": [],
    "answer": "180°",
    "solutionSteps": [
      "Arc length = (θ/360°) × 2πr",
      "22 = (θ/360°) × 2 × 22/7 × 7",
      "22 = (θ/360°) × 44",
      "θ = 180°"
    ],
    "finalAnswer": "180°",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 11.1"
  },
  {
    "id": "ARC2-030",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Combined Figures",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A square of side 10 cm has a circle inscribed in it. Find the area enclosed between the square and circle.",
    "options": [],
    "answer": "21.5 cm²",
    "solutionSteps": [
      "Area of square = 10² = 100 cm²",
      "Radius of inscribed circle = 5 cm",
      "Area of circle = π × 5² = 78.5 cm²",
      "Area enclosed = 100 - 78.5 = 21.5 cm²"
    ],
    "finalAnswer": "21.5 cm²",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 11.3"
  },
  {
    "id": "ARC2-031",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Sector Area",
    "section": "B",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Assertion (A): The area of a sector with angle 180° and radius 7 cm is 77 cm². Reason (R): Area of sector = (θ/360°) × πr².",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "Area = (180°/360°) × 22/7 × 49",
      "= (1/2) × 22/7 × 49 = 77 cm²",
      "A is true and R is the correct formula"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 11.1"
  },
  {
    "id": "ARC2-032",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Arc Length",
    "section": "B",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Assertion (A): Arc length is directly proportional to the central angle. Reason (R): Arc length = (θ/360°) × 2πr.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "From formula: Arc length = (θ/360°) × 2πr",
      "As θ increases, arc length increases proportionally",
      "Both statements are true and related"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 11.1"
  },
  {
    "id": "ARC2-033",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Segment Area",
    "section": "B",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Analysing",
    "questionText": "Assertion (A): For a semicircle, the area of segment equals the area of the semicircle. Reason (R): A semicircle has no triangular portion to subtract from the sector.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "For semicircle: sector area = (1/2)πr²",
      "Triangle formed by diameter has 180° angle, so no height",
      "Segment area = sector area = (1/2)πr²"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 11.2"
  },
  {
    "id": "ARC2-034",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Sector Area",
    "section": "C",
    "marks": 2,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "A clock has radius 10 cm. The area swept by the minute hand in 15 minutes is:",
    "options": [
      "78.5 cm²",
      "157 cm²",
      "50 cm²",
      "314 cm²"
    ],
    "answer": "78.5 cm²",
    "solutionSteps": [
      "Minute hand moves 360° in 60 minutes",
      "In 15 minutes, it moves (15/60) × 360° = 90°",
      "Area = (90°/360°) × πr² = (1/4) × π × 100",
      "= 78.5 cm²"
    ],
    "finalAnswer": "78.5 cm²",
    "isCompetencyBased": true,
    "pyqYear": "2021",
    "pyqSet": "Set 1",
    "ncertRef": "Ex 11.1"
  },
  {
    "id": "ARC2-035",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Combined Figures",
    "section": "E",
    "marks": 4,
    "format": "Case-Based",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "A park is designed in the shape of a circle with radius 21 m. A straight path divides the circle into two equal parts. On one side of the path, there is a square garden of side 14 m inscribed in the semicircle.\n\nQuestion 1: Find the area of the semicircle.\nQuestion 2: Find the area of the square garden.\nQuestion 3: Find the area available for landscaping on that side of the path.\nQuestion 4: If the other semicircle is divided into 4 equal sectors, find the area of one sector.",
    "options": [],
    "answer": "Q1: 693 m² | Q2: 196 m² | Q3: 497 m² | Q4: 346.5 m²",
    "solutionSteps": [
      "Q1: Area of semicircle = (1/2)πr² = (1/2) × 22/7 × 21² = 693 m²",
      "Q2: Area of square = 14² = 196 m²",
      "Q3: Landscaping area = 693 - 196 = 497 m²",
      "Q4: One sector of semicircle = (1/4) × 693 = 346.5 m²"
    ],
    "finalAnswer": "Q1: 693 m² | Q2: 196 m² | Q3: 497 m² | Q4: 346.5 m²",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 11.3"
  },
  {
    "id": "ARC2-036",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Sector Area",
    "section": "C",
    "marks": 2,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Applying",
    "questionText": "Two sectors of a circle have the same radius but different central angles of 60° and 120°. The ratio of their areas is:",
    "options": [
      "1:2",
      "2:1",
      "1:4",
      "3:1"
    ],
    "answer": "1:2",
    "solutionSteps": [
      "Area of sector 1 = (60°/360°) × πr²",
      "Area of sector 2 = (120°/360°) × πr²",
      "Ratio = (60°/360°)/(120°/360°) = 60°/120° = 1:2"
    ],
    "finalAnswer": "1:2",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": "Set 2",
    "ncertRef": "Ex 11.1"
  },
  {
    "id": "ARC2-037",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Segment Area",
    "section": "C",
    "marks": 5,
    "format": "Long",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "A circular disc of radius 10 cm has a segment cut off by a chord at a distance of 6 cm from the center. Calculate: (i) The central angle subtended by the chord, (ii) The area of the segment, (iii) The length of the arc.",
    "options": [],
    "answer": "(i) θ ≈ 106.26° (ii) Segment area ≈ 44.73 cm² (iii) Arc length ≈ 18.55 cm",
    "solutionSteps": [
      "Given: radius = 10 cm, distance from center = 6 cm",
      "(i) Using cos(θ/2) = 6/10 = 0.6, θ/2 = 53.13°, θ ≈ 106.26°",
      "Area of sector = (106.26°/360°) × π × 100 = 92.73 cm²",
      "Area of triangle = (1/2) × base × height",
      "Base = 2√(10²-6²) = 16 cm, height = 6 cm",
      "Area of triangle = (1/2) × 16 × 6 = 48 cm²",
      "(ii) Area of segment = 92.73 - 48 = 44.73 cm²",
      "(iii) Arc length = (106.26°/360°) × 2π × 10 = 18.55 cm"
    ],
    "finalAnswer": "(i) θ ≈ 106.26° (ii) Segment area ≈ 44.73 cm² (iii) Arc length ≈ 18.55 cm",
    "isCompetencyBased": true,
    "pyqYear": "2024",
    "pyqSet": "Set 3",
    "ncertRef": "Ex 11.2"
  },
  {
    "id": "ARC2-038",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Combined Figures",
    "section": "C",
    "marks": 5,
    "format": "Long",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "A square of side 20 cm has semicircles drawn on each of its four sides (externally). Calculate: (i) The total area covered by the figure, (ii) The perimeter of the entire figure, (iii) The area of overlap if semicircles were drawn internally instead.",
    "options": [],
    "answer": "(i) 1028.57 cm² (ii) 125.71 cm (iii) 228.57 cm²",
    "solutionSteps": [
      "(i) Area of square = 400 cm²",
      "Area of 4 semicircles = 4 × (1/2) × π × 10² = 628.57 cm²",
      "Total area = 400 + 628.57 = 1028.57 cm²",
      "(ii) Perimeter = 4 semicircles = 4 × π × 10 = 125.71 cm",
      "(iii) If internal: overlap area = 628.57 - 400 = 228.57 cm²"
    ],
    "finalAnswer": "(i) 1028.57 cm² (ii) 125.71 cm (iii) 228.57 cm²",
    "isCompetencyBased": true,
    "pyqYear": "2022",
    "pyqSet": "Set 1",
    "ncertRef": "Ex 11.3"
  },
  {
    "id": "ARC2-039",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Arc Length",
    "section": "C",
    "marks": 2,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "A wheel of radius 0.5 m completes 10 revolutions. The distance traveled is:",
    "options": [
      "3.14 m",
      "31.4 m",
      "314 m",
      "3140 m"
    ],
    "answer": "31.4 m",
    "solutionSteps": [
      "Circumference = 2πr = 2 × 22/7 × 0.5",
      "= 3.14 m (approximately π)",
      "Distance in 10 revolutions = 10 × 3.14 = 31.4 m"
    ],
    "finalAnswer": "31.4 m",
    "isCompetencyBased": true,
    "pyqYear": "2025",
    "pyqSet": "Set 2",
    "ncertRef": "Ex 11.1"
  },
  {
    "id": "ARC2-040",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Sector Area",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "The formula for the area of a sector is:",
    "options": [
      "θ × πr²",
      "(θ/180°) × πr²",
      "(θ/360°) × πr²",
      "(θ/90°) × πr²"
    ],
    "answer": "(θ/360°) × πr²",
    "solutionSteps": [
      "Area of a full circle = πr²",
      "Full angle = 360°",
      "So area of sector with angle θ = (θ/360°) × πr²"
    ],
    "finalAnswer": "(θ/360°) × πr²",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 11.1"
  },
  {
    "id": "ARC2-041",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Combined Figures",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A circle of radius 5 cm is inscribed in a square. Find the area of the region outside the circle but inside the square.",
    "options": [],
    "answer": "21.5 cm²",
    "solutionSteps": [
      "Side of square = 2r = 10 cm",
      "Area of square = 100 cm²",
      "Area of circle = πr² = 78.5 cm²",
      "Required area = 100 - 78.5 = 21.5 cm²"
    ],
    "finalAnswer": "21.5 cm²",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 11.3"
  },
  {
    "id": "ARC2-042",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Segment Area",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Find the area of a segment cut off by a chord in a circle of radius 8 cm, if the chord subtends an angle of 90° at the center.",
    "options": [],
    "answer": "18.29 cm²",
    "solutionSteps": [
      "Area of sector = (90°/360°) × π × 8² = 50.29 cm²",
      "Area of right triangle = (1/2) × 8 × 8 = 32 cm²",
      "Area of segment = 50.29 - 32 = 18.29 cm²"
    ],
    "finalAnswer": "18.29 cm²",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 11.2"
  },
  {
    "id": "ARC2-043",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Arc Length",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "An arc of a circle subtending an angle of 120° at the center has length 22 cm. The radius of the circle is:",
    "options": [
      "10.5 cm",
      "21 cm",
      "42 cm",
      "5.25 cm"
    ],
    "answer": "10.5 cm",
    "solutionSteps": [
      "Arc length = (θ/360°) × 2πr",
      "22 = (120°/360°) × 2 × 22/7 × r",
      "22 = (1/3) × 44r/7",
      "r = 10.5 cm"
    ],
    "finalAnswer": "10.5 cm",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 11.1"
  },
  {
    "id": "ARC2-044",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Combined Figures",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Analysing",
    "questionText": "Two concentric circles have radii 7 cm and 14 cm. Find the area of the ring (annulus) between them.",
    "options": [],
    "answer": "462 cm²",
    "solutionSteps": [
      "Area of outer circle = π × 14² = 615.44 cm²",
      "Area of inner circle = π × 7² = 153.86 cm²",
      "Area of ring = 615.44 - 153.86 = 461.58 ≈ 462 cm²"
    ],
    "finalAnswer": "462 cm²",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 11.3"
  },
  {
    "id": "ARC2-045",
    "subject": "Maths",
    "topicKey": "Areas Related to Circles",
    "subtopic": "Sector Area",
    "section": "B",
    "marks": 2,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A sector of a circle has area 154 cm² and central angle 60°. The radius of the circle is:",
    "options": [
      "7 cm",
      "14 cm",
      "21 cm",
      "28 cm"
    ],
    "answer": "21 cm",
    "solutionSteps": [
      "Area of sector = (θ/360°) × πr²",
      "154 = (60°/360°) × 22/7 × r²",
      "154 = (1/6) × 22r²/7",
      "r² = 441",
      "r = 21 cm"
    ],
    "finalAnswer": "21 cm",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 11.1"
  }
];
