import type { CanonicalQuestion } from "../../types";

export const PL2_PACK2: CanonicalQuestion[] = [
  {
    "id": "PL2-001",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Zeroes of Polynomial",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "If p(x) = x² - 5x + 6, then the zeroes of p(x) are:",
    "options": [
      "2, 3",
      "1, 6",
      "-2, -3",
      "2, -3"
    ],
    "answer": "2, 3",
    "solutionSteps": [
      "Factorize: x² - 5x + 6 = (x-2)(x-3)",
      "Setting each factor to zero: x = 2 or x = 3"
    ],
    "finalAnswer": "2, 3",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 2.1"
  },
  {
    "id": "PL2-002",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Zeroes of Polynomial",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "A polynomial with zeroes 1 and -2 is:",
    "options": [
      "x² + x - 2",
      "x² - x + 2",
      "x² - x - 2",
      "x² + 2x - 1"
    ],
    "answer": "x² + x - 2",
    "solutionSteps": [
      "Polynomial = (x-1)(x+2) = x² + 2x - x - 2 = x² + x - 2"
    ],
    "finalAnswer": "x² + x - 2",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 2.1"
  },
  {
    "id": "PL2-003",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Zeroes of Polynomial",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "The number of zeroes of the polynomial p(x) = x³ - 1 is:",
    "options": [
      "1",
      "2",
      "3",
      "0"
    ],
    "answer": "3",
    "solutionSteps": [
      "A cubic polynomial has at most 3 zeroes",
      "x³ - 1 = (x-1)(x² + x + 1), which gives 3 zeroes (one real, two complex)"
    ],
    "finalAnswer": "3",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 2.1"
  },
  {
    "id": "PL2-004",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Relationship between Zeroes and Coefficients",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "If α and β are zeroes of x² - 7x + 12, then α + β =",
    "options": [
      "7",
      "-7",
      "12",
      "-12"
    ],
    "answer": "7",
    "solutionSteps": [
      "For quadratic ax² + bx + c, sum of zeroes = -b/a",
      "Here: α + β = -(-7)/1 = 7"
    ],
    "finalAnswer": "7",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 2.2"
  },
  {
    "id": "PL2-005",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Relationship between Zeroes and Coefficients",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "If α and β are zeroes of 2x² - 3x + 1, then αβ =",
    "options": [
      "1/2",
      "3/2",
      "-3/2",
      "-1/2"
    ],
    "answer": "1/2",
    "solutionSteps": [
      "For quadratic ax² + bx + c, product of zeroes = c/a",
      "Here: αβ = 1/2"
    ],
    "finalAnswer": "1/2",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 2.2"
  },
  {
    "id": "PL2-006",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Division Algorithm",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "The division algorithm for polynomials states: Dividend = Divisor × Quotient + ___",
    "options": [
      "Remainder",
      "Product",
      "Divisor",
      "Coefficient"
    ],
    "answer": "Remainder",
    "solutionSteps": [
      "Division algorithm: f(x) = g(x) × q(x) + r(x)",
      "where r(x) is the remainder"
    ],
    "finalAnswer": "Remainder",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 2.3"
  },
  {
    "id": "PL2-007",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Zeroes of Polynomial",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Find the zeroes of the polynomial p(x) = x² - 2x - 8 and verify the relationship between zeroes and coefficients.",
    "options": [],
    "answer": "Zeroes are 4 and -2",
    "solutionSteps": [
      "Factorize: x² - 2x - 8 = (x-4)(x+2)",
      "Zeroes: x = 4, x = -2",
      "Sum of zeroes: 4 + (-2) = 2 = -b/a",
      "Product of zeroes: 4 × (-2) = -8 = c/a"
    ],
    "finalAnswer": "Zeroes are 4 and -2",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 2.1, Ex 2.2"
  },
  {
    "id": "PL2-008",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Relationship between Zeroes and Coefficients",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "If one zero of the polynomial 3x² + 8x + k is 1, find the value of k and the other zero.",
    "options": [],
    "answer": "k = -11, other zero = -11/3",
    "solutionSteps": [
      "If x = 1 is a zero: 3(1)² + 8(1) + k = 0",
      "3 + 8 + k = 0, so k = -11",
      "Product of zeroes = c/a = -11/3",
      "If one zero is 1, other zero = -11/3"
    ],
    "finalAnswer": "k = -11, other zero = -11/3",
    "isCompetencyBased": true,
    "pyqYear": "2021",
    "pyqSet": undefined,
    "ncertRef": "Ex 2.2"
  },
  {
    "id": "PL2-009",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Division Algorithm",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Divide x² + 3x + 2 by x + 1 and write the result in the form p(x) = g(x) × q(x) + r(x).",
    "options": [],
    "answer": "x² + 3x + 2 = (x + 1)(x + 2) + 0",
    "solutionSteps": [
      "Using polynomial division or factorization: x² + 3x + 2 = (x+1)(x+2)",
      "Quotient = x + 2, Remainder = 0",
      "In the form: (x + 1)(x + 2) + 0"
    ],
    "finalAnswer": "x² + 3x + 2 = (x + 1)(x + 2) + 0",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 2.3"
  },
  {
    "id": "PL2-010",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Zeroes of Polynomial",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Check whether x = -1 is a zero of the polynomial p(x) = x³ - 5x² + 7x - 3.",
    "options": [],
    "answer": "No, x = -1 is not a zero",
    "solutionSteps": [
      "p(-1) = (-1)³ - 5(-1)² + 7(-1) - 3",
      "= -1 - 5 - 7 - 3 = -16 ≠ 0",
      "So x = -1 is NOT a zero"
    ],
    "finalAnswer": "No, x = -1 is not a zero",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 2.1"
  },
  {
    "id": "PL2-011",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Relationship between Zeroes and Coefficients",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Form a quadratic polynomial whose zeroes are 3 and 5.",
    "options": [],
    "answer": "x² - 8x + 15",
    "solutionSteps": [
      "Polynomial = (x - 3)(x - 5)",
      "= x² - 5x - 3x + 15",
      "= x² - 8x + 15"
    ],
    "finalAnswer": "x² - 8x + 15",
    "isCompetencyBased": true,
    "pyqYear": "2020",
    "pyqSet": undefined,
    "ncertRef": "Ex 2.2"
  },
  {
    "id": "PL2-012",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Zeroes of Polynomial",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Find all zeroes of the polynomial p(x) = (x - 1)(x + 2)(x - 3).",
    "options": [],
    "answer": "x = 1, -2, 3",
    "solutionSteps": [
      "Setting p(x) = 0: (x - 1)(x + 2)(x - 3) = 0",
      "Either x - 1 = 0 or x + 2 = 0 or x - 3 = 0",
      "Zeroes: x = 1, x = -2, x = 3"
    ],
    "finalAnswer": "x = 1, -2, 3",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 2.1"
  },
  {
    "id": "PL2-013",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Division Algorithm",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Use the remainder theorem to find the remainder when p(x) = x³ + 1 is divided by x + 1.",
    "options": [],
    "answer": "Remainder = 0",
    "solutionSteps": [
      "By remainder theorem: remainder = p(-1)",
      "p(-1) = (-1)³ + 1 = -1 + 1 = 0"
    ],
    "finalAnswer": "Remainder = 0",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 2.3"
  },
  {
    "id": "PL2-014",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Relationship between Zeroes and Coefficients",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "If α and β are zeroes of x² + px + q, express (α - β)² in terms of p and q.",
    "options": [],
    "answer": "(α - β)² = p² - 4q",
    "solutionSteps": [
      "α + β = -p, αβ = q",
      "(α - β)² = (α + β)² - 4αβ",
      "= (-p)² - 4q = p² - 4q"
    ],
    "finalAnswer": "(α - β)² = p² - 4q",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 2.2"
  },
  {
    "id": "PL2-015",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Zeroes of Polynomial",
    "section": "C",
    "marks": 2,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "If the polynomial p(x) = x³ - 6x² + 11x - 6 has zeroes α, β, γ, then α + β + γ =",
    "options": [
      "6",
      "-6",
      "11",
      "-11"
    ],
    "answer": "6",
    "solutionSteps": [
      "For cubic ax³ + bx² + cx + d, sum of zeroes = -b/a",
      "Here: α + β + γ = -(-6)/1 = 6"
    ],
    "finalAnswer": "6",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 2.2"
  },
  {
    "id": "PL2-016",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Relationship between Zeroes and Coefficients",
    "section": "C",
    "marks": 2,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "If p(x) = ax² + bx + c and both zeroes are equal, then b² =",
    "options": [
      "4ac",
      "-4ac",
      "ac",
      "2ac"
    ],
    "answer": "4ac",
    "solutionSteps": [
      "For equal zeroes, discriminant = 0",
      "b² - 4ac = 0",
      "Therefore, b² = 4ac"
    ],
    "finalAnswer": "4ac",
    "isCompetencyBased": true,
    "pyqYear": "2022",
    "pyqSet": undefined,
    "ncertRef": "Ex 2.2"
  },
  {
    "id": "PL2-017",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Division Algorithm",
    "section": "C",
    "marks": 2,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "When p(x) = 2x³ + x² - 5x - 2 is divided by g(x), quotient is 2x - 3 and remainder is 4. Then g(x) =",
    "options": [
      "x² + 2x + 1",
      "x² + 2x - 1",
      "x² - 2x + 1",
      "x² - 2x - 1"
    ],
    "answer": "x² + 2x + 1",
    "solutionSteps": [
      "Using p(x) = g(x) × q(x) + r(x)",
      "2x³ + x² - 5x - 2 = g(x)(2x - 3) + 4",
      "2x³ + x² - 5x - 6 = g(x)(2x - 3)",
      "Dividing: g(x) = x² + 2x + 1"
    ],
    "finalAnswer": "x² + 2x + 1",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 2.3"
  },
  {
    "id": "PL2-018",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Zeroes of Polynomial",
    "section": "C",
    "marks": 3,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "If α, β, γ are zeroes of p(x) = x³ - 3x² + x + 1, find α + β + γ, αβ + βγ + γα, and αβγ.",
    "options": [],
    "answer": "Sum = 3, Sum of pairs = 1, Product = -1",
    "solutionSteps": [
      "For cubic x³ + ax² + bx + c:",
      "Sum of zeroes = -a = -(-3) = 3",
      "Sum of products of pairs = b = 1",
      "Product of zeroes = -c = -(1) = -1"
    ],
    "finalAnswer": "Sum = 3, Sum of pairs = 1, Product = -1",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 2.2"
  },
  {
    "id": "PL2-019",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Division Algorithm",
    "section": "C",
    "marks": 3,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Applying",
    "questionText": "Divide 3x³ - x² + 5x - 5 by x - 1 and verify using the remainder theorem.",
    "options": [],
    "answer": "Quotient = 3x² + 2x + 7, Remainder = 2",
    "solutionSteps": [
      "Using polynomial long division",
      "3x³ - x² + 5x - 5 = (x - 1)(3x² + 2x + 7) + 2",
      "Verification: p(1) = 3(1)³ - (1)² + 5(1) - 5 = 3 - 1 + 5 - 5 = 2 ✓"
    ],
    "finalAnswer": "Quotient = 3x² + 2x + 7, Remainder = 2",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": undefined,
    "ncertRef": "Ex 2.3"
  },
  {
    "id": "PL2-020",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Relationship between Zeroes and Coefficients",
    "section": "C",
    "marks": 3,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "If α and β are zeroes of 2x² - 6x + 3, find 1/α + 1/β and α² + β².",
    "options": [],
    "answer": "1/α + 1/β = 2, α² + β² = 6",
    "solutionSteps": [
      "α + β = 6/2 = 3, αβ = 3/2",
      "1/α + 1/β = (α + β)/(αβ) = 3/(3/2) = 2",
      "α² + β² = (α + β)² - 2αβ = 9 - 2(3/2) = 9 - 3 = 6"
    ],
    "finalAnswer": "1/α + 1/β = 2, α² + β² = 6",
    "isCompetencyBased": true,
    "pyqYear": "2024",
    "pyqSet": undefined,
    "ncertRef": "Ex 2.2"
  },
  {
    "id": "PL2-021",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Zeroes of Polynomial",
    "section": "D",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Assertion (A): Every polynomial has at least one real zero. Reason (R): The fundamental theorem of algebra states that every polynomial of degree n ≥ 1 has exactly n roots (real or complex).",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "A is false, R is true.",
    "solutionSteps": [
      "A is false: A polynomial may not have real zeroes (e.g., x² + 1 has no real zeroes)",
      "R is true: By fundamental theorem, every polynomial of degree n has exactly n roots in complex numbers"
    ],
    "finalAnswer": "A is false, R is true.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 2.1"
  },
  {
    "id": "PL2-022",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Relationship between Zeroes and Coefficients",
    "section": "D",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Assertion (A): If α and β are zeroes of ax² + bx + c, then α + β = b/a. Reason (R): This relationship comes from the expansion (x - α)(x - β) = x² - (α + β)x + αβ.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "A is false, R is true.",
    "solutionSteps": [
      "A is false: The correct relation is α + β = -b/a, not b/a",
      "R is true: Expansion gives x² - (α + β)x + αβ = ax² + bx + c after dividing by a"
    ],
    "finalAnswer": "A is false, R is true.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 2.2"
  },
  {
    "id": "PL2-023",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Division Algorithm",
    "section": "D",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "Assertion (A): The remainder when p(x) is divided by (x - a) is p(a). Reason (R): This is the remainder theorem.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "A is true: Remainder theorem states remainder = p(a)",
      "R is true: This is indeed the remainder theorem",
      "R explains A correctly"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 2.3"
  },
  {
    "id": "PL2-024",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Zeroes of Polynomial",
    "section": "D",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Analysing",
    "questionText": "Assertion (A): The polynomial x² + 2x + 2 has two distinct real zeroes. Reason (R): The discriminant of x² + 2x + 2 is -4.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "A is false, R is true.",
    "solutionSteps": [
      "Discriminant = 4 - 8 = -4 < 0, so no real zeroes",
      "A is false: The polynomial has no real zeroes",
      "R is true: The discriminant is indeed -4"
    ],
    "finalAnswer": "A is false, R is true.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 2.1"
  },
  {
    "id": "PL2-025",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Relationship between Zeroes and Coefficients",
    "section": "D",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "Assertion (A): If the product of zeroes of x² - (k + 6)x + 2(2k - 1) is -1, then k = -3. Reason (R): Product of zeroes equals the constant term divided by the leading coefficient.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "A is false, R is true.",
    "solutionSteps": [
      "Product of zeroes = 2(2k - 1)/1 = -1",
      "4k - 2 = -1",
      "4k = 1, k = 1/4"
    ],
    "finalAnswer": "A is false, R is true.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 2.2"
  },
  {
    "id": "PL2-026",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Division Algorithm",
    "section": "D",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Assertion (A): If p(x) = g(x) × q(x) + r(x), then degree of r(x) < degree of g(x). Reason (R): This is the division algorithm for polynomials.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "A is true: In division algorithm, remainder degree < divisor degree",
      "R is true: This is the division algorithm statement",
      "R correctly explains A"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 2.3"
  },
  {
    "id": "PL2-027",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Zeroes of Polynomial",
    "section": "E",
    "marks": 4,
    "format": "Case-Based",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A gardener wants to plant flowers in a rectangular garden. The area of the garden is represented by the polynomial A(x) = x² + 5x + 6 square meters, where x is a variable. (i) Find the zeroes of A(x). (ii) If x represents the width, what do the zeroes represent in this context? (iii) For what values of x is the area positive?",
    "options": [],
    "answer": "Zeroes: -2, -3; Area positive for x > 0",
    "solutionSteps": [
      "(i) A(x) = x² + 5x + 6 = (x+2)(x+3), zeroes are -2 and -3",
      "(ii) Zeroes represent values where area = 0, not meaningful for physical width",
      "(iii) Area > 0 when x > -2 (since x must be positive for width, x > 0)"
    ],
    "finalAnswer": "Zeroes: -2, -3; Area positive for x > 0",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 2.1, Ex 2.2"
  },
  {
    "id": "PL2-028",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Relationship between Zeroes and Coefficients",
    "section": "E",
    "marks": 4,
    "format": "Case-Based",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A cricket ball's height h(t) above ground after t seconds is given by h(t) = -16t² + 64t. (i) Find the zeroes of h(t). (ii) What do these zeroes represent physically? (iii) Find the sum and product of zeroes without finding individual zeroes.",
    "options": [],
    "answer": "Zeroes: 0, 4; Sum = 4; Product = 0",
    "solutionSteps": [
      "(i) h(t) = -16t(t - 4) = 0, so t = 0 or t = 4",
      "(ii) t = 0: initial time, t = 4: ball returns to ground",
      "(iii) For -16t² + 64t: Sum = -64/-16 = 4, Product = 0/-16 = 0"
    ],
    "finalAnswer": "Zeroes: 0, 4; Sum = 4; Product = 0",
    "isCompetencyBased": true,
    "pyqYear": "2021",
    "pyqSet": undefined,
    "ncertRef": "Ex 2.1, Ex 2.2"
  },
  {
    "id": "PL2-029",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Division Algorithm",
    "section": "E",
    "marks": 4,
    "format": "Case-Based",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "A company's profit function is P(x) = x³ - 6x² + 11x - 6, where x is the number of units sold (in hundreds). (i) Show that x - 1, x - 2, and x - 3 are factors. (ii) Find the profit when x = 1, 2, 3. (iii) Write P(x) in factored form using the division algorithm.",
    "options": [],
    "answer": "P(x) = (x-1)(x-2)(x-3); Profit = 0 at break-even points",
    "solutionSteps": [
      "(i) P(1) = 1 - 6 + 11 - 6 = 0, P(2) = 8 - 24 + 22 - 6 = 0, P(3) = 27 - 54 + 33 - 6 = 0",
      "(ii) Profit at x = 1, 2, 3 is 0 (break-even points)",
      "(iii) P(x) = (x-1)(x-2)(x-3)"
    ],
    "finalAnswer": "P(x) = (x-1)(x-2)(x-3); Profit = 0 at break-even points",
    "isCompetencyBased": true,
    "pyqYear": "2022",
    "pyqSet": undefined,
    "ncertRef": "Ex 2.1, Ex 2.3"
  },
  {
    "id": "PL2-030",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Zeroes of Polynomial",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "How many zeroes does the polynomial p(x) = (x - 2)²(x + 1) have?",
    "options": [
      "1",
      "2",
      "3",
      "4"
    ],
    "answer": "3",
    "solutionSteps": [
      "The polynomial has factors (x-2) twice and (x+1) once",
      "Zeroes: x = 2 (multiplicity 2) and x = -1 (multiplicity 1)",
      "Total zeroes = 3"
    ],
    "finalAnswer": "3",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 2.1"
  },
  {
    "id": "PL2-031",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Relationship between Zeroes and Coefficients",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "If both zeroes of x² + bx + c are equal, then:",
    "options": [
      "b² = 4c",
      "b = 2c",
      "b² = -4c",
      "c² = b"
    ],
    "answer": "b² = 4c",
    "solutionSteps": [
      "For equal zeroes, discriminant = 0",
      "b² - 4c = 0",
      "b² = 4c"
    ],
    "finalAnswer": "b² = 4c",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 2.2"
  },
  {
    "id": "PL2-032",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Division Algorithm",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "If p(x) = x³ - 3x² + 4x - 2 is divided by (x - 1), find the remainder using the remainder theorem.",
    "options": [],
    "answer": "Remainder = 0",
    "solutionSteps": [
      "By remainder theorem: R = p(1)",
      "p(1) = 1 - 3 + 4 - 2 = 0"
    ],
    "finalAnswer": "Remainder = 0",
    "isCompetencyBased": true,
    "pyqYear": "2020",
    "pyqSet": undefined,
    "ncertRef": "Ex 2.3"
  },
  {
    "id": "PL2-033",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Zeroes of Polynomial",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "If x = 2 is a zero of p(x) = x³ - x² + ax + b and x = -1 is also a zero, find a and b.",
    "options": [],
    "answer": "a = -2, b = -6",
    "solutionSteps": [
      "p(2) = 0: 8 - 4 + 2a + b = 0 → 2a + b = -4",
      "p(-1) = 0: -1 - 1 - a + b = 0 → -a + b = 2",
      "Solving: a = -2, b = -6"
    ],
    "finalAnswer": "a = -2, b = -6",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 2.1"
  },
  {
    "id": "PL2-034",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Relationship between Zeroes and Coefficients",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "If α and β are zeroes of 3x² - 12x + 9, find α² + β² without finding α and β individually.",
    "options": [],
    "answer": "α² + β² = 10",
    "solutionSteps": [
      "α + β = 12/3 = 4, αβ = 9/3 = 3",
      "α² + β² = (α + β)² - 2αβ = 16 - 6 = 10"
    ],
    "finalAnswer": "α² + β² = 10",
    "isCompetencyBased": true,
    "pyqYear": "2019",
    "pyqSet": undefined,
    "ncertRef": "Ex 2.2"
  },
  {
    "id": "PL2-035",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Zeroes of Polynomial",
    "section": "C",
    "marks": 2,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "If p(x) = x⁴ - 1 and one zero is 1, which of the following is NOT a zero of p(x)?",
    "options": [
      "-1",
      "i",
      "-i",
      "2"
    ],
    "answer": "2",
    "solutionSteps": [
      "p(x) = x⁴ - 1 = (x² - 1)(x² + 1) = (x-1)(x+1)(x-i)(x+i)",
      "Zeroes: ±1, ±i",
      "p(2) = 16 - 1 = 15 ≠ 0, so 2 is not a zero"
    ],
    "finalAnswer": "2",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 2.1"
  },
  {
    "id": "PL2-036",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Division Algorithm",
    "section": "C",
    "marks": 3,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "If x³ - 3x + 5 is divided by x² - 1, find the quotient and remainder.",
    "options": [],
    "answer": "Quotient = x, Remainder = -2x + 5",
    "solutionSteps": [
      "Using polynomial division:",
      "x³ - 3x + 5 = (x² - 1) × x + (-2x + 5)",
      "Quotient = x, Remainder = -2x + 5"
    ],
    "finalAnswer": "Quotient = x, Remainder = -2x + 5",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": undefined,
    "ncertRef": "Ex 2.3"
  },
  {
    "id": "PL2-037",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Relationship between Zeroes and Coefficients",
    "section": "C",
    "marks": 3,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "If the zeroes of x² + px + q are in the ratio 1:2, find the relationship between p and q.",
    "options": [],
    "answer": "2p² = 9q",
    "solutionSteps": [
      "Let zeroes be α and 2α",
      "Sum: α + 2α = 3α = -p → α = -p/3",
      "Product: α × 2α = 2α² = q → 2(p²/9) = q",
      "2p²/9 = q → 2p² = 9q"
    ],
    "finalAnswer": "2p² = 9q",
    "isCompetencyBased": true,
    "pyqYear": "2024",
    "pyqSet": undefined,
    "ncertRef": "Ex 2.2"
  },
  {
    "id": "PL2-038",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Zeroes of Polynomial",
    "section": "C",
    "marks": 5,
    "format": "Long",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "If α and β are zeroes of p(x) = x² - 5x + 6, form a new polynomial whose zeroes are 2α + β and α + 2β.",
    "options": [],
    "answer": "x² - 15x + 56",
    "solutionSteps": [
      "p(x) = x² - 5x + 6 = (x-2)(x-3), so α = 2, β = 3",
      "New zeroes: 2α + β = 4 + 3 = 7 and α + 2β = 2 + 6 = 8",
      "Sum of new zeroes = 15",
      "Product of new zeroes = 7 × 8 = 56",
      "New polynomial = x² - 15x + 56"
    ],
    "finalAnswer": "x² - 15x + 56",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 2.2"
  },
  {
    "id": "PL2-039",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Division Algorithm",
    "section": "C",
    "marks": 5,
    "format": "Long",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Verify the division algorithm for p(x) = x⁴ - 3x² + 2x + 5, g(x) = x² - 1 by finding quotient and remainder, and verify p(x) = g(x) × q(x) + r(x).",
    "options": [],
    "answer": "q(x) = x² - 2, r(x) = 2x + 3",
    "solutionSteps": [
      "Divide x⁴ - 3x² + 2x + 5 by x² - 1",
      "x⁴ - 3x² + 2x + 5 = (x² - 1)(x² - 2) + (2x + 3)",
      "Verification: (x² - 1)(x² - 2) + 2x + 3 = x⁴ - 2x² - x² + 2 + 2x + 3 = x⁴ - 3x² + 2x + 5 ✓"
    ],
    "finalAnswer": "q(x) = x² - 2, r(x) = 2x + 3",
    "isCompetencyBased": true,
    "pyqYear": "2025",
    "pyqSet": undefined,
    "ncertRef": "Ex 2.3"
  },
  {
    "id": "PL2-040",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Zeroes of Polynomial",
    "section": "C",
    "marks": 5,
    "format": "Long",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "If α, β, γ are zeroes of p(x) = x³ + 3x² - x - 3, find: (i) α + β + γ, (ii) αβ + βγ + γα, (iii) αβγ, (iv) Factor p(x) completely.",
    "options": [],
    "answer": "Sum=-3, Sum of products=-1, Product=3, p(x)=(x+3)(x+1)(x-1)",
    "solutionSteps": [
      "For x³ + 3x² - x - 3:",
      "(i) Sum = -3",
      "(ii) Sum of products = -1",
      "(iii) Product = 3",
      "Factoring: p(x) = (x+3)(x² - 1) = (x+3)(x+1)(x-1)",
      "Zeroes: -3, -1, 1"
    ],
    "finalAnswer": "Sum=-3, Sum of products=-1, Product=3, p(x)=(x+3)(x+1)(x-1)",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 2.1, Ex 2.2"
  },
  {
    "id": "PL2-041",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Relationship between Zeroes and Coefficients",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Find a quadratic polynomial with zeroes that are reciprocals of the zeroes of x² - 7x + 12.",
    "options": [],
    "answer": "12x² - 7x + 1",
    "solutionSteps": [
      "Zeroes of x² - 7x + 12 are 3 and 4",
      "Reciprocals are 1/3 and 1/4",
      "New polynomial: (x - 1/3)(x - 1/4) = x² - 7x/12 + 1/12",
      "Multiply by 12: 12x² - 7x + 1"
    ],
    "finalAnswer": "12x² - 7x + 1",
    "isCompetencyBased": true,
    "pyqYear": "2021",
    "pyqSet": undefined,
    "ncertRef": "Ex 2.2"
  },
  {
    "id": "PL2-042",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Zeroes of Polynomial",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Check whether x = 1/2 is a zero of 2x³ - x² - x + 2.",
    "options": [],
    "answer": "No, x = 1/2 is not a zero",
    "solutionSteps": [
      "p(1/2) = 2(1/8) - 1/4 - 1/2 + 2",
      "= 1/4 - 1/4 - 1/2 + 2 = 3/2 ≠ 0",
      "Verification: 2(1/8) - (1/4) - (1/2) + 2 = 1/4 - 1/4 - 2/4 + 8/4 = 6/4 ≠ 0"
    ],
    "finalAnswer": "No, x = 1/2 is not a zero",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 2.1"
  },
  {
    "id": "PL2-043",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Division Algorithm",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Find the remainder when p(x) = x⁴ - x³ + 1 is divided by (x + 1).",
    "options": [],
    "answer": "Remainder = 3",
    "solutionSteps": [
      "By remainder theorem: R = p(-1)",
      "p(-1) = (-1)⁴ - (-1)³ + 1 = 1 + 1 + 1 = 3"
    ],
    "finalAnswer": "Remainder = 3",
    "isCompetencyBased": true,
    "pyqYear": "2022",
    "pyqSet": undefined,
    "ncertRef": "Ex 2.3"
  },
  {
    "id": "PL2-044",
    "subject": "Maths",
    "topicKey": "Polynomials",
    "subtopic": "Relationship between Zeroes and Coefficients",
    "section": "C",
    "marks": 2,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "If the polynomial ax² + bx + c has one zero as 2 and product of zeroes is 3, then the other zero is:",
    "options": [
      "3/2",
      "1/2",
      "2/3",
      "3"
    ],
    "answer": "3/2",
    "solutionSteps": [
      "Product of zeroes = 3",
      "If one zero is 2: 2 × (other zero) = 3",
      "Other zero = 3/2"
    ],
    "finalAnswer": "3/2",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 2.2"
  }
];
