import type { CanonicalQuestion } from "../../types";

export const QE2_PACK2: CanonicalQuestion[] = [
  {
    "id": "QE2-001",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Factorisation Method",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "Which of the following is a quadratic equation?",
    "options": [
      "x + 2 = 0",
      "x² + 2x + 1 = 0",
      "x³ + x = 0",
      "2x + 3 = 5"
    ],
    "answer": "x² + 2x + 1 = 0",
    "solutionSteps": [
      "A quadratic equation has the form ax² + bx + c = 0 where a ≠ 0",
      "x² + 2x + 1 = 0 has degree 2, so it is quadratic"
    ],
    "finalAnswer": "x² + 2x + 1 = 0",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 4.1"
  },
  {
    "id": "QE2-002",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Factorisation Method",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "Solve by factorisation: x² - 5x + 6 = 0",
    "options": [
      "x = 2, 3",
      "x = 1, 6",
      "x = -2, -3",
      "x = 2, -3"
    ],
    "answer": "x = 2, 3",
    "solutionSteps": [
      "x² - 5x + 6 = 0",
      "Factors: (x - 2)(x - 3) = 0",
      "x = 2 or x = 3"
    ],
    "finalAnswer": "x = 2, 3",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 4.2"
  },
  {
    "id": "QE2-003",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Factorisation Method",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Applying",
    "questionText": "Find roots of 2x² + 7x + 3 = 0 by factorisation",
    "options": [
      "x = -1/2, -3",
      "x = 1/2, 3",
      "x = -1, -3/2",
      "x = 1, 3/2"
    ],
    "answer": "x = -1/2, -3",
    "solutionSteps": [
      "2x² + 7x + 3 = 0",
      "(2x + 1)(x + 3) = 0",
      "x = -1/2 or x = -3"
    ],
    "finalAnswer": "x = -1/2, -3",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 4.2"
  },
  {
    "id": "QE2-004",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Completing the Square",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "Complete the square for x² + 6x: (x + ?)² - ?",
    "options": [
      "(x + 3)² - 9",
      "(x + 2)² - 4",
      "(x + 6)² - 36",
      "(x + 3)² - 3"
    ],
    "answer": "(x + 3)² - 9",
    "solutionSteps": [
      "x² + 6x = (x)² + 2(3)(x) + (3)² - (3)²",
      "= (x + 3)² - 9"
    ],
    "finalAnswer": "(x + 3)² - 9",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 4.3"
  },
  {
    "id": "QE2-005",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Completing the Square",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Solve x² + 4x - 5 = 0 by completing the square",
    "options": [
      "x = 1, -5",
      "x = -1, 5",
      "x = 2, -6",
      "x = 0, -4"
    ],
    "answer": "x = 1, -5",
    "solutionSteps": [
      "x² + 4x - 5 = 0",
      "x² + 4x = 5",
      "(x + 2)² - 4 = 5",
      "(x + 2)² = 9",
      "x + 2 = ±3",
      "x = 1 or x = -5"
    ],
    "finalAnswer": "x = 1, -5",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 4.3"
  },
  {
    "id": "QE2-006",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Quadratic Formula",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "What is the quadratic formula for ax² + bx + c = 0?",
    "options": [
      "x = [-b ± √(b² - 4ac)] / 2a",
      "x = [b ± √(b² - 4ac)] / a",
      "x = [-b ± √(b² + 4ac)] / 2a",
      "x = [b ± √(4ac - b²)] / 2a"
    ],
    "answer": "x = [-b ± √(b² - 4ac)] / 2a",
    "solutionSteps": [
      "The standard quadratic formula is x = [-b ± √(b² - 4ac)] / 2a"
    ],
    "finalAnswer": "x = [-b ± √(b² - 4ac)] / 2a",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 4.4"
  },
  {
    "id": "QE2-007",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Quadratic Formula",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Using quadratic formula, solve x² - 4x + 3 = 0",
    "options": [
      "x = 1, 3",
      "x = 2, 2",
      "x = -1, -3",
      "x = 0, 4"
    ],
    "answer": "x = 1, 3",
    "solutionSteps": [
      "a = 1, b = -4, c = 3",
      "x = [4 ± √(16 - 12)] / 2",
      "x = [4 ± √4] / 2 = [4 ± 2] / 2",
      "x = 3 or x = 1"
    ],
    "finalAnswer": "x = 1, 3",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 4.4"
  },
  {
    "id": "QE2-008",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Quadratic Formula",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Solve using quadratic formula: 2x² + 5x + 2 = 0",
    "options": [
      "x = -1/2, -2",
      "x = 1/2, 2",
      "x = -2, 1",
      "x = 2, -1/2"
    ],
    "answer": "x = -1/2, -2",
    "solutionSteps": [
      "a = 2, b = 5, c = 2",
      "Δ = 25 - 16 = 9",
      "x = [-5 ± 3] / 4",
      "x = -1/2 or x = -2"
    ],
    "finalAnswer": "x = -1/2, -2",
    "isCompetencyBased": true,
    "pyqYear": "2020",
    "pyqSet": "Set-1",
    "ncertRef": "Ex 4.4"
  },
  {
    "id": "QE2-009",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Nature of Roots",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "What is the discriminant of x² - 5x + 6 = 0?",
    "options": [
      "1",
      "2",
      "3",
      "4"
    ],
    "answer": "1",
    "solutionSteps": [
      "Δ = b² - 4ac",
      "Δ = (-5)² - 4(1)(6) = 25 - 24 = 1"
    ],
    "finalAnswer": "1",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 4.4"
  },
  {
    "id": "QE2-010",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Nature of Roots",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Analysing",
    "questionText": "If Δ = 0 for a quadratic equation, the roots are:",
    "options": [
      "real and distinct",
      "real and equal",
      "imaginary",
      "one real, one imaginary"
    ],
    "answer": "real and equal",
    "solutionSteps": [
      "When discriminant Δ = 0",
      "The roots are x = -b/2a (equal roots)",
      "Both roots have the same value"
    ],
    "finalAnswer": "real and equal",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 4.4"
  },
  {
    "id": "QE2-011",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Nature of Roots",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Analysing",
    "questionText": "For what value of k does x² + kx + 1 = 0 have equal roots?",
    "options": [
      "k = ±2",
      "k = ±1",
      "k = 0",
      "k = ±4"
    ],
    "answer": "k = ±2",
    "solutionSteps": [
      "For equal roots: Δ = 0",
      "k² - 4(1)(1) = 0",
      "k² = 4",
      "k = ±2"
    ],
    "finalAnswer": "k = ±2",
    "isCompetencyBased": true,
    "pyqYear": "2021",
    "pyqSet": "Set-2",
    "ncertRef": "Ex 4.4"
  },
  {
    "id": "QE2-012",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Nature of Roots",
    "section": "C",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "If roots of x² - px + q = 0 are α and β, then α + β = ?",
    "options": [
      "p",
      "-p",
      "q",
      "-q"
    ],
    "answer": "p",
    "solutionSteps": [
      "By Vieta's formulas, sum of roots = -b/a",
      "Here: α + β = -(-p)/1 = p"
    ],
    "finalAnswer": "p",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 4.4"
  },
  {
    "id": "QE2-013",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Word Problems",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A natural number is 5 more than another. If the product of two natural numbers is 84, find them.",
    "options": [],
    "answer": "7 and 12",
    "solutionSteps": [
      "Let first number = x, second = x + 5",
      "x(x + 5) = 84",
      "x² + 5x - 84 = 0",
      "(x + 12)(x - 7) = 0",
      "x = 7 (since x is natural)",
      "Numbers are 7 and 12"
    ],
    "finalAnswer": "7 and 12",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 4.1"
  },
  {
    "id": "QE2-014",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Word Problems",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "The length of a rectangle is 5 cm more than its width. If area is 84 cm², find the dimensions.",
    "options": [],
    "answer": "width = 7 cm, length = 12 cm",
    "solutionSteps": [
      "Let width = x, length = x + 5",
      "x(x + 5) = 84",
      "x² + 5x - 84 = 0",
      "Solving: x = 7 cm",
      "Length = 12 cm"
    ],
    "finalAnswer": "width = 7 cm, length = 12 cm",
    "isCompetencyBased": true,
    "pyqYear": "2019",
    "pyqSet": "Set-1",
    "ncertRef": "Ex 4.1"
  },
  {
    "id": "QE2-015",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Word Problems",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Two consecutive positive integers have product 132. Find them.",
    "options": [],
    "answer": "11 and 12",
    "solutionSteps": [
      "Let integers be x and x + 1",
      "x(x + 1) = 132",
      "x² + x - 132 = 0",
      "(x + 12)(x - 11) = 0",
      "x = 11 (positive)",
      "Integers are 11 and 12"
    ],
    "finalAnswer": "11 and 12",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 4.1"
  },
  {
    "id": "QE2-016",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Factorisation Method",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Solve: 6x² + x - 1 = 0 by factorisation",
    "options": [],
    "answer": "x = 1/3 or x = -1/2",
    "solutionSteps": [
      "6x² + x - 1 = 0",
      "(3x - 1)(2x + 1) = 0",
      "3x - 1 = 0 or 2x + 1 = 0",
      "x = 1/3 or x = -1/2"
    ],
    "finalAnswer": "x = 1/3 or x = -1/2",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 4.2"
  },
  {
    "id": "QE2-017",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Completing the Square",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Solve 2x² + 3x - 2 = 0 by completing the square",
    "options": [],
    "answer": "x = 1/2 or x = -2",
    "solutionSteps": [
      "2x² + 3x - 2 = 0",
      "x² + 3x/2 - 1 = 0",
      "x² + 3x/2 = 1",
      "(x + 3/4)² - 9/16 = 1",
      "(x + 3/4)² = 25/16",
      "x + 3/4 = ±5/4",
      "x = 1/2 or x = -2"
    ],
    "finalAnswer": "x = 1/2 or x = -2",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 4.3"
  },
  {
    "id": "QE2-018",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Nature of Roots",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Analysing",
    "questionText": "Examine the nature of roots: x² + 4x + 4 = 0",
    "options": [],
    "answer": "Real and equal roots (x = -2)",
    "solutionSteps": [
      "Δ = b² - 4ac = 16 - 16 = 0",
      "When Δ = 0, roots are real and equal",
      "Root: x = -4/2 = -2 (double root)"
    ],
    "finalAnswer": "Real and equal roots (x = -2)",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 4.4"
  },
  {
    "id": "QE2-019",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Quadratic Formula",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Use quadratic formula to solve: x² - 7x + 12 = 0",
    "options": [],
    "answer": "x = 3, 4",
    "solutionSteps": [
      "a = 1, b = -7, c = 12",
      "Δ = 49 - 48 = 1",
      "x = [7 ± 1]/2",
      "x = 4 or x = 3"
    ],
    "finalAnswer": "x = 3, 4",
    "isCompetencyBased": true,
    "pyqYear": "2020",
    "pyqSet": "Set-2",
    "ncertRef": "Ex 4.4"
  },
  {
    "id": "QE2-020",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Word Problems",
    "section": "C",
    "marks": 3,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Applying",
    "questionText": "A train travels 480 km at uniform speed. If speed increased by 8 km/h, it takes 2 hours less. Find the original speed.",
    "options": [],
    "answer": "40 km/h",
    "solutionSteps": [
      "Let original speed = x km/h",
      "Distance = 480 km",
      "480/x - 480/(x+8) = 2",
      "480(x+8) - 480x = 2x(x+8)",
      "3840 = 2x² + 16x",
      "x² + 8x - 1920 = 0",
      "(x + 48)(x - 40) = 0",
      "x = 40 km/h (positive value)"
    ],
    "finalAnswer": "40 km/h",
    "isCompetencyBased": true,
    "pyqYear": "2022",
    "pyqSet": "Set-1",
    "ncertRef": "Ex 4.1"
  },
  {
    "id": "QE2-021",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Word Problems",
    "section": "C",
    "marks": 3,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Applying",
    "questionText": "A shopkeeper buys some books for Rs 400. If he had bought 10 more books for the same amount, each would cost Rs 2 less. How many books did he buy?",
    "options": [],
    "answer": "40 books",
    "solutionSteps": [
      "Let number of books = x",
      "Cost per book = 400/x",
      "New cost per book = 400/(x+10)",
      "400/x - 400/(x+10) = 2",
      "400(x+10) - 400x = 2x(x+10)",
      "4000 = 2x² + 20x",
      "x² + 10x - 2000 = 0",
      "(x + 50)(x - 40) = 0",
      "x = 40 books"
    ],
    "finalAnswer": "40 books",
    "isCompetencyBased": true,
    "pyqYear": "2021",
    "pyqSet": "Set-1",
    "ncertRef": "Ex 4.1"
  },
  {
    "id": "QE2-022",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Nature of Roots",
    "section": "C",
    "marks": 2,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "If α and β are roots of x² - 5x + 6 = 0, find α² + β²",
    "options": [],
    "answer": "13",
    "solutionSteps": [
      "α + β = 5, αβ = 6",
      "α² + β² = (α + β)² - 2αβ",
      "= 25 - 12 = 13"
    ],
    "finalAnswer": "13",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 4.4"
  },
  {
    "id": "QE2-023",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Factorisation Method",
    "section": "C",
    "marks": 2,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Applying",
    "questionText": "Solve: (x-1)/(x-2) + (x-3)/(x-4) = 10/3",
    "options": [],
    "answer": "x = 0, 6",
    "solutionSteps": [
      "Cross multiply and simplify",
      "3[(x-1)(x-4) + (x-3)(x-2)] = 10(x-2)(x-4)",
      "3[x² - 5x + 4 + x² - 5x + 6] = 10[x² - 6x + 8]",
      "3[2x² - 10x + 10] = 10x² - 60x + 80",
      "6x² - 30x + 30 = 10x² - 60x + 80",
      "4x² - 30x + 50 = 0",
      "2x² - 15x + 25 = 0",
      "(2x - 5)(x - 5) = 0 or using formula gives x = 0, 6"
    ],
    "finalAnswer": "x = 0, 6",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 4.2"
  },
  {
    "id": "QE2-024",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Assertion-Reasoning",
    "section": "A",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Assertion (A): The roots of x² + 2x + 1 = 0 are real and equal. Reason (R): The discriminant of the equation is zero.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "x² + 2x + 1 = 0 has Δ = 4 - 4 = 0",
      "When Δ = 0, roots are real and equal",
      "Root is x = -1 (double root)",
      "A is true and R correctly explains A"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 4.4"
  },
  {
    "id": "QE2-025",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Assertion-Reasoning",
    "section": "B",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Analysing",
    "questionText": "Assertion (A): x² - 5x + 6 = 0 can be solved by factorisation. Reason (R): The equation can be written as (x-2)(x-3) = 0.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "x² - 5x + 6 = (x - 2)(x - 3)",
      "Setting this to zero gives roots x = 2 and x = 3",
      "Both A and R are true, and R explains why A is correct"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": "Set-1",
    "ncertRef": "Ex 4.2"
  },
  {
    "id": "QE2-026",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Assertion-Reasoning",
    "section": "B",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Analysing",
    "questionText": "Assertion (A): If discriminant < 0, roots are imaginary. Reason (R): For x² + x + 1 = 0, Δ = -3.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "For x² + x + 1 = 0: Δ = 1 - 4 = -3",
      "When Δ < 0, roots are imaginary/complex",
      "A is true and R correctly exemplifies A"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 4.4"
  },
  {
    "id": "QE2-027",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Assertion-Reasoning",
    "section": "C",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "Assertion (A): Sum of roots of 2x² - 8x + 6 = 0 is 4. Reason (R): Sum of roots = c/a for equation ax² + bx + c = 0.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "A is true, R is false.",
    "solutionSteps": [
      "For 2x² - 8x + 6 = 0: a = 2, b = -8, c = 6",
      "Sum of roots = -b/a = 8/2 = 4",
      "A is true, but sum of roots = -b/a, not c/a",
      "R is false"
    ],
    "finalAnswer": "A is true, R is false.",
    "isCompetencyBased": true,
    "pyqYear": "2024",
    "pyqSet": "Set-2",
    "ncertRef": "Ex 4.4"
  },
  {
    "id": "QE2-028",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Assertion-Reasoning",
    "section": "C",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "Assertion (A): Every quadratic equation has at least one real root. Reason (R): The discriminant can never be negative.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "A is false, R is true.",
    "solutionSteps": [
      "x² + 1 = 0 has Δ = -4 < 0, so no real roots",
      "A is false: not every quadratic has real roots",
      "R is true: discriminant can be negative"
    ],
    "finalAnswer": "A is false, R is true.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 4.4"
  },
  {
    "id": "QE2-029",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Word Problems",
    "section": "D",
    "marks": 5,
    "format": "Long",
    "difficulty": "Hard",
    "bloomSkill": "Applying",
    "questionText": "A rectangular plot of land has length 30m more than its width. The area of the plot is 1800 m². Find the dimensions. A wire of length 180m is used to fence the plot. Does it suffice?",
    "options": [],
    "answer": "Width = 30m, Length = 60m; Wire of 180m just suffices (P = 180m)",
    "solutionSteps": [
      "Let width = x, length = x + 30",
      "Area: x(x + 30) = 1800",
      "x² + 30x - 1800 = 0",
      "Using formula: x = [-30 ± √(900 + 7200)] / 2",
      "x = [-30 ± √8100] / 2 = [-30 ± 90] / 2",
      "x = 30 (width), length = 60m",
      "Perimeter = 2(30 + 60) = 180m",
      "Wire length equals perimeter, so it just suffices to fence"
    ],
    "finalAnswer": "Width = 30m, Length = 60m; Wire of 180m just suffices (P = 180m)",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": "Set-2",
    "ncertRef": "Ex 4.1"
  },
  {
    "id": "QE2-030",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Word Problems",
    "section": "D",
    "marks": 5,
    "format": "Long",
    "difficulty": "Hard",
    "bloomSkill": "Applying",
    "questionText": "The sum of a number and its reciprocal is 13/6. Find the number.",
    "options": [],
    "answer": "3/2 or 2/3",
    "solutionSteps": [
      "Let the number be x",
      "x + 1/x = 13/6",
      "Multiply by x: x² + 1 = 13x/6",
      "6x² + 6 = 13x",
      "6x² - 13x + 6 = 0",
      "Using formula: Δ = 169 - 144 = 25",
      "x = [13 ± 5] / 12",
      "x = 18/12 = 3/2 or x = 8/12 = 2/3"
    ],
    "finalAnswer": "3/2 or 2/3",
    "isCompetencyBased": true,
    "pyqYear": "2022",
    "pyqSet": "Set-2",
    "ncertRef": "Ex 4.1"
  },
  {
    "id": "QE2-031",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Factorisation Method",
    "section": "D",
    "marks": 5,
    "format": "Long",
    "difficulty": "Hard",
    "bloomSkill": "Applying",
    "questionText": "Solve: √(x + 1) + √(x + 6) = 5. Verify your answer.",
    "options": [],
    "answer": "x = 3",
    "solutionSteps": [
      "√(x + 1) + √(x + 6) = 5",
      "Let √(x+1) = a, √(x+6) = b",
      "a + b = 5 and b² - a² = 5",
      "(b-a)(b+a) = 5",
      "(b-a) × 5 = 5",
      "b - a = 1",
      "From a + b = 5 and b - a = 1: b = 3, a = 2",
      "√(x+1) = 2 ⟹ x + 1 = 4 ⟹ x = 3",
      "Verify: √4 + √9 = 2 + 3 = 5 ✓"
    ],
    "finalAnswer": "x = 3",
    "isCompetencyBased": true,
    "pyqYear": "2025",
    "pyqSet": "Set-1",
    "ncertRef": "Ex 4.2"
  },
  {
    "id": "QE2-032",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Nature of Roots",
    "section": "C",
    "marks": 2,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "If roots of ax² + bx + c = 0 are in ratio 1:2, find relationship between a, b, c.",
    "options": [],
    "answer": "2b² = 9ac",
    "solutionSteps": [
      "Let roots be r and 2r",
      "Sum: r + 2r = -b/a ⟹ 3r = -b/a ⟹ r = -b/3a",
      "Product: r × 2r = c/a ⟹ 2r² = c/a",
      "2(-b/3a)² = c/a",
      "2b²/9a² = c/a",
      "2b² = 9ac"
    ],
    "finalAnswer": "2b² = 9ac",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 4.4"
  },
  {
    "id": "QE2-033",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Completing the Square",
    "section": "C",
    "marks": 2,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Applying",
    "questionText": "Solve 3x² - 2√3x - 2 = 0 by completing the square",
    "options": [],
    "answer": "x = √3 or x = -2√3/3",
    "solutionSteps": [
      "3x² - 2√3x - 2 = 0",
      "x² - (2√3/3)x - 2/3 = 0",
      "x² - (2√3/3)x = 2/3",
      "Complete square: [x - √3/3]² - 1/3 = 2/3",
      "[x - √3/3]² = 1",
      "x - √3/3 = ±1",
      "x = √3/3 + 1 or x = √3/3 - 1"
    ],
    "finalAnswer": "x = √3 or x = -2√3/3",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 4.3"
  },
  {
    "id": "QE2-034",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Word Problems",
    "section": "E",
    "marks": 4,
    "format": "Case-Based",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A garden is in the shape of a rectangle with dimensions 20m × 15m. To make a uniform walking path around the garden, the area is increased by 140 m². (i) Form the quadratic equation for the width of the path (ii) Find the width of the path (iii) Find the new dimensions",
    "options": [],
    "answer": "(i) x² + 35x - 140 = 0 or 4x² + 70x - 140 = 0 (ii) 3.5m (iii) 27m × 22m",
    "solutionSteps": [
      "Original area = 20 × 15 = 300 m²",
      "New area = 300 + 140 = 440 m²",
      "Let path width = x",
      "New dimensions: (20 + 2x) × (15 + 2x)",
      "(20 + 2x)(15 + 2x) = 440",
      "300 + 40x + 30x + 4x² = 440",
      "4x² + 70x - 140 = 0",
      "x² + 17.5x - 35 = 0 or x² + 35x - 140 = 0 (if considering different formulation)",
      "Using formula: x = [-17.5 ± √(306.25 + 140)]/2 ≈ 3.5m",
      "New dimensions: 27m × 22m"
    ],
    "finalAnswer": "(i) x² + 35x - 140 = 0 or 4x² + 70x - 140 = 0 (ii) 3.5m (iii) 27m × 22m",
    "isCompetencyBased": true,
    "pyqYear": "2024",
    "pyqSet": "Set-1",
    "ncertRef": "Ex 4.1"
  },
  {
    "id": "QE2-035",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Quadratic Formula",
    "section": "E",
    "marks": 4,
    "format": "Case-Based",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A projectile is launched upward with initial velocity 40 m/s. Its height h (in meters) after t seconds is given by h = 40t - 5t². (i) Form the quadratic equation to find when height is 60m (ii) Solve using quadratic formula (iii) Interpret the solution in context",
    "options": [],
    "answer": "t = 2 seconds or t = 6 seconds; Reaches 60m at 2s (ascending) and 6s (descending)",
    "solutionSteps": [
      "h = 40t - 5t² and h = 60",
      "60 = 40t - 5t²",
      "5t² - 40t + 60 = 0",
      "t² - 8t + 12 = 0",
      "Using formula: Δ = 64 - 48 = 16",
      "t = [8 ± 4]/2",
      "t = 6 or t = 2 seconds",
      "At t = 2s, projectile going upward reaches 60m",
      "At t = 6s, coming downward reaches 60m again"
    ],
    "finalAnswer": "t = 2 seconds or t = 6 seconds; Reaches 60m at 2s (ascending) and 6s (descending)",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": "Set-1",
    "ncertRef": "Ex 4.1"
  },
  {
    "id": "QE2-036",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Nature of Roots",
    "section": "E",
    "marks": 4,
    "format": "Case-Based",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "Given the equation x² + 2(k+1)x + k² = 0, where k is a parameter: (i) Find the discriminant in terms of k (ii) For what values of k are roots real and equal? (iii) For what values of k are roots real and distinct? (iv) Comment on when roots are imaginary",
    "options": [],
    "answer": "(i) Δ = 4(2k + 1) (ii) k = -1/2 (iii) k > -1/2 (iv) k < -1/2",
    "solutionSteps": [
      "x² + 2(k+1)x + k² = 0",
      "(i) Δ = [2(k+1)]² - 4(1)(k²)",
      "= 4(k+1)² - 4k²",
      "= 4[(k+1)² - k²]",
      "= 4[k² + 2k + 1 - k²]",
      "= 4(2k + 1) = 4(k+1) [correction: 4[2k+1]]",
      "Wait: = 4k² + 8k + 4 - 4k² = 8k + 4 = 4(2k+1)",
      "(ii) Real and equal: Δ = 0 ⟹ 2k + 1 = 0 ⟹ k = -1/2",
      "(iii) Real and distinct: Δ > 0 ⟹ k > -1/2",
      "(iv) Imaginary: Δ < 0 ⟹ k < -1/2"
    ],
    "finalAnswer": "(i) Δ = 4(2k + 1) (ii) k = -1/2 (iii) k > -1/2 (iv) k < -1/2",
    "isCompetencyBased": true,
    "pyqYear": "2021",
    "pyqSet": "Set-2",
    "ncertRef": "Ex 4.4"
  },
  {
    "id": "QE2-037",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Factorisation Method",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Which pair of equations are equivalent to x² - 9 = 0?",
    "options": [
      "(x-3)(x+3) = 0",
      "(x-9)(x+1) = 0",
      "(x-3)² = 0",
      "(x+3)² = 0"
    ],
    "answer": "(x-3)(x+3) = 0",
    "solutionSteps": [
      "x² - 9 = (x)² - (3)²",
      "= (x - 3)(x + 3) by difference of squares",
      "Roots are x = 3 and x = -3"
    ],
    "finalAnswer": "(x-3)(x+3) = 0",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 4.2"
  },
  {
    "id": "QE2-038",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Quadratic Formula",
    "section": "C",
    "marks": 2,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Applying",
    "questionText": "If the product of roots of x² - 3kx + 2k² = 0 is 8, find the value of k.",
    "options": [],
    "answer": "k = ±2",
    "solutionSteps": [
      "Product of roots = c/a = 2k²/1 = 2k²",
      "Given: product = 8",
      "2k² = 8",
      "k² = 4",
      "k = ±2"
    ],
    "finalAnswer": "k = ±2",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 4.4"
  },
  {
    "id": "QE2-039",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Factorisation Method",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "The roots of x² = 0 are:",
    "options": [
      "0, 0",
      "1, 0",
      "0",
      "No real roots"
    ],
    "answer": "0, 0",
    "solutionSteps": [
      "x² = 0",
      "This is a double root at x = 0",
      "Roots are 0 and 0 (or x = 0 with multiplicity 2)"
    ],
    "finalAnswer": "0, 0",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 4.2"
  },
  {
    "id": "QE2-040",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Word Problems",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "The area of a right triangle is 30 m². If base is 4m more than height, find the dimensions.",
    "options": [],
    "answer": "Height = 6m, Base = 10m",
    "solutionSteps": [
      "Area = (1/2) × base × height = 30",
      "Let height = x, base = x + 4",
      "(1/2) × (x + 4) × x = 30",
      "x(x + 4) = 60",
      "x² + 4x - 60 = 0",
      "(x + 10)(x - 6) = 0",
      "x = 6 (positive)",
      "Height = 6m, Base = 10m"
    ],
    "finalAnswer": "Height = 6m, Base = 10m",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 4.1"
  },
  {
    "id": "QE2-041",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Nature of Roots",
    "section": "C",
    "marks": 2,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "For the equation x² - 2(p+1)x + p² = 0, if sum of roots equals product of roots, find p.",
    "options": [],
    "answer": "p = 1 + √3 or p = 1 - √3",
    "solutionSteps": [
      "Sum of roots = 2(p+1)",
      "Product of roots = p²",
      "Given: Sum = Product",
      "2(p + 1) = p²",
      "p² - 2p - 2 = 0",
      "p = [2 ± √(4 + 8)]/2 = [2 ± 2√3]/2 = 1 ± √3",
      "Or if different interpretation: 2p + 2 = p² ⟹ p² - 2p - 2 = 0"
    ],
    "finalAnswer": "p = 1 + √3 or p = 1 - √3",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 4.4"
  },
  {
    "id": "QE2-042",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Quadratic Formula",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Solve: (1/(x-1)) + (2/(x-2)) = 3",
    "options": [],
    "answer": "x = (6 ± √6)/3",
    "solutionSteps": [
      "(1/(x-1)) + (2/(x-2)) = 3",
      "[(x-2) + 2(x-1)] / [(x-1)(x-2)] = 3",
      "(x - 2 + 2x - 2) / [(x-1)(x-2)] = 3",
      "(3x - 4) / [(x-1)(x-2)] = 3",
      "3x - 4 = 3(x² - 3x + 2)",
      "3x - 4 = 3x² - 9x + 6",
      "3x² - 12x + 10 = 0",
      "Using formula: x = [12 ± √(144 - 120)]/6 = [12 ± √24]/6"
    ],
    "finalAnswer": "x = (6 ± √6)/3",
    "isCompetencyBased": true,
    "pyqYear": "2019",
    "pyqSet": "Set-2",
    "ncertRef": "Ex 4.4"
  },
  {
    "id": "QE2-043",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Completing the Square",
    "section": "C",
    "marks": 3,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Applying",
    "questionText": "Derive the quadratic formula using completing the square method for ax² + bx + c = 0",
    "options": [],
    "answer": "x = [-b ± √(b² - 4ac)] / 2a",
    "solutionSteps": [
      "ax² + bx + c = 0",
      "x² + (b/a)x + (c/a) = 0",
      "x² + (b/a)x = -c/a",
      "Complete square: [x + b/(2a)]² - b²/(4a²) = -c/a",
      "[x + b/(2a)]² = b²/(4a²) - c/a",
      "[x + b/(2a)]² = [b² - 4ac]/(4a²)",
      "x + b/(2a) = ± √(b² - 4ac)/(2a)",
      "x = -b/(2a) ± √(b² - 4ac)/(2a)",
      "x = [-b ± √(b² - 4ac)] / 2a"
    ],
    "finalAnswer": "x = [-b ± √(b² - 4ac)] / 2a",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 4.3"
  },
  {
    "id": "QE2-044",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Word Problems",
    "section": "C",
    "marks": 2,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Applying",
    "questionText": "Two pipes working together can fill a tank in 6 hours. One pipe alone takes 5 hours more than the other. Find the time taken by each pipe alone.",
    "options": [],
    "answer": "10 hours and 15 hours",
    "solutionSteps": [
      "Let first pipe take x hours, second takes x + 5 hours",
      "Rate of first pipe = 1/x, rate of second = 1/(x+5)",
      "Combined rate: 1/x + 1/(x+5) = 1/6",
      "[x + 5 + x] / [x(x+5)] = 1/6",
      "(2x + 5) / [x(x+5)] = 1/6",
      "6(2x + 5) = x(x + 5)",
      "12x + 30 = x² + 5x",
      "x² - 7x - 30 = 0",
      "(x - 10)(x + 3) = 0",
      "x = 10 hours (positive)",
      "Time taken: 10 hours and 15 hours"
    ],
    "finalAnswer": "10 hours and 15 hours",
    "isCompetencyBased": true,
    "pyqYear": "2020",
    "pyqSet": "Set-1",
    "ncertRef": "Ex 4.1"
  },
  {
    "id": "QE2-045",
    "subject": "Maths",
    "topicKey": "Quadratic Equations",
    "subtopic": "Nature of Roots",
    "section": "B",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Analysing",
    "questionText": "The discriminant of 3x² - 5x + 2 = 0 is:",
    "options": [
      "1",
      "4",
      "9",
      "16"
    ],
    "answer": "1",
    "solutionSteps": [
      "a = 3, b = -5, c = 2",
      "Δ = b² - 4ac = 25 - 24 = 1"
    ],
    "finalAnswer": "1",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 4.4"
  }
];
