import type { CanonicalQuestion } from "../../types";

export const SAV2_PACK2: CanonicalQuestion[] = [
  {
    "id": "SAV2-001",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Combined Solids",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "A solid is formed by combining a hemisphere and a cylinder. What is the total surface area formula for this combined solid (hemisphere on top of cylinder)?",
    "options": [
      "πr² + 2πrh + 2πr²",
      "2πrh + 3πr²",
      "πr² + 2πrh + πr²",
      "2πr(h + r)"
    ],
    "answer": "2πrh + 3πr²",
    "solutionSteps": [
      "For hemisphere: curved surface = 2πr²",
      "For cylinder: lateral surface = 2πrh",
      "For cylinder base (only bottom): πr²",
      "Total = 2πr² + 2πrh + πr² = 2πrh + 3πr²"
    ],
    "finalAnswer": "2πrh + 3πr²",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 13.1"
  },
  {
    "id": "SAV2-002",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Combined Solids",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "A solid toy is made by joining a cone and a hemisphere. Both have radius 3 cm. If the cone's height is 4 cm, the volume of the toy is:",
    "options": [
      "30π cm³",
      "48π cm³",
      "36π cm³",
      "24π cm³"
    ],
    "answer": "30π cm³",
    "solutionSteps": [
      "Volume of hemisphere = (2/3)πr³ = (2/3)π(3)³ = 18π cm³",
      "Volume of cone = (1/3)πr²h = (1/3)π(3)²(4) = 12π cm³",
      "Total volume = 18π + 12π = 30π cm³"
    ],
    "finalAnswer": "30π cm³",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 13.1"
  },
  {
    "id": "SAV2-003",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Combined Solids",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A solid is formed by combining a cone and a cylinder of equal radius r. The cylinder has height h₁ and cone has height h₂. The total volume is:",
    "options": [
      "πr²(h₁ + h₂/3)",
      "πr²(h₁ + h₂)",
      "πr²h₁ + (1/3)πr²h₂",
      "Both A and C"
    ],
    "answer": "Both A and C",
    "solutionSteps": [
      "Volume of cylinder = πr²h₁",
      "Volume of cone = (1/3)πr²h₂",
      "Total = πr²h₁ + (1/3)πr²h₂ = πr²(h₁ + h₂/3)",
      "Options A and C are equivalent"
    ],
    "finalAnswer": "Both A and C",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 13.1"
  },
  {
    "id": "SAV2-004",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Combined Solids",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A capsule is formed by joining two hemispheres with a cylinder. If radius = 2 cm and cylinder height = 5 cm, find the total surface area of the capsule.",
    "options": [],
    "answer": "36π cm²",
    "solutionSteps": [
      "Two hemispheres form a complete sphere",
      "Surface area of sphere = 4πr² = 4π(2)² = 16π cm²",
      "Lateral surface area of cylinder = 2πrh = 2π(2)(5) = 20π cm²",
      "Total surface area = 16π + 20π = 36π cm²"
    ],
    "finalAnswer": "36π cm²",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 13.1"
  },
  {
    "id": "SAV2-005",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Conversion of Solids",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "A solid sphere of radius 6 cm is melted and recast into a cone of base radius 3 cm. The height of the cone is:",
    "options": [
      "48 cm",
      "144 cm",
      "96 cm",
      "72 cm"
    ],
    "answer": "96 cm",
    "solutionSteps": [
      "Volume of sphere = (4/3)πr³ = (4/3)π(6)³ = 288π cm³",
      "Volume of cone = (1/3)πR²h where R = 3 cm",
      "288π = (1/3)π(3)²h",
      "288 = 3h",
      "h = 96 cm"
    ],
    "finalAnswer": "96 cm",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 13.2"
  },
  {
    "id": "SAV2-006",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Conversion of Solids",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A metallic cone of radius 4 cm and height 24 cm is melted and recast into spheres of radius 4 mm each. How many spheres are formed?",
    "options": [
      "1500",
      "2000",
      "1000",
      "2500"
    ],
    "answer": "1500",
    "solutionSteps": [
      "Volume of cone = (1/3)π(4)²(24) = 128π cm³",
      "Volume of one sphere = (4/3)π(0.4)³ = (4/3)π(0.064) = 0.256π/3 cm³",
      "Number of spheres = 128π ÷ (256π/3000) = 128π × 3000/(256π) = 1500"
    ],
    "finalAnswer": "1500",
    "isCompetencyBased": true,
    "pyqYear": "2020",
    "pyqSet": "Delhi",
    "ncertRef": "Ex 13.2"
  },
  {
    "id": "SAV2-007",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Conversion of Solids",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A cylinder of radius 3 cm and height 10 cm is melted and recast into a sphere. Find the radius of the sphere.",
    "options": [],
    "answer": "R ≈ 4.07 cm",
    "solutionSteps": [
      "Volume of cylinder = πr²h = π(3)²(10) = 90π cm³",
      "Let radius of sphere = R",
      "Volume of sphere = (4/3)πR³",
      "(4/3)πR³ = 90π",
      "R³ = 270/4 = 67.5",
      "R = ∛67.5 ≈ 4.07 cm"
    ],
    "finalAnswer": "R ≈ 4.07 cm",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 13.2"
  },
  {
    "id": "SAV2-008",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Frustum of Cone",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "The slant height of a frustum of a cone is defined as:",
    "options": [
      "Distance between centers of two bases",
      "Distance along the lateral surface between two circular bases",
      "Height of original cone",
      "Sum of radii of two bases"
    ],
    "answer": "Distance along the lateral surface between two circular bases",
    "solutionSteps": [
      "Slant height (l) of frustum is the distance measured along the slant surface",
      "It connects corresponding points on the two circular bases"
    ],
    "finalAnswer": "Distance along the lateral surface between two circular bases",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 13.3"
  },
  {
    "id": "SAV2-009",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Frustum of Cone",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "The curved surface area of frustum of a cone is given by:",
    "options": [
      "π(r₁ + r₂)l",
      "π(r₁ - r₂)l",
      "πr₁l",
      "2π(r₁ + r₂)h"
    ],
    "answer": "π(r₁ + r₂)l",
    "solutionSteps": [
      "For frustum with radii r₁ (top) and r₂ (bottom) and slant height l",
      "Curved surface area = π(r₁ + r₂)l",
      "This is derived from the difference of two cones"
    ],
    "finalAnswer": "π(r₁ + r₂)l",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 13.3"
  },
  {
    "id": "SAV2-010",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Frustum of Cone",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A frustum of a cone has radii 7 cm and 5 cm at its two ends and slant height 10 cm. Find the curved surface area.",
    "options": [],
    "answer": "120π cm² or 377 cm²",
    "solutionSteps": [
      "Radii: r₁ = 7 cm, r₂ = 5 cm",
      "Slant height l = 10 cm",
      "Curved surface area = π(r₁ + r₂)l",
      "= π(7 + 5)(10)",
      "= 120π cm² ≈ 377 cm²"
    ],
    "finalAnswer": "120π cm² or 377 cm²",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 13.3"
  },
  {
    "id": "SAV2-011",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Frustum of Cone",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "The total surface area of a frustum of cone with radii 3 cm and 4 cm and height 5 cm is:",
    "options": [],
    "answer": "≈ 82.8π cm² or (7π√26 + 25π) cm²",
    "solutionSteps": [
      "r₁ = 3 cm, r₂ = 4 cm, h = 5 cm",
      "Slant height l = √(h² + (r₂-r₁)²) = √(25 + 1) = √26 cm",
      "Curved surface area = π(3 + 4)√26 = 7π√26 cm²",
      "Area of two bases = π(3)² + π(4)² = 9π + 16π = 25π cm²",
      "Total = 7π√26 + 25π ≈ 57.8π + 25π = 82.8π cm²"
    ],
    "finalAnswer": "≈ 82.8π cm² or (7π√26 + 25π) cm²",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 13.3"
  },
  {
    "id": "SAV2-012",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Frustum of Cone",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "The volume of a frustum of a cone is given by:",
    "options": [
      "(1/3)πh(r₁² + r₂² + r₁r₂)",
      "(1/3)πr₁²h",
      "πh(r₁ + r₂)²",
      "(2/3)πh(r₁ + r₂)"
    ],
    "answer": "(1/3)πh(r₁² + r₂² + r₁r₂)",
    "solutionSteps": [
      "Volume of frustum = Volume of larger cone - Volume of smaller cone",
      "This simplifies to V = (1/3)πh(r₁² + r₂² + r₁r₂)",
      "where h is height, r₁ and r₂ are radii of two bases"
    ],
    "finalAnswer": "(1/3)πh(r₁² + r₂² + r₁r₂)",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 13.4"
  },
  {
    "id": "SAV2-013",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Frustum of Cone",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A frustum of cone has height 12 cm, radii of ends 8 cm and 5 cm. Find its volume.",
    "options": [],
    "answer": "516π cm³ ≈ 1621 cm³",
    "solutionSteps": [
      "h = 12 cm, r₁ = 8 cm, r₂ = 5 cm",
      "Volume = (1/3)πh(r₁² + r₂² + r₁r₂)",
      "= (1/3)π(12)(64 + 25 + 40)",
      "= (1/3)π(12)(129)",
      "= 4π(129) = 516π cm³"
    ],
    "finalAnswer": "516π cm³ ≈ 1621 cm³",
    "isCompetencyBased": true,
    "pyqYear": "2021",
    "pyqSet": "All India",
    "ncertRef": "Ex 13.4"
  },
  {
    "id": "SAV2-014",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Combined Solids",
    "section": "C",
    "marks": 3,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "A solid consists of a cylinder of height 12 cm with radius 4 cm and two hemispheres at each end. Find the total volume and surface area.",
    "options": [],
    "answer": "Volume = 832π/3 cm³; Surface Area = 160π cm²",
    "solutionSteps": [
      "Cylinder: Volume = πr²h = π(4)²(12) = 192π cm³",
      "Two hemispheres = 1 sphere: Volume = (4/3)πr³ = (4/3)π(4)³ = 256π/3 cm³",
      "Total Volume = 192π + 256π/3 = (576π + 256π)/3 = 832π/3 cm³",
      "Surface Area: Lateral cylinder = 2πrh = 2π(4)(12) = 96π cm²",
      "Sphere surface = 4πr² = 4π(4)² = 64π cm²",
      "Total Surface Area = 96π + 64π = 160π cm²"
    ],
    "finalAnswer": "Volume = 832π/3 cm³; Surface Area = 160π cm²",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 13.1"
  },
  {
    "id": "SAV2-015",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Conversion of Solids",
    "section": "C",
    "marks": 3,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "A solid iron sphere of radius 6 cm is melted and recast into small cones of height 3 cm and base radius 1 cm. How many complete cones can be made?",
    "options": [],
    "answer": "288 complete cones",
    "solutionSteps": [
      "Volume of sphere = (4/3)πr³ = (4/3)π(6)³ = 288π cm³",
      "Volume of one cone = (1/3)πr²h = (1/3)π(1)²(3) = π cm³",
      "Number of cones = 288π ÷ π = 288"
    ],
    "finalAnswer": "288 complete cones",
    "isCompetencyBased": true,
    "pyqYear": "2019",
    "pyqSet": "Delhi",
    "ncertRef": "Ex 13.2"
  },
  {
    "id": "SAV2-016",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Frustum of Cone",
    "section": "A",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "Assertion (A): The curved surface area of a frustum depends only on the sum of radii and slant height. Reason (R): The formula is π(r₁ + r₂)l where l is slant height.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "CSA of frustum = π(r₁ + r₂)l",
      "This depends only on the sum (r₁ + r₂) and slant height l",
      "The reason correctly explains why A is true"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 13.3"
  },
  {
    "id": "SAV2-017",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Conversion of Solids",
    "section": "A",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Assertion (A): When a solid sphere is melted and recast into a cylinder, the volumes remain equal. Reason (R): Volume is conserved during the melting and recasting process.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "When material is melted and recast, volume is conserved",
      "Hence V(sphere) = V(cylinder after recasting)",
      "R correctly explains A"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 13.2"
  },
  {
    "id": "SAV2-018",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Combined Solids",
    "section": "A",
    "marks": 1,
    "format": "Assertion-Reasoning",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "Assertion (A): A solid formed by a cone on top of a cylinder has total surface area = 2πrh + 2πr² + πrl where h is cylinder height and l is cone slant height. Reason (R): The area where cone and cylinder meet is excluded from total surface area.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "TSA = Lateral cylinder + Base of cylinder + Curved cone surface",
      "= 2πrh + πr² + πrl",
      "The junction area is internal, hence excluded",
      "R explains why πr² (top of cylinder) is excluded from being counted twice"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 13.1"
  },
  {
    "id": "SAV2-019",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Combined Solids",
    "section": "E",
    "marks": 4,
    "format": "Case-Based",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A toy shop designs decorative items by joining a cone and a cylinder. The shop receives the following specifications: A cylinder with radius 5 cm and height 8 cm, with a cone of radius 5 cm and height 6 cm placed on top. (i) Find the curved surface area of the cone. (ii) Find the lateral surface area of the cylinder. (iii) Find the total surface area of the combined toy. (iv) What is the total volume?",
    "options": [],
    "answer": "(i) 5π√61 cm² (ii) 80π cm² (iii) 5π√61 + 105π cm² (iv) 250π cm³",
    "solutionSteps": [
      "(i) Slant height of cone: l = √(h² + r²) = √(36 + 25) = √61 cm",
      "Curved surface area of cone = πrl = 5π√61 ≈ 39π cm² [or using l=√61: 5π√61]",
      "For approximate: if using nearby value, ~65π",
      "(ii) Lateral surface area of cylinder = 2πrh = 2π(5)(8) = 80π cm²",
      "(iii) TSA = CSA of cone + Lateral of cylinder + Base of cylinder",
      "= 5π√61 + 80π + 25π = 5π√61 + 105π cm²",
      "(iv) Volume = Volume of cylinder + Volume of cone",
      "= π(5)²(8) + (1/3)π(5)²(6) = 200π + 50π = 250π cm³"
    ],
    "finalAnswer": "(i) 5π√61 cm² (ii) 80π cm² (iii) 5π√61 + 105π cm² (iv) 250π cm³",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": "Delhi",
    "ncertRef": "Ex 13.1"
  },
  {
    "id": "SAV2-020",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Frustum of Cone",
    "section": "E",
    "marks": 4,
    "format": "Case-Based",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "A company manufactures containers in the shape of a frustum of a cone. The container has a height of 20 cm, with the top radius being 6 cm and bottom radius being 10 cm. (i) Find the slant height of the frustum. (ii) Calculate the curved surface area. (iii) Find the total surface area including both bases. (iv) Calculate the volume of the container.",
    "options": [],
    "answer": "(i) 4√26 cm (ii) 64π√26 cm² (iii) (64π√26 + 136π) cm² (iv) 3920π/3 cm³",
    "solutionSteps": [
      "(i) Slant height l = √(h² + (r₂-r₁)²) = √(400 + 16) = √416 = 4√26 ≈ 20.4 cm",
      "(ii) CSA = π(r₁ + r₂)l = π(6 + 10)(4√26) = 64π√26 ≈ 326π cm²",
      "Using l ≈ 20.4: CSA ≈ 16π(20.4) ≈ 326π cm²",
      "(iii) TSA = CSA + πr₁² + πr₂² = 64π√26 + 36π + 100π ≈ 326π + 136π = 462π cm²",
      "(iv) V = (1/3)πh(r₁² + r₂² + r₁r₂) = (1/3)π(20)(36 + 100 + 60)",
      "= (20π/3)(196) = 3920π/3 cm³"
    ],
    "finalAnswer": "(i) 4√26 cm (ii) 64π√26 cm² (iii) (64π√26 + 136π) cm² (iv) 3920π/3 cm³",
    "isCompetencyBased": true,
    "pyqYear": "2024",
    "pyqSet": "All India",
    "ncertRef": "Ex 13.4"
  },
  {
    "id": "SAV2-021",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Conversion of Solids",
    "section": "D",
    "marks": 5,
    "format": "Long",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "A solid metallic cone with radius 6 cm and height 15 cm is melted and recast into (i) a sphere, (ii) a cylinder of height 8 cm. For each case, find the radius of the resulting solid. Also calculate the percentage change in surface area when the cone is converted to each solid.",
    "options": [],
    "answer": "(i) Sphere radius ≈ 5.13 cm; Surface area increases by ~148%; (ii) Cylinder radius ≈ 4.74 cm; Surface area increases by ~41%",
    "solutionSteps": [
      "Step 1: Volume of original cone = (1/3)πr²h = (1/3)π(6)²(15) = 180π cm³",
      "Step 2a: For sphere, (4/3)πR³ = 180π",
      "R³ = 135, R = ∛135 ≈ 5.13 cm",
      "Surface area of sphere = 4πR² = 4π(135)^(2/3) ≈ 330.4π cm²",
      "Step 2b: For cylinder, πr²h = 180π",
      "πr²(8) = 180π, r² = 22.5, r = √22.5 ≈ 4.74 cm",
      "Surface area of cylinder = 2πrh + 2πr² = 2π(4.74)(8) + 2π(22.5) ≈ 188π cm²",
      "Step 3: Surface area of cone = πr(r + l) where l = √(6² + 15²) = √261 ≈ 16.16",
      "= π(6)(6 + 16.16) ≈ 133.0π cm²",
      "Step 4: Change for sphere = (330.4π - 133.0π)/133.0π × 100% ≈ +148.3%",
      "Change for cylinder = (188π - 133.0π)/133.0π × 100% ≈ +41.4%"
    ],
    "finalAnswer": "(i) Sphere radius ≈ 5.13 cm; Surface area increases by ~148%; (ii) Cylinder radius ≈ 4.74 cm; Surface area increases by ~41%",
    "isCompetencyBased": true,
    "pyqYear": "2025",
    "pyqSet": "Delhi",
    "ncertRef": "Ex 13.2, Ex 13.5"
  },
  {
    "id": "SAV2-022",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Combined Solids",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A vessel is formed by combining a hemisphere of radius 7 cm at the bottom and a cylinder of the same radius and height 10 cm above it. The volume of the vessel is:",
    "options": [
      "2156π/3 cm³",
      "980π cm³",
      "539π cm³",
      "1470π cm³"
    ],
    "answer": "2156π/3 cm³",
    "solutionSteps": [
      "Volume of hemisphere = (2/3)πr³ = (2/3)π(7)³ = 686π/3 cm³",
      "Volume of cylinder = πr²h = π(7)²(10) = 490π cm³",
      "Total = 686π/3 + 490π = (686π + 1470π)/3 = 2156π/3 ≈ 718.67π cm³"
    ],
    "finalAnswer": "2156π/3 cm³",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 13.1"
  },
  {
    "id": "SAV2-023",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Conversion of Solids",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "Two solid spheres of radii 3 cm and 4 cm are melted and recast into a cone of height 10 cm. Find the radius of the base of the cone.",
    "options": [],
    "answer": "6 cm (approximately)",
    "solutionSteps": [
      "Volume of first sphere = (4/3)π(3)³ = 36π cm³",
      "Volume of second sphere = (4/3)π(4)³ = 256π/3 cm³",
      "Total volume = 36π + 256π/3 = (108π + 256π)/3 = 364π/3 cm³",
      "Volume of cone = (1/3)πr²h = (1/3)πr²(10)",
      "(1/3)πr²(10) = 364π/3",
      "10r² = 364",
      "r² = 36.4, r ≈ 6.03 cm ≈ 6 cm"
    ],
    "finalAnswer": "6 cm (approximately)",
    "isCompetencyBased": true,
    "pyqYear": "2022",
    "pyqSet": "Delhi",
    "ncertRef": "Ex 13.2"
  },
  {
    "id": "SAV2-024",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Combined Solids",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "A solid is formed by combining a cylinder and a hemisphere on top. If the radius is r and height of cylinder is h, what is the total curved surface area?",
    "options": [
      "2πrh + 3πr²",
      "2πrh + 2πr²",
      "πrh + 2πr²",
      "2πrh + πr²"
    ],
    "answer": "2πrh + 2πr²",
    "solutionSteps": [
      "Curved surface area of cylinder = 2πrh",
      "Curved surface area of hemisphere = 2πr²",
      "Total curved surface area = 2πrh + 2πr²"
    ],
    "finalAnswer": "2πrh + 2πr²",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 13.1"
  },
  {
    "id": "SAV2-025",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Combined Solids",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "A cone is placed on top of a cylinder of equal radius r. The total surface area includes:",
    "options": [
      "Curved surface area of both only",
      "Base of cylinder, curved surfaces of both, and lateral surface of cone",
      "Base of cylinder and curved surfaces of both",
      "All surfaces including the top of cylinder"
    ],
    "answer": "Base of cylinder and curved surfaces of both",
    "solutionSteps": [
      "Top of cylinder is hidden by cone base",
      "So only base of cylinder is counted",
      "Curved surfaces of cylinder and cone are included"
    ],
    "finalAnswer": "Base of cylinder and curved surfaces of both",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 13.1"
  },
  {
    "id": "SAV2-026",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Combined Solids",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "A cylinder of radius 3 cm and height 10 cm has a hemisphere of radius 3 cm placed on top. Find the total surface area (excluding the base of cylinder).",
    "options": [],
    "answer": "78π cm² (curved only) or 87π cm² (with top surface)",
    "solutionSteps": [
      "Curved surface area of cylinder = 2πrh = 2π(3)(10) = 60π cm²",
      "Curved surface area of hemisphere = 2πr² = 2π(3)² = 18π cm²",
      "Total = 60π + 18π = 78π cm²",
      "TSA = 2πrh + 2πr² = 2π(3)(10) + 2π(9) = 60π + 18π = 78π cm²",
      "Total excluding base = 60π + 18π + 9π = 87π ≈ 273 cm²"
    ],
    "finalAnswer": "78π cm² (curved only) or 87π cm² (with top surface)",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 13.1"
  },
  {
    "id": "SAV2-027",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Combined Solids",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A cone is mounted on a hemisphere of radius 7 cm. If the slant height of cone is 10 cm, find the curved surface area of the combined solid.",
    "options": [],
    "answer": "168π ≈ 527.52 cm²",
    "solutionSteps": [
      "Curved surface area of hemisphere = 2πr² = 2π(7)² = 98π cm²",
      "Curved surface area of cone = πrl = π(7)(10) = 70π cm²",
      "Total curved surface area = 98π + 70π = 168π ≈ 527.52 cm²"
    ],
    "finalAnswer": "168π ≈ 527.52 cm²",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 13.1"
  },
  {
    "id": "SAV2-028",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Combined Solids",
    "section": "B",
    "marks": 2,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "Two cylinders of equal radius 5 cm are joined end to end. If each has height 8 cm, the total surface area of the combined solid is:",
    "options": [
      "210π cm²",
      "160π cm²",
      "200π cm²",
      "240π cm²"
    ],
    "answer": "210π cm²",
    "solutionSteps": [
      "When joined end to end, two internal circular faces are hidden",
      "Combined solid is a cylinder with r = 5 cm, h = 16 cm",
      "CSA = 2πrh = 2π(5)(16) = 160π cm²",
      "Two exposed circular bases = 2πr² = 2π(25) = 50π cm²",
      "Total SA = 160π + 50π = 210π cm²"
    ],
    "finalAnswer": "210π cm²",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 13.1"
  },
  {
    "id": "SAV2-029",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Combined Solids",
    "section": "C",
    "marks": 2,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Analysing",
    "questionText": "Assertion: When a cone is placed on top of a cylinder of equal radius, the total surface area includes the base of cylinder but not the base of cone. Reason: The base of cone is internal and hidden by the top of cylinder.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "When cone is on cylinder with equal radii, cone's base coincides with cylinder's top",
      "This junction becomes internal and not part of surface",
      "Only the external surfaces are counted",
      "Cylinder's base is exposed, so it's included",
      "Both A and R are correct, and R explains why A is true"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 13.1"
  },
  {
    "id": "SAV2-030",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Conversion of Solids",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "When a solid sphere is melted and recast into smaller spheres, which property remains constant?",
    "options": [
      "Surface area",
      "Radius",
      "Volume",
      "Curved surface area"
    ],
    "answer": "Volume",
    "solutionSteps": [
      "When melting and recasting, mass/material remains same",
      "Volume is directly proportional to mass",
      "Therefore, total volume remains constant"
    ],
    "finalAnswer": "Volume",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 13.2"
  },
  {
    "id": "SAV2-031",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Conversion of Solids",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Easy",
    "bloomSkill": "Understanding",
    "questionText": "A sphere of radius 6 cm is melted and cast into a cone of base radius 4 cm. Find the height of the cone.",
    "options": [],
    "answer": "54 cm",
    "solutionSteps": [
      "Volume of sphere = (4/3)πr³ = (4/3)π(6)³ = (4/3)π(216) = 288π cm³",
      "Volume of cone = (1/3)πr²h",
      "288π = (1/3)π(4)²h",
      "288 = (1/3)(16)h",
      "288 = (16/3)h",
      "h = 288 × 3/16 = 864/16 = 54 cm"
    ],
    "finalAnswer": "54 cm",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 13.2"
  },
  {
    "id": "SAV2-032",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Conversion of Solids",
    "section": "B",
    "marks": 2,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A cylinder of radius 7 cm and height 14 cm is melted and cast into spheres of radius 3.5 cm. How many spheres are formed?",
    "options": [
      "4",
      "6",
      "8",
      "12"
    ],
    "answer": "12",
    "solutionSteps": [
      "Volume of cylinder = πr²h = π(7)²(14) = 686π cm³",
      "Volume of one sphere = (4/3)πr³ = (4/3)π(3.5)³ = (4/3)π(42.875) = 171.5π/3 cm³",
      "(3.5)³ = 42.875, so (4/3)π(42.875) = 57.167π cm³ ≈ 57.17π",
      "Number of spheres = 686π / 57.17π ≈ 12... verify",
      "(4/3)π(7/2)³ = (4/3)π(343/8) = 343π/6 cm³",
      "Number = 686π / (343π/6) = 686 × 6/343 = 4116/343 = 12"
    ],
    "finalAnswer": "12",
    "isCompetencyBased": true,
    "pyqYear": "2021",
    "pyqSet": undefined,
    "ncertRef": "Ex 13.2"
  },
  {
    "id": "SAV2-033",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Conversion of Solids",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A cone with base radius 5 cm and height 12 cm is melted and recast into a cylinder of radius 5 cm. What is the height of the cylinder?",
    "options": [],
    "answer": "4 cm",
    "solutionSteps": [
      "Volume of cone = (1/3)πr²h = (1/3)π(5)²(12) = (1/3)π(300) = 100π cm³",
      "Volume of cylinder = πr²h = π(5)²h = 25πh cm³",
      "100π = 25πh",
      "h = 100/25 = 4 cm"
    ],
    "finalAnswer": "4 cm",
    "isCompetencyBased": true,
    "pyqYear": "2019",
    "pyqSet": undefined,
    "ncertRef": "Ex 13.2"
  },
  {
    "id": "SAV2-034",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Frustum of Cone",
    "section": "A",
    "marks": 1,
    "format": "MCQ",
    "difficulty": "Easy",
    "bloomSkill": "Remembering",
    "questionText": "A frustum of a cone is formed when a cone is cut by a plane parallel to the base. What are the two circular surfaces called?",
    "options": [
      "Bases",
      "Vertices",
      "Lateral surfaces",
      "Slant heights"
    ],
    "answer": "Bases",
    "solutionSteps": [
      "A frustum has two parallel circular surfaces",
      "These are called the top base (smaller) and bottom base (larger)"
    ],
    "finalAnswer": "Bases",
    "isCompetencyBased": false,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 13.3"
  },
  {
    "id": "SAV2-035",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Frustum of Cone",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Understanding",
    "questionText": "The radii of the circular ends of a frustum are 10 cm and 8 cm, and the slant height is 12 cm. Find its curved surface area.",
    "options": [],
    "answer": "216π cm² ≈ 678.24 cm²",
    "solutionSteps": [
      "Curved surface area of frustum = π(r₁ + r₂)l",
      "where r₁ = 10 cm, r₂ = 8 cm, l = 12 cm",
      "CSA = π(10 + 8)(12) = π(18)(12) = 216π cm²",
      "≈ 678.24 cm²"
    ],
    "finalAnswer": "216π cm² ≈ 678.24 cm²",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 13.3"
  },
  {
    "id": "SAV2-036",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Frustum of Cone",
    "section": "B",
    "marks": 2,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A frustum has radii 6 cm and 4 cm with height 3 cm. The slant height is:",
    "options": [
      "√10 cm",
      "√13 cm",
      "√17 cm",
      "√20 cm"
    ],
    "answer": "√13 cm",
    "solutionSteps": [
      "Slant height l = √(h² + (r₁ - r₂)²)",
      "l = √(3² + (6-4)²) = √(9 + 4) = √13 cm"
    ],
    "finalAnswer": "√13 cm",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 13.3"
  },
  {
    "id": "SAV2-037",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Frustum of Cone",
    "section": "C",
    "marks": 2,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "A frustum of a cone has radii 12 cm and 8 cm, and height 8 cm. Find the total surface area (including both bases).",
    "options": [],
    "answer": "80π√5 + 208π ≈ 1216.77 cm²",
    "solutionSteps": [
      "First find slant height: l = √(h² + (r₁-r₂)²) = √(8² + (12-8)²) = √(64+16) = √80 = 4√5 cm",
      "Curved surface area = π(r₁+r₂)l = π(12+8)(4√5) = 80π√5 cm²",
      "Area of top base = πr₂² = π(8)² = 64π cm²",
      "Area of bottom base = πr₁² = π(12)² = 144π cm²",
      "Total surface area = 80π√5 + 64π + 144π = 80π√5 + 208π = 80π(√5 + 2.6) ≈ 80π(4.836)",
      "Simpler: 80π(2.236) + 208π ≈ 178.88π + 208π ≈ 1216.77 cm²"
    ],
    "finalAnswer": "80π√5 + 208π ≈ 1216.77 cm²",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 13.3"
  },
  {
    "id": "SAV2-038",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Frustum of Cone",
    "section": "C",
    "marks": 2,
    "format": "MCQ",
    "difficulty": "Hard",
    "bloomSkill": "Analysing",
    "questionText": "A container in the shape of a frustum has radii 20 cm and 10 cm with slant height 26 cm. The volume of the frustum is:",
    "options": [
      "5600π cm³",
      "7000π cm³",
      "8400π cm³",
      "4200π cm³"
    ],
    "answer": "5600π cm³",
    "solutionSteps": [
      "First find height: h² + (r₁-r₂)² = l² → h² + 10² = 26²",
      "h² = 676 - 100 = 576 → h = 24 cm",
      "Volume of frustum = (1/3)πh(r₁² + r₂² + r₁r₂)",
      "V = (1/3)π(24)(400 + 100 + 200) = (1/3)π(24)(700) = 8π(700) = 5600π"
      ],
    "finalAnswer": "5600π cm³",
    "isCompetencyBased": true,
    "pyqYear": "2023",
    "pyqSet": undefined,
    "ncertRef": "Ex 13.3"
  },
  {
    "id": "SAV2-039",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Combined Solids",
    "section": "E",
    "marks": 4,
    "format": "Case-Based",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A factory manufactures decorative items by joining a hemisphere and a cone of the same radius 7 cm. The slant height of the cone is 14 cm. \nBased on this information, answer the following:\n(i) Find the curved surface area of the hemisphere.\n(ii) Find the curved surface area of the cone.\n(iii) What is the total curved surface area of the combined solid?\n(iv) If 100 such items are made, what is the total curved surface area of all items?",
    "options": [],
    "answer": "(i) 98π cm² (ii) 98π cm² (iii) 196π ≈ 615.44 cm² (iv) 19600π ≈ 61544 cm²",
    "solutionSteps": [
      "(i) Curved surface area of hemisphere = 2πr² = 2π(7)² = 98π cm²",
      "(ii) Curved surface area of cone = πrl = π(7)(14) = 98π cm²",
      "(iii) Total curved surface area = 98π + 98π = 196π cm²",
      "(iv) For 100 items = 100 × 196π = 19600π cm²"
    ],
    "finalAnswer": "(i) 98π cm² (ii) 98π cm² (iii) 196π ≈ 615.44 cm² (iv) 19600π ≈ 61544 cm²",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 13.1"
  },
  {
    "id": "SAV2-040",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Conversion of Solids",
    "section": "C",
    "marks": 2,
    "format": "Assertion-Reasoning",
    "difficulty": "Medium",
    "bloomSkill": "Analysing",
    "questionText": "Assertion: If a metallic sphere of radius 6 cm is melted and recast into a cone of base radius 3 cm, the height of the cone will be 96 cm. Reason: Volume is conserved during melting and recasting.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "Volume of sphere = (4/3)π(6)³ = 288π cm³",
      "Volume of cone = (1/3)πr²h = (1/3)π(3)²h = 3πh cm³",
      "288π = 3πh → h = 96 cm",
      "Assertion is true, reason is true, and reason explains why assertion is correct"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 13.2"
  },
  {
    "id": "SAV2-041",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Frustum of Cone",
    "section": "C",
    "marks": 2,
    "format": "Assertion-Reasoning",
    "difficulty": "Hard",
    "bloomSkill": "Evaluating",
    "questionText": "Assertion: The curved surface area of a frustum with radii 10 cm and 5 cm and slant height 15 cm is 225π cm². Reason: The formula for curved surface area of frustum is π(r₁ + r₂)l.",
    "options": [
      "Both A and R are true, and R is the correct explanation of A.",
      "Both A and R are true, but R is not the correct explanation of A.",
      "A is true, R is false.",
      "A is false, R is true."
    ],
    "answer": "Both A and R are true, and R is the correct explanation of A.",
    "solutionSteps": [
      "Curved surface area = π(r₁ + r₂)l = π(10 + 5)(15) = π(15)(15) = 225π cm²",
      "Both assertion and reason are true",
      "Reason directly explains the assertion"
    ],
    "finalAnswer": "Both A and R are true, and R is the correct explanation of A.",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 13.3"
  },
  {
    "id": "SAV2-042",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Combined Solids",
    "section": "D",
    "marks": 5,
    "format": "Long",
    "difficulty": "Hard",
    "bloomSkill": "Creating",
    "questionText": "A solid toy is made by joining a hemisphere and a cone with the same radius of 10 cm. The height of the cone is 24 cm. Calculate: (i) the total surface area of the toy, (ii) the total volume of the toy, and (iii) if the density of the material is 2 g/cm³, find the mass of the toy.",
    "options": [],
    "answer": "(i) TSA = 460π cm² ≈ 1445 cm² (ii) Volume = 4400π/3 ≈ 4613 cm³ (iii) Mass = 8800π/3 ≈ 9214 g",
    "solutionSteps": [
      "(i) First find slant height of cone: l = √(h² + r²) = √(24² + 10²) = √(576 + 100) = √676 = 26 cm",
      "Curved surface area of hemisphere = 2πr² = 2π(10)² = 200π cm²",
      "Curved surface area of cone = πrl = π(10)(26) = 260π cm²",
      "Base of hemisphere is not exposed (joined with cone base)",
      "But base of cone is also not exposed",
      "The hemisphere and cone share a circular base. This shared base is internal.",
      "Total external surface area = curved surface of hemisphere + curved surface of cone",
      "= 200π + 260π = 460π cm²",
      "If pyramid sits on hemisphere: only external surfaces count",
      "TSA = 2πr² + πrl = 200π + 260π = 460π cm²",
      "(ii) Volume of hemisphere = (2/3)πr³ = (2/3)π(1000) = 2000π/3 cm³",
      "Volume of cone = (1/3)πr²h = (1/3)π(100)(24) = 800π cm³ = 2400π/3 cm³",
      "Total volume = 2000π/3 + 2400π/3 = 4400π/3 cm³",
      "(iii) Mass = Volume × Density = (4400π/3) × 2 = 8800π/3 g ≈ 9214 g"
    ],
    "finalAnswer": "(i) TSA = 460π cm² ≈ 1445 cm² (ii) Volume = 4400π/3 ≈ 4613 cm³ (iii) Mass = 8800π/3 ≈ 9214 g",
    "isCompetencyBased": true,
    "pyqYear": "2022",
    "pyqSet": undefined,
    "ncertRef": "Ex 13.1, Ex 13.2"
  },
  {
    "id": "SAV2-043",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Conversion of Solids",
    "section": "D",
    "marks": 5,
    "format": "Long",
    "difficulty": "Hard",
    "bloomSkill": "Creating",
    "questionText": "Three spheres of radii 3 cm, 4 cm, and 5 cm are melted and recast into a single sphere. (i) Find the radius of the new sphere. (ii) Find the surface area of the new sphere. (iii) Compare it with the sum of surface areas of the three original spheres.",
    "options": [],
    "answer": "(i) r = 6 cm (ii) SA = 144π ≈ 452.39 cm² (iii) Original total = 200π ≈ 628.32 cm². New sphere has less SA.",
    "solutionSteps": [
      "(i) Volume of sphere with radius 3 cm = (4/3)π(3)³ = 36π cm³",
      "Volume of sphere with radius 4 cm = (4/3)π(4)³ = (256/3)π cm³",
      "Volume of sphere with radius 5 cm = (4/3)π(5)³ = (500/3)π cm³",
      "Total volume = 36π + (256/3)π + (500/3)π = (108/3)π + (256/3)π + (500/3)π = (864/3)π = 288π cm³",
      "Volume of new sphere = (4/3)πr³ = 288π",
      "(4/3)πr³ = 288π → r³ = 216 → r = 6 cm",
      "(ii) Surface area of new sphere = 4πr² = 4π(6)² = 144π cm²",
      "(iii) Surface area of original spheres = 4π(3)² + 4π(4)² + 4π(5)²",
      "= 36π + 64π + 100π = 200π cm²",
      "Difference: 200π - 144π = 56π cm²",
      "New sphere has less surface area despite same volume"
    ],
    "finalAnswer": "(i) r = 6 cm (ii) SA = 144π ≈ 452.39 cm² (iii) Original total = 200π ≈ 628.32 cm². New sphere has less SA.",
    "isCompetencyBased": true,
    "pyqYear": "2020",
    "pyqSet": undefined,
    "ncertRef": "Ex 13.2"
  },
  {
    "id": "SAV2-044",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Combined Solids",
    "section": "B",
    "marks": 2,
    "format": "MCQ",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A solid is formed by combining a cube of side 10 cm with a hemisphere of radius 5 cm placed on one of its faces. What is the total surface area?",
    "options": [
      "600 + 50π cm²",
      "500 + 50π cm²",
      "600 + 100π cm²",
      "550 + 75π cm²"
    ],
    "answer": "500 + 50π cm²",
    "solutionSteps": [
      "Surface area of cube = 6a² = 6(10)² = 600 cm²",
      "One face is covered by hemisphere = -100 cm²",
      "Curved surface area of hemisphere = 2πr² = 2π(5)² = 50π cm²",
      "Total = 600 - 100 + 50π = 500 + 50π cm²",
      "But option A is 600 + 50π, which assumes no subtraction",
      "This implies the hemisphere adds to the outer surface. Correct interpretation: TSA = 5×100 + 50π + base of cube if exposed"
    ],
    "finalAnswer": "500 + 50π cm²",
    "isCompetencyBased": true,
    "pyqYear": undefined,
    "pyqSet": undefined,
    "ncertRef": "Ex 13.1"
  },
  {
    "id": "SAV2-045",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Frustum of Cone",
    "section": "B",
    "marks": 2,
    "format": "Short",
    "difficulty": "Medium",
    "bloomSkill": "Applying",
    "questionText": "A frustum of a cone is cut from a cone of height 20 cm and base radius 12 cm, by removing the top cone of height 8 cm. Find the height of the frustum.",
    "options": [],
    "answer": "12 cm",
    "solutionSteps": [
      "Original cone height = 20 cm",
      "Removed cone height = 8 cm",
      "Height of frustum = 20 - 8 = 12 cm"
    ],
    "finalAnswer": "12 cm",
    "isCompetencyBased": true,
    "pyqYear": "2024",
    "pyqSet": undefined,
    "ncertRef": "Ex 13.3"
  },
  {
    "id": "SAV2-046",
    "subject": "Maths",
    "topicKey": "Surface Areas and Volumes",
    "subtopic": "Combined Solids",
    "section": "C",
    "marks": 3,
    "format": "Short",
    "difficulty": "Hard",
    "bloomSkill": "Creating",
    "questionText": "A pen stand is made by fitting a cone on top of a cylinder. The cylinder has radius 3 cm and height 8 cm, and the cone has the same radius and height 4 cm. Find the volume of the pen stand.",
    "options": [],
    "answer": "84π cm³ ≈ 263.89 cm³",
    "solutionSteps": [
      "Volume of cylinder = πr²h = π(3)²(8) = 72π cm³",
      "Volume of cone = (1/3)πr²h = (1/3)π(3)²(4) = (1/3)π(9)(4) = 12π cm³",
      "Total volume = 72π + 12π = 84π cm³",
      "If both height 8 and 4 are 12 total: 72 + 12 = 84π, or check: 36 × 12 × π / 3 + 72π = 144π + 72π = 216π... no",
      "Actual: 72π + 12π = 84π cm³ ≈ 263.89 cm³"
    ],
    "finalAnswer": "84π cm³ ≈ 263.89 cm³",
    "isCompetencyBased": true,
    "pyqYear": "2025",
    "pyqSet": undefined,
    "ncertRef": "Ex 13.1, Ex 13.2"
  }
];
