// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homepage-redesign/CleanFocus.tsx": () => import("../components/mockups/homepage-redesign/CleanFocus.tsx"),
  "./components/mockups/homepage-redesign/NeonCampus.tsx": () => import("../components/mockups/homepage-redesign/NeonCampus.tsx"),
  "./components/mockups/homepage-redesign/StoryScroll.tsx": () => import("../components/mockups/homepage-redesign/StoryScroll.tsx"),
  "./components/mockups/homepage-redesign/StoryScrollLight.tsx": () => import("../components/mockups/homepage-redesign/StoryScrollLight.tsx"),
  "./components/mockups/homepage-redesign/StoryScrollLightBg.tsx": () => import("../components/mockups/homepage-redesign/StoryScrollLightBg.tsx"),
  "./components/mockups/student-dashboard/DashboardMobile.tsx": () => import("../components/mockups/student-dashboard/DashboardMobile.tsx"),
  "./components/mockups/analytics-dashboard/AnalyticsOptions.tsx": () => import("../components/mockups/analytics-dashboard/AnalyticsOptions.tsx"),
  "./components/mockups/analytics-dashboard/Dashboard.tsx": () => import("../components/mockups/analytics-dashboard/Dashboard.tsx"),
  "./components/mockups/analytics-dashboard/Journey.tsx": () => import("../components/mockups/analytics-dashboard/Journey.tsx"),
  "./components/mockups/analytics-dashboard/Scorecard.tsx": () => import("../components/mockups/analytics-dashboard/Scorecard.tsx")
};
