// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homepage-redesign/CleanFocus.tsx": () => import("../components/mockups/homepage-redesign/CleanFocus.tsx"),
  "./components/mockups/homepage-redesign/NeonCampus.tsx": () => import("../components/mockups/homepage-redesign/NeonCampus.tsx"),
  "./components/mockups/homepage-redesign/StoryScroll.tsx": () => import("../components/mockups/homepage-redesign/StoryScroll.tsx")
};
