import type { ExamQuestion } from "./types";

export const mathsExamQuestions: ExamQuestion[] = [
  {
    id: "M-A1",
    subject: "Maths",
    topicKey: "Real Numbers",
    subtopic: "HCF & LCM",
    section: "A",
    marks: 1,
    format: "MCQ",
    difficulty: "Easy",
    questionText: "If HCF(336, 54) = 6, find LCM(336, 54).",
    options: ["(a) 3024", "(b) 2016", "(c) 1008", "(d) 576"],
  },
  {
    id: "M-A2",
    subject: "Maths",
    topicKey: "Polynomials",
    subtopic: "Zeroes",
    section: "A",
    marks: 1,
    format: "MCQ",
    difficulty: "Easy",
    questionText: "The zeroes of the polynomial x\u00b2 \u2212 3x \u2212 4 are:",
    options: ["(a) 4, \u22121", "(b) \u22124, 1", "(c) 4, 1", "(d) \u22124, \u22121"],
  },
  {
    id: "M-A3",
    subject: "Maths",
    topicKey: "Trigonometry",
    subtopic: "Trig Ratios",
    section: "A",
    marks: 1,
    format: "MCQ",
    difficulty: "Easy",
    questionText: "If tan \u03b8 = 5/12, then the value of sin \u03b8 is:",
    options: ["(a) 5/13", "(b) 12/13", "(c) 13/5", "(d) 13/12"],
  },
  {
    id: "M-A4",
    subject: "Maths",
    topicKey: "Coordinate Geometry",
    subtopic: "Distance Formula",
    section: "A",
    marks: 1,
    format: "MCQ",
    difficulty: "Easy",
    questionText: "The distance between (2, 3) and (\u22121, 7) is:",
    options: ["(a) 4", "(b) 5", "(c) 6", "(d) 7"],
  },
  {
    id: "M-A5",
    subject: "Maths",
    topicKey: "Real Numbers",
    subtopic: "Irrational Numbers",
    section: "A",
    marks: 1,
    format: "MCQ",
    difficulty: "Easy",
    questionText: "Which of the following is irrational?",
    options: ["(a) \u221a4", "(b) \u221a9/\u221a16", "(c) \u221a5", "(d) 0.\u03053"],
  },
  {
    id: "M-B1",
    subject: "Maths",
    topicKey: "Quadratic Equations",
    subtopic: "Roots",
    section: "B",
    marks: 2,
    format: "Short",
    difficulty: "Medium",
    questionText: "Find the roots of the quadratic equation 2x\u00b2 + x \u2212 6 = 0.",
  },
  {
    id: "M-B2",
    subject: "Maths",
    topicKey: "Real Numbers",
    subtopic: "Irrational Proof",
    section: "B",
    marks: 2,
    format: "Short",
    difficulty: "Medium",
    questionText: "Prove that \u221a3 is irrational.",
    orAlternative: {
      id: "M-B2-OR",
      subject: "Maths",
      topicKey: "Real Numbers",
      subtopic: "Irrational Proof",
      section: "B",
      marks: 2,
      format: "Short",
      difficulty: "Medium",
      questionText: "Prove that \u221a2 is irrational.",
    },
  },
  {
    id: "M-B3",
    subject: "Maths",
    topicKey: "Arithmetic Progressions",
    subtopic: "nth Term",
    section: "B",
    marks: 2,
    format: "Short",
    difficulty: "Easy",
    questionText: "Find the 20th term of the AP: 3, 8, 13, 18, ...",
  },
  {
    id: "M-C1",
    subject: "Maths",
    topicKey: "Coordinate Geometry",
    subtopic: "Area of Triangle",
    section: "C",
    marks: 3,
    format: "Short",
    difficulty: "Medium",
    questionText: "A triangle ABC with vertices A(1,\u22121), B(0,4) and C(\u22125,3). Find the area of the triangle.",
  },
  {
    id: "M-C2",
    subject: "Maths",
    topicKey: "Circles",
    subtopic: "Tangent Properties",
    section: "C",
    marks: 3,
    format: "Short",
    difficulty: "Medium",
    questionText: "Two concentric circles are of radii 5 cm and 3 cm. Find the length of the chord of the larger circle which touches the smaller circle.",
    orAlternative: {
      id: "M-C2-OR",
      subject: "Maths",
      topicKey: "Circles",
      subtopic: "Tangent Properties",
      section: "C",
      marks: 3,
      format: "Short",
      difficulty: "Medium",
      questionText: "Prove that the tangent at any point of a circle is perpendicular to the radius through the point of contact.",
    },
  },
  {
    id: "M-D1",
    subject: "Maths",
    topicKey: "Triangles",
    subtopic: "BPT",
    section: "D",
    marks: 5,
    format: "Long",
    difficulty: "Hard",
    questionText: "State and prove the Basic Proportionality Theorem (Thales' Theorem). Using this, if DE \u2225 BC in \u25b3ABC where D and E lie on AB and AC respectively, and AD/DB = 2/3, find AE/EC.",
    orAlternative: {
      id: "M-D1-OR",
      subject: "Maths",
      topicKey: "Triangles",
      subtopic: "Pythagoras Theorem",
      section: "D",
      marks: 5,
      format: "Long",
      difficulty: "Hard",
      questionText: "State and prove the Pythagoras Theorem. In a right triangle, if the hypotenuse is 13 cm and one side is 5 cm, find the other side.",
    },
  },
  {
    id: "M-D2",
    subject: "Maths",
    topicKey: "Constructions",
    subtopic: "Tangent Construction",
    section: "D",
    marks: 5,
    format: "Long",
    difficulty: "Hard",
    questionText: "Draw a pair of tangents to a circle of radius 4 cm from a point 6 cm away from the centre. Describe the steps of construction.",
  },
  {
    id: "M-E1",
    subject: "Maths",
    topicKey: "Statistics",
    subtopic: "Mean (Step-Deviation)",
    section: "E",
    marks: 4,
    format: "Case-Based",
    difficulty: "Medium",
    questionText: "Case Study: A survey was conducted on 30 families regarding monthly expenditure on education. The data is: 1000-1500: 2, 1500-2000: 5, 2000-2500: 8, 2500-3000: 7, 3000-3500: 5, 3500-4000: 3. Find the mean expenditure using the step-deviation method.",
  },
];

export const scienceExamQuestions: ExamQuestion[] = [
  {
    id: "S-A1",
    subject: "Science",
    topicKey: "Chemical Reactions",
    subtopic: "Chemical Formulas",
    section: "A",
    marks: 1,
    format: "MCQ",
    difficulty: "Easy",
    questionText: "The chemical formula of baking soda is:",
    options: ["(a) Na\u2082CO\u2083", "(b) NaHCO\u2083", "(c) NaCl", "(d) NaOH"],
  },
  {
    id: "S-A2",
    subject: "Science",
    topicKey: "Light",
    subtopic: "Mirrors",
    section: "A",
    marks: 1,
    format: "MCQ",
    difficulty: "Easy",
    questionText: "Which of the following is not a type of mirror?",
    options: ["(a) Concave", "(b) Convex", "(c) Plane", "(d) Refractive"],
  },
  {
    id: "S-A3",
    subject: "Science",
    topicKey: "Electricity",
    subtopic: "Units",
    section: "A",
    marks: 1,
    format: "MCQ",
    difficulty: "Easy",
    questionText: "The SI unit of electric current is:",
    options: ["(a) Volt", "(b) Watt", "(c) Ampere", "(d) Ohm"],
  },
  {
    id: "S-A4",
    subject: "Science",
    topicKey: "Chemical Reactions",
    subtopic: "Gas Evolution",
    section: "A",
    marks: 1,
    format: "MCQ",
    difficulty: "Easy",
    questionText: "Which gas is evolved when zinc reacts with dilute HCl?",
    options: ["(a) O\u2082", "(b) CO\u2082", "(c) H\u2082", "(d) Cl\u2082"],
  },
  {
    id: "S-A5",
    subject: "Science",
    topicKey: "Life Processes",
    subtopic: "Plant Physiology",
    section: "A",
    marks: 1,
    format: "MCQ",
    difficulty: "Easy",
    questionText: "Stomata open and close due to:",
    options: ["(a) Xylem", "(b) Phloem", "(c) Guard cells", "(d) Companion cells"],
  },
  {
    id: "S-B1",
    subject: "Science",
    topicKey: "Carbon Compounds",
    subtopic: "Homologous Series",
    section: "B",
    marks: 2,
    format: "Short",
    difficulty: "Medium",
    questionText: "What is a homologous series? Give an example with the first three members.",
    orAlternative: {
      id: "S-B1-OR",
      subject: "Science",
      topicKey: "Carbon Compounds",
      subtopic: "Functional Groups",
      section: "B",
      marks: 2,
      format: "Short",
      difficulty: "Medium",
      questionText: "What are functional groups? Give the functional groups of alcohols and carboxylic acids with examples.",
    },
  },
  {
    id: "S-B2",
    subject: "Science",
    topicKey: "Control & Coordination",
    subtopic: "Reflex Arc",
    section: "B",
    marks: 2,
    format: "Short",
    difficulty: "Medium",
    questionText: "Define reflex arc. Draw a neat labelled diagram.",
  },
  {
    id: "S-B3",
    subject: "Science",
    topicKey: "Electricity",
    subtopic: "Ohm\u2019s Law",
    section: "B",
    marks: 2,
    format: "Short",
    difficulty: "Easy",
    questionText: "State Ohm\u2019s law. What is the resistance of a conductor if V = 12V and I = 3A?",
  },
  {
    id: "S-C1",
    subject: "Science",
    topicKey: "Life Processes",
    subtopic: "Nutrition in Amoeba",
    section: "C",
    marks: 3,
    format: "Short",
    difficulty: "Medium",
    questionText: "Explain the process of nutrition in Amoeba with the help of diagrams.",
    orAlternative: {
      id: "S-C1-OR",
      subject: "Science",
      topicKey: "Life Processes",
      subtopic: "Photosynthesis",
      section: "C",
      marks: 3,
      format: "Short",
      difficulty: "Medium",
      questionText: "Describe the process of photosynthesis. Why is it important for life on Earth?",
    },
  },
  {
    id: "S-C2",
    subject: "Science",
    topicKey: "Chemical Reactions",
    subtopic: "Balancing Equations",
    section: "C",
    marks: 3,
    format: "Short",
    difficulty: "Medium",
    questionText: "What happens when dilute hydrochloric acid is added to iron filings? Write balanced chemical equation.",
  },
  {
    id: "S-D1",
    subject: "Science",
    topicKey: "Light",
    subtopic: "Convex Lens",
    section: "D",
    marks: 5,
    format: "Long",
    difficulty: "Hard",
    questionText: "Draw ray diagrams for image formation by a convex lens for objects placed (i) beyond 2F\u2081 (ii) at F\u2081. State the nature, position and size of the image in each case.",
  },
  {
    id: "S-D2",
    subject: "Science",
    topicKey: "Life Processes",
    subtopic: "Human Heart",
    section: "D",
    marks: 5,
    format: "Long",
    difficulty: "Hard",
    questionText: "Describe the structure of human heart with a labelled diagram. How does blood flow through the four chambers?",
    orAlternative: {
      id: "S-D2-OR",
      subject: "Science",
      topicKey: "Life Processes",
      subtopic: "Human Excretory System",
      section: "D",
      marks: 5,
      format: "Long",
      difficulty: "Hard",
      questionText: "Describe the structure and function of a nephron. Draw a labelled diagram of the human excretory system.",
    },
  },
  {
    id: "S-E1",
    subject: "Science",
    topicKey: "Electricity",
    subtopic: "Series Circuit",
    section: "E",
    marks: 4,
    format: "Case-Based",
    difficulty: "Medium",
    questionText: "Case Study: A student set up a circuit with a 9V battery, an ammeter, a voltmeter and three resistors of 2\u03a9, 3\u03a9 and 4\u03a9 connected in series. (i) Find total resistance. (ii) Find current. (iii) Find potential difference across the 3\u03a9 resistor.",
  },
];
